### ISSUE TITLE
Adding 10.0.3 plugin to Calibre 6.1 macOS ARM

### ISSUE THREAD

**Issue by grantbarrett** [noDRM/DeDRM_tools#106]
### Question / bug report

Upon adding the plugin version 10.0.3 to Calibre 6.1, it is rejected by Calibre. "InvalidPlugin: Blacklisting the DeDRM version  (10, 0, 2) plugin as it is too old and causes crashes. Update it to the latest version to use it."

### Which version of Calibre are you running?

6.1  macOS ARM

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
calibre, version 6.1.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:Blacklisting the DeDRM version (10, 0, 2) plugin as it is too old and causes crashes. Update it to the latest version to use it.

calibre 6.1  embedded-python: True
macOS-12.4-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('12.4', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && Package KFX (from KFX Input) (1, 49, 0) && Amazon.com Multiple Countries (1, 0, 0) && Audit Log (1, 0, 18) && Embed Comic Metadata (1, 6, 1) && EpubCheck (0, 2, 4) && EpubMerge (2, 13, 0) && Extract ISBN (1, 5, 1) && Favourites Menu (1, 1, 0) && Find Duplicates (1, 9, 6) && Goodreads (1, 5, 3) && Goodreads More Tags (1, 2, 1) && Goodreads Sync (1, 15, 4) && Goodreads_Rating (4, 0, 0) && Job Spy (1, 0, 192) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 63, 0) && KFX Output (1, 63, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && Library Codes (1, 0, 53) && Manage Series (1, 3, 0) && Modify ePub (1, 7, 3) && MultiColumnSearch (1, 0, 89) && Obok DeDRM (10, 0, 3) && Quality Check (1, 12, 0) && Reading List (1, 12, 0) && Save To Format (0, 0, 6) && User Category (1, 5, 6) && View Manager (1, 8, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 483, in add_plugin
  File "calibre/customize/ui.py", line 671, in initialize_plugin
calibre.customize.InvalidPlugin: Blacklisting the DeDRM version (10, 0, 2) plugin as it is too old and causes crashes. Update it to the latest version to use it.
```

**Comment by ElleKayEm** [comment]
Completely uninstall any previous version of DeDRM. Restart calibre.  Then try loading 10.0.3.
