### ISSUE TITLE
No DeDRM_plugin.zip

### ISSUE THREAD

**Issue by StresseJesse** [noDRM/DeDRM_tools#11]
### Question / bug report

Hi! Sorry, I'm trying to install the Calibre plugin, but there is no DeDRM_plugin.zip file in the unzipped DeDRM_tools-master folder.

Am I crazy and missing something (so sorry if I am)?

### Which version of Calibre are you running?

5.32

### Which version of the DeDRM plugin are you running?

v10.0.0

### Log output

```log
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/customize/ui.py", line 828, in main
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 281, in load
calibre.customize.PluginNotFound: Cannot access 'DeDRM_plugin.zip'
```

**Comment by noDRM** [comment]
If you have a `DeDRM_tools-master` folder, you downloaded the wrong thing - the source code. You probably downloaded that through the Code -> Download ZIP button on Github. 

What you need to do instead is go to the Releases page - https://github.com/noDRM/DeDRM_tools/releases - then download the DeDRM_tools_X.X.X.zip file, and in there will be a DeDRM_plugin.zip

**Comment by noDRM** [comment]
No further response, I'm assuming that this fixed the issue. If you still can't get the plugin to work, feel free to re-open.
