### ISSUE TITLE
Can´t remove DRM on Kindle/amazon AZW3 files

### ISSUE THREAD

**Issue by mondomedia2022** [noDRM/DeDRM_tools#110]
### Question / bug report

completely unable to remove any DRM from amazon AZW3 files... please help!

### Which version of Calibre are you running?

6.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

5.14.3.0.1

### Log output

Microsoft Windows [Version 10.0.22000.795]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\WINDOWS\system32>calibre-debug -g
calibre 6.1  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 72.62613065326633 x 72.57142857142857
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[0.55] main UI initialized...
[0.55] Hiding splash screen
Starting QuickView
[1.02] splash screen hidden
[1.02] Started up in 1.02 seconds with 24 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xb24\xbc\x95\xef\xbc\x9d\xf4T\x05\xaa\xbe\x9e\xa8\x97\xe2\x94E\xe6jW7\x81[\x8a\x98\xd7\x0fs\x14,\x96', b'C:\\Users\\chost\\Downloads\\Nationalsozialisten vor dem Volksgericht Wien_ \xc3\x96sterreichs Ringen um Gerechtigkeit 1945-1955 in der zeitgen\xc3\xb6ssischen \xc3\xb6ffentlichen Wahrnehmung (German Edition).azw3']
DeDRM v10.0.3: Trying to decrypt Nationalsozialisten vor dem Volksgericht Wien_ Österreichs Ringen um Gerechtigkeit 1945-1955 in der zeitgenössischen öffentlichen Wahrnehmung (German Edition).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Nationalsozialisten vor dem Volksgericht Wien: Österreichs Ringen um Gerechtigkeit 1945-1955 in der zeitgenössischen öffentlichen Wahrnehmung (German Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\chost\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\chost\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\chost\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Nationalsozialisten vor dem Volksgericht Wien: Österreichs Ringen um Gerechtigkeit 1945-1955 in der zeitgenössischen öffentlichen Wahrnehmung (German Edition) to db in: 1.5
Added 1 books in 1.9 seconds
Worker Launch took: 0.00 seconds

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle (not a Fire), then you need to add that Kindle's serial number to DeDRM's customization.

**Comment by mondomedia2022** [comment]
> If that's from or for an E-ink Kindle (not a Fire), then you need to add that Kindle's serial number to DeDRM's customization.

yes, it´s for a kindle => where shall I add the serialnumber?

**Comment by mondomedia2022** [comment]
ok, found it, added the serial of my kindle in DRM-plugin => but unfortunately STILL unable to get rid of DRM - adding the serial to the plugin didn´t change a thing...

**Comment by ElleKayEm** [comment]
After adding the serial number, be sure to click ok and apply on your way out of the dialog boxes.  Restart calibre and re-add the book.

**Comment by mondomedia2022** [comment]
> After adding the serial number, be sure to click ok and apply on your way out of the dialog boxes. Restart calibre and re-add the book.

Done all the above - tried more than once. No luck. doesn´t work.
![drm](https://user-images.githubusercontent.com/109902242/180650894-3450b197-245e-486f-b6e7-fabd439fcb75.jpg)

**Comment by Anarconda** [comment]
I have a similar problem too, but on Linux. I have a Kindle Keyboard and with serial number in place some books can be converted, but others show that message. The files that can NOT be converted are .azw and .azw3. In short, I can deDRM some files but others not.

**Comment by ElleKayEm** [comment]
When downloading from the website, make sure you're choosing an E-ink Kindle -- doesn't work for Fire devices.  Make sure the serial number for that Kindle is correctly entered into DeDRM -- copy and paste it from the website.

**Comment by aloctavodia** [comment]
Hi, same issue here. Any chance this will work for Kindle Fire in the near future?

**Comment by ElleKayEm** [comment]
Not likely, but you can always use the Kindle for PC/Mac apps instead.  See this post: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by aloctavodia** [comment]
Thanks, I should check if that works with Linux

**Comment by ElleKayEm** [comment]
From what I've seen here, yes but sometimes it's tricky to get set up.

**Comment by GastonRimbaud** [comment]
I have the same issue with 10.0.3 Kindle for PC.  I do not own a Kindle.  I could get a couple to work if i dedrm'd on one book at a time.  But i didnt investigate that because ...

For now, i'm reverting to the 10.0.2 DeDrm that worked -- except for the occasional PDF on which I'd use an old version 4 Calibre.

**Comment by ElleKayEm** [comment]
Strange, DeDRM 10.0.3 working for me with Kindle for PC, Adobe epubs, and Obok 10.0.3 is fine too.  Just tested with calibre 6.2.1 and calibre 5.44 on another PC.

**Comment by elfiflos** [comment]
I have the same problem. 

### Which version of Calibre are you running?
I tried 6, 6.2.1, and 6.3. 

### Which version of the DeDRM plugin are you running?
v10.0.3

I have put the plugin, and added the SN, and clicked on ok and apply. 

When I convert, I keep on getting "this book has DRM, cannot convert". 

Log file:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.2.1  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.2.1  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 105.21682847896439 x 105.10344827586206
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[0.89] main UI initialized...
[0.89] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt The Winner Effect.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Winner Effect
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Monfi\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Monfi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Monfi\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[3.23] splash screen hidden
[3.23] Started up in 3.23 seconds with 0 books
Added The Winner Effect to db in: 0.3
Added 1 books in 0.9 seconds

**Comment by elfiflos** [comment]
I managed to make it work.
Here's what I did. 
1. Delete Calibre data. 
To do so, go to preferences -> advanced -> Miscellaneous, then click "open calibre configuration directory". File explorer opens. 
Close off Calibre. 
Delete all of the files in the file explorer that opened (they'll have names like gui.py, gui.json, global.py, etc). 
2. Uninstall Calibre. 
3. Install Calibre version 6.2.1. 
4. Start Calibre. Indicate which file you will have your books exported to. 
5. Download the DeDRM plugin version 10.0.3
6. Write the series number of your kindle.
7. Hit ok. Hit apply. 
8. Close Calibre. 
9. Start calibre again. 

That should work.

**Comment by ElleKayEm** [comment]
I'm surprised steps 1 and 2 were necessary.  Do you know what version of calibre you had before you updated to 6.x?

**Comment by elfiflos** [comment]
I tried 4, 4.23, the one before 4.23, 5, 6, 6.3 before I figured I may need to delete the data. That being said, my SN may also have been incorrect. In any ways, now, it has worked!
________________________________

**Comment by ElleKayEm** [comment]
5.0 to 6.0 may have been too big of a jump for the database to take.
