### ISSUE TITLE
invalid decimal literal

### ISSUE THREAD

**Issue by swarzarossa** [noDRM/DeDRM_tools#113]
**bug report**
I used ADE 2.0 to obtain the epub.

**Which version of Calibre are you running?**
6.1

**Which version of the DeDRM plugin are you running?**
10.0.3

**Log Output**

calibre Debug log
calibre 6.1  embedded-python: False
Linux-5.18.14-arch1-1-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.18.14-arch1-1', '#1 SMP PREEMPT_DYNAMIC Sat, 23 Jul 2022 11:46:17 +0000')
Python 3.10.5
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.1  embedded-python: False
Linux-5.18.14-arch1-1-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.18.14-arch1-1', '#1 SMP PREEMPT_DYNAMIC Sat, 23 Jul 2022 11:46:17 +0000')
Python 3.10.5
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.28 x 80.68235294117646
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.03] splash screen shown
[0.03] Initializing db...
[0.04] db initialized
[0.04] Constructing main UI...
[0.48] main UI initialized...
[0.48] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Buddenbrooks.epub
DeDRM v10.0.3: Verifying zip archive integrity
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 356, in ePubDecrypt
    import ineptepub
  File "/home/user/.config/calibre/plugins/DeDRM.zip/ineptepub.py", line 57, in <module>
    from Cryptodome.Cipher import AES, PKCS1_v1_5
  File "/home/user/.local/lib/python3.10/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 73, in <module>
    from Crypto.Util.number import ceil_div
  File "/home/user/.local/lib/python3.10/site-packages/Crypto/Util/number.py", line 139
    value |= 2L ** (N-1)                # Ensure high bit is set
             ^
SyntaxError: invalid decimal literal
[2.73] splash screen hidden
[2.73] Started up in 2.73 seconds with 170 books
Added Buddenbrooks: Verfall einer Familie to db in: 0.2
Added 1 books in 0.5 seconds

**Comment by ElleKayEm** [comment]
Try with the official Linux calibre: https://calibre-ebook.com/download_linux

**Comment by ElleKayEm** [comment]
Official calibre is using its own embedded Python.
