### ISSUE TITLE
Cannot decrypt Adobe Digital Editions epub.

### ISSUE THREAD

**Issue by Draconicrose** [noDRM/DeDRM_tools#116]
Hello! 
After much work to even get the plugin to import my ADE key, I am still getting an error that has now left me stumped:
```
DeDRM v10.0.3: Trying to decrypt Aristotle and Dante Discover the Secrets of the Universe.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Aristotle and Dante Discover the Secrets of the Universe.epub is a secure Adobe Adept ePub for UUID REDACTED
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
    userkey = codecs.decode(userkeyhex, 'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
```
I am unsure how to proceed from here.
Linux Mint 20.3 Cinnamon
Calibre 6.2.1 (native)
DeDRM 10.0.3
ADE 4.5
Wine 7.14 Staging

**Comment by ElleKayEm** [comment]
There is a bug which causes a problem when there is something wrong with the currently saved key. Try going into DeDRM's customization and deleting the Adobe Digital Editions key. Then restart calibre and re-add the book to see if DeDRM can automatically retrieve the correct key.

**Comment by Draconicrose** [comment]
This solved the issue! Thank you.
