### ISSUE TITLE
10.0.3 install fails

### ISSUE THREAD

**Issue by hobbyfarmer115** [noDRM/DeDRM_tools#118]
### Question / bug report

Most recent DeDRM tools won't install. Am I doing something wrong here? 

### Which version of Calibre are you running?

6.2.1

### Which version of the DeDRM plugin are you running?

v10.03

### Log output

```log
Paste log output here.
```calibre, version 6.2.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\Rem\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.2.1  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: en_AU
Successfully initialized third party plugins: DeACSM (0, 0, 16)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 300, in load
  File "calibre\customize\zipplugin.py", line 395, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\Rem\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.

**Comment by hobbyfarmer115** [comment]
Thanks! This worked. Knew it was me.
