### ISSUE TITLE
Can't remove DRM from Kindle for PC 1.30 with AZW3 patch

### ISSUE THREAD

**Issue by poopingpenis** [noDRM/DeDRM_tools#123]
### Question / bug report

I installed Kindle for PC 1.30 and the [patch](https://github.com/apprenticeharper/DeDRM_tools/wiki/Exactly-how-to-remove-DRM) to make it download only in AZW3 format.

Anyway, I had to install a very outdated version of Python 3 in Wine for it to get as far as it did, but the crypto dependencies it needs require Visual C++ 14.0 which I can't install over Wine at all. It would be brilliant if it could, on Linux, use Python natively.

I'm using Calibre through Flatpak.

### Which version of Calibre are you running?

6.2.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

1.30

### Log output

```log
DeDRM v10.0.3: Trying to decrypt B09T5JYMYH_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Fascinating Origin of the Dominican Republic
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
DeDRM v10.0.3: Exception when getting default Kindle Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/duds/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/duds/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 975, in KindleMobiDecrypt
    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
  File "/home/duds/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "/home/duds/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
    self.check_call(["-c", self.py3_test])
  File "/home/duds/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 364, in check_call
  File "subprocess.py", line 345, in call
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1842, in _execute_child
FileNotFoundError: [Errno 2] No existe el fichero o el directorio: 'wine'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/duds/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/duds/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

```

**Comment by ElleKayEm** [comment]
Try using the official Linux calibre: https://calibre-ebook.com/download_linux

**Comment by poopingpenis** [comment]
> Try using the official Linux calibre: https://calibre-ebook.com/download_linux

Same issue. Still tries using Python inside of wine.

**Comment by noDRM** [comment]
I did some crypto cleanup in 10.0.3, maybe I fucked something up. Would you mind testing 10.0.2 and see if the same error occurs with that, and post a log of the same book with 10.0.2?

**Comment by ElleKayEm** [comment]
Would they need to use a previous 5.x version of calibre with 10.0.2?

**Comment by noDRM** [comment]
Damn, I didn't check the version. Yes, for 10.0.2 you'll probably need Calibre 5.x. I can try to make a patched version of 10.0.2 later that just has the Calibre-6 fixes and none of the other 10.0.3 changes, just in case this issue is related to Calibre 6 somehow (but I doubt that).

**Comment by poopingpenis** [comment]
> I did some crypto cleanup in 10.0.3, maybe I fucked something up. Would you mind testing 10.0.2 and see if the same error occurs with that, and post a log of the same book with 10.0.2?

No luck here either. Same problem using Calibre 5.44.0 and DeDRM_tools 10.0.2. It tries to run the Python script inside of Wine, instead of natively, which I think is the problem. I can't install Python and the script's dependencies inside Wine.

```log
DeDRM v10.0.2: Trying to decrypt B09T5JYMYH_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Fascinating Origin of the Dominican Republic
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.0 seconds
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.2: wine py.exe -3 is not python3
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.2: wine python3.exe is not python3
Application could not be started, or no application associated with the specifie
d file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.2: wine python.exe is not python3
wine: failed to open "C:\\Python27\\python.exe": c0000135
DeDRM v10.0.2: wine C:\Python27\python.exe does not exist
DeDRM v10.0.2: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.2: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```

**Comment by noDRM** [comment]
The script needs to be executed in WINE - after all, it needs to load / extract the cryptography keys from the Kindle4PC installation that's running under WINE. Taking the Windows script and just running it under wine is way easier than writing a wine-aware Linux python script that can run under a native Linux Python interpreter and still read data from an application that's running under WINE. 

What's the issue with running Python under WINE? As far as I know, that's the solution most Linux users used to get the Kindle 4 PC key. 

As a workaround - but I'm not sure if that's going to work - you could try running the Windows version of Calibre in the same WINEPREFIX as your Kindle4PC installation, then run the plugin inside that. That should use all the python binaries and packages that come included with the Windows Calibre. Once the plugin is loaded and you've dumped the Kindle 4 PC key, you can then extract the key from the Windows Calibre and import it in your Linux calibre.

**Comment by poopingpenis** [comment]
> The script needs to be executed in WINE - after all, it needs to load / extract the cryptography keys from the Kindle4PC installation that's running under WINE. Taking the Windows script and just running it under wine is way easier than writing a wine-aware Linux python script that can run under a native Linux Python interpreter and still read data from an application that's running under WINE.
> 
> What's the issue with running Python under WINE? As far as I know, that's the solution most Linux users used to get the Kindle 4 PC key.
> 
> As a workaround - but I'm not sure if that's going to work - you could try running the Windows version of Calibre in the same WINEPREFIX as your Kindle4PC installation, then run the plugin inside that. That should use all the python binaries and packages that come included with the Windows Calibre. Once the plugin is loaded and you've dumped the Kindle 4 PC key, you can then extract the key from the Windows Calibre and import it in your Linux calibre.

The problem is it's hard to find a Python 3 version that works with WINE (I had to use a really outdated one before forgetting the version after switching distros two days ago due to a separate issue), and then there's the Python crypto module dependencies themselves which include Visual C++ 14.0 (can't install in WINE at all).

I'll try again as I'm on a new setup now anyway, so may as well, but idk how well it'll go ; ;

**Comment by poopingpenis** [comment]
Log after installing the latest Python 3 with WINE after changing its system version to Windows 8.1 in winecfg:
```log
DeDRM v10.0.2: Trying to decrypt B09T5JYMYH_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Fascinating Origin of the Dominican Republic
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.0 seconds
DeDRM v10.0.2: Python3 exec found as wine py.exe -3
DeDRM v10.0.2: Running kindlekey.py under Wine
kindlekey.py v3.0
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\duds\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\users\duds\AppData\Local\Amazon\Kindle\storage\.kinf2018
Traceback (most recent call last):
  File "Z:\home\duds\.config\calibre\plugins\DeDRM\libraryfiles\kindlekey.py", line 1835, in <module>
    sys.exit(cli_main())
  File "Z:\home\duds\.config\calibre\plugins\DeDRM\libraryfiles\kindlekey.py", line 1776, in cli_main
    if not getkey(outpath, files):
  File "Z:\home\duds\.config\calibre\plugins\DeDRM\libraryfiles\kindlekey.py", line 1709, in getkey
    keys = kindlekeys(files)
  File "Z:\home\duds\.config\calibre\plugins\DeDRM\libraryfiles\kindlekey.py", line 1696, in kindlekeys
    key = getDBfromFile(file)
  File "Z:\home\duds\.config\calibre\plugins\DeDRM\libraryfiles\kindlekey.py", line 1146, in getDBfromFile
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
DeDRM v10.0.2: Wine subprocess call error: 1
DeDRM v10.0.2: Found and decrypted 0 key files
DeDRM v10.0.2: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Fascinating Origin of the Dominican Republic
Error getting PIDs from database default_key_1: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
Error getting PIDs from database default_key_2: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
Found 0 keys to try after 2.9 seconds
Crypto Type is: 2
DeDRM v10.0.2: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```
Now I'll try getting those dependencies from pip, but this is where I last got stuck.

**Comment by poopingpenis** [comment]
I actually managed to install pycryptodome without the Visual C++ requirement thrust onto me, but now I get this error, which I don't know how to get through at all...
```log
DeDRM v10.0.2: Trying to decrypt B09T5JYMYH_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Fascinating Origin of the Dominican Republic
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.0 seconds
DeDRM v10.0.2: Python3 exec found as wine py.exe -3
DeDRM v10.0.2: Running kindlekey.py under Wine
kindlekey.py v3.0
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\duds\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\users\duds\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1124073472' and UserName 'duds'
Saved a key to Z:\home\duds\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey1.k4i
DeDRM v10.0.2: Found and decrypted 1 key file
DeDRM v10.0.2: Found 2 new keys
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Fascinating Origin of the Dominican Republic
Error getting PIDs from database default_key_1: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
Error getting PIDs from database default_key_2: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
Found 0 keys to try after 2.9 seconds
Crypto Type is: 2
DeDRM v10.0.2: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```

**Comment by poopingpenis** [comment]
I fixed it by just going back to the latest versions of both Calibre and DeDRM_tools and using installing pycryptodome on pip through WINE. The latest versions of Python 3 *do* work in WINE as long as you set your system to Windows 8.1 on winecfg and run it in a 32-bit prefix.
