### ISSUE TITLE
Not able to install DeDRM_tools in calibre

### ISSUE THREAD

**Issue by amroc** [noDRM/DeDRM_tools#124]
Not sure what the issue is but I always get this issue if I try to install any version of the plugin.

calibre, version 5.42.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'A:\\Users\\Axxxx\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22621 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.8.5
Windows: ('10', '10.0.22621', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: EpubMerge (2, 13, 0) && EpubSplit (3, 3, 0) && Find Duplicates (1, 9, 5)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 326, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 283, in load
  File "calibre\customize\zipplugin.py", line 378, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'A:\\Users\\Axxxx\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by amroc** [comment]
It was my mistake. I had to extract the zip and then use the DeDRM plugin zip.
