### ISSUE TITLE
Adobe DRM not removed

### ISSUE THREAD

**Issue by Piseed** [noDRM/DeDRM_tools#126]
### Question / bug report

Bought a book on a site which, as the information on it say, uses Adobe DRM for PDFs. Extracted it through program files with an Android file manager, installed the plugin for calibre, uploaded it there, but it didn't work.

### Which version of Calibre are you running?

6.3

### Which version of the DeDRM plugin are you running?

v.10.0.3

### Log output

```log
Paste log output here.
```
calibre, version 6.3.0
ERROR: Loading book failed: Failed to open the book at C:\Users\misha\Calibre Library\Unknown\Puzakov S. Himia Sbornik zadach 10-1 (2)\Puzakov S. Himia Sbornik zadach - Unknown.pdf. Click "Show details" for more info.

Failed to convert book: C:\Users\misha\Calibre Library\Unknown\Puzakov S. Himia Sbornik zadach 10-1 (2)\Puzakov S. Himia Sbornik zadach - Unknown.pdf with error:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 435, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 323, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
DeDRM v7.2.1: Trying to decrypt Puzakov S. Himia Sbornik zadach - Unknown.pdf
DeDRM v7.2.1: Puzakov S. Himia Sbornik zadach - Unknown.pdf is a PDF ebook
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 359, in adeptkeys
FileNotFoundError: [WinError 2] Unable to locate file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 461, in PDFDecrypt
  File "calibre_plugins.dedrm.adobekey", line 361, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Warning: May not be a PDF file (continuing anyway)

Syntax Error (56): Illegal character '>'

Syntax Error (71): Illegal character '{'

Syntax Error: Couldn't find trailer dictionary

Syntax Error: Couldn't find trailer dictionary

Syntax Error: Couldn't read xref table

pdfinfo errored out with return code: 1
InputFormatPlugin: PDF Input running
on C:\Users\misha\Calibre Library\Unknown\Puzakov S. Himia Sbornik zadach 10-1 (2)\Puzakov S. Himia Sbornik zadach - Unknown.pdf
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 821, in viewer_main
  File "calibre\srv\render_book.py", line 812, in render_for_viewer
  File "calibre\srv\render_book.py", line 789, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 51, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Warning: May not be a PDF file (continuing anyway)

Syntax Error (56): Illegal character '>'

Syntax Error (71): Illegal character '{'

Syntax Error: Couldn't find trailer dictionary

Syntax Error: Couldn't find trailer dictionary

Syntax Error: Couldn't read xref table
Exception ignored in: <function NativeFunction.__del__ at 0x0000023401D42DD0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x0000023401D42DD0>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
Log shows you're using DeDRM 7.2.1.  So first update to 10.0.3.  Then you'll either need Adobe Digital Editions authorized with your Adobe ID on the same machine and user as calibre with DeDRM or you can use the ACSM Input plugin: https://www.mobileread.com/forums/showthread.php?t=341975

**Comment by Piseed** [comment]
Well, actually I messed up versions of the repository and versions of the plugin. Looks like 7.2.1 is the latest

**Comment by ElleKayEm** [comment]
For calibre 6, use DeDRM 10.0.3.  An ACSM file is what you use to download an Adobe DRM epub or pdf via ADE or the ACSM plugin.  If you downloaded the pdf another way, was it authorized with your Adobe ID?  You need to use ADE or the ACSM Input plugin so DeDRM can get
