### ISSUE TITLE
DeDRM not decrypting because of incorrect key

### ISSUE THREAD

**Issue by NWJeff** [noDRM/DeDRM_tools#129]
### Question / bug report

Book added to library from e-ink kindle is not getting decrypted. Log shows that key is incorrect. Same results after reinstalling the DeDRM plug in. Book on kindle opens ok. Same result for most of the other books on kindle, too.

### Which version of Calibre are you running?

6.3.0

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

5.12.2.2

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.3  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (10, 0, 3) && Overdrive Link (2, 51, 0)
calibre 6.3  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (10, 0, 3) && Overdrive Link (2, 51, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 101.07357512953367
[0.00] Starting up...
[0.00] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.31] db initialized
[0.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.69] main UI initialized...
[1.69] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing F:\documents\101 of the Best Free Websites for Climbing Your Family Tree (Genealogy Book 1)_B004RR1CEA.kfx
[6.59] splash screen hidden
[6.59] Started up in 6.59 seconds with 457 books
Storage number map:
{(7, 0): [(3, 'C'), (5, 'D')], (7, 1): [(1, 'F')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\B0D4220433650AMV&0: StorageDeviceNumber(type=7, number=1, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=14)
{'drive_letters': ['F'],
 'pnp_id_map': {'F': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#b0d4220433650amv&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'F': (1, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.5 USBMS: scan from root False F:\documents
Job: 1 Set library information finished
No details available.
DEBUG:    9.5 USBMS: count found in cache: 434, count of files in metadata: 434, need_sync: False
DEBUG:    9.5 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    9.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    9.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 434
DeviceJob: set_books_in_library finished: time= 0.10799670219421387
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 2 Get list of books on device finished
No details available.
Job: 3 Prepare files for transfer from device started
DeviceJob: 3 Prepare files for transfer from device done, calling callback
DeviceJob: 3 Prepare files for transfer from device callback returned
Job: 3 Prepare files for transfer from device finished
No details available.
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\toomu\AppData\Local\Temp\calibre_is6d5wx1\dz69bdnq.kfx-zip
DeDRM v10.0.3: Trying to decrypt dz69bdnq.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: dz69bdnq
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: voucher
Traceback (most recent call last):
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\toomu\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\toomu\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '142114821' and UserName 'toomu'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: dz69bdnq
Got DSN key from database key_0
Found 1 keys to try after 0.4 seconds
Decrypting KFX DRM voucher: voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\toomu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.49.0: Packaging C:\Users\toomu\AppData\Local\Temp\calibre_is6d5wx1\dz69bdnq.kfx-zip
Processing container: 101 of the Best Free Websites for Climbing Your Family Tree (Genealogy Book 1)_B004RR1CEA.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container 101 of the Best Free Websites for Climbing Your Family Tree (Genealogy Book 1)_B004RR1CEA.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\toomu\AppData\Local\Temp\calibre_is6d5wx1\kmfvg00g_add_books\0\101 of the Best Free WebsiAdded 101 of the Best Free Websites for Climbing Your Family Tree (Genealogy) to db in: 3.0
Added 1 books in 4.6 seconds
DeviceJob: set_books_in_library: books to process= 434
DeviceJob: set_books_in_library finished: time= 0.0008521080017089844

```

**Comment by ElleKayEm** [comment]
KFX format directly from a Kindle cannot be decrypted.  Use another method to get a copy that can be decrypted: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by NWJeff** [comment]
ElleKayEm --- thank you for the reply. In the post that you refer to is listed Method 3, Import from e-ink Kindle. That is what I am attempting to do, I believe.

**Comment by ElleKayEm** [comment]
Yes, method 3 downloading from the website should work for you as long as it's an E-ink Kindle (not a Fire).  Your Kindle is too new to get the book directly from the Kindle itself.  The website download will get you the older decryptable format instead of KFX.

**Comment by NWJeff** [comment]
My understanding after reading the FAQs, readme files and associated information for the DeDRM plugin (as well as the KFX input plugin that DeDRM works in conjunction with) is that an KFX file imported from an e-ink kindle device to Calibre should have its DRM removed. The log file shows that removal is attempted but for some reason, the error "Exception: Incorrect padding - Wrong key" occurs. I have tried reinstalling the DeDRM plugin and deleting/re-entering the Kindle device serial number but the error still exists. Why does the plugin keep getting incorrect padding for the decrypted key? I have tried examining the code but my python is not very good and also the currently available plugin still uses the alfcrypt code. Might a plugin update with the new python code for decryption help troubleshoot this problem? Thank you for your help. I would like to get this to work directly from the e-ink Kindle I already have and not use the outdated PC Kindle software.

**Comment by ElleKayEm** [comment]
The DRM on KFX files downloaded directly to a Kindle cannot be removed.  The only KFX files which can be decypted at this time are those downloaded with Kindle for PC/Mac version 1.26 or earlier.

Since you have an E-ink Kindle, you can download a non-KFX format from the website and decrypt that -- avoiding Kindle for PC.  Unless a book is one of the few that is only available in KFX format.

**Comment by noDRM** [comment]
Closing this issue, as this (no support for KFX) is a known issue that I doubt is getting fixed soon. 

Stick with old K4PC/K4Mac versions, or books downloaded for USB transfer for an eInk Kindle.
