### ISSUE TITLE
Unable to decrypt ADE epub

### ISSUE THREAD

**Issue by smolz** [noDRM/DeDRM_tools#133]
### Question / bug report

Trying to dedrm an ADE ePub, gets added with nothing removed.  Log output below

### Which version of Calibre are you running?

6.3

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
DeDRM v10.0.3: Trying to decrypt Flip.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Flip.epub is a secure Adobe Adept ePub for UUID xxxxxxxxx
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[58.16] splash screen hidden
[58.16] Started up in 58.16 seconds with 2 books```

**Comment by ElleKayEm** [comment]
There's a bug where if there is something wrong with the saved key, DeDRM doesn't try to retrieve a new one.  Delete the Adobe key from DeDRM's customization.  Re-add the book and let it automatically retrieve the correct key.

**Comment by smolz** [comment]
Yup , that did it!  thanks!
