### ISSUE TITLE
dedrm .tpz file failed

### ISSUE THREAD

**Issue by tshemeng** [noDRM/DeDRM_tools#135]
### Question / bug report

Key is: G090G10573140D10
[demo_tpz_files.zip](https://github.com/noDRM/DeDRM_tools/files/9438915/demo_tpz_files.zip)

### Which version of Calibre are you running?

6.3.0

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

1.36.0 (65107)

### Log output

```log
calibre, version 6.3.0
WARNING: Error while saving: Failed to update metadata in some books, click "Show details" for more information

Failed to update the metadata in the TPZ format of: 2 by Unknown, with error:
    Traceback (most recent call last):
      File "calibre\customize\ui.py", line 454, in set_file_type_metadata
      File "calibre\customize\builtins.py", line 548, in set_metadata
      File "calibre\ebooks\metadata\topaz.py", line 381, in set_metadata
      File "calibre\ebooks\metadata\topaz.py", line 112, in __init__
    ValueError: 'E:\Unknown\2\2 - Unknown.tpz': Invalid Topaz format - no metadata record


______________________________________________________________________

Failed to update the metadata in the TPZ format of: 1 by Unknown, with error:
    Traceback (most recent call last):
      File "calibre\customize\ui.py", line 454, in set_file_type_metadata
      File "calibre\customize\builtins.py", line 548, in set_metadata
      File "calibre\ebooks\metadata\topaz.py", line 381, in set_metadata
      File "calibre\ebooks\metadata\topaz.py", line 112, in __init__
    ValueError: 'E:\Unknown\1\1 - Unknown.tpz': Invalid Topaz format - no metadata record

```

**Comment by ElleKayEm** [comment]
These books where downloaded to or for the Paperwhite Kindle that you have given the serial number for?

Can you [post a log](https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that) of adding a book to calibre so we can see what is happening with your setup?  Just add one book only.

**Comment by tshemeng** [comment]
I download these books from amazon.cn, Kindle Paperwhite Key is: G090G10573140D10.
[](url)
[tmpt_t3gxcz.txt](https://github.com/noDRM/DeDRM_tools/files/9440034/tmpt_t3gxcz.txt)

**Comment by ElleKayEm** [comment]
When you downloaded from the website, you chose that Paperwhite for the device?  Have you tried with Kindle for PC at all?

**Comment by tshemeng** [comment]
I tried Kindle & Kindle for PC, both have the same issue.

**Comment by ChangITP** [comment]
I meet the same issue and also, my book is downloaded from amazon.cn

**Comment by ElleKayEm** [comment]
Post a log and we'll take a look.

**Comment by ChangITP** [comment]
Here is the log file
[calibre_log.txt](https://github.com/noDRM/DeDRM_tools/files/11483783/calibre_log.txt)

**Comment by ElleKayEm** [comment]
Looks like it's probably a bug.  Assume the book is from or for an E-ink Kindle and that you have the Kindle's serial number entered in DeDRM's customization.  Are you able to decrypt other books for that Kindle?

Rarer formats like this haven't gotten much testing on newer versions of DeDRM.  You might actually have luck with calibre 4.23 and DeDRM 6.8.1.

https://download.calibre-ebook.com/4.23.0/
https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

**Comment by ChangITP** [comment]
In my kindle library, it is the only one in .tpz format. \
All other books are in .azw3 format. And the DeDRM works fine on them.

Fortunately, the calibre 4.23 and DeDRM 6.8.1 can decrypt the .tpz one successfully.
Thank you very much！

**Comment by ElleKayEm** [comment]
Thanks for reporting back that it worked!

**Comment by pratt360** [comment]
Unfortunately I'm still having some trouble with the older versions of both DeDRM and the portable version of Calibre 4.23.

**Comment by pratt360** [comment]
Here's a log file.
[tmpg2o2fl.txt](https://github.com/noDRM/DeDRM_tools/files/12046686/tmpg2o2fl.txt)

**Comment by pratt360** [comment]
I actually now just found a way to get an AZW file of the book I'm trying to strip the DRM from by downloading it through an older version of the Kindle for PC software, but now when I try to convert that file to EPUB it fails. Here's another log file after it fails to convert.
[tmp_3it81tc.txt](https://github.com/noDRM/DeDRM_tools/files/12046868/tmp_3it81tc.txt)

**Comment by ElleKayEm** [comment]
Your first log is calibre 4.23, but DeDRM 10.0.3.  Try DeDRM 6.8.1 with calibre 4.23.  The book in the second log is still Topaz.  All books downloaded with Kindle for PC have the azw extension no matter the underlying format.
