### ISSUE TITLE
DRM not removed

### ISSUE THREAD

**Issue by somegirlinhere** [noDRM/DeDRM_tools#145]
### Question / bug report

Bought a book on a site which, as the information on it say, uses Adobe DRM for ePUBs. Added it to Adobe Digital Editions to get the ePUB (my computer is authorized for ADE). When importing it to calibre I can't open the eBook.

The installed Adobe Digital Editions Version is: 4.5.11.187607

I'm currently running MacOS 12.5 (if that's relevant)

### Which version of Calibre are you running?

6.4.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.4  embedded-python: True
macOS-12.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110')
Python 3.10.1
OSX: ('12.5', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.4  embedded-python: True
macOS-12.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110')
Python 3.10.1
OSX: ('12.5', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.5000019298764 x 128.5000019298764
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.98] main UI initialized...
[0.98] Hiding splash screen
[0.99] splash screen hidden
[0.99] Started up in 0.99 seconds with 1 books
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Unterricht kompetent planen (E-Book).epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Unterricht kompetent planen (E-Book).epub is a secure Adobe Adept ePub for UUID 251386d9-147c-46dd-92c4-d4024260d23c
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
    userkey = codecs.decode(userkeyhex, 'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Added Unterricht kompetent planen (E-Book) to db in: 0.0
Added 1 books in 0.4 seconds
```

**Comment by ElleKayEm** [comment]
There is a bug where if there is an issue with the saved Adobe key, DeDRM doesn't looked for the correct one.  Delete the saved Adobe key from DeDRM's customization.  Then re-add your book letting DeDRM automatically retrieve the key.
