### ISSUE TITLE
`MemoryError` when processing large books

### ISSUE THREAD

**Issue by dingwen07** [noDRM/DeDRM_tools#15]
I tried to import and remove DRM for some manga with size of about 500MB (Amazon Kindle `AZW3` format), finding the plugin is failing due to `MemoryError`. Here is the log:

```
Extensions: frozenset({'azw3'})
Decrypted key file using IDString '2024375763' and UserName ''
DeDRM v10.0.2: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
DeDRM v10.0.2: Ultimately failed to decrypt after 3.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.mobidedrm", line 331, in __init__
  File "calibre_plugins.dedrm.mobidedrm", line 392, in patchSection
  File "calibre_plugins.dedrm.mobidedrm", line 382, in patch
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 223, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 341, in __init__
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 3.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/maAdded
```

My system has 16GB of RAM. I tried to close as much running software as possible, leaving the available memory to be at least 4.2GB, but this did not help. I suspect that available memory is not the problem because the operating system will use page files to ensure that the software has enough memory to address. Does Calibre have memory limitations for the extension? I tried some search but didn't find any documentation.

**Comment by ElleKayEm** [comment]
If on Windows, are you using 64-bit calibre?

**Comment by dingwen07** [comment]
I am using Calibre Portable to remove DRM; the portable version is 32-bit. The issue was resolved using the 64-bit installer version.
