### ISSUE TITLE
Fails to import azw file due to "ValueError: embedded null character"

### ISSUE THREAD

**Issue by LupeChristoph** [noDRM/DeDRM_tools#151]
### Question / bug report

While I can read other azw files OK, this particular file is not imported.

### Which version of Calibre are you running?

6.4.0

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

1.31.0

### Log output

```log
calibre, version 6.4.0 (win32, embedded-python: True)
Konvertierungsfehler: Fehlgeschlagen: Buch 1 von 1 (CR!KDA0S32TF914FFSEM4N2T6AN0KPQ.azw) konvertieren

Buch 1 von 1 (CR!KDA0S32TF914FFSEM4N2T6AN0KPQ.azw) konvertieren
Conversion options changed from defaults:
  verbose: 2
  cover: 'C:\\Users\\Lupe\\AppData\\Local\\Temp\\calibre_g1a4wleg\\o26kjzoo.jpeg'
  read_metadata_from_opf: 'C:\\Users\\Lupe\\AppData\\Local\\Temp\\calibre_g1a4wleg\\gzkdirm8.opf'
Resolved conversion options
calibre version: 6.4.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\Lupe\\AppData\\Local\\Temp\\calibre_g1a4wleg\\o26kjzoo.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'formatting_type': 'auto',
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001BE92D60250>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markdown_extensions': 'footnotes, tables, toc',
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x000001BE92D63EB0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paragraph_type': 'auto',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'preserve_spaces': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\Lupe\\AppData\\Local\\Temp\\calibre_g1a4wleg\\gzkdirm8.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'txt_in_remove_indents': False,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: TXT Input running
on C:\Users\Lupe\AppData\Local\Temp\calibre_g1a4wleg\2etznv5g.md
Reading text from file...
File extension indicates particular formatting. Forcing formatting type to: markdown
Detected input encoding as iso-8859-1 with a confidence of 100%
Running text through markdown conversion...
Language not specified
Creator not specified
Building file list...
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\txt_input.py", line 310, in convert
  File "calibre\ebooks\conversion\plugins\html_input.py", line 90, in convert
  File "calibre\ebooks\conversion\plugins\html_input.py", line 153, in create_oebbook
  File "calibre\ebooks\html\input.py", line 287, in get_filelist
  File "calibre\ebooks\html\input.py", line 265, in traverse
  File "calibre\ebooks\html\input.py", line 109, in __init__
ValueError: embedded null character
IgnoreFile('Could not read from file: C:\\Users\\Lupe\\AppData\\Local\\Temp\\calibre_g1a4wleg\\oiwjo3ix_plumber\\»\x9b\x90L$ò\x05\x923ôØë\x96\\\x16\x98\x16\xa0MfåÙ>?9ãQ\x8aE;\x95$\x15,\x7fz  ö¹¹ÈÇ{\x9dò¬\x86çÅ\xad\x1dükñÈù\x04cîñºû«¤¾\x1dµÊ\x15¢¦\x17*éý}\'×ÑrE\x8d\x87üB»U with error: [Errno 22] Invalid argument: "C:\\\\Users\\\\Lupe\\\\AppData\\\\Local\\\\Temp\\\\calibre_g1a4wleg\\\\oiwjo3ix_plumber\\\\»\\x9b\\x90L$ò\\x05\\x923ôØë\\x96\\\\\\x16\\x98\\x16\\xa0MfåÙ>?9ãQ\\x8aE;\\x95$\\x15,\\x7fz  ö¹¹ÈÇ{\\x9dò¬\\x86çÅ\\xad\\x1dükñÈù\\x04cîñºû«¤¾\\x1dµÊ\\x15¢¦\\x17*éý}\'×ÑrE\\x8d\\x87üB»U"')
IgnoreFile("Could not read from file: C:\\Users\\Lupe\\AppData\\Local\\Temp\\calibre_g1a4wleg\\oiwjo3ix_plumber\\ª\x05 ÃÖ\x81aø\x041½ûý\x12«=¨Ê]\x8b\x152tD\x12^\x17\x11¸KÕe5ø@Û\x92UÔ-\x95\x8aß½LJ}¤¥\x87¨EfÀ(ÚLvÐ¤d\x04x\x8cÒÈw¹}*4\x91É\x95©8!£µ \x80K\x9eDm\x19Z\x0bA\x08\x0e[VL¾À\x93u\x90v<Ý\x13ÏI²Î±Þ\x92Yg\x1e\x04l\x98Ógî\x85=Úf¤\xadn\x8cÑ\x7f\x9a*Ì\x8b-\x01\x8aÃÈßðï\x04*j<X\x86ÀØ+\x8c\xa0\x158ñ%ÂR\x8b$Í\x1cC³NÅA\xad\x9añs\x80 BÐü_bl\xa0\xa0DÚoñú\x17Ã\x9a with error: [Errno 22] Invalid argument: 'C:\\\\Users\\\\Lupe\\\\AppData\\\\Local\\\\Temp\\\\calibre_g1a4wleg\\\\oiwjo3ix_plumber\\\\ª\\x05 ÃÖ\\x81aø\\x041½ûý\\x12«=¨Ê]\\x8b\\x152tD\\x12^\\x17\\x11¸KÕe5ø@Û\\x92UÔ-\\x95\\x8aß½LJ}¤¥\\x87¨EfÀ(ÚLvÐ¤d\\x04x\\x8cÒÈw¹}*4\\x91É\\x95©8!£µ \\x80K\\x9eDm\\x19Z\\x0bA\\x08\\x0e[VL¾À\\x93u\\x90v<Ý\\x13ÏI²Î±Þ\\x92Yg\\x1e\\x04l\\x98Ógî\\x85=Úf¤\\xadn\\x8cÑ\\x7f\\x9a*Ì\\x8b-\\x01\\x8aÃÈßðï\\x04*j<X\\x86ÀØ+\\x8c\\xa0\\x158ñ%ÂR\\x8b$Í\\x1cC³NÅA\\xad\\x9añs\\x80 BÐü_bl\\xa0\\xa0DÚoñú\\x17Ã\\x9a'")
IgnoreFile("Could not read from file: C:\\Users\\Lupe\\AppData\\Local\\Temp\\calibre_g1a4wleg\\oiwjo3ix_plumber\\e\\\x8e7Z\x93äÍÛ\x9a÷©¢Ýb4Òö\x85\x95¤é\x9f\x19ñäO\x951Í a,q(\x87s!\x91·\x0f$\x8c\x8a\xa0\x90Ô]¨êWê,\x0eÎ®\x8e<l¬@Ø\x14ñ\x86õHKì$\xa0\x05©«¶ p=H:£®YöýÇøõÝ;º:T¶ with error: [Errno 22] Invalid argument: 'C:\\\\Users\\\\Lupe\\\\AppData\\\\Local\\\\Temp\\\\calibre_g1a4wleg\\\\oiwjo3ix_plumber\\\\e\\\\\\x8e7Z\\x93äÍÛ\\x9a÷©¢Ýb4Òö\\x85\\x95¤é\\x9f\\x19ñäO\\x951Í a,q(\\x87s!\\x91·\\x0f$\\x8c\\x8a\\xa0\\x90Ô]¨êWê,\\x0eÎ®\\x8e<l¬@Ø\\x14ñ\\x86õHKì$\\xa0\\x05©«¶ p=H:£®YöýÇøõÝ;º:T¶'")
IgnoreFile("Could not read from file: C:\\Users\\Lupe\\AppData\\Local\\Temp\\calibre_g1a4wleg\\oiwjo3ix_plumber\\ÈåtÆ[\x9f«\x98ôÑDçÙlÖ¬Ûd¥Y$°ÔPÝýMÛ\x9dü-¬ü\x9e with error: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Lupe\\\\AppData\\\\Local\\\\Temp\\\\calibre_g1a4wleg\\\\oiwjo3ix_plumber\\\\ÈåtÆ[\\x9f«\\x98ôÑDçÙlÖ¬Ûd¥Y$°ÔPÝýMÛ\\x9dü-¬ü\\x9e'")
```

**Comment by ElleKayEm** [comment]
Can't tell what happened with DRM removal with this conversion log.  Let's see a log of adding the book:  https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by LupeChristoph** [comment]
No worries, I tried to import some other file, and while that seemed to work, the result war a big file of funny characters. I'll close this ticket. The NUL character was probably generated by the bad import.

**Comment by ElleKayEm** [comment]
> the result was a big file of funny characters

Sounds like it wasn't decrypted then.  Post an import log if you want help.

**Comment by LupeChristoph** [comment]
I did not remember that you have to use an old version of the Kindle program. It updated itself when I started it and the KFX Input picked up something DeDRM could not decode. Neither plugin noticed a problem.

**Comment by ElleKayEm** [comment]
You won't see an error about DRM on import unless you do it in debug mode.  If you've sorted it out, you can close the issue.  Otherwise, happy to help.

**Comment by LupeChristoph** [comment]
Nothing more to contribute, closing the ticket.
