### ISSUE TITLE
DeDRM Plugin Fails to Install in Calibre 4.99.4

### ISSUE THREAD

**Issue by lhhel9l3** [noDRM/DeDRM_tools#155]
Installing the latest release 10.0.3 fails in Calibre 4.99.4. Stack trace below:

```
calibre 4.99.4  embedded-python: False is64bit: True
Linux-5.15.0-46-generic-x86_64-with-glibc2.29 Linux ('64bit', 'ELF')
('Linux', '5.15.0-46-generic', '#49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022')
Python 3.8.10
Interface language: None
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 319, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.dedrm.__init__", line 117, in <module>
ModuleNotFoundError: No module named '__version'
```

**Comment by ElleKayEm** [comment]
You may run into additional problems using this version of calibre.  Recommend using the official Linux calibre with its embedded Python.

**Comment by ElleKayEm** [comment]
Here's the official one: https://calibre-ebook.com/download_linux

**Comment by keithstellyes** [comment]
As a workaround: https://github.com/noDRM/DeDRM_tools/issues/329#issuecomment-1912842807
