### ISSUE TITLE
DRM removal for FKZ-ZIP failed

### ISSUE THREAD

**Issue by JorgeBoado** [noDRM/DeDRM_tools#16]
### Question / bug report

Hi, is my first day using this plugin so maybe I'm doing somethign wrong.
I downloaded 2 eBooks from the Kindle 1.26 version on PC and the first one (Dune) was in FKZ and the DRM removal was success full, but the second one (Dark Souls. Beyond the Grave - Volume 2) is in format FKZ-ZIP and this one failed when I tried to convert in AWZ3.
After that I tried with other few books that I have on Amazon and all of them were FKZ-ZIP, so I tried with those ones too and nothing. I always get the error with the FKZ-ZIP format eBooks.
Someone can help me or there's a known solution for this?

### Which version of Calibre are you running?

v5.34 Portable

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1.26

### Log output

```log
calibre Registro de depuración
calibre 5.34 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0)
calibre 5.34 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 101.6 x 101.6
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.41] splash screen shown
[0.41] Initializing db...
[0.41] db initialized
[0.41] Constructing main UI...
[0.95] main UI initialized...
[0.95] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.46.0: Importing C:\Users\Jorge\Documents\My Kindle Content\B07NWPP5LJ_EBOK\B07NWPP5LJ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\Jorge\AppData\Local\Temp\calibre__jt7i_33\mcekg9rq.kfx-zip
DeDRM v10.0.2: Trying to decrypt mcekg9rq.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: mcekg9rq
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8921bba6-7e27-4fbb-a562-84b399ba74ec.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.2: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Jorge\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Jorge\AppData\Local\Amazon\Kindle\storage\.kinf2018
[12.53] splash screen hidden
[12.53] Started up in 12.53 seconds with 53 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe4r\xf1\x13\xe2F\x13`\x18\xc5\x1e#\xc6]+9\xce\x95\xf1\x15\xf1.\xd3-\x8e\xbc\xef\x9c\x87j\xfd\x12', b'C:\\Users\\Jorge\\Documents\\My Kindle Content\\B07NWPP5LJ_EBOK\\B07NWPP5LJ_EBOK.azw']
Decrypted key file using IDString '4029591085' and UserName 'Jorge'
DeDRM v10.0.2: Found 1 new key
Decrypting KFX-ZIP ebook: mcekg9rq
Got DSN key from database default_key_1
Found 1 keys to try after 2.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.8921bba6-7e27-4fbb-a562-84b399ba74ec.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "D:\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.2: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.46.0: Packaging C:\Users\Jorge\AppData\Local\Temp\calibre__jt7i_33\mcekg9rq.kfx-zip
Processing container: B07NWPP5LJ_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\Jorge\AppData\Local\Temp\calibre__jt7i_33\0i0t2uc0_add_books\0\B07NWPP5LJ_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 84, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book conAdded Dark Souls. Beyond the Grave - Volume 2: Bloodborne & Dark Souls III to db in: 6.0
Added 1 books in 9.2 seconds
```

**Comment by ElleKayEm** [comment]
Probably best to avoid KFX format.  Even though it should work if the books were downloaded with Kindle for PC 1.26.  At any rate, see this post for info on getting books in the older formats:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by JorgeBoado** [comment]
Okay, I'll try to get the Book in some older format.
I'll try tomorrow.

**Comment by JorgeBoado** [comment]
Just checked one thing.
Aparrently my Kindle App on PC updates to 1.30 I don't know how.

I just reinstall the 1.26 and it work like a charm.
Sorry for opening an Issue without checking all possibilities.

**Comment by ElleKayEm** [comment]
Kindle for PC will try any chance it gets to update.  See the link I gave above for a way to help prevent that.
