### ISSUE TITLE
Failing to remove DRM

### ISSUE THREAD

**Issue by chatlumo** [noDRM/DeDRM_tools#166]
### Question / bug report

Hello, I can't remove DRM, i used Calibre 5.4.4 and I tried with last version of Calibre 6 too.
I used Adobe Digital Editions 2.0 to open .acsm file.

### Which version of Calibre are you running?

5.4.4

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
calibre Journal de débogage
calibre 5.44  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 5.44  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.00000162199728 x 108.00000162199726
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[0.74] main UI initialized...
[0.74] Hiding splash screen
Starting QuickView
qt.qpa.fonts: Populating font family aliases took 398 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
DeDRM v10.0.3: Trying to decrypt xxxxx.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: xxxxx.epub is a secure Adobe Adept ePub for UUID f8a2af74-eaca-493f-9b99-e6520d7e5ae8
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
    defaultkeys, defaultnames = adeptkeys()
  File "/Users/julien/Library/Preferences/calibre/plugins/DeDRM.zip/adobekey.py", line 439, in adeptkeys
    raise ADEPTError("Could not find ADE activation.dat file.")
adobekey.ADEPTError: Could not find ADE activation.dat file.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[2.32] splash screen hidden
[2.32] Started up in 2.32 seconds with 2 books
Added xxxxx to db in: 0.0
Added 1 books in 0.6 seconds
Worker Launch took: 0.05 seconds
```

**Comment by ElleKayEm** [comment]
Is ADE authorized with your Adobe ID and on the same machine and user as calibre with DeDRM?

**Comment by chatlumo** [comment]
No, it's not the same machine (but ADE is authorized with Adobe ID).
The solution was to retry from a Windows PC, and it's now ok.
Thanks.

**Comment by ElleKayEm** [comment]
ADE needs to be on the same machine and user as calibre in order for DeDRM to retrieve the key initially.  If you're all set, you can close the issue.

**Comment by noDRM** [comment]
Assuming that this is fixed, closing the issue.
