### ISSUE TITLE
Failed to remove DRM from KFX-Zip file

### ISSUE THREAD

**Issue by kirkmcb** [noDRM/DeDRM_tools#169]
### Question / bug report

The plugin worked fine on the previous KFX-Zip book but failed to remove DRM from this one.

![image](https://user-images.githubusercontent.com/100996665/192659369-2404b1c8-2e31-4434-a1cf-a4580de8888a.png)

### Which version of Calibre are you running?

6.50

### Which version of the DeDRM plugin are you running?

7.2.1

### If applicable, which version of the Kindle software are you running?

1.2.4

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.5  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: en_AU
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (7, 2, 1)
calibre 6.5  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: en_AU
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.64] main UI initialized...
[0.64] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing C:\Users\kirkm\OneDrive\Documents\My Kindle Content\B08RCVR4T4_EBOK\B08RCVR4T4_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\kirkm\AppData\Local\Temp\calibre_pfzzsgcv\lwbk0cw5.kfx-zip
DeDRM v7.2.1: Trying to decrypt lwbk0cw5.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: lwbk0cw5
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.2771e6dd-b63f-45a1-96a7-b5f519db932e.voucher
KFX DRM voucher successfully decrypted
DeDRM v7.2.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\kirkm\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\kirkm\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '1550953632' and UserName 'kirkm'
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 95, in decrypt_voucher
Exception: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.49.0: Packaging C:\Users\kirkm\AppData\Local\Temp\calibre_pfzzsgcv\lwbk0cw5.kfx-zip
Processing container: B08RCVR4T4_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08RCVR4T4_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\kirkm\AppData\Local\Temp\calibre_pfzzsgcv\f94frs39_add_books\0\B08RCVR4T4_EBOK.kfx-zip
[4.34] splash screen hidden
[4.34] Started up in 4.34 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\x92\xd2\xf9\xa3[*I\xeb($&S\xcc\xbc`M\xa3\xed'\x15\x7f?\x9f\xd9A(n\x19\xdc\xcd\x1e\x93", b'C:\\Users\\kirkm\\OneDrive\\Documents\\My Kindle Content\\B08RCVR4T4_EBOK\\B08RCVR4T4_EBOK.azw']
Added Buddhism & the Twelve Steps Daily Reflections: Thoughts on Dharma and Recovery to db in: 0.1
Added 1 books in 0.5 seconds
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Buddhism & the Twelve Steps Daily Reflections: Thoughts on Dharma and Recovery) finished
Convert book 1 of 1 (Buddhism & the Twelve Steps Daily Reflections: Thoughts on Dharma and Recovery)
	DeDRM v7.2.1: Trying to decrypt i2cvrw9j.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: i2cvrw9j
	Got DSN key from database default_key
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.2771e6dd-b63f-45a1-96a7-b5f519db932e.voucher
	KFX DRM voucher successfully decrypted
	DeDRM v7.2.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\kirkm\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\kirkm\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '1550953632' and UserName 'kirkm'
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 95, in decrypt_voucher
	Exception: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  pdf_mono_family: 'Courier New'
	  pdf_serif_family: 'Arial'
	  cover: 'C:\\Users\\kirkm\\AppData\\Local\\Temp\\calibre_pfzzsgcv\\khubortv.jpeg'
	  pdf_sans_family: 'Arial'
	  verbose: 2
	  allow_conversion_with_errors: True
	  output_profile: 'kindle_pw3'
	  read_metadata_from_opf: 'C:\\Users\\kirkm\\AppData\\Local\\Temp\\calibre_pfzzsgcv\\725qo148.opf'
	Resolved conversion options
	calibre version: 6.5.0
	{'allow_conversion_with_errors': True,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': 'C:\\Users\\kirkm\\AppData\\Local\\Temp\\calibre_pfzzsgcv\\khubortv.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000027BA5EFC160>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x0000027BA5EFEA40>,
	 'page_breaks_before': '/',
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Arial',
	 'pdf_serif_family': 'Arial',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\kirkm\\AppData\\Local\\Temp\\calibre_pfzzsgcv\\725qo148.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	DeDRM v7.2.1: Trying to decrypt i2cvrw9j.kfx-zip
	Decrypting KFX-ZIP ebook: i2cvrw9j
	Got DSN key from database default_key
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.2771e6dd-b63f-45a1-96a7-b5f519db932e.voucher
	KFX DRM voucher successfully decrypted
	DeDRM v7.2.1: Failed to decrypt with error: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
	DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\kirkm\AppData\Local
	Found K4PC 1.9+ kinf2011 file: C:\Users\kirkm\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '1550953632' and UserName 'kirkm'
	DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
	  File "calibre_plugins.dedrm.kfxdedrm", line 95, in decrypt_voucher
	Exception: This book is licensed as KindleUnlimited. These tools are intended for use on purchased books.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 633, in run
	  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on C:\Users\kirkm\AppData\Local\Temp\calibre_pfzzsgcv\i2cvrw9j.kfx-zip
	Software versions: KFX Input 1.49.0, calibre 6.5, Windows-10-10.0.22000-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\kirkm\AppData\Local\Temp\calibre_pfzzsgcv\i2cvrw9j.kfx-zip
	Processing container: B08RCVR4T4_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08RCVR4T4_EBOK.azw has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 196, in _run_module_as_main
	  File "runpy.py", line 86, in _run_code
	  File "site.py", line 82, in <module>
	  File "site.py", line 77, in main
	  File "site.py", line 49, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
	  File "calibre\customize\conversion.py", line 242, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 125, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by kirkmcb** [comment]
I see you've updated the plugin to v10.0.0.  Can I pull the all the files in the new plugin down as a zip file from anywhere?

**Comment by kirkmcb** [comment]
It worked with the newer version.  Sorry for the inconvenience.
