### ISSUE TITLE
Fail to remove DRM in Kindle

### ISSUE THREAD

**Issue by hgpnguyen** [noDRM/DeDRM_tools#170]
### Question / bug report

Hello, I cann't remove DRM of my Kindle ebook. I have entered my Elink Kindle Serial Number and KFX Input plugin but it still failed to work.

### Which version of Calibre are you running?

6.2.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

Kindle Paperwhite (6th Generation) Kindle 5.12.2.2 (3791510038)

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22622-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22622')
Python 3.10.1
Windows: ('10', '10.0.22622', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22622-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22622')
Python 3.10.1
Windows: ('10', '10.0.22622', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.02] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[1.05] main UI initialized...
[1.05] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing D:\documents\Re_ZERO -Starting Life in Another World-, Vol. 17 (light novel)_B093ZQ8KZW.kfx
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Nghe\AppData\Local\Temp\calibre_pcz9qclp\vvry70ju.kfx-zip
Storage number map:
{(7, 0): [(3, 'C')], (7, 1): [(1, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0100\90172202515309MN&0: StorageDeviceNumber(type=7, number=1, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x4 bcd=0x100 devid=usb\vid_1949&pid_0004&rev_0100 devinst=3)
{'drive_letters': ['D'],
 'pnp_id_map': {'D': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0100#90172202515309mn&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'D': (1, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.1 USBMS: scan from root False D:\documents
DEBUG:    0.5 USBMS: count found in cache: 221, count of files in metadata: 221, need_sync: False
DEBUG:    0.5 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.5 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 221
DeviceJob: set_books_in_library finished: time= 0.007796287536621094
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
[17.19] splash screen hidden
[17.19] Started up in 17.19 seconds with 121 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe0,\x13\x94\xf5)xo\xac\xc3\x1b\xca<\xa9 \xd2ze\xa5=bn.\xf6\x9e\xbf\x08\xc7\xf5 \x1f;', b'D:\\documents\\Re_ZERO -Starting Life in Another World-, Vol. 17 (light novel)_B093ZQ8KZW.kfx']
DeDRM v10.0.3: Trying to decrypt vvry70ju.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: vvry70ju
Found 1 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: voucher
Traceback (most recent call last):
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Nghe\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Nghe\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '4001230616' and UserName 'Nghe'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: vvry70ju
Got DSN key from database key_0
Found 1 keys to try after 0.4 seconds
Decrypting KFX DRM voucher: voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Nghe\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.49.0: Packaging C:\Users\Nghe\AppData\Local\Temp\calibre_pcz9qclp\vvry70ju.kfx-zip
Processing container: CR!PVZ6H2ZENX7D1BGFSKJKQ1R3P7RW.kfx
Processing container: Re_ZERO -Starting Life in Another World-, Vol. 17 (light novel)_B093ZQ8KZW.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Re_ZERO -Starting Life in Another World-, Vol. 17 (light novel)_B093ZQ8KZW.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Nghe\AppData\Local\Temp\calibre_pcz9qclp\omgh3s9g_add_books\0\Re_ZERO -StAdded Re:ZERO -Starting Life in Another World-, Vol. 17 (light novel) to db in: 0.0
Added 1 books in 1.6 seconds

```

**Comment by hgpnguyen** [comment]
Thank you, I understand
