### ISSUE TITLE
Cannot remove FileOpen DRM

### ISSUE THREAD

**Issue by uyha** [noDRM/DeDRM_tools#171]
### Question / bug report

I want to remove the FileOpen DRM from my PDF but was not able to.

### Which version of Calibre are you running?

6.6.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.6.1  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.6.1  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.80] main UI initialized...
[0.80] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt ANSI+NEMA+Z535.4-2011.pdf
DeDRM v10.0.3: ANSI+NEMA+Z535.4-2011.pdf is a PDF ebook with encryption FOPN_foweb
DeDRM v10.0.3: FileOpen encryption 'FOPN_foweb' is unsupported.
DeDRM v10.0.3: Try the standalone script from the 'Tetrachroma_FileOpen_ineptpdf' folder in the Github repo.
DeDRM v10.0.3: Finished after 0.1 seconds
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 435, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
[61.88] splash screen hidden
[61.88] Started up in 61.88 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x12\xea\xbc\x03\xe6\xda6(\x04\x85`\xdc\xc6\xd1\xb6=mAt\xc0\xbd\xe2\xa3\x04\xe1\xffWB\xb5\xc6\x9ee', b'D:\\Downloads\\ANSI+NEMA+Z535.4-2011.pdf']
Added ANSI+NEMA+Z535.4-2011 to db in: 1.1
Syntax Error: Couldn't find the 'FOPN_foweb' security handler
pdfinfo errored out with return code: 1
```

**Comment by ElleKayEm** [comment]
As the log says:

> FileOpen encryption 'FOPN_foweb' is unsupported.
DeDRM v10.0.3: Try the standalone script from the 'Tetrachroma_FileOpen_ineptpdf' folder in the Github repo.

**Comment by uyha** [comment]
oh, ok, thanks.
