### ISSUE TITLE
DeDrm plugin failing to install in Calibre 6.6.1 ("No module named '__version'")

### ISSUE THREAD

**Issue by Boneist** [noDRM/DeDRM_tools#176]
### Question / bug report

Hi,

I just installed the latest version of Calibre (6.6.1) 64 bit, on Windows 10 and I wanted to update the DeDRM tools. I created a zip file of the latest code from master (clicked on the Code button and selected create zip file), unzipped that file once it had downloaded, and then  created a zip file each of the DeDRM and Obok plugin directories.

Over in Calibre, I was able to successfully install (via Preferences > Plugins > Install plugin from file) the Obok plugin, but the DeDRM plugin fails with "ModuleNotFoundError:No module named '__version'". I can see there's a file called "__version.py" in the directory, but nothing called just "__version".

Have I done something daft in my extraction of the code, or is there a genuine issue here? I've tried copying the "__version.py" file and renaming it "__version" but Calibre gives the same error.

### Which version of Calibre are you running?

6.6.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

calibre, version 6.6.1
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named '__version'

calibre 6.6.1  embedded-python: True
Windows-10-10.0.19043-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19043')
Python 3.10.1
Windows: ('10', '10.0.19043', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 1, 0) && Goodreads Sync (1, 15, 6) && KePub Input (3, 4, 3) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 5, 3) && Kobo Utilities (2, 16, 6) && KoboTouchExtended (3, 4, 4) && Manage Series (1, 4, 0) && Obok DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 305, in load
  File "polyglot\builtins.py", line 123, in reload
  File "importlib\__init__.py", line 169, in reload
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "calibre\customize\zipplugin.py", line 206, in exec_module
  File "calibre_plugins.dedrm.__init__", line 98, in <module>
ModuleNotFoundError: No module named '__version'

**Comment by Boneist** [comment]
Ah, seems like maybe I wasn't getting the release from the right place. I've gone to the [release page](https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3), downloaded that and extracted it, then I was able to load the zip file that was already present there.
