### ISSUE TITLE
DeDRM cannot find the key of Kindle for PC 1.39

### ISSUE THREAD

**Issue by promeneur** [noDRM/DeDRM_tools#178]
openSUSE Tumbleweed
wine 7.18
kindle for PC 1.39.65306
calibre 6.6.1
DeDRM 10.0.3

Last day I bought a book. I discover randomly the 1.17 version is not connected to internet and when it is connected to internet there is no more sync thus my new book is not in the list. I cannot download it.

Then I switched to 1.39.

No problem to download a book and to read it with kindle

But DeDRM cannot find the key.

In a text console, I get this
*******************************************************************************************************************************************************
:~> calibre
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
0080:fixme:wineusb:add_usb_device Interface 1 has 12 alternate settings; using the first one.
0080:fixme:wineusb:add_usb_device Interface 3 has 5 alternate settings; using the first one.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
00d8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0060F544
DeDRM v10.0.3: Python3 exec found as wine py.exe -3
DeDRM v10.0.3: Running kindlekey.py under Wine
kindlekey.py v3.1
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\roubach\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
Could not retrieve Kindle for Mac/PC key.
00f8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0060F544
DeDRM v10.0.3: Found and decrypted 0 key files
Traceback (most recent call last):
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/config.py", line 1261, in __init__
    self.default_key = defaultkeys[0]

*******************************************************************************************************************************************************

what is the exact name of the file which DeDRM looks for ?

thanks

**Comment by promeneur** [comment]
thanks

I installed the 1.34.63103 as recommended.

I launch kindle with KFX_begone4.bat (I changed "%PROGRAM FILES (x86)" by "%PROGRAM FILES" because kindle is installed in C:\Program Files\)

I downloaded a book and this time I get what I got with the 1.17, a sole azw file.

DeDRM cannot remove the drm. It cannot find the key for the same reason with the 1.39

**Comment by promeneur** [comment]
I installed the 1.26.55076 as recommended.

I launch kindle with KFX_begone4.bat (I changed "%PROGRAM FILES (x86)" by "%PROGRAM FILES" because kindle is installed in C:\Program Files)

I downloaded a book then I get what I got with the 1.17, a sole azw file.

DeDRM cannot remove the drm. It cannot find the key for the same reason with the 1.39

**Comment by ElleKayEm** [comment]
Ok, the file it needs is .kinf2018 and for me it is found here: `C:\Users\{username}\AppData\Local\Amazon\Kindle\storage`.  Maybe yours is in another location?

**Comment by promeneur** [comment]
you speak about ".kinf2018" but the message from calibre says

"No K4PC kindle.info/kinf/kinf2011 files have been found."

**Comment by promeneur** [comment]
Here is the trace of calibre execution using "KFX input".
It is interesting because it can't extract any key from the voucher file and other problems
***************************************************************************************************************************************************
calibre
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing /home/roubach/Documents/My Kindle Content/B0B5KPGK4H_EBOK/B0B5KPGK4H_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /tmp/calibre_6.6.1_tmp_1iy1_3px/onz9udnc.kfx-zip
DeDRM v10.0.3: Trying to decrypt onz9udnc.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: onz9udnc
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c5760b77-ca2b-4057-962f-8619955cf57e.voucher
Traceback (most recent call last):
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/ion.py", line 762, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:wineusb:add_usb_device Interface 1 has 12 alternate settings; using the first one.
0080:fixme:wineusb:add_usb_device Interface 3 has 5 alternate settings; using the first one.
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
00d8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0060F544
DeDRM v10.0.3: Python3 exec found as wine py.exe -3
DeDRM v10.0.3: Running kindlekey.py under Wine
kindlekey.py v3.1
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\roubach\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
Could not retrieve Kindle for Mac/PC key.
00f8:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0060F544
DeDRM v10.0.3: Found and decrypted 0 key files
DeDRM v10.0.3: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 178, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 2.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.49.0: Packaging /tmp/calibre_6.6.1_tmp_1iy1_3px/onz9udnc.kfx-zip
Processing container: B0B5KPGK4H_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 178, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0B5KPGK4H_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /tmp/calibre_6.6.1_tmp_1iy1_3px/by89adwd_add_books/0/B0B5KPGK4H_EBOK.kfx-zip

**Comment by ElleKayEm** [comment]
This log looks as though you're trying to decrypt a kfx file that was downloaded with a version of Kindle for PC later then 1.26.

The name of the key file changed from kinf2011 to kinf 2018 in the later versions.  DeDRM should find either one.

**Comment by promeneur** [comment]
No i did the test with 1.26.55076

**Comment by ElleKayEm** [comment]
And you're sure it didn't update?  Kindle for PC is very aggressive about updating itself.  At any rate, I'd recommend disabling KFX and getting the book in the older format if possible.

**Comment by promeneur** [comment]
I reinstalled 1.26. This time before importing a book, i checked this is the 1.26.
I get the same trace. DeDRM searches for a kinf2011 file not a kinf2018.
***************************************************************************************************************************************************
:~> calibre
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing /home/roubach/Documents/My Kindle Content/B0B5KPGK4H_EBOK/B0B5KPGK4H_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /tmp/calibre_6.6.1_tmp_g2vjhrxj/nl39gu56.kfx-zip
DeDRM v10.0.3: Trying to decrypt nl39gu56.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: nl39gu56
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c5760b77-ca2b-4057-962f-8619955cf57e.voucher
Traceback (most recent call last):
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/ion.py", line 762, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
002c:err:winediag:getaddrinfo Failed to resolve your host name IP
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0080:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:wineusb:add_usb_device Interface 1 has 12 alternate settings; using the first one.
0084:fixme:wineusb:add_usb_device Interface 3 has 5 alternate settings; using the first one.
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
0080:fixme:wineusb:query_id Unhandled ID query type 0x5.
00dc:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0060F544
DeDRM v10.0.3: Python3 exec found as wine py.exe -3
DeDRM v10.0.3: Running kindlekey.py under Wine
kindlekey.py v3.1
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\roubach\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
Could not retrieve Kindle for Mac/PC key.
00fc:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0060F544
DeDRM v10.0.3: Found and decrypted 0 key files
DeDRM v10.0.3: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/home/roubach/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 178, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 2.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.49.0: Packaging /tmp/calibre_6.6.1_tmp_g2vjhrxj/nl39gu56.kfx-zip
Processing container: B0B5KPGK4H_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 178, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0B5KPGK4H_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /tmp/calibre_6.6.1_tmp_g2vjhrxj/vfqd3rfy_add_books/0/B0B5KPGK4H_EBOK.kfx-zip
