### ISSUE TITLE
Can't remove DRM from Kindle book

### ISSUE THREAD

**Issue by istaraa** [noDRM/DeDRM_tools#181]
### Question / bug report

Can't remove DRM from/convert a (legally bought) Amazon Kindle book from Kindle for Mac.

Thank you if you are able to help.

### Which version of Calibre are you running?

6.6.1

### Which version of the DeDRM plugin are you running?

v.10.0.3

### If applicable, which version of the Kindle software are you running?

1.39.0

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.6.1  embedded-python: True
macOS-12.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
calibre 6.6.1  embedded-python: True
macOS-12.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 132.00000198244115 x 132.50000198995036
[0.00] Starting up...
[0.03] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.76] main UI initialized...
[0.76] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.49.0: Importing /Users/loki/Library/Application Support/Kindle/My Kindle Content/B0BH98GL9N_EBOK/B0BH98GL9N_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/xx/y5vzqq217bg1yfn5x6ymcgzm0000gn/C/calibre_6.6.1_tmp_p9tcnq6k/z_8fo053.kfx-zip
DeDRM v10.0.3: Trying to decrypt z_8fo053.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: z_8fo053
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.938e2fda-3209-41a2-9291-6e20916c42ee.voucher
Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 763, in pkcs7unpad
    _assert(msg[-paddinglen:] == bchr(paddinglen) * paddinglen, "Incorrect padding - Wrong key")
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/loki/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/loki/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2011 file: /Users/loki/Library/Application Support/Kindle/storage/.kinf2011
trying username  b'loki'  on file  /Users/loki/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a670d8288'
trying IDString: b'27e69b05a3a4'
trying IDString: b'27e69b05a3a5'
trying IDString: b'27e69b05a3a0'
[3.75] splash screen hidden
[3.75] Started up in 3.75 seconds with 259 books
trying IDString: b'27e69b05a3a1'
trying IDString: b'27e69b05a3a4'
trying IDString: b'disk1s1s1'
trying IDString: b'disk1s5'
trying IDString: b'disk1s3'
trying IDString: b'disk1s6'
trying IDString: b'disk1s2'
trying IDString: b'disk2s1'
trying IDString: b'disk4s1'
trying IDString: b'9999999999'
Couldn't decrypt file.
trying username  b'loki'  on file  /Users/loki/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'5d5a670d8288'
Decrypted key file using IDString '5d5a670d8288' and UserName 'loki'
trying username  b'loki'  on file  /Users/loki/Library/Application Support/Kindle/storage/.kinf2011
trying IDString: b'5d5a670d8288'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'27e69b05a3a4'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'27e69b05a3a5'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'27e69b05a3a0'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'27e69b05a3a1'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'27e69b05a3a4'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'disk1s1s1'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'disk1s5'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'disk1s3'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'disk1s6'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'disk1s2'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'disk2s1'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'disk4s1'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

trying IDString: b'9999999999'
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 823, in getDBfromFile
    cud = CryptUnprotectData(entropy,IDString)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kindlekey.py", line 696, in __init__
    self.crp.set_decrypt_key(self.key, self.iv)
AttributeError: 'CryptUnprotectData' object has no attribute 'crp'

Couldn't decrypt file.
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: z_8fo053
Got DSN key from database key_0
Found 1 keys to try after 2.9 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.938e2fda-3209-41a2-9291-6e20916c42ee.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 763, in pkcs7unpad
    _assert(msg[-paddinglen:] == bchr(paddinglen) * paddinglen, "Incorrect padding - Wrong key")
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 763, in pkcs7unpad
    _assert(msg[-paddinglen:] == bchr(paddinglen) * paddinglen, "Incorrect padding - Wrong key")
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/loki/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.49.0: Packaging /var/folders/xx/y5vzqq217bg1yfn5x6ymcgzm0000gn/C/calibre_6.6.1_tmp_p9tcnq6k/z_8fo053.kfx-zip
Processing container: B0BH98GL9N_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0BH98GL9N_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/xx/y5vzqq217bg1yfn5x6ymcgzm0000gn/C/calibre_6.6.1_tmp_p9tcnq6k/li6k3p38_add_books/0/B0BH98GL9N_EBOK.kfx-zip

```

**Comment by ElleKayEm** [comment]
You'll need an earlier version of Kindle for Mac.  See this post: https://www.mobileread.com/forums/showthread.php?t=283371

And this: https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
