### ISSUE TITLE
Plugin is invalid. It does not contain a top-level __init__.py file

### ISSUE THREAD

**Issue by cnichte** [noDRM/DeDRM_tools#188]
### Question / bug report

Can't install the Plugin. The plugin in 'DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

### Which version of Calibre are you running?

6.7.1

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
calibre, version 6.7.1
FEHLER: Unbehandelter Ausnahmefehler: <b>InvalidPlugin</b>:The plugin in '/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.7.1  embedded-python: True
macOS-12.6.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.1', ('', '', ''), 'x86_64')
Interface language: de
Successfully initialized third party plugins: DeACSM (0, 0, 16)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 479, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 298, in load
  File "calibre/customize/zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by ElleKayEm** [comment]
You loading the whole archive instead of just the plugin.  Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.
