### ISSUE TITLE
Issue Importing DMR book from ADE

### ISSUE THREAD

**Issue by sanzinluka** [noDRM/DeDRM_tools#202]
### Question / bug report

Hello,
I am trying to import an .epub downloaded from ADE (in this case it was a Kobo book downloaded from the website in the .acsm format) but when I import it into Calibre, the epub still has the DMR.

Tryed to do it on the latest Calibre version (6.8) and it didn't work, so I tried to downgrade to 6.7

The issue is on a 14" Macbook Pro with the latest OS version.

Thank you for your great work!!

### Which version of Calibre are you running?

6.7

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.7  embedded-python: True
macOS-13.0-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.0', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.7  embedded-python: True
macOS-13.0-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.0', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Key '' for shortcut Book list header menu is already used by Manage categories, ignoring
[0.53] main UI initialized...
[0.53] Hiding splash screen
Starting QuickView
2022-11-05 19:30:46.887 calibre-debug[70086:2443434] +[CATransaction synchronize] called within transaction
DeDRM v10.0.3: Trying to decrypt Hyperion - I canti di Hyperion volume 1.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Hyperion - I canti di Hyperion volume 1.epub is a secure Adobe Adept ePub for UUID b73c7a9c-cdd9-4a1a-94e6-c52b172e169c
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
    userkey = codecs.decode(userkeyhex, 'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[9.81] splash screen hidden
[9.81] Started up in 9.81 seconds with 125 books
Added Hyperion - I canti di Hyperion volume 1 to db in: 0.0
Added 1 books in 0.4 seconds
Worker Launch took: 0.01 seconds
```

**Comment by ElleKayEm** [comment]
Try deleting your saved Adobe key from DeDRM.  Add the book to calibre again letting DeDRM automatically retrieve the key.

**Comment by sanzinluka** [comment]
Yes, this did it!

Thank you!
If you accept donations I would gladly contribute!
