### ISSUE TITLE
DeDRM_plugin fails to install; calibre 6.8

### ISSUE THREAD

**Issue by crisnoh** [noDRM/DeDRM_tools#207]
Downloaded DeDRM_tools. Unzipped and attempted to install DeDRM_plugin.zip via calibre > Preferences > Plugins > Load plugin from file. Received "unhandled exception" error: 

> **InvalidPlugin**: The plugin in '/Users/cris/Desktop/DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

```
calibre, version 6.8.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/cris/Desktop/DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.8  embedded-python: True
macOS-13.0.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.1.0', 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.0.1', ('', '', ''), 'arm64')
Interface language: None
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 479, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 298, in load
  File "calibre/customize/zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/cris/Desktop/DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

```

**Comment by ElleKayEm** [comment]
Download the latest release 10.0.3 here: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Unzip DeDRM_tools_10.0.3.zip and then load DeDRM_plugin.zip.

**Comment by crisnoh** [comment]
Problem solved, thank you
