### ISSUE TITLE
ERROR: Unhandled exception FileNotFoundError

### ISSUE THREAD

**Issue by maria8899** [noDRM/DeDRM_tools#208]
Hi, first thanks for still working on this project!

I have downloaded the acsm file from kobo, converted it via Adobe DE to epub.
I have been using calibre and installed the 2 plugins, re-launched calibre. The book can be added but I can't read it (says its protected). If I click on obok button, I get this

```
calibre, version 5.37.0
ERROR: Unhandled exception: FileNotFoundError:[Errno 2] No such file or directory: '/home/maria/.config/calibre/kobo location'

calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-52-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-52-generic', '#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022')
Python 3.10.6
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 97, in launchObok
    self.library = KoboLibrary(tmpserials, device_path, cfg['kobo_directory'])
  File "calibre_plugins.obok_dedrm.obok.obok", line 340, in __init__
    f = open(kobodir_cache_file, 'r' )
FileNotFoundError: [Errno 2] No such file or directory: '/home/maria/.config/calibre/kobo location'
```

I have tested this on two laptop running different linux flavor. I tried creating the directory, but it did not work. What am I missing?

**Comment by maria8899** [comment]
in debug mode:

```
calibre Debug log
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-52-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-52-generic', '#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022')
Python 3.10.6
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-52-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-52-generic', '#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022')
Python 3.10.6
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.14671814671814 x 94.07407407407408
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.06] splash screen shown
[0.06] Initializing db...
[0.07] db initialized
[0.07] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.55] main UI initialized...
[0.55] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt test.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: test.epub is a secure Adobe Adept ePub for UUID ddc9c855-281c-4934-95a0-2bcf1dd18a73
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 596, in ePubDecrypt
    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
  File "/home/maria/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "/home/maria/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
    self.check_call(["-c", self.py3_test])
  File "/home/maria/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[6.24] splash screen hidden
[6.25] Started up in 6.25 seconds with 1 books
Worker Launch took: 0.00 seconds
Worker Launch took: 0.00 seconds
Added Nothing’s Wrong to db in: 0.8
Added 1 books in 1.3 seconds
```

**Comment by maria8899** [comment]
FYI I have managed to remove the drm using this other tool: https://github.com/Leseratte10/acsm-calibre-plugin

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
