### ISSUE TITLE
using DeDRM with newer Kindle for Mac

### ISSUE THREAD

**Issue by christalee** [noDRM/DeDRM_tools#211]
### Question / bug report

I'm trying to remove DRM from my books using Kindle for Mac 1.39 (last updated April 2019). Although this version of Kindle app is "too new" to work according to the FAQ, I have successfully used it to DeDRM using prior versions of the plugin, most recently in April 2021 (so presumably v7.2.1). Any tips or success stories from other users?

### Which version of Calibre are you running?

6.8

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

1.39

### Log output

```log
Using calibre Qt style: False
FFF: DEBUG: 2022-11-20 10:18:40,522: calibre_plugins.fanficfare_plugin.fff_plugin(216): Plugin FanFicFare macmenuhack file_path:/Users/christalee/Library/Preferences/calibre/plugins/fanficfare_macmenuhack.txt
calibre Debug log
calibre 6.8  embedded-python: True
macOS-12.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && Audit Log (1, 0, 18) && Count Pages (1, 12, 0) && Extract ISBN (1, 6, 0) && FanFicFare (4, 17, 0) && Fantastic Fiction (1, 6, 0) && Fantastic Fiction Adults (1, 3, 0) && Find Duplicates (1, 10, 7) && Goodreads (1, 7, 1) && Goodreads Sync (1, 16, 2) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Library Codes (1, 0, 53) && Modify ePub (1, 8, 1) && Overdrive Link (2, 52, 0) && Quality Check (1, 13, 2) && Smashwords Metadata (1, 0, 2) && Zotero Metadata Importer (1, 0, 76)
calibre 6.8  embedded-python: True
macOS-12.6-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && Audit Log (1, 0, 18) && Count Pages (1, 12, 0) && Extract ISBN (1, 6, 0) && FanFicFare (4, 17, 0) && Fantastic Fiction (1, 6, 0) && Fantastic Fiction Adults (1, 3, 0) && Find Duplicates (1, 10, 7) && Goodreads (1, 7, 1) && Goodreads Sync (1, 16, 2) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Library Codes (1, 0, 53) && Modify ePub (1, 8, 1) && Overdrive Link (2, 52, 0) && Quality Check (1, 13, 2) && Smashwords Metadata (1, 0, 2) && Zotero Metadata Importer (1, 0, 76)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
[0.00] Starting up...
[0.09] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.43] db initialized
[0.43] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 872, 'width': 1440, 'x': 0, 'y': 28},
 'maximized': True,
 'normal_geometry': {'height': 872, 'width': 1440, 'x': 0, 'y': 28},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 872, 'width': 1440, 'x': 0, 'y': 28}
Restoring widget to maximized
[3.35] main UI initialized...
[3.35] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.50.0: Importing /Users/christalee/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/My Kindle Content/B07Q9PJXBZ_EBOK/B07Q9PJXBZ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /var/folders/k3/_m7kqcyd3s7bmhmb7nw6flv40000gn/C/calibre_6.8.0_tmp_bify71w7/dvycvw64.kfx-zip
DeDRM v10.0.3: Trying to decrypt dvycvw64.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: dvycvw64
Found 0 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c9f2c504-6bea-4336-9d16-0a9360b8c69e.voucher
Traceback (most recent call last):
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 762, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/christalee/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
[7.33] splash screen hidden
[7.33] Started up in 7.33 seconds with 420 books
Restoring geometry for: preferences dialog geometry
{'frame_geometry': {'height': 849, 'width': 1154, 'x': 188, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 821, 'width': 1154, 'x': 188, 'y': 28},
 'maximized': False,
 'normal_geometry': {'height': 821, 'width': 1154, 'x': 188, 'y': 28},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 821, 'width': 1154, 'x': 188, 'y': 28}
Restoring geometry for: plugin config dialog:File type:DeDRM
{'frame_geometry': {'height': 591, 'width': 333, 'x': 544, 'y': 194},
 'full_screened': False,
 'geometry': {'height': 563, 'width': 333, 'x': 544, 'y': 222},
 'maximized': False,
 'normal_geometry': {'height': 563, 'width': 333, 'x': 544, 'y': 222},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 563, 'width': 333, 'x': 544, 'y': 222}
Saving geometry for: plugin config dialog:File type:DeDRM
{'frame_geometry': {'height': 591, 'width': 333, 'x': 544, 'y': 194},
 'full_screened': False,
 'geometry': {'height': 563, 'width': 333, 'x': 544, 'y': 222},
 'maximized': False,
 'normal_geometry': {'height': 563, 'width': 333, 'x': 544, 'y': 222},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
Saving geometry for: preferences dialog geometry
{'frame_geometry': {'height': 849, 'width': 1154, 'x': 188, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 821, 'width': 1154, 'x': 188, 'y': 28},
 'maximized': False,
 'normal_geometry': {'height': 821, 'width': 1154, 'x': 188, 'y': 28},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
trying username  b'christalee'  on file  /Users/christalee/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'55bd3d90350e'
Decrypted key file using IDString '55bd3d90350e' and UserName 'christalee'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: dvycvw64
Got DSN key from database key_0
Found 1 keys to try after 0.8 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.c9f2c504-6bea-4336-9d16-0a9360b8c69e.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 762, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 762, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/christalee/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.50.0: Packaging /var/folders/k3/_m7kqcyd3s7bmhmb7nw6flv40000gn/C/calibre_6.8.0_tmp_bify71w7/dvycvw64.kfx-zip
Processing container: B07Q9PJXBZ_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07Q9PJXBZ_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/k3/_m7kqcyd3s7bmhmb7nw6flv40000gn/C/calibre_6.8.0_tmp_bify71w7/65mn0g52_add_books/0/B07Q9PJXBZ_EBOK.kfx-zip
Added Manners and Monsters to db in: 0.1
Added 1 books in 1.9 seconds
Saving geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 872, 'width': 1440, 'x': 0, 'y': 28},
 'maximized': True,
 'normal_geometry': {'height': 872, 'width': 1440, 'x': 0, 'y': 28},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}

```

**Comment by ElleKayEm** [comment]
It could work if you happened to find a book which was not available in the latest KFX format (unlike the book in this log).  Otherwise you'd need to use one of the methods for getting older formats.

**Comment by christalee** [comment]
I see now that despite the notation "Last updated 4/1/2019" under About Kindle, that's somehow not the date the app last updated - my mistake. I will decide whether to downgrade to Kindle 1.31 or give up on this task. Thank you for your prompt response!
