### ISSUE TITLE
ProQuest Ebook Central import into calibre only gives blank pages

### ISSUE THREAD

**Issue by henrydatei** [noDRM/DeDRM_tools#218]
### Question / bug report

After trying to import a book from [Adobes Sample Library](https://www.adobe.com/solutions/ebook/digital-editions/sample-ebook-library.html) (20,000 Lieues Sous les Mers) I tried to import a book from ProQuest Ebook Central via the ACSM file provided by ProQuest Ebook Central.

Interestingly I can't read this file in Adobe Digital Editions 4.5 too - it says there that there is a fulfillment error (`E_LIC_ALREADY_FULFILLED_BY_ANOTHER_USER`). I found very unhelpful [article](https://support.proquest.com/s/article/Ebook-Central-Download-ADE-Error-E-LIC-ALREADY-FULFILLED-BY-ANOTHER-USER) by Proquest because it says something about Adobe IDs (I have a one) but when downloading the ASCM file ProQuest Ebook Central didn't asked me for my Adobe ID or anything else. They say that you can even read this book with an anonymous authorisation. I should mention that I have access to ProQuest Ebook Central via my library.

### Which version of Calibre are you running?

6.9

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.9  embedded-python: True
macOS-12.6.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3)
calibre 6.9  embedded-python: True
macOS-12.6.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 128.00000192236715
[0.00] Starting up...
[0.04] Showing splash screen...
[0.31] splash screen shown
[0.31] Initializing db...
[0.32] db initialized
[0.32] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 636, 'width': 1231, 'x': 165, 'y': 43},
 'full_screened': False,
 'geometry': {'height': 608, 'width': 1231, 'x': 165, 'y': 71},
 'maximized': False,
 'normal_geometry': {'height': 608, 'width': 1231, 'x': 165, 'y': 71},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 608, 'width': 1231, 'x': 165, 'y': 71}
[1.28] main UI initialized...
[1.28] Hiding splash screen
Starting QuickView
[3.42] splash screen hidden
[3.42] Started up in 3.42 seconds with 1 books
DeDRM v10.0.3: Trying to decrypt 20000 lieues sous les mers.pdf
DeDRM v10.0.3: 20000 lieues sous les mers.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: 20000 lieues sous les mers.pdf is a PDF ebook (EBX) for UUID 0d078f9a-4aa0-4093-9913-333835530ffe
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Found new key 'DeACSM_uuid_27d24937-1e91-442c-aa01-c554b5c77cea' in DeACSM plugin
DeDRM v10.0.3: Trying a new default key
DeDRM v10.0.3: Saving a new default key
DeDRM v10.0.3: Saved a new default key after 1.5 seconds
DeDRM v10.0.3: Finished after 1.5 seconds
Added 20000 lieues sous les mers to db in: 0.0
Added 1 books in 3.3 seconds
Restoring geometry for: preferences dialog geometry
{'frame_geometry': {'height': 748, 'width': 930, 'x': 140, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 720, 'width': 930, 'x': 140, 'y': 53},
 'maximized': False,
 'normal_geometry': {'height': 720, 'width': 930, 'x': 140, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 720, 'width': 930, 'x': 140, 'y': 53}
Saving geometry for: preferences dialog geometry
{'frame_geometry': {'height': 748, 'width': 930, 'x': 140, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 720, 'width': 930, 'x': 140, 'y': 53},
 'maximized': False,
 'normal_geometry': {'height': 720, 'width': 930, 'x': 140, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 900, 'width': 1440, 'x': 0, 'y': 0}}}
DeDRM v10.0.3: Trying to decrypt 4e73za5t.pdf
DeDRM v10.0.3: 4e73za5t.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: 4e73za5t.pdf is a PDF ebook (EBX) for UUID 27d24937-1e91-442c-aa01-c554b5c77cea
DeDRM v10.0.3: Trying encryption key default_ade_key_uuid_0d078f9a-4aa0-4093-9913-333835530ffe_AdobeID_ulf.m.2@web.de
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 724, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with key default_ade_key_uuid_0d078f9a-4aa0-4093-9913-333835530ffe_AdobeID_ulf.m.2@web.de after 0.2 seconds
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Found new key 'DeACSM_uuid_27d24937-1e91-442c-aa01-c554b5c77cea' in DeACSM plugin
DeDRM v10.0.3: Trying a new default key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.6 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with new default key after 0.6 seconds
DeDRM v10.0.3: Trying a new default key
ebx_V is 4  and ebx_type is 6
length is 16 and len(bookkey) is 0
DeDRM v10.0.3: Exception when decrypting after 0.6 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2286, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2094, in __init__
    doc.initialize(userkey, inept)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1253, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "/Users/henryhaustein/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1707, in initialize_ebx_inept
    print("bookkey[0] is %d" % bookkey[0])
IndexError: index out of range
DeDRM v10.0.3: Failed to decrypt with new default key after 0.6 seconds
DeDRM v10.0.3: Finished after 0.6 seconds
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
DeACSM v0.0.16: Trying to parse file 6963065.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://acs.ebookcentral.proquest.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://acs.ebookcentral.proquest.com/document/006/006963/4ee80bcf-1d3c-3f74-abd8-a5793b9de5e9.pdf
Download took 2449 ms (HTTP 200)
That's a PDF file
DeACSM v0.0.16: Downloaded PDF, adding encryption config ...
Searching for startxref ...
Got startxref: 12245096
Found ENC after 5 attempts - took 0 ms
Found EBX after 2464 attempts - took 9 ms


Encryption handler:
<</Root 1 0 R/Info 8 0 R/Encrypt 2453 0 R/ID[<4FF484ECCF028903DF0358A85A468126><7AB216F45B827D6238AB42F87EA0188D>]/Size 2454>>
EBX handler:
<</EBX_PUBLISHER(Beuth Verlag)/Filter/EBX_HANDLER/Length 128/ADEPT_ID(urn:uuid:00000000-0000-0000-0000-000006963065)/V 4/EBX_TITLE(Holzschutz)/EBX_AUTHOR(Glauner, Roland;Grosser, Dietger;Melcher, Eckhard;Plarre, Rudy;)>>
Trimmed encryption handler:
<</Root 1 0 R/Info 8 0 R/Encrypt 2453 0 R/ID[<4FF484ECCF028903DF0358A85A468126><7AB216F45B827D6238AB42F87EA0188D>]/Size 2454>>
Updated EBX handler not logged due to sensitive data
Whole DRM patching took 32 milliseconds.
DeACSM v0.0.16: File successfully fulfilled ...
DeACSM v0.0.16: Executing plugin DeDRM ...
DeACSM v0.0.16: Plugin returned nothing - skipping
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
```

**Comment by ElleKayEm** [comment]
You'll definitely need to get it tied to an Adobe ID in order to remove the DRM -- it won't work with an anonymous authorization that ties it to only that app installation.  You won't be asked for your Adobe ID when downloading the acsm file.  The ebook file gets tied to your Adobe ID when you open the acsm file in an app authorized with that ID.  I see you have the DeACSM plugin.  Is that setup with your Adobe ID?

**Comment by henrydatei** [comment]
I tried around with this DRM stuff the whole afternoon. Currently I have the DeASCM plugin but I have the original Adobe Digital Editions App for Mac too. In the Adobe App I’m logged in with my Adobe ID. 

Before I had the Adobe App I tried around with the anonymous authorization but then I remembered my Adobe ID and started using that

**Comment by ElleKayEm** [comment]
If you downloaded it first without your Adobe ID, then that's why it is showing as already fulfilled when you try with your Adobe ID.  You'll probably need a new checkout to reset it.

**Comment by henrydatei** [comment]
Ok thanks but how am I going to do this?

**Comment by henrydatei** [comment]
Thanks again for your help. I'll see what I can do to get a new checkout

**Comment by noDRM** [comment]
If this issue is still not solved, try going into the DeACSM settings and export the account encryption key, then import that key in the DeDRM settings. There might be a bug in the DeDRM plugin with automatically acquiring that key if ADE is also installed on the machine. 

In general, DeDRM can also remove DRM from eBooks authorized for a machine / an anonymous authorization. It just needs to have the correct key to do that, and according to your log that doesn't seem to be the case.

If the issue was already solved with a new checkout you can close this issue.

**Comment by henrydatei** [comment]
It now works. Thanks for your help
