### ISSUE TITLE
Unable to remove DRM from new book

### ISSUE THREAD

**Issue by leefranke** [noDRM/DeDRM_tools#226]
The book is Failure Mode (Expeditionary Force Book 15). The file name on my Kindle is Failure Mode (Expeditionary Force Book 15)_B0BMNZ9T2B.kfx

My Kindle is up to date and is the older 'Paperwhite 6th Generation'. The firmware s 5.12.2.2

Calibre is the latest version (I just updated this morning).

I'm pasting in the Calibre log.  Attaching doesn't seem to be working.

Thanks!

ApplicationPaletteChange event ignored
Using calibre Qt style: True
Traceback (most recent call last):
  File "calibre\gui2\store\loader.py", line 90, in load_cache
  File "calibre\gui2\store\loader.py", line 176, in load_object
  File "<string>", line 10, in <module>
ImportError: cannot import name 'urlencode' from 'urllib' (C:\Program Files\Calibre2\app\bin\python-lib.bypy.frozen\urllib\__init__.pyc)
Traceback (most recent call last):
  File "calibre\gui2\store\loader.py", line 90, in load_cache
  File "calibre\gui2\store\loader.py", line 176, in load_object
  File "<string>", line 10, in <module>
ModuleNotFoundError: No module named 'urllib2'
Traceback (most recent call last):
  File "calibre\gui2\store\loader.py", line 90, in load_cache
  File "calibre\gui2\store\loader.py", line 176, in load_object
  File "<string>", line 10, in <module>
ModuleNotFoundError: No module named 'urllib2'
Traceback (most recent call last):
  File "calibre\gui2\store\loader.py", line 90, in load_cache
  File "calibre\gui2\store\loader.py", line 176, in load_object
  File "<string>", line 10, in <module>
ModuleNotFoundError: No module named 'urllib2'
Traceback (most recent call last):
  File "calibre\gui2\store\loader.py", line 90, in load_cache
  File "calibre\gui2\store\loader.py", line 176, in load_object
  File "<string>", line 10, in <module>
ModuleNotFoundError: No module named 'urllib2'
Traceback (most recent call last):
  File "calibre\gui2\store\loader.py", line 90, in load_cache
  File "calibre\gui2\store\loader.py", line 176, in load_object
  File "<string>", line 12, in <module>
ModuleNotFoundError: No module named 'urllib2'
calibre Debug log
calibre 6.9  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
calibre 6.9  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.2912482065997 x 93.3061224489796
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
Failed to load cached store: baen_webscription
Failed to load cached store: beam_ebooks_de
Failed to load cached store: ebook_nl
Failed to load cached store: libri_de
Failed to load cached store: mills_boon_uk
Failed to load cached store: smashwords
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 4480, 'x': -1920, 'y': 0}}
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080,
                                'width': 1920,
                                'x': -1920,
                                'y': 0},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1440, 'width': 4480, 'x': -1920, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 730, 'width': 1503, 'x': 400, 'y': 154},
 'full_screened': False,
 'geometry': {'height': 699, 'width': 1503, 'x': 400, 'y': 185},
 'maximized': False,
 'normal_geometry': {'height': 699, 'width': 1503, 'x': 400, 'y': 185},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 2560,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 2560},
            'virtual_geometry': {'height': 1440,
                                 'width': 4480,
                                 'x': -1920,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 4480, 'x': -1920, 'y': 0}}
Setting widget geometry to: {'height': 699, 'width': 1503, 'x': 400, 'y': 185}
[1.17] main UI initialized...
[1.17] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.50.0: Importing C:\Users\Dad\Documents\My Books\Failure Mode (Expeditionary Force Book 15)_B0BMNZ9T2B.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\Dad\AppData\Local\Temp\calibre_u8dk_30s\_6uekt7n.kfx-zip
DeDRM v10.0.3: Trying to decrypt _6uekt7n.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: _6uekt7n
Found 1 keys to try after 0.3 seconds
DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Dad\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Dad\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Dad\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Dad\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.50.0: Packaging C:\Users\Dad\AppData\Local\Temp\calibre_u8dk_30s\_6uekt7n.kfx-zip
Processing container: Failure Mode (Expeditionary Force Book 15)_B0BMNZ9T2B.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Failure Mode (Expeditionary Force Book 15)_B0BMNZ9T2B.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Dad\AppData\Local\Temp\calibre_u8dk_30s\fizdra6s_add_books\0\Failure Mode (Expeditionary Force Book 15)_B0BMNZ9T2B.kfx-zip
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 435, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
Exception: Failed to locate a KFX container with metadata
[7.94] splash screen hidden
[7.94] Started up in 7.94 seconds with 67 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\x1a\x97y\xc1\xdf\x8bi\x96(\x07Alo/\xf3\x06-\x17v\xed48+'%Xq\xa1\xe2\x9b\xb5\xe4", b'C:\\Users\\Dad\\Documents\\My Books\\Failure Mode (Expeditionary Force Book 15)_B0BMNZ9T2B.kfx']
Added Failure Mode (Expeditionary Force Book 15) B0BMNZ9T2B to db in: 0.1

**Comment by leefranke** [comment]
Worked great. Didn't realize my Kindle was still too new. 

thanks!!
