### ISSUE TITLE
DeDRM does not work

### ISSUE THREAD

**Issue by rkoehler2017** [noDRM/DeDRM_tools#230]
### Question / bug report

ADE installed and authorized on same pc

### Which version of Calibre are you running?

6.9.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.9 Portable embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.9 Portable embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 65.24147157190636 x 65.31428571428572
[0.00] Starting up...
[0.01] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864, 'width': 1536, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 3456, 'x': -1920, 'y': 0}}
{'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864,
                                'width': 1536,
                                'x': -1920,
                                'y': 0},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 3456, 'x': -1920, 'y': 0}}
Restoring geometry for: jobs_dialog_geometry
{'frame_geometry': {'height': 364, 'width': 456, 'x': -1390, 'y': 236},
 'full_screened': False,
 'geometry': {'height': 334, 'width': 456, 'x': -1390, 'y': 266},
 'maximized': False,
 'normal_geometry': {'height': 334, 'width': 456, 'x': -1390, 'y': 266},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.25,
            'geometry_in_logical_pixels': {'height': 864,
                                           'width': 1536,
                                           'x': -1920,
                                           'y': 0},
            'index_in_screens_list': 1,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY2',
            'serial': '',
            'size_in_logical_pixels': {'height': 864, 'width': 1536},
            'virtual_geometry': {'height': 864,
                                 'width': 3456,
                                 'x': -1920,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864,
                                'width': 1536,
                                'x': -1920,
                                'y': 0},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 3456, 'x': -1920, 'y': 0}}
Moving widget to saved screen
Setting widget geometry to: {'height': 334, 'width': 456, 'x': -1390, 'y': 266}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 871, 'width': 1536, 'x': -1920, 'y': -7},
 'full_screened': False,
 'geometry': {'height': 841, 'width': 1536, 'x': -1920, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 841, 'width': 1536, 'x': -1920, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.25,
            'geometry_in_logical_pixels': {'height': 864,
                                           'width': 1536,
                                           'x': -1920,
                                           'y': 0},
            'index_in_screens_list': 1,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY2',
            'serial': '',
            'size_in_logical_pixels': {'height': 864, 'width': 1536},
            'virtual_geometry': {'height': 864,
                                 'width': 3456,
                                 'x': -1920,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864,
                                'width': 1536,
                                'x': -1920,
                                'y': 0},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 3456, 'x': -1920, 'y': 0}}
Moving widget to saved screen
Setting widget geometry to: {'height': 841, 'width': 1536, 'x': -1920, 'y': 23}
Restoring widget to maximized
[0.53] main UI initialized...
[0.53] Hiding splash screen
Starting QuickView
Job: 0 Set library information started
DeviceJob: 0 Set library information done, calling callback
DeviceJob: 0 Set library information callback returned
Job: 1 Get device information started
DeviceJob: 1 Get device information done, calling callback
DeviceJob: 1 Get device information callback returned
Job: 2 Set library information started
DeviceJob: 2 Set library information done, calling callback
DeviceJob: 2 Set library information callback returned
Job: 3 Get list of books on device started
MTP: Loading filesystem metadata...
MTP: Ignored object: Music
MTP: Ignored object: Ringtones
MTP: Ignored object: Alarms
MTP: Ignored object: Notifications
MTP: Ignored object: Pictures
MTP: Ignored object: Movies
MTP: Ignored object: DCIM
MTP: Ignored object: Android/obb
MTP: Ignored object: Android/data/de.etecture.ekz.onleihe
MTP: Ignored object: Android/data/com.apkpure.aegon
MTP: Ignored object: Android/data/com.easybrain.sudoku.android
MTP: Ignored object: Android/data/com.artatech.android.inkbook.reader
MTP: Ignored object: Android/data/pl.artatech.inkbookfilemanager
MTP: Ignored object: Android/data/net.skoobe.reader
MTP: Ignored object: Android/data/com.potatojam.classic.solitaire.klondike
MTP: Ignored object: Android/data/com.adobe.reader
MTP: Ignored object: LOST.DIR
MTP: Ignored object: Android/obb
MTP: Ignored object: Android/data/de.etecture.ekz.onleihe
MTP: Ignored object: Android/data/net.skoobe.reader
MTP: Ignored object: Android/data/pl.artatech.inkbookfilemanager
MTP: Ignored object: Android/data/com.apkpure.aegon
MTP: Ignored object: Android/data/com.potatojam.classic.solitaire.klondike
MTP: Ignored object: Android/data/com.easybrain.sudoku.android
MTP: Ignored object: Android/data/com.adobe.reader
MTP: Filesystem metadata loaded in 0.050209 seconds (376 objects)
MTP: Using cached metadata for Interner gemeinsamer Speicher/Android/sdcardpath.txt
MTP: Using cached metadata for Interner gemeinsamer Speicher/Books/manual/de/Benutzerhandbuch - Focus.epub
MTP: Using cached metadata for Interner gemeinsamer Speicher/Document/Geheimnis des Winterhauses, Das - Sarah Lark.epub
DeviceJob: 3 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 3
DeviceJob: set_books_in_library finished: time= 0.0010263919830322266
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 3 Get list of books on device callback returned
Job: 0 Set library information finished
No details available.
Job: 1 Get device information finished
No details available.
Job: 3 Get list of books on device finished
No details available.
Job: 2 Set library information finished
No details available.
DeDRM v10.0.3: Trying to decrypt Kinder ihrer Zeit.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Kinder ihrer Zeit.epub is a secure Adobe Adept ePub for UUID 9c483048-1317-4dd8-b67b-5b2d6f52dafb
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[2.56] splash screen hidden
[2.56] Started up in 2.56 seconds with 4 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xc3S\x8b\xe8\xac'\xe21WCR\xact\xc8E\x9e\xe6\xad\xc2\x9f\xf8,\xb5\xb5\x0c\xc8\x87\xa4(*\x80\xa0", b'C:\\Users\\PCMaster\\Documents\\My Digital Editions\\Kinder ihrer Zeit.epub']
Added Kinder ihrer Zeit to db in: 0.1
Added 1 books in 0.4 seconds

```

**Comment by rkoehler2017** [comment]
find the problem/solution for me.
In the deDrm delete the Adobe IDs
if importing a book the id will added automatically to the plugin, that works for me, but i found this not documented

**Comment by noDRM** [comment]
That's a bug in the latest release of the plugin. The bug is already fixed on the latest master but there hasn't been a new release since then. Once 10.0.4 comes out this will no longer occur.
