### ISSUE TITLE
if trying to save the ADE Keys getting this error

### ISSUE THREAD

**Issue by rkoehler2017** [noDRM/DeDRM_tools#231]
calibre, version 6.9.0
ERROR: Unhandled exception: <b>ValueError</b>:decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)

calibre 6.9 Portable embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\programme\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\config.py", line 585, in export_key
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)

**Comment by rkoehler2017** [comment]
That works
