### ISSUE TITLE
DRM not removed - tried epub and pdf formats

### ISSUE THREAD

**Issue by kelawson48** [noDRM/DeDRM_tools#234]
### Question / bug report

Downloaded acsm files using Adobe Digital Editions, then tried loading the resulting pdf and epub files into Calibre.

### Which version of Calibre are you running?

6.10.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.10  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 50, 0) && Find Duplicates (1, 10, 7) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Obok DeDRM (7, 2, 1)
calibre 6.10  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 50, 0) && Find Duplicates (1, 10, 7) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Obok DeDRM (7, 2, 1)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.96245733788396 x 110.83636363636363
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.5,
 'geometry_in_logical_pixels': {'height': 720, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 720, 'width': 1280},
 'virtual_geometry': {'height': 1800, 'width': 1920, 'x': 0, 'y': -1080}}
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080,
                                'width': 1920,
                                'x': 0,
                                'y': -1080},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1800, 'width': 1920, 'x': 0, 'y': -1080}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1058, 'width': 1920, 'x': 0, 'y': -1058},
 'full_screened': False,
 'geometry': {'height': 1027, 'width': 1920, 'x': 0, 'y': -1027},
 'maximized': True,
 'normal_geometry': {'height': 677, 'width': 1279, 'x': 202, 'y': -894},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': -1080},
            'index_in_screens_list': 1,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY2',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1800,
                                 'width': 1920,
                                 'x': 0,
                                 'y': -1080}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080,
                                'width': 1920,
                                'x': 0,
                                'y': -1080},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1800, 'width': 1920, 'x': 0, 'y': -1080}}
Setting widget geometry to: {'height': 1027, 'width': 1920, 'x': 0, 'y': -1027}
Restoring widget to maximized
[1.38] main UI initialized...
[1.38] Hiding splash screen
Starting QuickView
[11.61] splash screen hidden
[11.61] Started up in 11.61 seconds with 1819 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x86\xf7\x8a\xb8.\xfb\xa8hv\xaa\xfdj\x14]l0\x9c\xfe\x10\x87\xc7\xad\x95\xc9{g\x8f\xbeC\xeaV\x14', b'C:\\Users\\Kathryn\\Documents\\My Digital Editions\\Marine Ornamental Species Aquaculture.pdf', b'C:\\Users\\Kathryn\\Documents\\My Digital Editions\\Marine Ornamental Species Aquaculture.epub']
DeDRM v7.2.1: Trying to decrypt Marine Ornamental Species Aquaculture.pdf
DeDRM v7.2.1: Marine Ornamental Species Aquaculture.pdf is a PDF ebook
DeDRM v7.2.1: Trying Encryption key default_key
DeDRM v7.2.1: Trying to decrypt Marine Ornamental Species Aquaculture.epub
DeDRM v7.2.1: Exception when decrypting after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 174, in decrypt
ValueError: Ciphertext with incorrect length (not 128 bytes)
DeDRM v7.2.1: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v7.2.1: Trying Encryption key default_key_2
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 436, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 174, in decrypt
ValueError: Ciphertext with incorrect length (not 128 bytes)
DeDRM v7.2.1: Failed to decrypt with key default_key_2 after 0.2 seconds
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v7.2.1: Trying a new default key
DeDRM v7.2.1: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 487, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2178, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 1984, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1469, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1599, in initialize_ebx
  File "calibre_plugins.dedrm.ineptpdf", line 390, in decrypt
  File "Crypto\Cipher\PKCS1_v1_5.py", line 174, in decrypt
ValueError: Ciphertext with incorrect length (not 128 bytes)
DeDRM v7.2.1: Failed to decrypt with new default key after 0.3 seconds
DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 640, in run
  File "calibre_plugins.dedrm.__init__", line 515, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v7.2.1: “Marine Ornamental Species Aquaculture.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.2 seconds. DRM free perhaps?
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 435, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Added Marine Ornamental Species Aquaculture to db in: 0.3
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Exception ignored in: <function NativeFunction.__del__ at 0x000001B065D7A710>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001B065D7A710>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

```

**Comment by ElleKayEm** [comment]
Log shows you're still running DeDRM 7.2.1.  Update to 10.0.3.

**Comment by kelawson48** [comment]
Updated and problem solved - thought I'd updated it before, but apparently selected the wrong file. Thank you for the support, and apologies for the simple issue!
