### ISSUE TITLE
        No K4PC kindle.info/kinf/kinf2011 files have been found.

### ISSUE THREAD

**Issue by fritzphantom** [noDRM/DeDRM_tools#236]
### Question / bug report

I tried to remove DRM form an azw3 book, but it fails for reasons that I don't understand. 
Any idea what it could be ? 

### Which version of Calibre are you running?

6.20

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

none

### Log output

```log
       [1.84] main UI initialized...
        [1.84] Hiding splash screen
        Starting QuickView
        DeDRM v10.0.3: Trying to decrypt booktitle.azw3
        Using Library AlfCrypto DLL/DYLIB/SO
        MobiDeDrm v1.1.
        Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
        Decrypting Kindle Format 8 ebook: booktitle
        Found 2 keys to try after 0.3 seconds
        Crypto Type is: 2
        DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
        DeDRM v10.0.3: Looking for new default Kindle Key after 0.3 seconds
        searching for kinfoFiles in C:\Users\me\AppData\Local
        No K4PC kindle.info/kinf/kinf2011 files have been found.
        DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
        Running file type plugin DeDRM failed with traceback:
        Traceback (most recent call last):
          File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
          File "C:\Users\me\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
          File "C:\Users\me\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
        mobidedrm.DrmException: No key found in 2 PIDs tried.
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
          File "calibre_plugins.dedrm.__init__", line 1056, in run
          File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
        calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
        [5.55] splash screen hidden
        [5.55] Started up in 5.55 seconds with 506 books
```

**Comment by ElleKayEm** [comment]
Looks like you don't have the correct serial number in DeDRM's customization.

**Comment by fritzphantom** [comment]
Yes, that was indeed the problem, thank you!

In case somebody else if having the same issue, it was hard to distinguish the zeros and "O" in the serial number. The safe way is to copy it from your amazon account, instructions are here: https://thebookbuff.com/find-kindle-serial-number/
