### ISSUE TITLE
Plugin doesn't work with AZW file on Windows or Mac

### ISSUE THREAD

**Issue by GMTheDoctor** [noDRM/DeDRM_tools#237]
### Question / bug report

Hello, I checked all the faqs and videos possibile but I can't understand what is the problem. I did the "debug procedure" and here you are my log. Can you please help me? (I tried to do it both on windows and Mac, but I downloaded the AZW from Kindle in Windows)

### Which version of Calibre are you running?

6.10.0

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

1.17

### Log output

Using calibre Qt style: True
calibre Log di debug
calibre 6.10  embedded-python: True
macOS-13.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.1', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.10  embedded-python: True
macOS-13.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.2.0', 'Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.1', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.00000162199728 x 108.00000162199726
[0.00] Starting up...
[0.08] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 4000, 'x': 0, 'y': 0}}
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900,
                                'width': 1440,
                                'x': 2560,
                                'y': 540},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 1440, 'width': 4000, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 849, 'width': 1190, 'x': 261, 'y': 289},
 'full_screened': False,
 'geometry': {'height': 821, 'width': 1190, 'x': 261, 'y': 317},
 'maximized': False,
 'normal_geometry': {'height': 821, 'width': 1190, 'x': 261, 'y': 317},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 2560,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 2560},
            'virtual_geometry': {'height': 1440,
                                 'width': 4000,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 4000, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 821, 'width': 1190, 'x': 261, 'y': 317}
[0.79] main UI initialized...
[0.79] Hiding splash screen
Starting QuickView
qt.qpa.fonts: Populating font family aliases took 86 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
2023-01-03 14:30:37.801 calibre-debug[14489:5953998] +[CATransaction synchronize] called within transaction
DeDRM v10.0.3: Trying to decrypt B01CDGUT9U_EBOK.azw
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Miniviti e placche: Dispositivi temporanei di ancoraggio in ortodonzia (Italian Edition)
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/gianmarco/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/gianmarco/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[4.03] splash screen hidden
[4.03] Started up in 4.03 seconds with 2 books
Added Miniviti e placche: Dispositivi temporanei di ancoraggio in ortodonzia (Italian Edition) to db in: 0.0
Added 1 books in 0.6 seconds
Worker Launch took: 0.01 seconds
Saving geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 849, 'width': 1190, 'x': 261, 'y': 289},
 'full_screened': False,
 'geometry': {'height': 821, 'width': 1190, 'x': 261, 'y': 317},
 'maximized': False,
 'normal_geometry': {'height': 821, 'width': 1190, 'x': 261, 'y': 317},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 2560,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 2560},
            'virtual_geometry': {'height': 1440,
                                 'width': 4000,
                                 'x': 0,
                                 'y': 0}}}

**Comment by GMTheDoctor** [comment]
> Each installation of the Kindle for Mac/PC app has a unique key. Calibre with DeDRM needs to be on the same machine and user as the app which was used to download that copy of the book in order to get the correct key to decrypt it.

Thanks for your reply, but I tried on windows too and it didn’t work the same, now I send that log file too

**Comment by GMTheDoctor** [comment]
> > Each installation of the Kindle for Mac/PC app has a unique key. Calibre with DeDRM needs to be on the same machine and user as the app which was used to download that copy of the book in order to get the correct key to decrypt it.
> 
> Thanks for your reply, but I tried on windows too and it didn’t work the same, now I send that log file too

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Log di debug
calibre 6.10  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.10  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.0836842105263 x 111.87545454545453
[0.00] Starting up...
[0.00] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 969, 'width': 1617, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 969, 'width': 1617},
 'virtual_geometry': {'height': 969, 'width': 1617, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 512, 'width': 1324, 'x': 303, 'y': 60},
 'full_screened': False,
 'geometry': {'height': 481, 'width': 1324, 'x': 303, 'y': 91},
 'maximized': False,
 'normal_geometry': {'height': 481, 'width': 1324, 'x': 303, 'y': 91},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 969,
                                           'width': 1617,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 969, 'width': 1617},
            'virtual_geometry': {'height': 969, 'width': 1617, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 969, 'width': 1617, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 969, 'width': 1617},
 'virtual_geometry': {'height': 969, 'width': 1617, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 481, 'width': 1324, 'x': 303, 'y': 91}
[1.61] main UI initialized...
[1.61] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt B01CDGUT9U_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
[5.28] splash screen hidden
[5.28] Started up in 5.28 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'/\xc89v\x85\t\x96\xb9\x84y\xf7\x99\xd8\x7f\\k\x86\x03\x92;\xc9}w\xc8\x97\xe6d\x8d\xba<\xb1\xd8', b'\\\\Mac\\Home\\Documents\\My Kindle Content\\B01CDGUT9U_EBOK.azw']
Decrypting Kindle Format 8 ebook: Miniviti e placche: Dispositivi temporanei di ancoraggio in ortodonzia (Italian Edition)
Found 0 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\gianmarco\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\gianmarco\AppData\Local\Amazon\Kindle\storage\.kinf2018
DeDRM v10.0.3: Exception when getting default Kindle Key after 0.6 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 969, in KindleMobiDecrypt
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\kindlekey.py", line 947, in kindlekeys
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\kindlekey.py", line 458, in getDBfromFile
UnboundLocalError: local variable 'version' referenced before assignment
DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
Looks like Kindle for PC has updated past 1.17.  See this post: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by GMTheDoctor** [comment]
> Looks like Kindle for PC has updated past 1.17. See this post: https://www.mobileread.com/forums/showthread.php?t=283371

This is the post that I already followed. Anyway, I installed everything and tried again but same problem. Here you are my log again

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Log di debug
calibre 6.10  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.10  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.0836842105263 x 111.87545454545453
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 969, 'width': 1617, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 969, 'width': 1617},
 'virtual_geometry': {'height': 969, 'width': 1617, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 512, 'width': 1324, 'x': 303, 'y': 60},
 'full_screened': False,
 'geometry': {'height': 481, 'width': 1324, 'x': 303, 'y': 91},
 'maximized': False,
 'normal_geometry': {'height': 481, 'width': 1324, 'x': 303, 'y': 91},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 969,
                                           'width': 1617,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 969, 'width': 1617},
            'virtual_geometry': {'height': 969, 'width': 1617, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 969, 'width': 1617, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 969, 'width': 1617},
 'virtual_geometry': {'height': 969, 'width': 1617, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 481, 'width': 1324, 'x': 303, 'y': 91}
[1.06] main UI initialized...
[1.06] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt B01CDGUT9U_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Miniviti e placche: Dispositivi temporanei di ancoraggio in ortodonzia (Italian Edition)
Found 0 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.5 seconds
[7.23] splash screen hidden
[7.23] Started up in 7.23 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'.\t\x9c9\xc2\xb3\xd0\xe2\xe9z\xb0\x11e\x80.9\x1f\x03m\xe5\x96b!~\xa5O%J\xc4_9\xc5', b'\\\\Mac\\Home\\Documents\\My Kindle Content\\B01CDGUT9U_EBOK.azw']
searching for kinfoFiles in C:\Users\gianmarco\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\gianmarco\AppData\Local\Amazon\Kindle\storage\.kinf2011
DeDRM v10.0.3: Exception when getting default Kindle Key after 0.5 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 969, in KindleMobiDecrypt
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\kindlekey.py", line 947, in kindlekeys
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\kindlekey.py", line 458, in getDBfromFile
UnboundLocalError: local variable 'version' referenced before assignment
DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gianmarco\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
Did you redownload the book after reinstalling Kindle for PC?

**Comment by GMTheDoctor** [comment]
> Did you redownload the book after reinstalling Kindle for PC?

Yes I did

**Comment by ElleKayEm** [comment]
Something is off here with the key retrieval.  I think @noDRM may need to take a look.

**Comment by GMTheDoctor** [comment]
> Something is off here with the key retrieval. I think @noDRM may need to take a look.

Waiting for @noDRM
