### ISSUE TITLE
deDRM 10.0.3 conversion issues from epub to PDF

### ISSUE THREAD

**Issue by MichelRobitaille** [noDRM/DeDRM_tools#246]
It takes a very long time to convert an ePub file to PDF.
It took more than an hour and got stuck to 47%.
It then after an additional time of an hour it move to 67%
Then after 2 hours and 13 minutes, it reach 100% but FAILED due to a lack of the cover file image.

In other blogs we can find explanations about the ePub document structure complexity.
That said, the intermediary files creation might be a problem.
For instance after processing all the pages, the plugin just failed, see the log below.

Regards,
=====
[...The user account folder name has been changed to "user".
....all the lines not relevant have been removed from the log....]

Creating PDF Output...
Converting input as a text based book...
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1281, in run
  File "calibre\ebooks\conversion\plugins\pdf_output.py", line 183, in convert
  File "calibre\ebooks\conversion\plugins\pdf_output.py", line 232, in convert_text
  File "calibre\ebooks\conversion\plugins\pdf_output.py", line 194, in get_cover_data
  File "calibre\ebooks\oeb\base.py", line 1030, in data
  File "calibre\ebooks\oeb\base.py", line 582, in read
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Local\\Temp\\calibre_yw4sioys\\viugy30s_plumber\\OPS/images/9782017879817_Couv.jpg'

**Comment by ElleKayEm** [comment]
Conversion is handled by calibre, not DeDRM.
