### ISSUE TITLE
MacOS - DeDRM azw3 file

### ISSUE THREAD

**Issue by scarletinches** [noDRM/DeDRM_tools#249]
### Question / bug report

I am on a Mac, running Catalina 10.15.7. Downloaded calibre 6.11, installed DeDRM 10.0.3 and added my Kindle serial number. Added KFX plug-in, restarted the app, and my Kindle file that I downloaded onto my desktop from Amazon still has DRM. Restarted my mac too, still no luck.

Could any of my issue be that my Kindle is old? Its a kindle fire HDX 3rd generation from 2013 running Fire OS 4.5.5.3 which is "up to date". Its connected to wifi and I can still see all current my Amazon books etc so my Kindle seems to be functioning properly.

**Bug Report**

Using calibre Qt style: True
calibre Debug log
calibre 6.11  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
calibre 6.11  embedded-python: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 113.50000170459899 x 113.50000170459901
[0.00] Starting up...
[0.02] Showing splash screen...
[0.21] splash screen shown
[0.21] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Restoring geometry for: jobs_dialog_geometry
{'frame_geometry': {'height': 356, 'width': 688, 'x': 475, 'y': 221},
 'full_screened': False,
 'geometry': {'height': 334, 'width': 688, 'x': 475, 'y': 243},
 'maximized': False,
 'normal_geometry': {'height': 334, 'width': 688, 'x': 475, 'y': 243},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 334, 'width': 688, 'x': 475, 'y': 243}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'full_screened': True,
 'geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'maximized': False,
 'normal_geometry': {'height': 611, 'width': 1029, 'x': 90, 'y': 66},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 800, 'width': 1280, 'x': 0, 'y': 0}
Restoring widget to full screen
[1.54] main UI initialized...
[1.54] Hiding splash screen
[1.55] splash screen hidden
[1.55] Started up in 1.55 seconds with 1 books
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Pediatric Acute Care.azw3
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Pediatric Acute Care
Found 2 keys to try after 0.4 seconds
Crypto Type is: 2
Warning: This is a library or rented ebook (1681300799000). Continuing ...
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.4 seconds
Found k4Mac kinf2018 file: /Users/scarletinches/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'scarletinches'  on file  /Users/scarletinches/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'0919972b2a56'
Decrypted key file using IDString '0919972b2a56' and UserName 'scarletinches'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Pediatric Acute Care
Got DSN key from database key_0
Found 4 keys to try after 1.0 seconds
Crypto Type is: 2
Warning: This is a library or rented ebook (1681300799000). Continuing ...
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/scarletinches/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/scarletinches/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/scarletinches/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/scarletinches/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/scarletinches/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/scarletinches/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Pediatric Acute Care to db in: 0.1
Added 1 books in 1.8 seconds

### Which version of Calibre are you running?

6.11

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

4.5.5.3

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Won't work for a Kindle Fire.  Needs to be an E-ink Kindle.  See this post for possible alternatives:  https://www.mobileread.com/forums/showthread.php?t=283371

Also see this Mac specific info:  https://www.mobileread.com/forums/showpost.php?p=3819708&postcount=508
