### ISSUE TITLE
Cannot open Adobe DRM PDF

### ISSUE THREAD

**Issue by nesoberis** [noDRM/DeDRM_tools#25]
### Question / bug report

Trying to open a file that was not authorized with my Adobe ID (needs some sort of vendor ID?). Keeps erroring with the provided log output.

### Which version of Calibre are you running?

5.12

### Which version of the DeDRM plugin are you running?

10.0.2

### Log output

```log
calibre, version 5.12.0
ERROR: Loading book failed: Failed to open the book at C:\Unknown.pdf. Click "Show details" for more info.

Failed to convert book: C:\Unknown.pdf with error:
DeDRM v10.0.2: Trying to decrypt Unknown.pdf
DeDRM v10.0.2: Unknown.pdf is a PDF ebook for UUID 269417a0-1db3-47a1-90ff-1705cfd577f2
DeDRM v10.0.2: Looking for new default Adobe Digital Editions Keys after 0.5 seconds
Found 1 keys
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 35, in checkForDeACSMkeys
ModuleNotFoundError: No module named 'calibre_plugins.deacsm'
DeDRM v10.0.2: Trying a new default key
DeDRM v10.0.2: Exception when decrypting after 0.9 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 712, in PDFDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2322, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 2128, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1504, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1713, in initialize_ebx_inept
TypeError: object of type 'int' has no len()
DeDRM v10.0.2: Failed to decrypt with new default key after 0.9 seconds
DeDRM v10.0.2: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
InputFormatPlugin: PDF Input running
on C:\Unknown.pdf
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 346, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 895, in run
  File "calibre_plugins.dedrm.__init__", line 770, in PDFDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 197, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 867, in viewer_main
  File "calibre\srv\render_book.py", line 858, in render_for_viewer
  File "calibre\srv\render_book.py", line 835, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 63, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 54, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
```

**Comment by ElleKayEm** [comment]
Needs to be authorized with an Adobe ID.

**Comment by noDRM** [comment]
That doesn't seem to be the issue, as the log says "Found 1 keys", meaning, it did find a new ADE key. Unfortunately, I don't really have an idea where this error comes from. The only place in the function `initialize_ebx_inept` where "len" is called is to get the length of the encrypted book key. And that's not supposed to be an int as in the error message ...

**Comment by ElleKayEm** [comment]
Are you saying you cannot open it in ADE?

**Comment by j-howell** [comment]
> Unfortunately, I don't really have an idea where this error comes from. The only place in the function `initialize_ebx_inept` where "len" is called is to get the length of the encrypted book key. And that's not supposed to be an int as in the error message ...

There is a bug in RSA decryption on line 399:
`            return _PKCS1_v1_5.new(self._rsa).decrypt(data, 172)`

The second argument to decrypt() is the value to return if decryption is unsuccessful. So in that case it returns the number 172 instead of a byte string causing the length check to fail on line 1713.

**Comment by ableeker** [comment]
That 172 value definitely is incorrect here. I suggest changing this to:

`            return _PKCS1_v1_5.new(self._rsa).decrypt(data, b'')`

Adding the following to verify_book_key:

`        if len(bookkey) <= 16:`
`            return False`

And removing line 1713:

`        if len(bookkey) > 16:`

This way, when decryption fails, decrypt will return a byte string of length 0, and in that case verify_book_key will check for this and return False to indicate that decrypting the key has failed.

I'll submit a PR.

**Comment by ableeker** [comment]
PR #40 submitted.

**Comment by ableeker** [comment]
This PR is working correctly stand-alone, but isn't after creating the plugin. I'm going to submit a new PR.

**Comment by ableeker** [comment]
PR #45 submitted.

**Comment by noDRM** [comment]
By merging #48 this should now also be fixed, closing this issue. If this still occurs, please reopen.
