### ISSUE TITLE
DeDRM MacOS ePub

### ISSUE THREAD

**Issue by bluedogtwo** [noDRM/DeDRM_tools#251]
### Question / bug report

Not working

### Which version of Calibre are you running?

3.48

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log

calibre 3.48  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: xx
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 3.48  embedded-python: True is64bit: True
Darwin-17.7.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '17.7.0', 'Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64')
Python 2.7.15
OSX: ('10.13.6', ('', '', ''), 'x86_64')
Interface language: sv
Successfully initialized third party plugins: DeDRM (10, 0, 3)
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 133.000001997 x 139.000002088
Using calibre Qt style: True
[0.00] Starting up...
[0.08] Showing splash screen...
[0.61] splash screen shown
[0.61] Initializing db...
[0.64] db initialized
[0.64] Constructing main UI...
[3.39] main UI initialized...
[3.39] Hiding splash screen
[3.45] splash screen hidden
[3.46] Started up in 3.46 seconds with 12 books
DeDRM v10.0.3: Trying to decrypt xx.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: xx.epub is a secure Adobe Adept ePub for UUID xxxxx-xxxx-xxxx-xxx-xxxx
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
  File "lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
TypeError: Non-hexadecimal digit found
Added xx to db in: 0.1
Added 1 books in 2.5 seconds

```

**Comment by ElleKayEm** [comment]
For calibre 3.48, try DeDRM 6.8.1: https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

**Comment by bluedogtwo** [comment]
I have tried that, but with on luck.

**Comment by ElleKayEm** [comment]
Did you download the epub with ADE 2.0.1?  On the same machine and user as where you have calibre with DeDRM?

**Comment by bluedogtwo** [comment]
I used ADO 4.5. All on the same machine.

**Comment by ElleKayEm** [comment]
Possible that it's the hardened Adobe DRM which the older DeDRM can't handle.  You could test that by seeing if ADE 2.0.1 authorized with the same Adobe ID can open the book.  DeDRM 10.0.3 can handle the newer Adobe DRM, but you probably need to be able to run at least calibre 4 and preferably calibre 6.
