### ISSUE TITLE
Cannot dedrm library loan pdf 

### ISSUE THREAD

**Issue by ministoat** [noDRM/DeDRM_tools#256]
### Question / bug report

I'm downloading into Adobe DE from a variety of sites, I've one pdf that isn't working properly and I'm assuming that I've done something wrong. 

DE is authenticating via my Adobe account. 

### Which version of Calibre are you running?

6.11.0

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
DeDRM v10.0.3: Trying to decrypt Ethnographic I.pdf
DeDRM v10.0.3: Ethnographic I.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: Ethnographic I.pdf is a PDF ebook (EBX) for UUID e32af688-5fb1-407c-af42-9ee9b925edcf
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 923, in PDFDecrypt
    return self.PDFIneptDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 718, in PDFIneptDecrypt
    userkey = codecs.decode(userkeyhex,'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[8.61] splash screen hidden
[8.61] Started up in 8.61 seconds with 16 books
Added Ethnographic I to db in: 0.1
Added 1 books in 1.0 seconds

```

**Comment by ElleKayEm** [comment]
Try deleting the Adobe key from DeDRM's customization.  Then re-add the book letting DeDRM automatically retrieve the key.

**Comment by ministoat** [comment]
`DeDRM v10.0.3: Trying to decrypt Ethnographic I.pdf
DeDRM v10.0.3: Ethnographic I.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: Ethnographic I.pdf is a PDF ebook (EBX) for UUID e32af688-5fb1-407c-af42-9ee9b925edcf
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 923, in PDFDecrypt
    return self.PDFIneptDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 718, in PDFIneptDecrypt
    userkey = codecs.decode(userkeyhex,'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1`

**Comment by ministoat** [comment]
Done, rebooted machine etc.  

DeDRM v10.0.3: Trying to decrypt Ethnographic I.pdf
DeDRM v10.0.3: Ethnographic I.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: Ethnographic I.pdf is a PDF ebook (EBX) for UUID e32af688-5fb1-407c-af42-9ee9b925edcf
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 923, in PDFDecrypt
    return self.PDFIneptDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 718, in PDFIneptDecrypt
    userkey = codecs.decode(userkeyhex,'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1

**Comment by ElleKayEm** [comment]
There are some fixes in the latest code that might help.  Go to this page: https://github.com/noDRM/DeDRM_tools/actions/runs/3855619930

Scroll to the bottom and download the plugin from there.

**Comment by ministoat** [comment]
Thanks - I'm getting the top level init error with that. 

Do I need to do a git checkout?

**Comment by ministoat** [comment]
Thanks - I ran make locally and installed that version, seems to be the same error still: 

`[0.85] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Ethnographic I.pdf
DeDRM v10.0.3: Ethnographic I.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: Ethnographic I.pdf is a PDF ebook (EBX) for UUID e32af688-5fb1-407c-af42-9ee9b925edcf
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1036, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 896, in PDFDecrypt
    return self.PDFIneptDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 691, in PDFIneptDecrypt
    userkey = codecs.decode(userkeyhex,'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
[2.71] splash screen hidden
[2.71] Started up in 2.71 seconds with 0 books
Added Ethnographic I to db in: 0.1
Added 1 books in 0.7 seconds
`

**Comment by ElleKayEm** [comment]
Alright, seems like @noDRM will need to take a look at this.

**Comment by michaelglass** [comment]
@ElleKayEm fwiw I ran into the same error and [your first suggestion](https://github.com/noDRM/DeDRM_tools/issues/256#issuecomment-1396117558) fixed it for me. Thanks! 🤗
