### ISSUE TITLE
DeDRM fails

### ISSUE THREAD

**Issue by Flyfisher1972** [noDRM/DeDRM_tools#259]
### Question / bug report

DRM is not removed from the new Amazon KFX-Zip format using DeDRM 10.0.3. OpSys Windows 7 64-bit

### Which version of Calibre are you running?

3.48

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

1.39

### Log output

```log
Paste log output here.
```calibre Debug log
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 72.035450517 x 72.0
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.08] splash screen shown
[0.08] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[1.81] main UI initialized...
[1.81] Hiding splash screen
[52.64] splash screen hidden
[52.65] Started up in 52.65 seconds with 1128 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['=.\xf2inK\xc9\x8cu\x16\xa4J\x19\xa9\xf1\xa3\x08!\x9f\xe6\xe1\xa3\x01\xba\x90\xda\x95\x13T\x9bk\x06', 'C:\\Users\\Bob Casanova\\Documents\\New eBooks\\B00I3QCLWS_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 1.50.0: Importing C:\Users\Bob Casanova\Documents\New eBooks\B00I3QCLWS_EBOK.azw
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\BOBCAS~1\AppData\Local\Temp\calibre_3muqy0\ctee_u.kfx-zip
DeDRM v10.0.3: Trying to decrypt ctee_u.kfx-zip
Using Library AlfCrypto Python
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 944, in KindleMobiDecrypt
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 105, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 181, in load_module
  File "calibre_plugins.dedrm.topazextract", line 246
    if debug: print("%d records in header " % nbValues, end=' ')
                                                           ^
SyntaxError: invalid syntax
Package KFX (from KFX Input) 1.50.0: Packaging C:\Users\BOBCAS~1\AppData\Local\Temp\calibre_3muqy0\ctee_u.kfx-zip
Processing container: B00I3QCLWS_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
KFXDRMError: Book container B00I3QCLWS_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\BOBCAS~1\AppData\Local\Temp\calibre_3muqy0\teu_ub_add_books\0\B00I3QCLWS_EBOK.kfx-zip
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 428, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added B00I3QCLWS EBOK to db in: 1.8
Added 1 books in 2.6 seconds
Worker Launch took: 0.181999921799
Job: 0 Convert book 1 of 1 (B00I3QCLWS EBOK) finished
Convert book 1 of 1 (B00I3QCLWS EBOK)
	DeDRM v10.0.3: Trying to decrypt c6bmom.kfx-zip
	Using Library AlfCrypto Python
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	  File "calibre_plugins.dedrm.__init__", line 944, in KindleMobiDecrypt
	  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
	  File "calibre_plugins.dedrm.k4mobidedrm", line 105, in <module>
	  File "site-packages\calibre\customize\zipplugin.py", line 181, in load_module
	  File "calibre_plugins.dedrm.topazextract", line 246
	    if debug: print("%d records in header " % nbValues, end=' ')
	                                                           ^
	SyntaxError: invalid syntax
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: u'kobo'
	  read_metadata_from_opf: u'C:\\Users\\BOBCAS~1\\AppData\\Local\\Temp\\calibre_3muqy0\\3vsfgr.opf'
	Resolved conversion options
	calibre version: 3.48.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000000003DAACF8>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x0000000003FE74A8>,
	 'page_breaks_before': u'/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\BOBCAS~1\\AppData\\Local\\Temp\\calibre_3muqy0\\3vsfgr.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.3: Trying to decrypt c6bmom.kfx-zip
	DeDRM v10.0.3: Failed to decrypt with error: 'module' object has no attribute 'GetDecryptedBook'
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	DeDRM v10.0.3: Exception when getting default Kindle Key after 0.0 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 969, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.kindlekey", line 945, in kindlekeys
	  File "calibre_plugins.dedrm.kindlekey", line 338, in getKindleInfoFiles
	TypeError: ExpandEnvironmentStrings() argument 1 must be unicode, not str
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on C:\Users\BOBCAS~1\AppData\Local\Temp\calibre_3muqy0\c6bmom.kfx-zip
	Software versions: KFX Input 1.50.0, calibre 3.48 [64bit], Windows-7-6.1.7601-SP1
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\BOBCAS~1\AppData\Local\Temp\calibre_3muqy0\c6bmom.kfx-zip
	Processing container: B00I3QCLWS_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
	KFXDRMError: Book container B00I3QCLWS_EBOK.azw has DRM and cannot be converted
	Python function terminated unexpectedly
	  This book has DRM! (Error Code: 1)
	Traceback (most recent call last):
	  File "site.py", line 101, in main
	  File "site.py", line 78, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 199, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 125, in convert
	calibre.ebooks.DRMError: This book has DRM!

**Comment by Flyfisher1972** [comment]
Yeah, that seems to be the current status; can only hope for a newer version of DeDRM. And since new books can't be downloaded with older versions of KfPC those of us who use readers other than Kindles are pretty much stuck unless we want to buy a cheap(er) Kindle just to use the "Download to USB" option. Anyway, thanks.

**Comment by ElleKayEm** [comment]
The last 2 times that DeDRM was updated to deal with newer KFX DRM, Amazon broke the update within a day.  At this point, figuring out and releasing a fix is a recipe for Amazon getting even further ahead on this than they already are.  If you intend to convert to epub, you're better off with azw3/kf8 anyway.  Who knows how long the remaining loopholes for getting older decryptable books will last.  Even books which are suppose to be DRM-free have DRM in KFX format.  Best ongoing solution in my opinion, buy books elsewhere.

**Comment by Flyfisher1972** [comment]
Buying elsewhere would be a good solution *if* most of the authors I read, especially those with ongoing series, were available elsewhere.

**Comment by ElleKayEm** [comment]
And you don't already have a Kindle?! ;)

**Comment by Flyfisher1972** [comment]
If I had a Kindle I assume I wouldn't have even seen the problem. I use Calibre to convert to epub to use my Kobo reader.
