### ISSUE TITLE
DeDRM don't work with the book

### ISSUE THREAD

**Issue by oetzi72** [noDRM/DeDRM_tools#261]
### Question / bug report

Using calibre Qt style: True
qt.qpa.fonts: Populating font family aliases took 51 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
calibre Log di debug
calibre 6.11  embedded-python: True
macOS-13.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.2', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.11  embedded-python: True
macOS-13.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.2', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 982, 'width': 1512, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 982, 'width': 1512},
 'virtual_geometry': {'height': 982, 'width': 1512, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 505, 'width': 1139, 'x': 158, 'y': 81},
 'full_screened': False,
 'geometry': {'height': 477, 'width': 1139, 'x': 158, 'y': 109},
 'maximized': False,
 'normal_geometry': {'height': 477, 'width': 1139, 'x': 158, 'y': 109},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 982,
                                           'width': 1512,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '',
            'serial': '',
            'size_in_logical_pixels': {'height': 982, 'width': 1512},
            'virtual_geometry': {'height': 982, 'width': 1512, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 982, 'width': 1512, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 982, 'width': 1512},
 'virtual_geometry': {'height': 982, 'width': 1512, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 477, 'width': 1139, 'x': 158, 'y': 109}
[0.50] main UI initialized...
[0.50] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Il treno dei bambini.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Il treno dei bambini.epub is a secure Adobe Adept ePub for UUID ae026a2c-9c75-414b-a7a3-91f554823665
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v10.0.3: Trying a new default key
6v36vcu7.epub is a secure Adobe Adept ePub.
Could not decrypt 6v36vcu7.epub because of an exception:
Traceback (most recent call last):
  File "/Users/oetzi72/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 327, in decryptBook
    decryptor = Decryptor(bookkey, encryption)
  File "/Users/oetzi72/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 150, in __init__
    self._aes = AES.new(bookkey, AES.MODE_CBC, b'\x00'*16)
  File "Crypto/Cipher/AES.py", line 232, in new
  File "Crypto/Cipher/__init__.py", line 79, in _create_cipher
  File "Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto/Cipher/AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.3: Failed to decrypt with new default key after 0.1 seconds
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[9.82] splash screen hidden
[9.82] Started up in 9.82 seconds with 1 books
Added Il treno dei bambini to db in: 0.0
Added 1 books in 0.4 seconds

### Which version of Calibre are you running?

6.11.0

### Which version of the DeDRM plugin are you running?

v10

### Log output

```log
Using calibre Qt style: True
qt.qpa.fonts: Populating font family aliases took 51 ms. Replace uses of missing font family "MS Shell Dlg 2" with one that exists to avoid this cost. 
calibre Log di debug
calibre 6.11  embedded-python: True
macOS-13.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.2', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.11  embedded-python: True
macOS-13.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.2', ('', '', ''), 'arm64')
Interface language: it
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 982, 'width': 1512, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 982, 'width': 1512},
 'virtual_geometry': {'height': 982, 'width': 1512, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 505, 'width': 1139, 'x': 158, 'y': 81},
 'full_screened': False,
 'geometry': {'height': 477, 'width': 1139, 'x': 158, 'y': 109},
 'maximized': False,
 'normal_geometry': {'height': 477, 'width': 1139, 'x': 158, 'y': 109},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 982,
                                           'width': 1512,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '',
            'serial': '',
            'size_in_logical_pixels': {'height': 982, 'width': 1512},
            'virtual_geometry': {'height': 982, 'width': 1512, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 982, 'width': 1512, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 982, 'width': 1512},
 'virtual_geometry': {'height': 982, 'width': 1512, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 477, 'width': 1139, 'x': 158, 'y': 109}
[0.50] main UI initialized...
[0.50] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Il treno dei bambini.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Il treno dei bambini.epub is a secure Adobe Adept ePub for UUID ae026a2c-9c75-414b-a7a3-91f554823665
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v10.0.3: Trying a new default key
6v36vcu7.epub is a secure Adobe Adept ePub.
Could not decrypt 6v36vcu7.epub because of an exception:
Traceback (most recent call last):
  File "/Users/oetzi72/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 327, in decryptBook
    decryptor = Decryptor(bookkey, encryption)
  File "/Users/oetzi72/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 150, in __init__
    self._aes = AES.new(bookkey, AES.MODE_CBC, b'\x00'*16)
  File "Crypto/Cipher/AES.py", line 232, in new
  File "Crypto/Cipher/__init__.py", line 79, in _create_cipher
  File "Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto/Cipher/AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.3: Failed to decrypt with new default key after 0.1 seconds
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[9.82] splash screen hidden
[9.82] Started up in 9.82 seconds with 1 books
Added Il treno dei bambini to db in: 0.0
Added 1 books in 0.4 seconds

```

**Comment by ElleKayEm** [comment]
Did you download the epub with ADE or DeACSM?  Did you add the key to DeDRM's customization or let DeDRM retrieve it automatically?

**Comment by Patitapetit** [comment]
@ElleKayEm All of now 74 issues will be unsolved?

**Comment by ElleKayEm** [comment]
@Patitapetit Why?

**Comment by j-howell** [comment]
I believe that Patitapetit is referring to the number of currently open issues.

**Comment by ElleKayEm** [comment]
@j-howell Yes, but why ask if they're all going to remain unsolved?

**Comment by j-howell** [comment]
And why ask in this particular issue? We will probably never know what was meant by that.

**Comment by ElleKayEm** [comment]
Probably just because it was at top of the list of open issues at that moment.  (The next issue has already been resolved and closed!)

**Comment by j-howell** [comment]
It’s not as if the number of open issues actually matters. Most are due to a failure to read the instructions.

This would be a good time to acknowledge all of the effort you put into helping people here. I couldn’t answer the same questions over and over while remaining civil.

**Comment by ElleKayEm** [comment]
Thanks!

**Comment by NickFabry** [comment]
I second @j-howell - I’ve learned a great deal from your patient and informative responses to so many of the issues brought up here. Thank you @ElleKayEm !

**Comment by Patitapetit** [comment]
I supposed that nodrm/drm is a group of people who help another with problems with dedrmed. If someone ask and got an answer and dont return. Why keep open the issue?.

**Comment by ElleKayEm** [comment]
If the original poster doesn't close it themself, noDRM will occasionally come through and close things that appear resolved.  But it's low priority.  As far as I know, no one else has the ability.
