### ISSUE TITLE
DeDRM 10.0.3 dont work

### ISSUE THREAD

**Issue by Bramdal77** [noDRM/DeDRM_tools#262]
### Question / bug report

Hello,

I tried to free my first book from DRM today and it doesn't work. I have attached the log file.

### Which version of Calibre are you running?

6.11

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Fehlerdiagnoseprotokoll
calibre 6.11  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.11  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.55183946488295 x 81.64285714285714
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1048, 'width': 1920, 'x': 0, 'y': -8},
 'full_screened': False,
 'geometry': {'height': 1017, 'width': 1920, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 1017, 'width': 1920, 'x': 0, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 1017, 'width': 1920, 'x': 0, 'y': 23}
Restoring widget to maximized
[0.99] main UI initialized...
[0.99] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Die Sternenschnüffler.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Die Sternenschnüffler.epub is a secure Adobe Adept ePub for UUID 03a0940e-31c5-4c19-9632-1b61cab44c37
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[11.61] splash screen hidden
[11.61] Started up in 11.61 seconds with 2030 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x8c\x07\xf5\x7f!\xcfxJ\xf2\x88\x80G\xfb\x03\x98\xbc\xd5P\xf2\xb7\x8du\x1cSz\xd8\x8a\x04\xabY\xd5-', b'C:\\Users\\david\\Documents\\My Digital Editions\\Die Sternenschn\xc3\xbcffler.epub']
Added Die Sternenschnüffler to db in: 0.1
Added 1 books in 0.6 seconds
```

**Comment by Bramdal77** [comment]
I deleted the key in DeDRM and then reloaded the book without adding a key manually. The key was now automatically entered correctly by DeDRM and the protected epub was now decrypted

**Comment by jmhammond** [comment]
> I deleted the key in DeDRM and then reloaded the book without adding a key manually. The key was now automatically entered correctly by DeDRM and the protected epub was now decrypted

Thank you for sharing this! It turns out, at least for our experience on these Adept DRM books, we need to *not* manually add the keys.
