### ISSUE TITLE
Cannot add as Calibre plugin

### ISSUE THREAD

**Issue by vpvrosa** [noDRM/DeDRM_tools#264]
### Question / bug report

error when attempting to add as a plugin

calibre, version 6.2.1
ERROR: Unhandled exception: <b>SyntaxError</b>:Missing parentheses in call to 'print'. Did you mean print(...)? (calibre_plugins.dedrm.__init__, line 161)

calibre 6.2.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 309, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 201, in exec_module
  File "calibre\customize\zipplugin.py", line 197, in get_code
  File "calibre_plugins.dedrm.__init__", line 161
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

### Which version of Calibre are you running?

6.2.1

### Which version of the DeDRM plugin are you running?

10.0.2

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
For calibre 6, use DeDRM 10.0.3: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

**Comment by vpvrosa** [comment]
Tried 10.0.3

calibre, version 6.2.1
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\carl\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.2.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 479, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 300, in load
  File "calibre\customize\zipplugin.py", line 395, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\carl\\Downloads\\DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.

**Comment by owdun** [comment]
I am having similar issues. I have tried several versions, the latest being 10.0.3. When I unzip the tools file there isn't a zipped file within it, just a single folder that contains folders/directories. Version 6.8.1 unzips to a set of 2 zipped files and 3 text files. However, that version fails to load with a python parenthesis error, presumably related to python version 2.

**Comment by ElleKayEm** [comment]
You're downloading 10.0.3 from the first link under Assets on this page?  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

When you unzip that there will be the 2 plugins (zip files) and 3 readmes (text files).  Make sure your browser isn't automatically unzipping the plugins too.

**Comment by owdun** [comment]
Thanks for the link. It seems I was downloading the source code zip. Installed and working fine. :+1:
