### ISSUE TITLE
DeDRM_plugin Files Greyed Out - MacOS

### ISSUE THREAD

**Issue by mlbeeker** [noDRM/DeDRM_tools#266]
### Question / bug report

MacBook with Intel Core
OS: MacOS Ventura 13.2

Trying to load the DeDRM Plugin files wasn't successful. The files in DeDRM_plugin folder are greyed out.
Have tried 2 older versions of Calibre (10.4 and 10.6) with this version of DeDRM plugin and seeing the same problem. I just got a Kindle Paperwhite 7th generation but don't see if I'm able to load serial number other than the plugin.

Imported then attempted to convert an .azw3 file
Error: This book has DRM

### Which version of Calibre are you running?

6.11

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```lUsing calibre Qt style: True
calibre Debug log
calibre 6.11  embedded-python: True
macOS-13.2-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
calibre 6.11  embedded-python: True
macOS-13.2-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 98.00000147181235 x 98.00000147181234
[0.00] Starting up...
[0.06] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 694, 'width': 1111, 'x': 0, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 666, 'width': 1111, 'x': 0, 'y': 53},
 'maximized': False,
 'normal_geometry': {'height': 666, 'width': 1111, 'x': 0, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 666, 'width': 1111, 'x': 0, 'y': 53}
[0.89] main UI initialized...
[0.89] Hiding splash screen
Starting QuickView
2023-01-29 19:50:44.078 calibre-debug[4916:183677] +[CATransaction synchronize] called within transaction
2023-01-29 19:50:44.162 calibre-debug[4916:183677] +[CATransaction synchronize] called within transaction
2023-01-29 19:51:27.304 calibre-debug[4916:183677] +[CATransaction synchronize] called within transaction
2023-01-29 19:51:27.429 calibre-debug[4916:183677] +[CATransaction synchronize] called within transaction
[30.64] splash screen hidden
[30.64] Started up in 30.64 seconds with 1105 books
Restoring geometry for: preferences dialog geometry
{'frame_geometry': {'height': 694, 'width': 930, 'x': 31, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 666, 'width': 930, 'x': 31, 'y': 53},
 'maximized': False,
 'normal_geometry': {'height': 666, 'width': 930, 'x': 31, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 800, 'width': 1280, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'Color LCD',
 'serial': '',
 'size_in_logical_pixels': {'height': 800, 'width': 1280},
 'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 666, 'width': 930, 'x': 31, 'y': 53}
Saving geometry for: preferences dialog geometry
{'frame_geometry': {'height': 694, 'width': 930, 'x': 31, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 666, 'width': 930, 'x': 31, 'y': 53},
 'maximized': False,
 'normal_geometry': {'height': 666, 'width': 930, 'x': 31, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Added The Cloister Walk to db in: 0.0
Added 1 books in 0.4 seconds
Saving geometry for: convert_single_dialog_geom
{'frame_geometry': {'height': 630, 'width': 1210, 'x': 0, 'y': 49},
 'full_screened': False,
 'geometry': {'height': 602, 'width': 1210, 'x': 0, 'y': 77},
 'maximized': False,
 'normal_geometry': {'height': 602, 'width': 1210, 'x': 0, 'y': 77},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (The Cloister Walk) finished
Convert book 1 of 1 (The Cloister Walk)
	Conversion options changed from defaults:
	  verbose: 2
	  cover: '/var/folders/t4/tg94j9xj165dyq6sjwb5t7dh0000gq/C/calibre_6.11.0_tmp_e3_qmgwv/gi1fl07r.jpeg'
	  output_profile: 'ipad3'
	  read_metadata_from_opf: '/var/folders/t4/tg94j9xj165dyq6sjwb5t7dh0000gq/C/calibre_6.11.0_tmp_e3_qmgwv/25csv8f5.opf'
	Resolved conversion options
	calibre version: 6.11.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/t4/tg94j9xj165dyq6sjwb5t7dh0000gq/C/calibre_6.11.0_tmp_e3_qmgwv/gi1fl07r.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x119d9a590>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x119d9a140>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/t4/tg94j9xj165dyq6sjwb5t7dh0000gq/C/calibre_6.11.0_tmp_e3_qmgwv/25csv8f5.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/t4/tg94j9xj165dyq6sjwb5t7dh0000gq/C/calibre_6.11.0_tmp_e3_qmgwv/nii6bz2t.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 196, in _run_module_as_main
	  File "runpy.py", line 86, in _run_code
	  File "site.py", line 41, in <module>
	  File "site.py", line 37, in main
	  File "calibre/utils/ipc/worker.py", line 215, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
	  File "calibre/customize/conversion.py", line 242, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
	calibre.ebooks.DRMError: The Cloister Walk

Saving geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 694, 'width': 1111, 'x': 0, 'y': 25},
 'full_screened': False,
 'geometry': {'height': 666, 'width': 1111, 'x': 0, 'y': 53},
 'maximized': False,
 'normal_geometry': {'height': 666, 'width': 1111, 'x': 0, 'y': 53},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 800,
                                           'width': 1280,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'Color LCD',
            'serial': '',
            'size_in_logical_pixels': {'height': 800, 'width': 1280},
            'virtual_geometry': {'height': 800, 'width': 1280, 'x': 0, 'y': 0}}}

```

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_10.0.3.zip from here: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Unzip it and load DeDRM_plugin.zip into calibre.

**Comment by mlbeeker** [comment]
I've tried that a few times but can't load the plugin. I'd appreciate any suggestions on things I could try.  Here are my steps when trying to load the plugin:

- Download the .zip file to Macbook
- Open zipped folder with Archive Utility app
- Open Calibre > Preferences > Plugins > Load Plugin from File
- In DeDRM_plugin folder all files are greyed out (I can't select them)

In case it helps, I'm attaching a screenshot of the plugin files as they appear when I try to load them.

Thanks for any help.

![941C2974-5039-4A2F-8254-35DB1177ABBA](https://user-images.githubusercontent.com/15850892/218911830-d2f8487c-66e6-4148-954c-68887e565a9a.jpeg)

**Comment by ElleKayEm** [comment]
You're downloading the wrong file or you're unzipping too much.  At the link I gave, download the first file under Assets.  When you unzip it, there will be 2 zip files and 3 txt files.  Load the still zipped DeDRM_plugin.zip.

**Comment by mlbeeker** [comment]
ElleKayEm, I just wanted to say thanks for your patience in explaining things.  This advice plus your advice in another comment thread about copying/pasting my eink kindle serial number did the trick!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by mlbeeker** [comment]
Thanks again.
