### ISSUE TITLE
Error when opening DeDRMed book

### ISSUE THREAD

**Issue by RunicPlays** [noDRM/DeDRM_tools#267]
The original error is:

`calibre, version 6.11.0
ERROR: Loading book failed: Failed to open the book at C:\Users\kaido\Calibre Library\Unknown\CR!PYW63RMG5H7XH95PA8RRA14EFYCW.azw (6)\CR!PYW63RMG5H7XH95PA8RRA14EFYCW - Unknown.md. Click "Show details" for more info.`

When opened it says this:

`Failed to convert book: C:\Users\kaido\Calibre Library\Unknown\CR!PYW63RMG5H7XH95PA8RRA14EFYCW.azw (6)\CR!PYW63RMG5H7XH95PA8RRA14EFYCW - Unknown.md with error:
InputFormatPlugin: TXT Input running
on C:\Users\kaido\Calibre Library\Unknown\CR!PYW63RMG5H7XH95PA8RRA14EFYCW.azw (6)\CR!PYW63RMG5H7XH95PA8RRA14EFYCW - Unknown.md
File extension indicates particular formatting. Forcing formatting type to: markdown
Language not specified
Creator not specified
Building file list...
IgnoreFile("Could not read from file: C:\\Users\\kaido\\AppData\\Local\\calibre-cache\\ev2\\t\\c0-3l4tusus\\£\x91\x94î¬\x80JÈÜöíÞ\x1a\x7fxg\x82µù¦YG7Ã< with error: [Errno 22] Invalid argument: 'C:\\\\Users\\\\kaido\\\\AppData\\\\Local\\\\calibre-cache\\\\ev2\\\\t\\\\c0-3l4tusus\\\\£\\x91\\x94î¬\\x80JÈÜöíÞ\\x1a\\x7fxg\\x82µù¦YG7Ã<'")
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 821, in viewer_main
  File "calibre\srv\render_book.py", line 812, in render_for_viewer
  File "calibre\srv\render_book.py", line 789, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\txt_input.py", line 310, in convert
  File "calibre\ebooks\conversion\plugins\html_input.py", line 90, in convert
  File "calibre\ebooks\conversion\plugins\html_input.py", line 153, in create_oebbook
  File "calibre\ebooks\html\input.py", line 287, in get_filelist
  File "calibre\ebooks\html\input.py", line 265, in traverse
  File "calibre\ebooks\html\input.py", line 109, in __init__
ValueError: embedded null character`

**Comment by ElleKayEm** [comment]
Looks like you've imported a file that's part of a KFX format book.  Take a look at this post:  https://www.mobileread.com/forums/showthread.php?t=283371
