### ISSUE TITLE
Cannot Convert - This Book is Locked by DRM

### ISSUE THREAD

**Issue by samsenrohm** [noDRM/DeDRM_tools#269]
### Question / bug report

Tried the noDRM version linked in Issue #244 no luck...

[B0BSVL2X6Z_EBOK.zip](https://github.com/noDRM/DeDRM_tools/files/10557022/B0BSVL2X6Z_EBOK.zip)

### Which version of Calibre are you running?

6.11

### Which version of the DeDRM plugin are you running?

v10.0.0.3 (Jan 6th)

### If applicable, which version of the Kindle software are you running?

1.39.2

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Started to say you'd need an E-ink Kindle to decrypt this, but I see it's not available for E-ink Kindles.  Let's take a look at a log:  https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by samsenrohm** [comment]
Not sure why, but in trying to follow the instructions in the above link, I see no option 'Restart in debug mode' in 6.11

**Comment by samsenrohm** [comment]
`calibre 6.11  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && BOL_NL (5, 1, 2) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Obok DeDRM (10, 0, 3)
USB devices on system:
(USBDevice(vendor_id=None product_id=None bcd=None devid=usb\root_hub30&vid1b73&pid1009&rev0002 devinst=8),
 USBDevice(vendor_id=0x46d product_id=0xc52b bcd=0x2401 devid=usb\vid_046d&pid_c52b&rev_2401 devinst=9),
 USBDevice(vendor_id=0x67b product_id=0x2773 bcd=0x100 devid=usb\vid_067b&pid_2773&rev_0100 devinst=10),
 USBDevice(vendor_id=0x67b product_id=0x2506 bcd=0x100 devid=usb\vid_067b&pid_2506&rev_0100 devinst=11),
 USBDevice(vendor_id=None product_id=None bcd=None devid=usb\root_hub20&vid8086&pid1d2d&rev0005 devinst=12),
 USBDevice(vendor_id=0x4f9 product_id=0x24a bcd=0x100 devid=usb\vid_04f9&pid_024a&rev_0100&mi_00 devinst=13),
 USBDevice(vendor_id=None product_id=None bcd=None devid=usb\root_hub30&vid1b73&pid1009&rev0002 devinst=14),
 USBDevice(vendor_id=0x67b product_id=0x2773 bcd=0x100 devid=usb\vid_067b&pid_2773&rev_0100 devinst=15),
 USBDevice(vendor_id=0x8087 product_id=0x24 bcd=0x0 devid=usb\vid_8087&pid_0024&rev_0000 devinst=16),
 USBDevice(vendor_id=0x4f9 product_id=0x24a bcd=0x100 devid=usb\vid_04f9&pid_024a&rev_0100 devinst=17),
 USBDevice(vendor_id=0x8087 product_id=0x24 bcd=0x0 devid=usb\vid_8087&pid_0024&rev_0000 devinst=18),
 USBDevice(vendor_id=0x17ef product_id=0x6019 bcd=0x100 devid=usb\vid_17ef&pid_6019&rev_0100 devinst=19),
 USBDevice(vendor_id=0x4f9 product_id=0x24a bcd=0x100 devid=usb\vid_04f9&pid_024a&rev_0100&mi_01 devinst=20),
 USBDevice(vendor_id=0x67b product_id=0x2506 bcd=0x100 devid=usb\vid_067b&pid_2506&rev_0100 devinst=21),
 USBDevice(vendor_id=None product_id=None bcd=None devid=usb\root_hub20&vid8086&pid1d26&rev0005 devinst=22),
 USBDevice(vendor_id=0x46d product_id=0xc52b bcd=0x2401 devid=usb\vid_046d&pid_c52b&rev_2401&mi_02 devinst=23),
 USBDevice(vendor_id=0x46d product_id=0xc52b bcd=0x2401 devid=usb\vid_046d&pid_c52b&rev_2401&mi_01 devinst=24),
 USBDevice(vendor_id=0x46d product_id=0xc52b bcd=0x2401 devid=usb\vid_046d&pid_c52b&rev_2401&mi_00 devinst=25))

No disabled plugins
Looking for devices of type: MTP_DEVICE
The Windows WPD service says there are no portable devices connected
 
Looking for devices of type: SMART_DEVICE_APP
All IP addresses {'{8D69708D-DDEC-A599-BB02-0475A5D2150E}': [{'addr': '10.14.0.2', 'netmask': '255.255.0.0', 'broadcast': '10.14.255.255'}], '{A4602486-F5D8-49AE-B0B0-41A6FC595925}': [{'addr': '192.168.17.100', 'netmask': '255.255.255.0', 'broadcast': '192.168.17.255'}], '{219A3126-349D-4E5B-89A7-4FE1099CEC73}': [{'addr': '169.254.186.70', 'netmask': '255.255.0.0', 'broadcast': '169.254.255.255'}], '{846EE342-7039-11DE-9D20-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
No device is connected
 
Looking for devices...
 
Devices possibly connected: None 
`

**Comment by ElleKayEm** [comment]
It's under the drop-down menu for Preferences on the main toolbar.

**Comment by samsenrohm** [comment]
And yes, I found the drop-down menu.... and here's the log:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.11  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && BOL_NL (5, 1, 2) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Obok DeDRM (10, 0, 3)
calibre 6.11  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && BOL_NL (5, 1, 2) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 81.79119496855346 x 81.8865671641791
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864, 'width': 1536, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 831, 'width': 1536, 'x': 0, 'y': -7},
 'full_screened': False,
 'geometry': {'height': 801, 'width': 1536, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 801, 'width': 1536, 'x': 0, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.25,
            'geometry_in_logical_pixels': {'height': 864,
                                           'width': 1536,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 864, 'width': 1536},
            'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.25,
 'geometry_in_logical_pixels': {'height': 864, 'width': 1536, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 864, 'width': 1536},
 'virtual_geometry': {'height': 864, 'width': 1536, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 801, 'width': 1536, 'x': 0, 'y': 23}
Restoring widget to maximized
[1.45] main UI initialized...
[1.45] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.44:  0.809) _startup_on_demand listening on port 9090
SMART_DEV (   1.48:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.51:  0.000) _startup_on_demand broadcast socket listening on port 54982
[3.22] splash screen hidden
[3.22] Started up in 3.22 seconds with 599 books
Gather KFX-ZIP (from KFX Input) 1.50.0: Importing E:\Calibre\My Kindle Content\B0BSVL2X6Z_EBOK\B0BSVL2X6Z_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 6 file(s) as C:\Users\samsen\AppData\Local\Temp\calibre_inwht4jt\1cwkrcor.kfx-zip
DeDRM v10.0.3: Trying to decrypt 1cwkrcor.kfx-zip
Decrypting KFX-ZIP ebook: 1cwkrcor
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.40ab45bb-aaa1-49a9-8e28-3faf28b662c2.voucher
Traceback (most recent call last):
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\samsen\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\samsen\AppData\Local\Amazon\Kindle\storage\.kinf2018
SMART_DEV (   2.56:  1.012) run All IP addresses {'{8D69708D-DDEC-A599-BB02-0475A5D2150E}': [{'addr': '10.14.0.2', 'netmask': '255.255.0.0', 'broadcast': '10.14.255.255'}], '{A4602486-F5D8-49AE-B0B0-41A6FC595925}': [{'addr': '192.168.17.100', 'netmask': '255.255.255.0', 'broadcast': '192.168.17.255'}], '{219A3126-349D-4E5B-89A7-4FE1099CEC73}': [{'addr': '169.254.186.70', 'netmask': '255.255.0.0', 'broadcast': '169.254.255.255'}], '{846EE342-7039-11DE-9D20-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'fmm!\x8a\x9e\xa9y\xe7\x03\xb1#\xecT\xb8\xd5\xdehs\x93w\xa63]e\x0f$\x12h\xd2\x93\x14', b'E:\\Calibre\\My Kindle Content\\B0BSVL2X6Z_EBOK\\B0BSVL2X6Z_EBOK.azw']
Decrypted key file using IDString '203048609' and UserName 'samsen'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: 1cwkrcor
Got DSN key from database key_0
Found 1 keys to try after 0.4 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.40ab45bb-aaa1-49a9-8e28-3faf28b662c2.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 930, in KindleMobiDecrypt
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 930, in KindleMobiDecrypt
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 930, in KindleMobiDecrypt
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 964, in KindleMobiDecrypt
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 930, in KindleMobiDecrypt
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\samsen\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1029, in run
  File "calibre_plugins.dedrm.__init__", line 980, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.50.0: Packaging C:\Users\samsen\AppData\Local\Temp\calibre_inwht4jt\1cwkrcor.kfx-zip
Processing container: B0BSVL2X6Z_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0BSVL2X6Z_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\samsen\AppData\Local\Temp\calibre_inwht4jt\ezpio7ka_add_books\0\B0BSVL2X6Z_EBOK.kfx-zip

**Comment by ElleKayEm** [comment]
Sorry, seems like you're out of luck with this one.  I don't see any way you could get this in a format that can be decrypted.

**Comment by samsenrohm** [comment]
Okay, it is what it is... hopefully a work-around will be figured out eventually.

Thanks for investigating... much appreciated.

Again, for future reference, the problematic eBook is included at the top of this thread...
