### ISSUE TITLE
Recent .azw3 not DeDRM'd

### ISSUE THREAD

**Issue by dtowell** [noDRM/DeDRM_tools#272]
### Question / bug report

Can anything be done about this book? I used the download USB option, but ...

### Which version of Calibre are you running?

6.11

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

1.17.1 (but shouldn't matter)

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.11  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && EpubSplit (3, 5, 0) && Find Duplicates (1, 10, 7)
calibre 6.11  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && EpubSplit (3, 5, 0) && Find Duplicates (1, 10, 7)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 141.4020618556701
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 2520, 'width': 3440, 'x': -717, 'y': -1440}}
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440,
                                'width': 3440,
                                'x': -717,
                                'y': -1440},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 3440},
 'virtual_geometry': {'height': 2520, 'width': 3440, 'x': -717, 'y': -1440}}
Restoring geometry for: jobs_dialog_geometry
{'frame_geometry': {'height': 572, 'width': 633, 'x': 1547, 'y': -1007},
 'full_screened': False,
 'geometry': {'height': 541, 'width': 633, 'x': 1547, 'y': -976},
 'maximized': False,
 'normal_geometry': {'height': 541, 'width': 633, 'x': 1547, 'y': -976},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 3440,
                                           'x': -717,
                                           'y': -1440},
            'index_in_screens_list': 1,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY2',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 3440},
            'virtual_geometry': {'height': 2520,
                                 'width': 3440,
                                 'x': -717,
                                 'y': -1440}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440,
                                'width': 3440,
                                'x': -717,
                                'y': -1440},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 3440},
 'virtual_geometry': {'height': 2520, 'width': 3440, 'x': -717, 'y': -1440}}
Moving widget to saved screen
Setting widget geometry to: {'height': 541, 'width': 633, 'x': 1547, 'y': -976}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1439, 'width': 1718, 'x': 1004, 'y': -1440},
 'full_screened': False,
 'geometry': {'height': 1408, 'width': 1718, 'x': 1004, 'y': -1409},
 'maximized': False,
 'normal_geometry': {'height': 1408, 'width': 1718, 'x': 1004, 'y': -1409},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 3440,
                                           'x': -717,
                                           'y': -1440},
            'index_in_screens_list': 1,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY2',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 3440},
            'virtual_geometry': {'height': 2520,
                                 'width': 3440,
                                 'x': -717,
                                 'y': -1440}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1440,
                                'width': 3440,
                                'x': -717,
                                'y': -1440},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 3440},
 'virtual_geometry': {'height': 2520, 'width': 3440, 'x': -717, 'y': -1440}}
Setting widget geometry to: {'height': 1408, 'width': 1718, 'x': 1004, 'y': -1409}
[1.14] main UI initialized...
[1.14] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Meru.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Meru
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 6 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 6 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\dwayne\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\dwayne\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '2391831850' and UserName 'dwayne'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Meru
Got DSN key from database key_0
Found 4 keys to try after 0.2 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\dwayne\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\dwayne\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 6 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\dwayne\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\dwayne\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\dwayne\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\dwayne\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 6 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[3.97] splash screen hidden
[3.97] Started up in 3.97 seconds with 1138 books
Added Meru to db in: 0.1
Added 1 books in 0.7 seconds

```

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) for the device when downloading?  Do you have that Kindle's serial number entered correctly into DeDRM's customization?

**Comment by dtowell** [comment]
Ah! I skipped a step. Sorry to bother you.
