### ISSUE TITLE
Unable to convert: this book is protected by DRM (another person)

### ISSUE THREAD

**Issue by aspergerway** [noDRM/DeDRM_tools#277]
### Question / bug report

I think at the time of downloading the version was 1.34. But I'm not ruling anything out.
I would like to know how to do to remove the DRM since I would like to convert it to pdf.

### Which version of Calibre are you running?

6.12.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

1.39.1

### Log output

```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Log di debug
calibre 6.12  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
calibre 6.12  embedded-python: True
Windows-10-10.0.22000-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 50, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 50, 0) && KFX metadata reader (from KFX Input) (1, 50, 0) && KFX Input (1, 50, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 54.98083427282976 x 54.864
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'SAMSUNG',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: jobs_dialog_geometry
{'frame_geometry': {'height': 573, 'width': 633, 'x': 644, 'y': 225},
 'full_screened': False,
 'geometry': {'height': 542, 'width': 633, 'x': 644, 'y': 256},
 'maximized': False,
 'normal_geometry': {'height': 542, 'width': 633, 'x': 644, 'y': 256},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'SAMSUNG',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'SAMSUNG',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 542, 'width': 633, 'x': 644, 'y': 256}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1040, 'width': 1920, 'x': 0, 'y': -8},
 'full_screened': False,
 'geometry': {'height': 1009, 'width': 1920, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 1009, 'width': 1920, 'x': 0, 'y': 23},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'SAMSUNG',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'SAMSUNG',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 1009, 'width': 1920, 'x': 0, 'y': 23}
Restoring widget to maximized
[0.78] main UI initialized...
[0.78] Hiding splash screen
Starting QuickView
[21.12] splash screen hidden
[21.12] Started up in 21.12 seconds with 2 books
Restoring geometry for: convert_single_dialog_geom
{'frame_geometry': {'height': 963, 'width': 1850, 'x': 35, 'y': 30},
 'full_screened': False,
 'geometry': {'height': 932, 'width': 1850, 'x': 35, 'y': 61},
 'maximized': False,
 'normal_geometry': {'height': 932, 'width': 1850, 'x': 35, 'y': 61},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'SAMSUNG',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'SAMSUNG',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 932, 'width': 1850, 'x': 35, 'y': 61}
Saving geometry for: convert_single_dialog_geom
{'frame_geometry': {'height': 963, 'width': 1850, 'x': 35, 'y': 30},
 'full_screened': False,
 'geometry': {'height': 932, 'width': 1850, 'x': 35, 'y': 61},
 'maximized': False,
 'normal_geometry': {'height': 932, 'width': 1850, 'x': 35, 'y': 61},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'SAMSUNG',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Worker Launch took: 0.00 seconds
Job: 0 Converti libro 1 di 1 (B0B34RZ358 EBOK) finished
Converti libro 1 di 1 (B0B34RZ358 EBOK)
	DeDRM v10.0.3: Trying to decrypt etat_z8o.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: etat_z8o
	Got DSN key from database default_key
	Found 1 keys to try after 0.1 seconds
	DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\jovan\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\jovan\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '1590439088' and UserName 'jovan'
	DeDRM v10.0.3: Found 1 new key
	Decrypting KFX-ZIP ebook: etat_z8o
	Got DSN key from database key_0
	Found 1 keys to try after 0.3 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  pdf_mono_family: 'Courier New'
	  output_profile: 'kindle_pw3'
	  read_metadata_from_opf: 'D:\\Temp\\calibre_jj8jyyhk\\1tuvymnl.opf'
	  pdf_serif_family: 'Arial'
	  verbose: 2
	  pdf_sans_family: 'Arial'
	Resolved conversion options
	calibre version: 6.12.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002D6B7F27520>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x000002D6B7F27B20>,
	 'page_breaks_before': '/',
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Courier New',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Arial',
	 'pdf_serif_family': 'Arial',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'D:\\Temp\\calibre_jj8jyyhk\\1tuvymnl.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	DeDRM v10.0.3: Trying to decrypt etat_z8o.kfx-zip
	Decrypting KFX-ZIP ebook: etat_z8o
	Got DSN key from database default_key
	Found 1 keys to try after 0.0 seconds
	DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\jovan\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\jovan\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '1590439088' and UserName 'jovan'
	DeDRM v10.0.3: Found 1 new key
	Decrypting KFX-ZIP ebook: etat_z8o
	Got DSN key from database key_0
	Found 1 keys to try after 0.2 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\jovan\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on D:\Temp\calibre_jj8jyyhk\etat_z8o.kfx-zip
	Software versions: KFX Input 1.50.0, calibre 6.12, Windows-10-10.0.22000-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting D:\Temp\calibre_jj8jyyhk\etat_z8o.kfx-zip
	Processing container: B0B34RZ358_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0B34RZ358_EBOK.azw has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 196, in _run_module_as_main
	  File "runpy.py", line 86, in _run_code
	  File "site.py", line 83, in <module>
	  File "site.py", line 78, in main
	  File "site.py", line 50, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
	  File "calibre\customize\conversion.py", line 242, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 125, in convert
	calibre.ebooks.DRMError: This book has DRM!
```

**Comment by ElleKayEm** [comment]
You'll need an earlier version of Kindle for PC or an E-ink Kindle.  See this post: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by ElusiveZatchmo** [comment]
but, I can't speak for this person, but for me, Kindle won't download certain books until I update to the latest version of Kindle

**Comment by ElleKayEm** [comment]
@ElusiveZatchmo That's true for books published after 3 January, 2023.  This one was published last year.

**Comment by BRASPO22** [comment]
Caliber is not converting purchased ebooks downloaded from the Amazon site since yesterday.
Caliber 6.11 and 6.12
plugins KFX Input, DRM 10.0.3, KFX Output.

Would you know if there is KFX Begone 5?

Thanks in advance.

**Comment by ElleKayEm** [comment]
All current known workarounds for getting Kindle books you can decrypt are at the link in my last comment.

**Comment by romad275** [comment]
I had an interesting problem when I downloaded a newly published Kindle book for transfer via USB. It arrived but was grayed out for transfer. I tried redownloading it for transfer to a different device, but with the same result. I then realized the files were arriving without a .azw3 extension so I tried adding it and the file became available. I don’t know if this download was a glitch, a bug, or deliberate, but in case anyone else gets a similar download result, just try adding the .azw3 extension to the file name. Interestingly, this was a book that supposedly was required to be sold DRM free by the publisher.

Sincerely,
Dennis B. Swaney

Cogito Ergo Mac

**Comment by aspergerway** [comment]
OK thanks I did it. Hopefully a way will be found in the future to unprotect them to convert them to pdf. I love reading them in pdf.

**Comment by ElleKayEm** [comment]
@aspergerway If you're all set, you can close the issue.

**Comment by aspergerway** [comment]
Ok, thanks!
