### ISSUE TITLE
Failing to convert Kindle book, "No key found"

### ISSUE THREAD

**Issue by virtual-violet** [noDRM/DeDRM_tools#28]
### Question / bug report

Every time I try to convert this ebook I bought from Amazon, I get the same error, telling me that it can't find a key and can't decrypt. I'm not sure what happened, I converted one book, then went to do this one, and it doesn't work. I can convert other books fine, it's only this title that is creating the error. [Here is a link to the book in question.](https://www.amazon.com/gp/product/B08TRJHRVZ)

### Which version of Calibre are you running?

5.36.0

### Which version of the DeDRM plugin are you running?

v10.0.2

### Log output

```log
DeDRM v10.0.2: Trying to decrypt The Perfect Match_ A Valentine's Day Novella.azw3
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Perfect Match: A Valentine's Day Novella
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.3 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.2: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v10.0.2: Trying to decrypt The Perfect Match_ A Valentine's Day Novella.azw3
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Perfect Match: A Valentine's Day Novella
Found 0 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.2: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
1% Converting input to HTML...
InputFormatPlugin: MOBI Input running
on /Users/vi/Downloads/The Perfect Match_ A Valentine's Day Novella.azw3
Found KF8 MOBI of type 'standalone'
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/ebooks/conversion/cli.py", line 419, in main
  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
calibre.ebooks.DRMError: The Perfect Match: A Valentine's Day Novella
```

**Comment by ElleKayEm** [comment]
If this is from or downloaded for an E-ink Kindle (not a Fire), then you need to enter your Kindle's serial number into DeDRM's customization.
