### ISSUE TITLE
Unable to open EPUB, decrypt ADEPT, or convert to PDF.

### ISSUE THREAD

**Issue by Jedec22** [noDRM/DeDRM_tools#280]
### Question / bug report

Hello, I'm new to this. 

Apologies if the solution is simple and I've missed it.

I'm using the latest versions of Calibre, ADE and DeDRM Plugin.

Any advice would be greatly appreciated. Thank you in advance.

### Which version of Calibre are you running?

6.12.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

ADE 4.5.11

### Log output

```ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.12  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: en_AU
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.12  embedded-python: True
Windows-10-10.0.19044-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19044')
Python 3.10.1
Windows: ('10', '10.0.19044', 'SP0', 'Multiprocessor Free')
Interface language: en_AU
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.84180790960451 x 91.7458193979933
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'VX248',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 512, 'width': 1204, 'x': 272, 'y': 185},
 'full_screened': False,
 'geometry': {'height': 481, 'width': 1204, 'x': 272, 'y': 216},
 'maximized': False,
 'normal_geometry': {'height': 481, 'width': 1204, 'x': 272, 'y': 216},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'VX248',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'VX248',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 481, 'width': 1204, 'x': 272, 'y': 216}
[0.67] main UI initialized...
[0.67] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Property Law in NSW, 5th ed.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Property Law in NSW, 5th ed.epub is a secure Adobe Adept ePub for UUID 07bb7a9e-fcf9-4ca2-904f-c06518f8d50f
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[3.14] splash screen hidden
[3.14] Started up in 3.14 seconds with 2 books
Added Property Law in NSW, 5th ed to db in: 0.2
Added 1 books in 0.5 seconds
Worker Launch took: 0.00 seconds
Restoring geometry for: convert_single_dialog_geom
{'frame_geometry': {'height': 1011, 'width': 959, 'x': 518, 'y': 18},
 'full_screened': False,
 'geometry': {'height': 980, 'width': 959, 'x': 518, 'y': 49},
 'maximized': False,
 'normal_geometry': {'height': 980, 'width': 959, 'x': 518, 'y': 49},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'VX248',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': 'VX248',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 980, 'width': 959, 'x': 518, 'y': 49}
Saving geometry for: convert_single_dialog_geom
{'frame_geometry': {'height': 1011, 'width': 959, 'x': 518, 'y': 18},
 'full_screened': False,
 'geometry': {'height': 980, 'width': 959, 'x': 518, 'y': 49},
 'maximized': False,
 'normal_geometry': {'height': 980, 'width': 959, 'x': 518, 'y': 49},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': 'VX248',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Worker Launch took: 0.02 seconds
Job: 1 Convert book 1 of 1 (Property Law in NSW, 5th ed) finished

```

**Comment by ElleKayEm** [comment]
Delete the Adobe key in DeDRM's customization.  Then re-add your book letting DeDRM automatically retrieve the key.

**Comment by Jedec22** [comment]
> Delete the Adobe key in DeDRM's customization. Then re-add your book letting DeDRM automatically retrieve the key.

This resolved the problem, thank you.

Please close this ticket.
