### ISSUE TITLE
FileNotFoundError when there's books on external sdcard

### ISSUE THREAD

**Issue by X-static** [noDRM/DeDRM_tools#284]
```
calibre, version 6.12.0
ERROR: Unhandled exception: <b>FileNotFoundError</b>:[Errno 2] No such file or directory: 'F:\\.kobo\\kepub\\856ca411-ad8a-4ff4-82ce-db9b8c979980'

calibre 6.12  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Count Pages (1, 12, 1) && Extract ISBN (1, 6, 0) && Goodreads (1, 7, 3) && Goodreads Sync (1, 16, 2) && Job Spy (1, 0, 204) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 3) && Kobo Books (1, 9, 2) && Kobo Utilities (2, 16, 6) && KoboTouchExtended (3, 6, 3) && Obok DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.dialogs", line 272, in do_book_action
  File "calibre_plugins.obok_dedrm.action", line 220, in get_decrypted_kobo_books
  File "calibre_plugins.obok_dedrm.action", line 374, in decryptBook
  File "zipfile.py", line 1240, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\.kobo\\kepub\\856ca411-ad8a-4ff4-82ce-db9b8c979980'

```

**Comment by ElleKayEm** [comment]
Importing from a Kobo ereader or Kobo Desktop?

**Comment by X-static** [comment]
Kobo ereader

**Comment by ElleKayEm** [comment]
I don't know.  I'd try installing Kobo Desktop.

**Comment by ElleKayEm** [comment]
Further thoughts: is that the normal location the books download to?

Did you have the ereader attached before or after you opened calibre?  I'd try the opposite of whatever you did before.

I've never had an issue myself with Obok not finding books, but I've seen it come up here occassionally.  I usually download the Adobe DRM epubs and use DeDRM.

**Comment by ElleKayEm** [comment]
I've seen people say that if they close the Kobo app, then Obok will see that the books have DRM.

@noDRM might want to take a look at what is going on with the SD card.  Since a lot of the models don't have SD cards, I don't know if the problem has been reported before.
