### ISSUE TITLE
Error Loading plugin "alfcrypto_src.zip is invalid. It does not contain a top-level__init__.py file."

### ISSUE THREAD

**Issue by fketterman** [noDRM/DeDRM_tools#285]
### Question / bug report

calibre, version 6.12.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'F:\\Storage\\noDRM-DeDRM_tools\\DeDRM_plugin\\alfcrypto_src.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.12  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 480, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'F:\\Storage\\noDRM-DeDRM_tools\\DeDRM_plugin\\alfcrypto_src.zip' is invalid. It does not contain a top-level __init__.py file

### Which version of Calibre are you running?

6.12

### Which version of the DeDRM plugin are you running?

noDRM-DeDRM_tools

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Looks like you have the wrong file.  Download the current release from this page: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

The first link under Assets.  Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip.
