### ISSUE TITLE
Unable to Decrypt AZW from Kindle 4th Gen

### ISSUE THREAD

**Issue by recreational-grade** [noDRM/DeDRM_tools#288]
### Question / bug report

Using Calibre to transfer an AZW e-book from a Kindle 4th Gen has generated a DRM error, I have previously been able to import books this way (as recently as last week). This e-book was newly published 2023-02-14.

Any assistance would be great and I am willing to provide the file.

### Which version of Calibre are you running?

6.12

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

4.14

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.12  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && Find Duplicates (1, 10, 7) && Goodreads (1, 7, 3) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 3)
calibre 6.12  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && Find Duplicates (1, 10, 7) && Goodreads (1, 7, 3) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 2.25
logicalDpi: 96.0 x 96.0
physicalDpi: 126.04011627906975 x 125.69072164948453
[0.00] Starting up...
[0.00] Initializing db...
[0.38] db initialized
[0.38] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 2.25,
 'geometry_in_logical_pixels': {'height': 960, 'width': 1707, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 960, 'width': 1707},
 'virtual_geometry': {'height': 960, 'width': 1707, 'x': 0, 'y': 0}}
Restoring geometry for: jobs_dialog_geometry
{'frame_geometry': {'height': 535, 'width': 821, 'x': 444, 'y': 174},
 'full_screened': False,
 'geometry': {'height': 506, 'width': 821, 'x': 444, 'y': 203},
 'maximized': False,
 'normal_geometry': {'height': 506, 'width': 821, 'x': 444, 'y': 203},
 'screen': {'depth': 32,
            'device_pixel_ratio': 2.25,
            'geometry_in_logical_pixels': {'height': 960,
                                           'width': 1707,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 960, 'width': 1707},
            'virtual_geometry': {'height': 960, 'width': 1707, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 2.25,
 'geometry_in_logical_pixels': {'height': 960, 'width': 1707, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 960, 'width': 1707},
 'virtual_geometry': {'height': 960, 'width': 1707, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 506, 'width': 821, 'x': 444, 'y': 203}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 926, 'width': 1707, 'x': 0, 'y': -6},
 'full_screened': False,
 'geometry': {'height': 897, 'width': 1707, 'x': 0, 'y': 23},
 'maximized': True,
 'normal_geometry': {'height': 335, 'width': 526, 'x': 831, 'y': 187},
 'screen': {'depth': 32,
            'device_pixel_ratio': 2.25,
            'geometry_in_logical_pixels': {'height': 960,
                                           'width': 1707,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 960, 'width': 1707},
            'virtual_geometry': {'height': 960, 'width': 1707, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 2.25,
 'geometry_in_logical_pixels': {'height': 960, 'width': 1707, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 960, 'width': 1707},
 'virtual_geometry': {'height': 960, 'width': 1707, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 897, 'width': 1707, 'x': 0, 'y': 23}
Restoring widget to maximized
[2.09] main UI initialized...
[2.09] Started up in 2.09 seconds with 6347 books
Starting QuickView
SMART_DEV (   0.00:  0.002) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.30:  0.820) _startup_on_demand listening on port 9090
SMART_DEV (   1.32:  0.001) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.35:  0.001) _startup_on_demand broadcast socket listening on port 54982
Gather KFX-ZIP (from KFX Input) 1.51.0: Importing C:/Users/user/OneDrive/Desktop/Age of Steel Rise of Mankind Boo-asin_B0BN4WW2HY-type_EBOK-v_0.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.3: Trying to decrypt Age of Steel Rise of Mankind Boo-asin_B0BN4WW2HY-type_EBOK-v_0.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Age of Steel (Rise of Mankind Book 4)
Got DSN key from database default_key
Got DSN key from database default_key_2
Found 10 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 10 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\user\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '443880967' and UserName 'user'
Decrypted key file using IDString '443880967' and UserName 'user'
DeDRM v10.0.3: Found 2 new keys
MobiDeDrm v1.1.
Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Age of Steel (Rise of Mankind Book 4)
Got DSN key from database key_0
Got DSN key from database key_1
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 10 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 10 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
SMART_DEV (   2.38:  1.008) run All IP addresses {'{0695B14B-DBF7-0AD7-D2D7-EF9E329450D6}': [{'addr': '10.15.211.54', 'netmask': '128.0.0.0', 'broadcast': '127.255.255.255'}], '{00E0CFBD-0145-45E9-9F9A-87E758CC5D52}': [{'addr': '192.168.1.115', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{F8958E1A-6DBF-11ED-B06D-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
Added Age of Steel (Rise of Mankind Book 4) to db in: 0.2
Added 1 books in 1.3 seconds
Restoring geometry for: convert_single_dialog_geom
{'frame_geometry': {'height': 729, 'width': 1024, 'x': 341, 'y': 65},
 'full_screened': False,
 'geometry': {'height': 700, 'width': 1024, 'x': 341, 'y': 94},
 'maximized': False,
 'normal_geometry': {'height': 700, 'width': 1024, 'x': 341, 'y': 94},
 'screen': {'depth': 32,
            'device_pixel_ratio': 2.25,
            'geometry_in_logical_pixels': {'height': 960,
                                           'width': 1707,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY1',
            'serial': '',
            'size_in_logical_pixels': {'height': 960, 'width': 1707},
            'virtual_geometry': {'height': 960, 'width': 1707, 'x': 0, 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 2.25,
 'geometry_in_logical_pixels': {'height': 960, 'width': 1707, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY1',
 'serial': '',
 'size_in_logical_pixels': {'height': 960, 'width': 1707},
 'virtual_geometry': {'height': 960, 'width': 1707, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 700, 'width': 1024, 'x': 341, 'y': 94}
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Age of Steel (Rise of Mankind Book 4)) finished
Convert book 1 of 1 (Age of Steel (Rise of Mankind Book 4))
	DeDRM v10.0.3: Trying to decrypt nb03y1uj.azw
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.1.
	Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 6 ebook: Age of Steel (Rise of Mankind Book 4)
	Got DSN key from database default_key
	Got DSN key from database default_key_2
	Found 10 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v10.0.3: Failed to decrypt with error: No key found in 10 PIDs tried.
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\user\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Found K4PC 1.9+ kinf2011 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '443880967' and UserName 'user'
	Decrypted key file using IDString '443880967' and UserName 'user'
	DeDRM v10.0.3: Found 2 new keys
	MobiDeDrm v1.1.
	Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 6 ebook: Age of Steel (Rise of Mankind Book 4)
	Got DSN key from database key_0
	Got DSN key from database key_1
	Found 4 keys to try after 0.4 seconds
	Crypto Type is: 2
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 10 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 4 PIDs tried.
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 10 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  margin_right: 0.0
	  output_profile: 'kindle_pw3'
	  read_metadata_from_opf: 'C:\\Users\\user\\AppData\\Local\\Temp\\calibre_r3399xna\\gspjgrjf.opf'
	  change_justification: 'left'
	  margin_left: 0.0
	  cover: 'C:\\Users\\user\\AppData\\Local\\Temp\\calibre_r3399xna\\fya6ezvg.jpeg'
	  verbose: 2
	Resolved conversion options
	calibre version: 6.12.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'left',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': 'C:\\Users\\user\\AppData\\Local\\Temp\\calibre_r3399xna\\fya6ezvg.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002D3893BDA20>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 0.0,
	 'margin_right': 0.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x000002D3893ADD50>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\user\\AppData\\Local\\Temp\\calibre_r3399xna\\gspjgrjf.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.3: Trying to decrypt nb03y1uj.azw
	MobiDeDrm v1.1.
	Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 6 ebook: Age of Steel (Rise of Mankind Book 4)
	Got DSN key from database default_key
	Got DSN key from database default_key_2
	Found 10 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v10.0.3: Failed to decrypt with error: No key found in 10 PIDs tried.
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\user\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Found K4PC 1.9+ kinf2011 file: C:\Users\user\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '443880967' and UserName 'user'
	Decrypted key file using IDString '443880967' and UserName 'user'
	DeDRM v10.0.3: Found 2 new keys
	MobiDeDrm v1.1.
	Copyright Â© 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Mobipocket 6 ebook: Age of Steel (Rise of Mankind Book 4)
	Got DSN key from database key_0
	Got DSN key from database key_1
	Found 4 keys to try after 0.3 seconds
	Crypto Type is: 2
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 10 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 4 PIDs tried.
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\user\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 10 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on C:\Users\user\AppData\Local\Temp\calibre_r3399xna\nb03y1uj.azw
	Traceback (most recent call last):
	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 30, in convert
	  File "calibre\ebooks\mobi\reader\mobi6.py", line 166, in extract_content
	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm
	calibre.ebooks.DRMError: Age of Steel (Rise of Mankind Book 4)
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 196, in _run_module_as_main
	  File "runpy.py", line 86, in _run_code
	  File "site.py", line 83, in <module>
	  File "site.py", line 78, in main
	  File "site.py", line 50, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
	  File "calibre\customize\conversion.py", line 242, in __call__
	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 36, in convert
	  File "calibre\ebooks\mobi\reader\mobi6.py", line 166, in extract_content
	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm
	calibre.ebooks.DRMError: Age of Steel (Rise of Mankind Book 4)
```

**Comment by ElleKayEm** [comment]
Do you have that Kindle's serial number entered correctly in DeDRM's customization?  Easiest way to make sure you've got it in there correctly is copy and paste from the website.
