### ISSUE TITLE
Can't remove DRM from an ADE epub ebook

### ISSUE THREAD

**Issue by gicos63** [noDRM/DeDRM_tools#289]
### Question / bug report

The imported ebook has still DRMs (I've tried to deinstall and reinstall calibre, deinstall and reinstall the plugin). The ADE keys have been found without any problem.

### Which version of Calibre are you running?

5.44

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
calibre Log di debug
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.6235294117647 x 95.58188153310104
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.53] splash screen shown
[0.53] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
[1.20] main UI initialized...
[1.20] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt La principessa di ghiaccio.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: La principessa di ghiaccio.epub is a secure Adobe Adept ePub for UUID b635b926-a447-4750-a6c8-548432181b57
[9.56] splash screen hidden
[9.56] Started up in 9.56 seconds with 0 books
Added La principessa di ghiaccio to db in: 3.2
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII charactersAdded 1 books in 3.6 seconds

```

**Comment by ElleKayEm** [comment]
Delete the saved key from DeDRM customization.  Re-add the book letting DeDRM automatically retrieve the key.  (This is a known bug which is fixed and shouldn't be an issue in the next release.)

**Comment by gicos63** [comment]
Perfect, it works!

 

Thank you.

 

 

 

Da: ElleKayEm ***@***.***> 
Inviato: giovedì 16 febbraio 2023 14:29
A: noDRM/DeDRM_tools ***@***.***>
Cc: gicos63 ***@***.***>; Author ***@***.***>
Oggetto: Re: [noDRM/DeDRM_tools] Can't remove DRM from an ADE epub ebook (Issue #289)

 

Delete the saved key from DeDRM customization. Re-add the book letting DeDRM automatically retrieve the key. (This is a known bug which is fixed and shouldn't be an issue in the next release.)

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
