### ISSUE TITLE
Error on calibre macOS

### ISSUE THREAD

**Issue by chadlavi** [noDRM/DeDRM_tools#292]
log file from Calibre:

```
Using calibre Qt style: True
calibre Debug log
calibre 6.10  embedded-python: True
macOS-13.3-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.4.0', 'Darwin Kernel Version 22.4.0: Fri Feb 10 08:10:32 PST 2023; root:xnu-8796.100.721.505.3~4/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.3', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
calibre 6.10  embedded-python: True
macOS-13.3-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.4.0', 'Darwin Kernel Version 22.4.0: Fri Feb 10 08:10:32 PST 2023; root:xnu-8796.100.721.505.3~4/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.3', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 1563, 'width': 3360, 'x': -1920, 'y': -663}}
{'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 1080,
                                'width': 1920,
                                'x': -1920,
                                'y': -663},
 'index_in_screens_list': 1,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1563, 'width': 3360, 'x': -1920, 'y': -663}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 505, 'width': 1027, 'x': 199, 'y': 127},
 'full_screened': False,
 'geometry': {'height': 477, 'width': 1027, 'x': 199, 'y': 155},
 'maximized': False,
 'normal_geometry': {'height': 477, 'width': 1027, 'x': 199, 'y': 155},
 'screen': {'depth': 24,
            'device_pixel_ratio': 2.0,
            'geometry_in_logical_pixels': {'height': 900,
                                           'width': 1440,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '',
            'serial': '',
            'size_in_logical_pixels': {'height': 900, 'width': 1440},
            'virtual_geometry': {'height': 1563,
                                 'width': 3360,
                                 'x': -1920,
                                 'y': -663}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 2.0,
 'geometry_in_logical_pixels': {'height': 900, 'width': 1440, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '',
 'serial': '',
 'size_in_logical_pixels': {'height': 900, 'width': 1440},
 'virtual_geometry': {'height': 1563, 'width': 3360, 'x': -1920, 'y': -663}}
Setting widget geometry to: {'height': 477, 'width': 1027, 'x': 199, 'y': 155}
[0.57] main UI initialized...
[0.57] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre/devices/kindle/driver.py", line 131, in metadata_from_path
  File "calibre/ebooks/metadata/kfx.py", line 300, in read_metadata_kfx
  File "calibre/ebooks/metadata/kfx.py", line 127, in __init__
  File "calibre/ebooks/metadata/kfx.py", line 112, in __init__
calibre.ebooks.metadata.kfx.InvalidKFX: b'CONT' magic number is incorrect (ea 44 52 4d)
[5.59] splash screen hidden
[5.59] Started up in 5.59 seconds with 3 books

{'bsd_drives': {'main': '/dev/disk4s1'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/Applications/Apollo.app/Wrapper': '/private/var/folders/g3/prsvxdr922bb7chzpd73df180000gn/X/32B19EE7-FD5A-55B3-9884-6D2208A4C553',
               '/Applications/Headspace.app/Wrapper': '/private/var/folders/g3/prsvxdr922bb7chzpd73df180000gn/X/6597FBBB-865C-57BA-9366-0798F9AC0F7A',
               '/Applications/Mastodon.app/Wrapper': '/private/var/folders/g3/prsvxdr922bb7chzpd73df180000gn/X/3F9E1D4C-DDC4-59E0-AE91-7CEFC6FE5E2C',
               '/Applications/Overcast.app/Wrapper': '/private/var/folders/g3/prsvxdr922bb7chzpd73df180000gn/X/D61D5F44-61FD-5E81-AEEC-7FA18D171428',
               '/Applications/Shop.app/Wrapper': '/private/var/folders/g3/prsvxdr922bb7chzpd73df180000gn/X/5EDEEBFD-550A-571A-A1A1-98615FF10586',
               '/dev/disk1s1': '/System/Volumes/iSCPreboot',
               '/dev/disk1s2': '/System/Volumes/xarts',
               '/dev/disk1s3': '/System/Volumes/Hardware',
               '/dev/disk3s1s1': '/',
               '/dev/disk3s2': '/System/Volumes/Preboot',
               '/dev/disk3s4': '/System/Volumes/Update',
               '/dev/disk3s5': '/System/Volumes/Data',
               '/dev/disk3s6': '/System/Volumes/VM',
               '/dev/disk4s1': '/Volumes/Kindle',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.2 USBMS: scan from root False /Volumes/Kindle/documents
failed kfx path: /Volumes/Kindle/documents/Eternity (The Way Book 2)_B00J48FH2A.sdr/assets/metadata.kfx
KFX metadata reader (from KFX Input) activated for /Volumes/Kindle/documents/Eternity (The Way Book 2)_B00J48FH2A.kfx
Traceback (most recent call last):
  File "calibre/devices/kindle/driver.py", line 131, in metadata_from_path
  File "calibre/ebooks/metadata/kfx.py", line 300, in read_metadata_kfx
  File "calibre/ebooks/metadata/kfx.py", line 127, in __init__
  File "calibre/ebooks/metadata/kfx.py", line 112, in __init__
calibre.ebooks.metadata.kfx.InvalidKFX: b'CONT' magic number is incorrect (ea 44 52 4d)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
    md = YJ_Book(stream).get_metadata()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
    raise Exception("Failed to locate a KFX container with metadata")
Exception: Failed to locate a KFX container with metadata
Gather KFX-ZIP (from KFX Input) 1.51.0: Importing /Users/user/Downloads/Eternity (The Way Book 2)_B00J48FH2A.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /var/folders/g3/prsvxdr922bb7chzpd73df180000gn/C/calibre_6.10.0_tmp_ewsd_wuz/ozjuq0qa.kfx-zip
DeDRM v10.0.3: Trying to decrypt ozjuq0qa.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: ozjuq0qa
Found 1 keys to try after 0.0 seconds
DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/user/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'user'  on file  /Users/user/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'67fd00d7fc72'
trying IDString: b'7d49fbab12b8'
trying IDString: b'67fd00d7fc7d'
trying IDString: b'9353678173a5'
trying IDString: b'a941e41c410c'
Decrypted key file using IDString 'a941e41c410c' and UserName 'user'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: ozjuq0qa
Got DSN key from database key_0
Found 1 keys to try after 0.7 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.3: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/user/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.51.0: Packaging /var/folders/g3/prsvxdr922bb7chzpd73df180000gn/C/calibre_6.10.0_tmp_ewsd_wuz/ozjuq0qa.kfx-zip
Processing container: Eternity (The Way Book 2)_B00J48FH2A.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Eternity (The Way Book 2)_B00J48FH2A.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/g3/prsvxdr922bb7chzpd73df180000gn/C/calibre_6.10.0_tmp_ewsd_wuz/vc_cfb64_add_books/0/Eternity (The Way Book 2)_B00J48FH2A.kfx-zip
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 435, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
    md = YJ_Book(stream).get_metadata()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
    raise Exception("Failed to locate a KFX container with metadata")
Exception: Failed to locate a KFX container with metadata
DEBUG:    0.2 USBMS: count found in cache: 159, count of files in metadata: 160, need_sync: True
DEBUG:    0.2 USBMS: starting sync_booklists
DEBUG:    0.4 USBMS: finished sync_booklists
DEBUG:    0.4 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.4 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 160
DeviceJob: set_books_in_library finished: time= 0.0022499561309814453
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
Added Eternity (The Way Book 2) B00J48FH2A to db in: 0.0
Added 1 books in 1.1 seconds
```

The most relevant line here seems to be 

```
calibre.ebooks.metadata.kfx.InvalidKFX: b'CONT' magic number is incorrect (ea 44 52 4d)
```

The ebook file is a library loan downloaded via Amazon to an eInk kindle device.

**Comment by chadlavi** [comment]
MY bad -- it was a `.kfx` file. Have to download the `.azw` file from Amazon to do this (which succeeded for me).
