### ISSUE TITLE
Linux ,Calibre , v10.0.3 ,ADE encription 

### ISSUE THREAD

**Issue by g79petova** [noDRM/DeDRM_tools#298]
### Question / bug report

Not working for epub ADE

### Which version of Calibre are you running?

6.11

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.11  embedded-python: False
Linux-6.2.0-1-default-x86_64-with-glibc2.37 Linux ('64bit', 'ELF')
('Linux', '6.2.0-1-default', '#1 SMP PREEMPT_DYNAMIC Mon Feb 20 06:22:59 UTC 2023 (89e2785)')
Python 3.10.9
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Count Pages (1, 12, 1) && PocketBook Improved Device Interface (1, 0, 3) && Pocketbook Tools (0, 9, 6)
calibre 6.11  embedded-python: False
Linux-6.2.0-1-default-x86_64-with-glibc2.37 Linux ('64bit', 'ELF')
('Linux', '6.2.0-1-default', '#1 SMP PREEMPT_DYNAMIC Mon Feb 20 06:22:59 UTC 2023 (89e2785)')
Python 3.10.9
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Count Pages (1, 12, 1) && PocketBook Improved Device Interface (1, 0, 3) && Pocketbook Tools (0, 9, 6)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 304.79999999999995 x 304.79999999999995
[0.00] Starting up...
[0.00] Showing splash screen...
[0.02] splash screen shown
[0.02] Initializing db...
[0.04] db initialized
[0.04] Constructing main UI...
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': 'LG Electronics',
 'model': 'LG TV-',
 'name': 'HDMI-A-0',
 'serial': '16843009',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1036, 'width': 1920, 'x': 0, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 1000, 'width': 1912, 'x': 4, 'y': 32},
 'maximized': False,
 'normal_geometry': {'height': 1000, 'width': 1912, 'x': 4, 'y': 32},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': 'LG Electronics',
            'model': 'LG TV-',
            'name': 'HDMI-A-0',
            'serial': '16843009',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': 'LG Electronics',
 'model': 'LG TV-',
 'name': 'HDMI-A-0',
 'serial': '16843009',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 1000, 'width': 1912, 'x': 4, 'y': 32}
[0.88] main UI initialized...
[0.88] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Порочна омраза - Кн.3 Порочни истории.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Порочна омраза - Кн.3 Порочни истории.epub is a secure Adobe Adept ePub for UUID 499e45a4-fb9a-4f1d-8ff7-ae23bbb98136
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine py.exe -3 is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine python3.exe is not python3
[19.44] splash screen hidden
[19.47] Started up in 19.47 seconds with 1030 books
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine python.exe is not python3
wine: failed to open "C:\\Python27\\python.exe": c0000135
DeDRM v10.0.3: wine C:\Python27\python.exe does not exist
DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 178, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 1040, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 638, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Порочна омраза - Кн.3 Порочни истории to db in: 2.0
Added 1 books in 3.2 seconds
Saving geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1036, 'width': 1920, 'x': 0, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 1000, 'width': 1912, 'x': 4, 'y': 32},
 'maximized': False,
 'normal_geometry': {'height': 1000, 'width': 1912, 'x': 4, 'y': 32},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': 'LG Electronics',
            'model': 'LG TV-',
            'name': 'HDMI-A-0',
            'serial': '16843009',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}

```

**Comment by ElleKayEm** [comment]
Not finding Python installed under Wine in order to run the Adobe key retrieval script.  You might want to try using the DeACSM plugin to avoid using ADE altogether.  You may also want to use the official Linux calibre.
