### ISSUE TITLE
Corrupted output for decrypted AZW

### ISSUE THREAD

**Issue by EliZucker** [noDRM/DeDRM_tools#30]
### Question / bug report

I cannot get the output for an ebook I am trying to deDRM to appear non-corrupted. Any pointers in the right direction would be greatly appreciated.

- I downloaded my ebook in Kindle 1.30 on an M1 Mac (via right-click method).
- The folder containing the ebook has 2 files: a `.azw` and `.mbpV2`.
- I imported the `.azw` file into Calibre and tried various conversions.
- Conversions will always output corrupted files. I can read the ebook fine through the Kindle App, however.

No matter what, output will always look like this. The coverpage is intact, though.
![image](https://user-images.githubusercontent.com/5385874/152630364-d4e5603e-0079-4543-a8aa-92a1908e67e6.png)

### Which version of Calibre are you running?

5.36

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1.30

### Log output

```log
Convert book 1 of 1 (A que si! (World Languages))
DeDRM v10.0.2: Trying to decrypt wuh1d4xb.mobi
Using Library AlfCrypto Python
Using Library AlfCrypto Python
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: A que si! (World Languages)
Got DSN key from database default_key
Found 4 keys to try after 0.1 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.1 seconds
DeDRM v10.0.2: Finished after 0.1 seconds
Conversion options changed from defaults:
  output_profile: 'generic_eink'
  read_metadata_from_opf: '/var/folders/br/0rz9b0716cxgjdybdyb4qvzh0000gn/C/calibre_5.31.0_tmp_adysy3n6/rk1obekf.opf'
  cover: '/var/folders/br/0rz9b0716cxgjdybdyb4qvzh0000gn/C/calibre_5.31.0_tmp_adysy3n6/rotmc5f6.jpeg'
  verbose: 2
Resolved conversion options
calibre version: 5.31.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/var/folders/br/0rz9b0716cxgjdybdyb4qvzh0000gn/C/calibre_5.31.0_tmp_adysy3n6/rotmc5f6.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11a185070>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x11a185370>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/br/0rz9b0716cxgjdybdyb4qvzh0000gn/C/calibre_5.31.0_tmp_adysy3n6/rk1obekf.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.2: Trying to decrypt trkzc8fn.mobi
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: A que si! (World Languages)
Got DSN key from database default_key
Found 4 keys to try after 0.0 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.0 seconds
DeDRM v10.0.2: Finished after 0.0 seconds
InputFormatPlugin: MOBI Input running
on /var/folders/br/0rz9b0716cxgjdybdyb4qvzh0000gn/C/calibre_5.31.0_tmp_adysy3n6/k17d2dph.mobi
Extracting text...
Adding anchors...
Extracting images...
Cleaning up HTML...
Parsing HTML...
Malformed markup, parsing using html5-parser
Converting style information to CSS...
Creating OPF...
Parsing all content...
Parsing index.html ...
Initial parse failed, using more forgiving parsers
Parsing index.html as HTML
HTML 5 parsing failed, falling back to older parsers
Traceback (most recent call last):
  File "calibre/ebooks/oeb/parse_utils.py", line 211, in parse_html
  File "calibre/utils/xml_parse.py", line 27, in safe_xml_fromstring
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 22
lxml.etree.XMLSyntaxError: Attribute _ redefined, line 22, column 474

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/ebooks/oeb/parse_utils.py", line 218, in parse_html
  File "calibre/utils/xml_parse.py", line 27, in safe_xml_fromstring
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 22
lxml.etree.XMLSyntaxError: Attribute _ redefined, line 22, column 474

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/ebooks/oeb/parse_utils.py", line 224, in parse_html
  File "calibre/ebooks/oeb/parse_utils.py", line 105, in html5_parse
ValueError: HTML 5 parsing resulted in a tree with nesting depth > 100

Forcing index.html into XHTML namespace
Parsing styles.css ...
Generating default TOC from spine...
Merging user specified metadata...
Detecting structure...
Auto generated TOC with 0 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Trimming 'images/00002.jpg' from manifest
Trimming 'images/00001.jpg' from manifest
Creating MOBI Output...
Serializing resources...
Creating MOBI 6 output
Applying case-transforming CSS...
Parsing manglecase.css ...
Rasterizing SVG images...
Converting XHTML to Mobipocket markup...
Serializing markup content...
  Compressing markup content...
No TOC, MOBI index not generated
MOBI output written to /var/folders/br/0rz9b0716cxgjdybdyb4qvzh0000gn/C/calibre_5.31.0_tmp_adysy3n6/un27so6_.mobi

```

**Comment by ElleKayEm** [comment]
How does the original unconverted mobi look?

**Comment by jonathan2183** [comment]
i found it did this with a ebook with pictures. only wya i could view it was on  kindle for pc/android

**Comment by j-howell** [comment]
This is the same as issue apprenticeharper/DeDRM_tools#2010. It is caused by a Python 3 conversion bug in DeDRM, comparing with '%MOP' instead of b'%MOP', which causes it to not detect AZW4 format. (AZW4 is PDF contained in a MOBI wrapper.)

A workaround is to install the [KindleUnpack](https://www.mobileread.com/forums/showthread.php?t=171529) plugin and use that to extract the embedded PDF file from inside of the book. To do that import the book into calibre, select it, right click the KindleUnpack icon, and choose the option to extract the PDF.

**Comment by EliZucker** [comment]
Thanks @j-howell . That did the trick! 

I had actually tried that already after researching the issue, but for some reason the KindleUnpack plugin only showed "unpack MOBI" as an option. Your reply inspired me to re-install everything from scratch, and the "extract PDF" option was present that time.

**Comment by NickFabry** [comment]
This is great - I was having the same issue, and noticed that the raw output looked a lot like a PDF even though the tools output a MOBI. Thanks @j-howell for the explanation and solution!
