### ISSUE TITLE
Converting .kfx to pdf? Dosen't de-DRM

### ISSUE THREAD

**Issue by aarav2you** [noDRM/DeDRM_tools#304]
### Question / bug report

I plugged my kindle in, which got mounted at `/run/media/aarav/Kindle/`
![image](https://user-images.githubusercontent.com/37036762/226427788-9b645b61-a05d-4162-b453-cc0e2e9880e0.png)

I took this .kfx file:
![image](https://user-images.githubusercontent.com/37036762/226428245-e2d362f2-c1a6-4682-84cc-7a51200841d4.png)

I have also installed the `kfx-input` plutgin, so I imported this file into calibre. I clicked on the "convert book" option and press ok, but the DRM still could not be removed:
![image](https://user-images.githubusercontent.com/37036762/226428638-b430ac99-34d1-4496-aec3-c3e7dfbec01b.png)

### Which version of Calibre are you running?

6.14.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

wdym?

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.14.1  embedded-python: False
Linux-6.2.6-zen1-1-zen-x86_64-with-glibc2.37 Linux ('64bit', 'ELF')
('Linux', '6.2.6-zen1-1-zen', '#1 ZEN SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:40 +0000')
Python 3.10.10
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
calibre 6.14.1  embedded-python: False
Linux-6.2.6-zen1-1-zen-x86_64-with-glibc2.37 Linux ('64bit', 'ELF')
('Linux', '6.2.6-zen1-1-zen', '#1 ZEN SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:40 +0000')
Python 3.10.10
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.23899371069182 x 102.35820895522387
[0.00] Starting up...
[0.00] Showing splash screen...
[0.03] splash screen shown
[0.03] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
[0.48] main UI initialized...
[0.48] Hiding splash screen
Starting QuickView

Found device nodes: /dev/sdc1 None None
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /run/media/aarav/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /run/media/aarav/Kindle/documents
DEBUG:    0.0 USBMS: count found in cache: 25, count of files in metadata: 25, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 25
DeviceJob: set_books_in_library finished: time= 0.004620075225830078
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
[17.74] splash screen hidden
[17.74] Started up in 17.74 seconds with 7 books
Worker Launch took: 0.01 seconds
Job: 3 Convert book 1 of 1 (Sciences for the IB MYP 1fine) finished
Convert book 1 of 1 (Sciences for the IB MYP 1fine)
	DeDRM v10.0.3: Trying to decrypt _rnegjqk.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: _rnegjqk
	Found 1 keys to try after 0.1 seconds
	DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.3: wine py.exe -3 is not python3
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.3: wine python3.exe is not python3
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.3: wine python.exe is not python3
	wine: failed to open "C:\\Python27\\python.exe": c0000135
	DeDRM v10.0.3: wine C:\Python27\python.exe does not exist
	DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX=""
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/home/aarav/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/home/aarav/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
	    self.decrypt_voucher(totalpids)
	  File "/home/aarav/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 187, in _run_filetype_plugins
	    nfp = plugin.run(nfp) or nfp
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  pdf_mono_family: 'Nimbus Mono PS'
	  read_metadata_from_opf: '/tmp/calibre_6.14.1_tmp_5zr9r2hq/0bxcqudw.opf'
	  output_profile: 'kindle'
	  pdf_sans_family: 'Nimbus Sans [UKWN]'
	  pdf_serif_family: 'Nimbus Roman'
	  verbose: 2
	Resolved conversion options
	calibre version: 6.14.1
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f9623183a00>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x7f9623183f10>,
	 'page_breaks_before': '/',
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Nimbus Mono PS',
	 'pdf_mono_font_size': 16,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Nimbus Sans [UKWN]',
	 'pdf_serif_family': 'Nimbus Roman',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/tmp/calibre_6.14.1_tmp_5zr9r2hq/0bxcqudw.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	DeDRM v10.0.3: Trying to decrypt _rnegjqk.kfx-zip
	Decrypting KFX-ZIP ebook: _rnegjqk
	Found 1 keys to try after 0.0 seconds
	DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.3: wine py.exe -3 is not python3
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.3: wine python3.exe is not python3
	Application could not be started, or no application associated with the specified file.
	ShellExecuteEx failed: File not found.
	
	DeDRM v10.0.3: wine python.exe is not python3
	wine: failed to open "C:\\Python27\\python.exe": c0000135
	DeDRM v10.0.3: wine C:\Python27\python.exe does not exist
	DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX=""
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/home/aarav/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/home/aarav/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
	    self.decrypt_voucher(totalpids)
	  File "/home/aarav/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/lib/calibre/calibre/customize/ui.py", line 187, in _run_filetype_plugins
	    nfp = plugin.run(nfp) or nfp
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	qt.webenginecontext: 
	
	GL Type: disabled
	Surface Type: DefaultRenderableType
	Surface Profile: NoProfile
	Surface Version: 2.0
	QSG RHI Backend: OpenGL
	Using Supported QSG Backend: yes
	Using Software Dynamic GL: no
	Using Multithreaded OpenGL: no
	
	Init Parameters:
	  *  application-name calibre-parallel 
	  *  browser-subprocess-path /usr/lib/qt6/QtWebEngineProcess 
	  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
	  *  disable-gpu  
	  *  disable-setuid-sandbox  
	  *  disable-speech-api  
	  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
	  *  enable-threaded-compositing  
	  *  in-process-gpu  
	  *  use-gl disabled 
	
	InputFormatPlugin: KFX Input running
	on /tmp/calibre_6.14.1_tmp_5zr9r2hq/_rnegjqk.kfx-zip
	Software versions: KFX Input 1.51.0, calibre 6.14.1, Linux-6.2.6-zen1-1-zen-x86_64-with-glibc2.37
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting /tmp/calibre_6.14.1_tmp_5zr9r2hq/_rnegjqk.kfx-zip
	Processing container: Sciences for the IB MYP 1fine.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 105, in convert
	    book.decode_book(retain_yj_locals=True)
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
	    container = self.get_container(datafile)
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
	    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container Sciences for the IB MYP 1fine.kfx has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/bin/calibre-parallel", line 21, in <module>
	    sys.exit(main())
	  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 215, in main
	    result = func(*args, **kwargs)
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	    gui_convert(input, output, recommendations, notification=notification,
	  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	    plumber.run()
	  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1108, in run
	    self.oeb = self.input_plugin(stream, self.opts,
	  File "/usr/lib/calibre/calibre/customize/conversion.py", line 242, in __call__
	    ret = self.convert(stream, options, file_ext,
	  File "calibre_plugins.kfx_input.__init__", line 125, in convert
	    raise DRMError('This book has DRM!')
	calibre.ebooks.DRMError: This book has DRM!


```

**Comment by ElleKayEm** [comment]
The kfx format downloaded directly to the Kindle cannot be decrypted.  See this post for workarounds:  https://www.mobileread.com/forums/showthread.php?t=283371

You may also want to switch to the official Linux calibre.
