### ISSUE TITLE
adobekey.ADEPTError: Failed to decrypt user key key (sic)

### ISSUE THREAD

**Issue by rectalogic** [noDRM/DeDRM_tools#307]
### Question / bug report

DeDRM fails to decrypt ADE key. I also tried reinstalling on a different machine, and authorizing ADE on that machine but it still fails. The log is from opening Calibre and going to DeDRM preferences and choosing "Adobe Digital Editions ebooks" - it fails to load the key.

### Which version of Calibre are you running?

6.14.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.14.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.14.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.07011070110701 x 96.09458128078816
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[0.64] main UI initialized...
[0.64] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "C:\Users\aw\AppData\Roaming\calibre\plugins\DeDRM.zip\config.py", line 1158, in __init__
  File "C:\Users\aw\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 347, in adeptkeys
  File "C:\Users\aw\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 327, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
Traceback (most recent call last):
  File "C:\Users\aw\AppData\Roaming\calibre\plugins\DeDRM.zip\config.py", line 1158, in __init__
  File "C:\Users\aw\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 347, in adeptkeys
  File "C:\Users\aw\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 327, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
```

**Comment by ElleKayEm** [comment]
What about adding an Adobe DRM book to calibre and letting DeDRM automatically retrieve the key?

**Comment by rectalogic** [comment]
The book appears to import ok, but when I view it is still encrypted garbage. It gets the same `Failed to decrypt user key` when importing - that's why I tried to reproduce it by just configuring the plugin - the simplest way to reproduce the error.
```
Starting QuickView
DeDRM v10.0.3: Trying to decrypt xxx.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: xxx.epub is a secure Adobe Adept ePub for UUID 645df698-e402-47ca-954e-8485a2b856be
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\aw\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 347, in adeptkeys
  File "C:\Users\aw\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 327, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[3.12] splash screen hidden
```

Is there a way to run the plugin directly to get more info on what's going wrong - e.g. ` & 'C:\Program Files\Calibre2\calibre-debug.exe' -r DeDRM passhash ???`

**Comment by ElleKayEm** [comment]
Are you using ADE to download the book?  Is it installed on the same machine and user as calibre?

**Comment by rectalogic** [comment]
Yes I used ADE and it's same machine/user and the book is viewable in ADE.

I set a breakpoint in adobekey.py and running `'C:\Program Files\Calibre2\calibre-debug.exe' -e "C:\Users\aw\Desktop\DeDRM_plugin\adobekey.py" -- mykey`

I can see it finds my username and the binary key, but fails to decrypt it.

I'm running Windows 11 ARM in a [UTM](https://getutm.app/) virtual machine, so maybe UTM broke something - this used to work though, but perhaps some UTM upgrade incompatibility.

**Comment by ElleKayEm** [comment]
Do you still have a previous working setup?  If you used the same Adobe ID, you could import the key from there.  I've seen at least one case where a Windows 11 user was having issues, but I would have thought we would have seen more if that was a problem.

**Comment by ElleKayEm** [comment]
Let's take a look at the log for the epub.

**Comment by ElleKayEm** [comment]
Yes it does look like the same situation.  I don't know how to resolve it...other than trying on another machine that isn't Windows 11.

**Comment by ElleKayEm** [comment]
DeDRM 10.0.3 and up also works with the hardened Adobe DRM that it's possible to get with Adobe 3 and up from the few places that actually use it.  ProQuest is the only place I've seen mentioned here where they've switched to that exclusively.

I suspect this is something to do with the original setup you and the first poster had.  Glad you got things working.  And yeah don't bother trying to use the calibre ebook viewer for pdfs.
