### ISSUE TITLE
File still contains DRM

### ISSUE THREAD

**Issue by simkimehta** [noDRM/DeDRM_tools#310]
### Question / bug report

Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 6.14.1  embedded-python: True
macOS-13.2.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.2.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.14.1  embedded-python: True
macOS-13.2.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.2.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.51] main UI initialized...
[0.51] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Textbook of Pathology with Pathology Quick Review and MCQs.azw3
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Textbook of Pathology with Pathology Quick Review and MCQs
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/simki/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'simki'  on file  /Users/simki/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'ef10d66bc143'
trying IDString: b'ef10d66bc142'
trying IDString: b'932629d9c465'
trying IDString: b'151b268fd58f'
Decrypted key file using IDString '151b268fd58f' and UserName 'simki'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Textbook of Pathology with Pathology Quick Review and MCQs
Got DSN key from database key_0
Found 4 keys to try after 0.8 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[18.48] splash screen hidden
[18.48] Started up in 18.48 seconds with 1 books
Added Textbook of Pathology with Pathology Quick Review and MCQs to db in: 0.1
Added 1 books in 1.2 seconds

### Which version of Calibre are you running?

16.14.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

1.40.1

### Log output

```log
 Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 6.14.1  embedded-python: True
macOS-13.2.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.2.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.14.1  embedded-python: True
macOS-13.2.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.3.0', 'Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.2.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.51] main UI initialized...
[0.51] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Textbook of Pathology with Pathology Quick Review and MCQs.azw3
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Textbook of Pathology with Pathology Quick Review and MCQs
Found 2 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.2 seconds
Found k4Mac kinf2018 file: /Users/simki/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'simki'  on file  /Users/simki/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'ef10d66bc143'
trying IDString: b'ef10d66bc142'
trying IDString: b'932629d9c465'
trying IDString: b'151b268fd58f'
Decrypted key file using IDString '151b268fd58f' and UserName 'simki'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Textbook of Pathology with Pathology Quick Review and MCQs
Got DSN key from database key_0
Found 4 keys to try after 0.8 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/simki/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[18.48] splash screen hidden
[18.48] Started up in 18.48 seconds with 1 books
Added Textbook of Pathology with Pathology Quick Review and MCQs to db in: 0.1
Added 1 books in 1.2 seconds
```

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) for the device when downloading from the website?  And do you have the Kindle's serial number entered correctly into DeDRM's customization?

**Comment by jalbertcory** [comment]
I am getting this as well downloading directly onto a kindle paperwhite 5th generation with the serial configured in the plugin.  This seems to be new though, so it might be new DRM for some books.  I just downloaded 6 books and 2 converted fine and 4 did not.  The two newly released books are the ones that worked though so I am not sure.

**Comment by ElleKayEm** [comment]
Try the "download & transfer via usb" option from the website.

**Comment by jalbertcory** [comment]
I was able to fix this by clean installing everything.  I was using a slightly out of date calibre and I updated the plugin in that one.  Clean installing a new calibre and new plugin worked for me.  Not sure why tbh.
