### ISSUE TITLE
Can't decrypt epub file

### ISSUE THREAD

**Issue by budbongo** [noDRM/DeDRM_tools#312]
Question / bug report
Kobo epub file - Obok DeDRM Exception when getting default Adobe Key

Which version of Calibre are you running?
6.14.1

Which version of the DeDRM plugin are you running?
v10.0.3

If applicable, which version of the Kindle software are you running?
n/a

Log output
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
Using calibre Qt style: True
calibre Debug log
calibre 6.14.1  embedded-python: True
Linux-6.0.0-0.deb11.6-amd64-x86_64-with-glibc2.35 Linux ('64bit', '')
('Linux', '6.0.0-0.deb11.6-amd64', '#1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19)')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.14.1  embedded-python: True
Linux-6.0.0-0.deb11.6-amd64-x86_64-with-glibc2.35 Linux ('64bit', '')
('Linux', '6.0.0-0.deb11.6-amd64', '#1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19)')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.01608579088472 x 95.91689497716894
[0.00] Starting up...
[0.00] Showing splash screen...
[0.03] splash screen shown
[0.03] Initializing db...
[0.15] db initialized
[0.15] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.70] main UI initialized...
[0.70] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Grand.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Grand.epub is a secure Adobe Adept ePub for UUID 47e52574-a0d2-4d22-8906-438c914b5b27
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.0 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 596, in ePubDecrypt
    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
  File "/config/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "/config/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
    self.check_call(["-c", self.py3_test])
  File "/config/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 364, in check_call
  File "subprocess.py", line 345, in call
  File "subprocess.py", line 966, in __init__
  File "subprocess.py", line 1842, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[100.58] splash screen hidden
[100.58] Started up in 100.58 seconds with 1309 books
Added Grand to db in: 6.3
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
[689:695:0405/141822.692525:ERROR:command_buffer_proxy_impl.cc(126)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
Unable to detect a launcher for 'file:///tmp/tmpvrn22pqd.txt'
Added 1 books in 6.7 seconds
Worker Launch took: 0.00 seconds

**Comment by ElleKayEm** [comment]
Obok has nothing to do with Adobe DRM.  it is for books downloaded with Kobo Desktop or a Kobo ereader.

The log shows DeDRM is unable to find a wine installation in order to get the key from Adobe Digital Editions.  How did you download the book?

**Comment by budbongo** [comment]
Thanks fore your help. I bought the book digitally via the Kobo shop & imported it into Kobo reader on a PC. I then opened it in Adobe Digital editions and tried to import the resulting epub into Calibre.

**Comment by ElleKayEm** [comment]
I don't understand what you mean by importing into Kobo reader.  I assume you downloaded the epub by opening an acsm with ADE.  If that was on a different machine than calibre, then DeDRM has no way to retrieve the key.

**Comment by budbongo** [comment]
Oh, OK, calibre is on my server, I downloaded and opened the book on my desktop computer. I guess that is the problem

**Comment by ElleKayEm** [comment]
Yes, that would be it.  You could temporarily install calibre/DeDRM on your desktop.  Then once you've successfully decrypted a book there, you could save the key from that setup and import it into the DeDRM plugin on your server.
