### ISSUE TITLE
Decrypt failed: ValueError: string argument should contain only ASCII characters

### ISSUE THREAD

**Issue by thanatos2k** [noDRM/DeDRM_tools#313]
### Question / bug report

Trying to decrypt a book that came out today that was purchased on Kobo. Initially, I tried using DeDRM with the epub downloaded from their website, but the attached error log shows the failure. I've also tried Obok, which was able to successfully import the book from the Kobo desktop app, but the book is corrupted / not decrpyted. I can read the book fine in both ADE and the Kobo app.

### Which version of Calibre are you running?

6.14.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.14.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 6.14.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.73578595317724 x 108.85714285714285
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.55] main UI initialized...
[0.55] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt forge.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: forge.epub is a secure Adobe Adept ePub for UUID c863c5e1-11ca-45fb-b341-703550414c01
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[28.94] splash screen hidden
[28.94] Started up in 28.94 seconds with 30 books
stdout+stderr from file dialog helper: [b'10000 46000000\r\n', b'']
piped data from file dialog helper: [b'1)\x95Z\xb7yS\x9b\x8a;\xcf\x99R\x8e=\x98\xb8\xf1\x90\x7f=&\xdf\xdbj\x14\xb6\x88\x12\xf5\x1f\xd6', b'C:\\Users\\bp\\Downloads\\forge.epub']
Added Forge of the High Mage to db in: 0.2
Added 1 books in 0.4 seconds

```

**Comment by ElleKayEm** [comment]
Delete the Adobe key from DeDRM.  Re-add your book letting DeDRM automatically retrieve the key.

**Comment by thanatos2k** [comment]
That worked perfectly, thank you!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
