### ISSUE TITLE
"ModuleNotFoundError: No module named 'Crypto'" when importing azw3

### ISSUE THREAD

**Issue by mymro** [noDRM/DeDRM_tools#32]
### Question / bug report

When importing an azw3 file dedrm fails with the following message:
`ModuleNotFoundError: No module named 'Crypto'`

I am usign Calibre on Ubuntu Ubuntu 21.10

### Which version of Calibre are you running?

5.25

### Which version of the DeDRM plugin are you running?

10.0.2

### Log output

```log
calibre 5.25  embedded-python: False is64bit: True
Linux-5.13.0-28-generic-x86_64-with-glibc2.34 Linux ('64bit', 'ELF')
('Linux', '5.13.0-28-generic', '#31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022')
Python 3.9.7
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 46, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0) && Obok DeDRM (10, 0, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.99999999999999 x 128.18691588785046
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.07] db initialized
[0.07] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
Using proxies: {'no': 'localhost,127.0.0.0/8,::1'}
[0.65] main UI initialized...
[0.65] Hiding splash screen
Starting QuickView
[0.97] splash screen hidden
[0.97] Started up in 0.97 seconds with 226 books
DeDRM v10.0.2: Trying to decrypt 地球星人（新潮文庫）.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 18, in <module>
    from ion import DrmIon, DrmIonVoucher
  File "/tmp/calibre_5.25.0_tmp_x1cvjsnw/ezx_07h1plugin_unzip/ion.py", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 176, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 782, in KindleMobiDecrypt
    import calibre_plugins.dedrm.k4mobidedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.k4mobidedrm", line 88, in <module>
    from calibre_plugins.dedrm import kfxdedrm
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.kfxdedrm", line 20, in <module>
    from calibre_plugins.dedrm.ion import DrmIon, DrmIonVoucher
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 192, in exec_module
    exec(compiled, module.__dict__)
  File "calibre_plugins.dedrm.ion", line 33, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
Added 0 books in 2.7 seconds
```

**Comment by mymro** [comment]
I fixed it by installing it manually:
```console
sudo apt install python3-crypto
```

However, the information, that it is needed, should be easily available, or even better it should be automatically included,  when installing the plugin.

**Comment by ElleKayEm** [comment]
I believe if you use the [official Linux calibre](https://calibre-ebook.com/download_linux), this isn't an issue.  The plugin uses calibre's embedded python and modules.

**Comment by mymro** [comment]
@ElleKayEm Thank you. I wasn't aware of that.
