### ISSUE TITLE
AZW3 file drm cannot be removed

### ISSUE THREAD

**Issue by LieLeiSoft** [noDRM/DeDRM_tools#322]
### Question / bug report

Hello,
I bought an eBook on Amazon (because this is not available elsewhere) for my wife. I have a Kindle but my wife's e-Reader (Tolino Shine) only understand epub and pdf. How can I convert this AZW3-Format to epub-Format?
Greetings from Germany.

### Which version of Calibre are you running?

6.16.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

v1.40

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Fehlerdiagnoseprotokoll
calibre 6.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 101.6 x 101.6
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.78] main UI initialized...
[0.78] Hiding splash screen
Starting QuickView
[40.66] splash screen hidden
[40.66] Started up in 40.66 seconds with 3 books
Worker Launch took: 0.02 seconds
Job: 0 Buch 1 von 1 (Inselfest (Stürmische Zeiten auf Föhr) (German Edition)) konvertieren finished
Buch 1 von 1 (Inselfest (Stürmische Zeiten auf Föhr) (German Edition)) konvertieren

	DeDRM v10.0.3: Trying to decrypt 0g5kzt72.azw3
	Using Library AlfCrypto DLL/DYLIB/SO
	MobiDeDrm v1.1.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Inselfest (Stürmische Zeiten auf Föhr) (German Edition)
	Got DSN key from database default_key_2
	Got DSN key from database default_key_3
	Found 8 keys to try after 0.1 seconds
	Crypto Type is: 2
	DeDRM v10.0.3: Failed to decrypt with error: No key found in 8 PIDs tried.
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in D:\Benutzer\Eagle\AppData\Local
	Found K4PC 1.25+ kinf2018 file: D:\Benutzer\Eagle\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Found K4PC 1.9+ kinf2011 file: D:\Benutzer\Eagle\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '1713175228' and UserName 'Eagle'
	Decrypted key file using IDString '1713175228' and UserName 'Eagle'
	DeDRM v10.0.3: Found 2 new keys
	MobiDeDrm v1.1.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Inselfest (Stürmische Zeiten auf Föhr) (German Edition)
	Got DSN key from database key_0
	Got DSN key from database key_1
	Found 4 keys to try after 0.4 seconds
	Crypto Type is: 2
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 8 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 4 PIDs tried.
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt

	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook

	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook

	mobidedrm.DrmException: No key found in 8 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1056, in run

	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  verbose: 2

	  read_metadata_from_opf: 'D:\\Benutzer\\Eagle\\AppData\\Local\\Temp\\calibre_pp9fm6__\\gsaiq3cw.opf'

	  cover: 'D:\\Benutzer\\Eagle\\AppData\\Local\\Temp\\calibre_pp9fm6__\\5u3njqm2.jpeg'

	Resolved conversion options

	calibre version: 6.16.0

	{'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'D:\\Benutzer\\Eagle\\AppData\\Local\\Temp\\calibre_pp9fm6__\\5u3njqm2.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_max_image_size': 'none',

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001DC98E20250>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x000001DC98E23CD0>,

	 'page_breaks_before': "//*[name()='h1' or name()='h2']",

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'D:\\Benutzer\\Eagle\\AppData\\Local\\Temp\\calibre_pp9fm6__\\gsaiq3cw.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	DeDRM v10.0.3: Trying to decrypt 0g5kzt72.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Inselfest (Stürmische Zeiten auf Föhr) (German Edition)
	Got DSN key from database default_key_2
	Got DSN key from database default_key_3
	Found 8 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v10.0.3: Failed to decrypt with error: No key found in 8 PIDs tried.
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in D:\Benutzer\Eagle\AppData\Local
	Found K4PC 1.25+ kinf2018 file: D:\Benutzer\Eagle\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Found K4PC 1.9+ kinf2011 file: D:\Benutzer\Eagle\AppData\Local\Amazon\Kindle\storage\.kinf2011
	Decrypted key file using IDString '1713175228' and UserName 'Eagle'
	Decrypted key file using IDString '1713175228' and UserName 'Eagle'
	DeDRM v10.0.3: Found 2 new keys
	MobiDeDrm v1.1.
	Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Inselfest (Stürmische Zeiten auf Föhr) (German Edition)
	Got DSN key from database key_0
	Got DSN key from database key_1
	Found 4 keys to try after 0.3 seconds
	Crypto Type is: 2
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 8 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
	mobidedrm.DrmException: No key found in 4 PIDs tried.
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt

	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook

	  File "D:\Benutzer\Eagle\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook

	mobidedrm.DrmException: No key found in 8 PIDs tried.

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1056, in run

	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: MOBI Input running

	on D:\Benutzer\Eagle\AppData\Local\Temp\calibre_pp9fm6__\0g5kzt72.azw3

	Found KF8 MOBI of type 'standalone'

	Traceback (most recent call last):

	  File "runpy.py", line 196, in _run_module_as_main

	  File "runpy.py", line 86, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 242, in __call__

	  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 44, in convert

	  File "calibre\ebooks\mobi\reader\mobi8.py", line 85, in __call__

	  File "calibre\ebooks\mobi\reader\mobi6.py", line 162, in check_for_drm

	calibre.ebooks.DRMError: Inselfest (Stürmische Zeiten auf Föhr) (German Edition)

**Comment by LieLeiSoft** [comment]
The AZW3-File I used was the file I have downloaded via Amazon website ("Account & Lists" -> "Manage Your Content and Devices",  press the "..." button in the "Actions" column for that book, in the menu that pops up choose "Download & transfer via USB".)
According to Method 3 (https://www.mobileread.com/forums/showthread.php?t=283371) this should work. But in my case it doesn't :-(
What went wrong?

**Comment by ZolaLa9** [comment]
Did you add your serial number to the deDRM plugin?

**Comment by LieLeiSoft** [comment]
Hi, i have a Kindle Paperwhite (7th generation). Where can i find a serial
number?

ZolaLa ***@***.***> schrieb am So., 23. Apr. 2023, 23:47:

**Comment by ZolaLa9** [comment]
Go to the Manage Your Content and Devices. You should be able to copy the serial number for your Paperwhite from there. Do a copy/paste so you don't mix up zeroes with the letter O, etc. :)

**Comment by LieLeiSoft** [comment]
Hello ZolaLa, thank you very much, for your answer! It worked :-)
First I copied the serial number from the amazon-site, then I switched to
Calibre and created 2 keys: one for "Kindle eInk ebook" and one for "Kindle
for Mac/PC ebooks". Not sure, if I need really both of them. However, I
could convert the azw3-format to epub :-)

Maybe there is another german user who has the same situation, here is what
I did in german:
Seriennummer des Kindle ermitteln:
Einloggen auf Amazon.de
Konto und Listen -> Meine Inhalte und Geräte -> Geräte -> Kindle -> Kindle
Paperwhite

Seriennummer des Kindle in Calibre eintragen:
Einstellungen -> Erweiterungen -> DeDRM (10.0.3) -> Erweiterung anpassen:
 - Kindle eInk ebook
 - Kindle for Mac/PC ebooks
(unbekannt, ob tatsächlich beide Anpassungen nötig sind)


Am Mo., 24. Apr. 2023 um 08:37 Uhr schrieb ZolaLa ***@***.***
