### ISSUE TITLE
MLOL book not getting dedrm-ed

### ISSUE THREAD

**Issue by AndreaaMoro** [noDRM/DeDRM_tools#323]
calibre Log di debug
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.22621-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.22621')
Python 2.7.16+
Windows: ('10', '10.0.22621', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Goodreads Sync (1, 15, 0) && KindleUnpack - The Plugin (0, 82, 3)
calibre 4.23  embedded-python: True is64bit: False
Windows-10-10.0.22621-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.22621')
Python 2.7.16+
Windows: ('10', '10.0.22621', 'SP0', u'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Goodreads Sync (1, 15, 0) && KindleUnpack - The Plugin (0, 82, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 120.0 x 120.0
physicalDpi: 141.76744186 x 142.134715026
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.56] splash screen shown
[0.56] Initializing db...
[0.56] db initialized
[0.56] Constructing main UI...
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    1.6 HttpHelper::__init__: proxy=None
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
Key u'A' for shortcut Apri la cartella contenente is already used by Aggiungi libri, ignoring
[2.25] main UI initialized...
[2.25] Hiding splash screen
[14.64] splash screen hidden
[14.64] Started up in 14.64 seconds with 235 books
DeDRM v10.0.3: Trying to decrypt Cosa mangiamo.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Cosa mangiamo.epub is a secure Adobe Adept ePub for UUID 483acae1-078a-4123-bc61-8c41ec618f36
DeDRM v10.0.3: Trying Encryption key default_key
fwnqnh.epub is a secure Adobe Adept ePub.
Could not decrypt fwnqnh.epub because of an exception:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.ineptepub", line 305, in decryptBook
AttributeError: 'module' object has no attribute 'import_key'

DeDRM v10.0.3: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 372, in adeptkeys
NameError: global name 'FileNotFoundError' is not defined
DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Cosa mangiamo to db in: 1.8
Added 1 books in 2.7 seconds

**Comment by ElleKayEm** [comment]
Try updating calibre.

**Comment by AndreaaMoro** [comment]
Solved with updated calibre. Thanks @ElleKayEm!

**Comment by ElleKayEm** [comment]
Thanks for reporting back that it worked!
