### ISSUE TITLE
Load Plugin: ModuleNotFoundError

### ISSUE THREAD

**Issue by kyliiin** [noDRM/DeDRM_tools#329]
### Question / bug report

I ran into this error when loading the plugin in calibre. 

### Which version of Calibre are you running?

6.17

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

calibre, version 6.17.0
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named '__version'

calibre 6.17  embedded-python: True
Windows-10-10.0.19041-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.10.1
Windows: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 307, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 206, in exec_module
  File "calibre_plugins.dedrm.__init__", line 98, in <module>
ModuleNotFoundError: No module named '__version'

**Comment by kyliiin** [comment]
This did not happen when I tried to load Harper's last version

**Comment by keithstellyes** [comment]
I ran into this issue too. No idea what causes it, as a work-around, I did `calibre-customize --add` from the command line and that worked

**Comment by mauromol** [comment]
It does not work form me with `calibre-customize --add` either:

```bash
#############################
Failed to load the DeDRM plugin
Did you bundle this from source code yourself? If so, you'll need to run make_release.py instead to generate a valid plugin file.
If you have no idea what the above means, please redownload the most recent version of the plugin from the Github Releases page.
If you still receive this error with the released version, please open a bug report and attach the following information:
#############################
Debug information:
__version not found, path is:
['/tmp/dedrm', '/tmp', '/usr/lib/calibre', '/usr/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']
I'm at:
<calibre Plugin Loader>
#############################
Traceback (most recent call last):
  File "/usr/bin/calibre-customize", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/customize/ui.py", line 789, in main
    plugin = add_plugin(opts.add_plugin)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.dedrm.__init__", line 117, in <module>
ModuleNotFoundError: No module named '__version'
```

Using Calibre 4.99.4 under KUbuntu 20.04.
Above is with DeDRM plugin version 10.0.3. 
The following is with 10.0.9 instead:

```bash
#############################
Failed to load the DeDRM plugin
Did you bundle this from source code yourself? If so, you'll need to run make_release.py instead to generate a valid plugin file.
If you have no idea what the above means, please redownload the most recent version of the plugin from the Github Releases page.
If you still receive this error with the released version, please open a bug report and attach the following information:
#############################
Debug information:
__version not found, path is:
['/tmp/dedrm', '/tmp', '/usr/lib/calibre', '/usr/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']
I'm at:
<calibre Plugin Loader>
#############################
Traceback (most recent call last):
  File "/usr/bin/calibre-customize", line 20, in <module>
    sys.exit(main())
  File "/usr/lib/calibre/calibre/customize/ui.py", line 789, in main
    plugin = add_plugin(opts.add_plugin)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 200, in load
    reload(m)
  File "/usr/lib/calibre/polyglot/builtins.py", line 123, in reload
    return importlib.reload(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 602, in _exec
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 184, in load_module
    exec(compiled, mod.__dict__)
  File "calibre_plugins.dedrm.__init__", line 118, in <module>
ModuleNotFoundError: No module named '__version'
```

Finally, it works fine with version 10.0.2 instead.

**Comment by ElleKayEm** [comment]
How about the alpha release: https://github.com/noDRM/DeDRM_tools_autorelease/releases
