### ISSUE TITLE
Windows: Failed to remove DRM from Kobo book. 

### ISSUE THREAD

**Issue by datakid** [noDRM/DeDRM_tools#337]
### Which version of Calibre are you running?

6.17

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.17  embedded-python: True
Windows-10-10.0.22624-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22624')
Python 3.10.1
Windows: ('10', '10.0.22624', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (10, 0, 3)
calibre 6.17  embedded-python: True
Windows-10-10.0.22624-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22624')
Python 3.10.1
Windows: ('10', '10.0.22624', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
[0.00] Starting up...
[0.02] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.64] main UI initialized...
[0.64] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1722, in set_metadata
  File "calibre\db\cache.py", line 1645, in set_cover
  File "calibre\db\backend.py", line 1664, in set_cover
  File "calibre\utils\img.py", line 301, in save_cover_data_to
  File "calibre\utils\img.py", line 209, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty

```

**Comment by ElleKayEm** [comment]
This log doesn't show you importing a book with Obok.

**Comment by datakid** [comment]
I don't know what else to tell you - I did exactly as instructed in the README. I'll try again tonight.

**Comment by ElleKayEm** [comment]
You were using Obok to add the book from Kobo desktop or your Kobo ereader?

**Comment by datakid** [comment]
No, I was using the Obok plugin to add a book from my Kobo desktop, to my installation of Calibre.

**Comment by ElleKayEm** [comment]
Ok, just making sure you weren't talking about the Adobe DRM versions.  But, yeah, no sign of Obok trying to decrypt anything in that log.  Did the book not get added at all?

**Comment by datakid** [comment]
Please ignore - it would seem a second reboot solved the issue. Appreciate your patience.
