### ISSUE TITLE
DeDRMing a recently-purchased B&N book silently fails

### ISSUE THREAD

**Issue by meissnem** [noDRM/DeDRM_tools#338]
### Question / bug report

Last week I purchased a book from B&N but I'm unable to remove the DRM.

I'm running on a Mac, but installed Nook for Windows in a VM in order to extract the key. That process seems to have worked correctly.

After installing and configuring the plugin, I add the book to Calibre. Everything appears to work, but the ebook remains encrypted.

Some of the things I've attempted without any luck:

- Running Calibre in my Windows VM. Same result.
- Cloned the source code and packaged up a plugin based on the current state of `master` but that didn't change anything.
- Tried to run the plugin stand-alone but that doesn't seem to be hooked up to anything anymore.

I'm at a loss for how to proceed. I'm attaching the Calibre log (though it doesn't seem particularly insightful).

Is there anything else I can provide to help diagnose the problem?

### Which version of Calibre are you running?

6.17

### Which version of the DeDRM plugin are you running?

v10.0.3 and master

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.17  embedded-python: True
macOS-13.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Mon May  8 23:12:01 PDT 2023; root:xnu-8796.140.12.505.1~5/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.5', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.17  embedded-python: True
macOS-13.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Mon May  8 23:12:01 PDT 2023; root:xnu-8796.140.12.505.1~5/RELEASE_ARM64_T6000')
Python 3.10.1
OSX: ('13.5', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 107.50000161448803
[0.00] Starting up...
[0.04] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.51] main UI initialized...
[0.51] Hiding splash screen
Starting QuickView
2023-05-26 14:28:01.640 calibre-debug[39015:6434005] +[CATransaction synchronize] called within transaction
DeDRM v10.0.3: Trying to decrypt 9781501767838.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: “9781501767838.epub” is a secure PassHash-protected (B&N) ePub
DeDRM v10.0.3: Trying Encryption key NookForWindows_nookStore_1
u400e4mt.epub is a secure Adobe PassHash (B&N) ePub.
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 1.0 seconds
Traceback (most recent call last):
  File "calibre/db/cache.py", line 1722, in set_metadata
  File "calibre/db/cache.py", line 1645, in set_cover
  File "calibre/db/backend.py", line 1664, in set_cover
  File "calibre/utils/img.py", line 301, in save_cover_data_to
  File "calibre/utils/img.py", line 209, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
[8.78] splash screen hidden
[8.79] Started up in 8.79 seconds with 2 books
Added Marvel Comics in the 1970s to db in: 0.0
Added 1 books in 1.2 seconds
```

**Comment by ElleKayEm** [comment]
Yeah, I'm not sure if the issue is DRM here.  Normally the log would say if the DRM couldn't be removed.  Of course it isn't saying it was successful either.  But the error here is "ValueError: Failed to export image as JPEG with error: Image is empty".  Don't know how to resolve that.  Is it saying it still has drm when you try to open it?  Is this your only BN book?  Or just the only one giving trouble?

**Comment by meissnem** [comment]
Hi @ElleKayEm, thanks for the response!

> Is it saying it still has drm when you try to open it?

Yes, exactly. `ValueError: Failed to export image as JPEG with error: Image is empty` seems like a red herring -- Calibre can't read the cover image because it is still encrypted.

I verified this by stashing a copy of the resulting ePub file by applying this crude patch:

```patch
diff --git a/DeDRM_plugin/__init__.py b/DeDRM_plugin/__init__.py
index 9204600..1b20000 100644
--- a/DeDRM_plugin/__init__.py
+++ b/DeDRM_plugin/__init__.py
@@ -242,6 +242,8 @@ class DeDRM(FileTypePlugin):
             postProcessEnd = time.time()
             print("{0} v{1}: Post-processing took {2:.1f} seconds".format(PLUGIN_NAME, PLUGIN_VERSION, postProcessEnd-postProcessStart))
 
+            import shutil
+            shutil.copyfile(path_to_ebook, "/Users/matt/Desktop/THIS_IS_IT.epub")
             return path_to_ebook
 
         except: 

```

Unzipping `THIS_IS_IT.epub` I can see that the good bits are still DRMed.

```bash
% find THIS_IS_IT -type f -print0 | xargs -0 file
THIS_IS_IT/.DS_Store:                                     Apple Desktop Services Store
THIS_IS_IT/META-INF/container.xml:                        XML 1.0 document text, ASCII text, with CRLF line terminators
THIS_IS_IT/META-INF/com.apple.ibooks.display-options.xml: XML 1.0 document text, ASCII text
THIS_IS_IT/mimetype:                                      ASCII text, with no line terminators
THIS_IS_IT/OEBPS/.DS_Store:                               Apple Desktop Services Store
THIS_IS_IT/OEBPS/Images/Fig_001.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_015.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_014.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_016.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_002.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_003.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_017.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_013.jpg:                      PGP Secret Sub-key -
THIS_IS_IT/OEBPS/Images/Fig_007.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_006.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_012.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_004.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_010.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_011.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_005.jpg:                      data
THIS_IS_IT/OEBPS/Images/Cover.jpg:                        data
THIS_IS_IT/OEBPS/Images/Fig_008.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_020.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_021.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_009.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_023.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_022.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_026.jpg:                      OpenPGP Secret Key
THIS_IS_IT/OEBPS/Images/Fig_025.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_019.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_018.jpg:                      data
THIS_IS_IT/OEBPS/Images/Fig_024.jpg:                      data
THIS_IS_IT/OEBPS/Styles/Stylesheet.css:                   data
THIS_IS_IT/OEBPS/Styles/Apex_Responsive.css:              data
THIS_IS_IT/OEBPS/content.opf:                             XML 1.0 document text, Unicode text, UTF-8 text, with very long lines (617), with CRLF line terminators
THIS_IS_IT/OEBPS/Text/Dedication.xhtml:                   data
THIS_IS_IT/OEBPS/Text/Preface.xhtml:                      data
THIS_IS_IT/OEBPS/Text/TitlePage.xhtml:                    data
THIS_IS_IT/OEBPS/Text/Introduction.xhtml:                 data
THIS_IS_IT/OEBPS/Text/References.xhtml:                   data
THIS_IS_IT/OEBPS/Text/TOC.xhtml:                          data
THIS_IS_IT/OEBPS/Text/Frontmatter.xhtml:                  data
THIS_IS_IT/OEBPS/Text/Chapter02.xhtml:                    data
THIS_IS_IT/OEBPS/Text/Index.xhtml:                        data
THIS_IS_IT/OEBPS/Text/Cover.xhtml:                        data
THIS_IS_IT/OEBPS/Text/Chapter06.xhtml:                    data
THIS_IS_IT/OEBPS/Text/Chapter04.xhtml:                    data
THIS_IS_IT/OEBPS/Text/Chapter03.xhtml:                    data
THIS_IS_IT/OEBPS/Text/Chapter01.xhtml:                    data
THIS_IS_IT/OEBPS/Text/Chapter05.xhtml:                    data
THIS_IS_IT/OEBPS/Text/Copyright.xhtml:                    data
THIS_IS_IT/OEBPS/Text/Chapter07.xhtml:                    data
THIS_IS_IT/OEBPS/Fonts/Franklin-Gothic-Demi.otf:          OpenPGP Secret Key
THIS_IS_IT/OEBPS/Fonts/metablfc.ttf:                      data
THIS_IS_IT/OEBPS/Fonts/FranklinGothicLTPro-Bk.otf:        data
THIS_IS_IT/OEBPS/Fonts/Franklin-Gothic-Heavy.otf:         data
THIS_IS_IT/OEBPS/Fonts/Franklin-Gothic-Book.otf:          data
THIS_IS_IT/OEBPS/Fonts/Minion-RegularSC.otf:              data
THIS_IS_IT/OEBPS/Fonts/Minion.otf:                        data
THIS_IS_IT/OEBPS/Fonts/Minion-BoldItalic.otf:             data
THIS_IS_IT/OEBPS/Fonts/Minion-Italic.otf:                 data
THIS_IS_IT/OEBPS/Fonts/Minion-Semibold.otf:               data
THIS_IS_IT/OEBPS/toc.ncx:                                 XML 1.0 document text, ASCII text, with CRLF line terminators
```

> Is this your only BN book? Or just the only one giving trouble?

I have a couple of other B&N books that I purchased years ago. I just attempted to remove DRM from those and the result is the same.

Could the key that's being extracted from Nook for Windows be incorrect? I am using Nook for Windows v1.11.0.4 downloaded from the Microsoft store. If that were the case, I'd think it would cause DeDRM to throw an exception at some point, so I'm still pretty confounded.

**Comment by ElleKayEm** [comment]
Were the books also downloaded with Nook for Windows?  I know that no matter how I download my BN books they always work with the same key and that same key has worked for many years.  But I have seen people report having more the one key and also keys sometimes changing.

**Comment by meissnem** [comment]
> Were the books also downloaded with Nook for Windows?

Yes. I downloaded all of the books fresh this week. I have DeDRM'd versions of the older books from years ago when I first purchased them (but alas, I do not have the _key_ from years ago), but I cannot DeDRM any of the downloads from this week.

**Comment by ElleKayEm** [comment]
Does a log of importing a book in your Windows VM calibre show anything more?
