### ISSUE TITLE
Trying to deDRM book from ADE

### ISSUE THREAD

**Issue by davids74** [noDRM/DeDRM_tools#339]
DeDRM v10.0.3: Trying to decrypt The blue lantern and other stories.pdf
DeDRM v10.0.3: The blue lantern and other stories.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: The blue lantern and other stories.pdf is a PDF ebook (EBX) for UUID f4593bea-4985-47fd-838e-338c8e431a04
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.8 seconds
DeDRM v10.0.3: Trying a new default key
DeDRM v10.0.3: Exception when decrypting after 1.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in PDFIneptDecrypt
  File "calibre_plugins.dedrm.ineptpdf", line 2286, in decryptBook
  File "calibre_plugins.dedrm.ineptpdf", line 2094, in __init__
  File "calibre_plugins.dedrm.ineptpdf", line 1253, in initialize
  File "calibre_plugins.dedrm.ineptpdf", line 1672, in initialize_ebx_inept
AttributeError: 'module' object has no attribute 'import_key'
DeDRM v10.0.3: Failed to decrypt with new default key after 1.3 seconds
DeDRM v10.0.3: Finished after 1.3 seconds
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 416, in get_file_type_metadata
  File "site-packages/calibre/customize/builtins.py", line 342, in get_metadata
  File "site-packages/calibre/ebooks/metadata/pdf.py", line 115, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

**Comment by davids74** [comment]
I clicked on + sign in customise plugin ADE dialog and it added a string but reimporting the book does not make it readable.

**Comment by ElleKayEm** [comment]
Try deleting the key and re-importing the book.

**Comment by davids74** [comment]
I did, I removed and readded the book in ADE 4.5 with and without key and then also with ADE 2.01 with no luck.

I also unauthorised and re-authorised the ADE 'for this computer'and tried without signing in the Adobe and with.

The Calibre plugin comes back with the same errors regardless of version of ADE or approach in download of the book.

**Comment by ElleKayEm** [comment]
The really old version of calibre with this newest version of DeDRM could be an issue.  Looks like you have High Sierra.  You could try calibre 3.48 and DeDRM 6.8.1.

https://download.calibre-ebook.com/3.48.0/
https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

**Comment by romad275** [comment]
I’m also limited to High Sierra on my iMac so I’stayed with Calibre 3.48 & DeDRM 6.6.2. BTW, DeDRM 6.8.1 is ONLY needed if you are using Big Sur on your Mac, so 6.8.0 should also work with High Sierra.

Sincerely,
Dennis B. Swaney

Cogito Ergo Mac

**Comment by davids74** [comment]
This time it worked. Thanks!

(I am stuck with High Sierra because it appeared my video card was not Metal. Now on latest HCLs it appears to be listed as Metal so maybe I can update to something newer. I have always been running on hackintoshes. The last one with Asus P5K mobo lasted for 8 years on Snow Leo, then Mountain Lion. After Google stopped supporting Chrome running on them in 2016 I upgraded to Z170k and GTX 750 Ti to get on High Sierra in 2018. I can't believe it is 2023 around. Time flies. Maybe since my video is Metal after all I can check out if my computer can run something newer.)
