### ISSUE TITLE
Can't convert Kindle book to PDF in Calibre 6

### ISSUE THREAD

**Issue by JessiZ** [noDRM/DeDRM_tools#343]
I followed the troubleshooting instructions and I am pasting the info from the calibre log file. I am using Calibre 6.19.1 and downloaded DeDRM10.0.3. The book is an AWZ file and I bought it in the Amazon Kinde Shop. I'm attaching a screenshot of all the files relating to the book. Thanks! 
![kindleBook](https://github.com/noDRM/DeDRM_tools/assets/18247164/cf74f477-4415-415b-9df1-21fe8f88e9b8)

Log File: 

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Fehlerdiagnoseprotokoll
calibre 6.19.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
calibre 6.19.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 51, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (1, 51, 0) && KFX metadata reader (from KFX Input) (1, 51, 0) && KFX Input (1, 51, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.69] main UI initialized...
[1.69] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.51.0: Importing C:\Users\Jessi\Documents\My Kindle Content\B074F1X8XB_EBOK\B074F1X8XB_EBOK.azw
[22.22] splash screen hidden
[22.22] Started up in 22.22 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'e\xa5U\xe9\xcf\x9a\xd4y\x8a\x19\xd4\xe7\x1bU\xceW\x18\xe9\xf5\xc8I\x12\x87\x81h\xa3\x06\x84\x92\xadMP', b'C:\\Users\\Jessi\\Documents\\My Kindle Content\\B074F1X8XB_EBOK\\B074F1X8XB_EBOK.azw']
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\Jessi\AppData\Local\Temp\calibre_rowjf0zb\thp10ebx.kfx-zip
DeDRM v10.0.3: Trying to decrypt thp10ebx.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: thp10ebx
Found 0 keys to try after 0.2 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5aa01c5f-a069-4004-928b-8df16fa999df.voucher
Traceback (most recent call last):
  File "C:\Users\Jessi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Jessi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Jessi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Jessi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Jessi\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Jessi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Jessi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Jessi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.51.0: Packaging C:\Users\Jessi\AppData\Local\Temp\calibre_rowjf0zb\thp10ebx.kfx-zip
Processing container: B074F1X8XB_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B074F1X8XB_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Jessi\AppData\Local\Temp\calibre_rowjf0zb\epf_yz_4_add_books\0\B074F1X8XB_EBOK.kfx-zip

**Comment by ElleKayEm** [comment]
That's the latest KFX format which can't be decrypted.  See this post for possoble workarounds: https://www.mobileread.com/forums/showthread.php?t=283371
