### ISSUE TITLE
Adobe Digital Editions Ebooks - Error saving key as .der file

### ISSUE THREAD

**Issue by KenH2000** [noDRM/DeDRM_tools#344]
### Question / bug report

The key is created and works, but I am unable to save the ADE key as .der file.  As a workaround, I was going to try to copy it from its saved location, but I don't know where it is stored.

Summary of Error:
```
Traceback (most recent call last):
  File "C:\Users\ken\AppData\Roaming\calibre\plugins\DeDRM.zip\config.py", line 585, in export_key
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
```

### Which version of Calibre are you running?

5.44

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```calibre Debug log
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 95.93704918032786 x 95.83231441048034
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.59] splash screen shown
[0.59] Initializing db...
[0.66] db initialized
[0.66] Constructing main UI...
[1.59] main UI initialized...
[1.59] Hiding splash screen
Starting QuickView
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ken\AppData\Roaming\calibre\plugins\DeDRM.zip\config.py", line 585, in export_key
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)

[4.31] splash screen hidden
[4.33] Started up in 4.33 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b')%\xab\xfc\x04\xf7\xb2XLs\x81Y\xd6\xc6\x80\xb4\x99:\xa2pT\x0c\x9d\xe5;\xf77{\xbf\x04&"', b'C:\\Users\\ken\\Downloads\\adobe_key.der']

```

**Comment by ElleKayEm** [comment]
Are you sure the key you're trying to save actually works?  I've seen that error when there is a corrupt key.  When I try to save my ADE default_key using DeDRM 10.0.3 and calibre 5.44, I don't have a problem.

A workaround would be to copy the dedrm.json file from calibre's configuration folder.  That has all saved keys and settings for the plugin.

**Comment by KenH2000** [comment]
That was the problem.  The key is not working.  Is there a procedure to remove/reinstall ADE so that the key gets generated correctly in Calibre?  I had changed ADE to log in using an Adobe ID instead of 'no ID'.  I'm sure that's what broke it.

**Comment by ElleKayEm** [comment]
Ah, delete the key.  Add a book downloaded with ADE that's authorized with your Adobe ID.  DeDRM should automatically retrieve the correct key.

**Comment by KenH2000** [comment]
It didn't work.  I tried uninstalling ADE and Calibre, and deleting everything I could find in the registry and file system with calibre and adobe.  Reinstalled both, downloaded a book, re-ran the key generation, and it still made a non-working key.  Any other ideas?

**Comment by KenH2000** [comment]
>>Don't run the key generation from within DeDRM's customization.

This was the key :-)  By not using the customization window, Calibre/DeDRM generated a working key by itself.  After the key was created, I was able to go into customization and save it.  I never would have guessed using the customization section was the cause of the problem. 

Just curious - do you know if the python program (adobekey.py) works too, or does it also have the bug preventing it from generating a valid key?

 Thank you for your help.

**Comment by ElleKayEm** [comment]
From what I understand, the bug has been fixed in the master code for the plugin [here.](https://github.com/noDRM/DeDRM_tools/blob/master/DeDRM_plugin/adobekey.py)  It just wasn't fixed in the last 10.0.3 release.  But I haven't checked on that myself.

**Comment by leolivier** [comment]
Hi @ElleKayEm 
FYI, I just got the issue today with the latest version of Calibre (7.20) and the latest version of the plugin.
I had created the ADE key in the plugin customization and it always failed with the "decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)" error. 
I deleted the key and retried and it worked like a charm...
So it looks like the error is not yet fixed more than one year later...

**Comment by ElleKayEm** [comment]
This was with DeDRM 10.0.9?

**Comment by leolivier** [comment]
No, it was with 10.0.3: this is marked as latest release in GitHub

**Comment by leolivier** [comment]
I didn't see this RC version and I have no other file to try again with 10.0.9 unfortunately
