### ISSUE TITLE
Failed to properly decrypt Kobo ebook.

### ISSUE THREAD

**Issue by watatomo** [noDRM/DeDRM_tools#345]
### Question / bug report

For some reason, books from [this series](https://www.kobo.com/jp/en/ebook/jC355MKYfj6i2LmNf4ZM7Q) fail to decrypt properly. I was able to decrypt [this magazine](https://www.kobo.com/jp/en/ebook/b7xzZe4x1jq4OxpMv8WGZw), however.

### Which version of Calibre are you running?

6.19.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
calibre, version 6.19.1
ERROR: Loading book failed: Failed to open the book at D:\Documents\Books\Calibre\Raws\Unknown\nk ix5b9 (62)\nk ix5b9 - Unknown.epub. Click "Show details" for more info.

Failed to convert book: D:\Documents\Books\Calibre\Raws\Unknown\nk ix5b9 (62)\nk ix5b9 - Unknown.epub with error:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 175, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 237, in get_quick_metadata
  File "calibre\ebooks\metadata\epub.py", line 217, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 155, in read_bytes
  File "calibre\utils\zipfile.py", line 1005, in read
  File "calibre\utils\zipfile.py", line 1033, in open
  File "calibre\utils\zipfile.py", line 994, in getinfo
KeyError: "There is no item named 'OPS/advanced.opf' in the archive"
DeDRM v10.0.3: Trying to decrypt nk ix5b9 - Unknown.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Post-processing took 0.0 seconds
DeDRM v10.0.3: Finished after 1.0 seconds
InputFormatPlugin: EPUB Input running
on C:\Users\Ren\AppData\Local\Temp\calibre_6k28f8nd\90nidttj.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 826, in viewer_main
  File "calibre\srv\render_book.py", line 817, in render_for_viewer
  File "calibre\srv\render_book.py", line 795, in render
  File "calibre\srv\render_book.py", line 608, in process_exploded_book
  File "calibre\srv\render_book.py", line 263, in create_cover_page
  File "calibre\srv\render_book.py", line 216, in find_epub_cover
  File "calibre\ebooks\oeb\polish\cover.py", line 284, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 430, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 41, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes
```

**Comment by ElleKayEm** [comment]
From what I've seen, the DRM is removed.  But the book has this error in it:  KeyError: "There is no item named 'OPS/advanced.opf' in the archive"

That error trips up calibre, but other apps ignore it.  I don't know how to fix it.
