### ISSUE TITLE
Amazon book failing on DRM (from Paperwhite)

### ISSUE THREAD

**Issue by darinhouston** [noDRM/DeDRM_tools#349]
### Question / bug report

Self explanatory.  Is there an update?  Known issue?

### Which version of Calibre are you running?

6.2

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.20  embedded-python: True
macOS-13.3.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.4.0', 'Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.3.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 0, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 0, 0) && KFX metadata reader (from KFX Input) (2, 0, 0) && KFX Input (2, 0, 0) && Obok DeDRM (10, 0, 3)
calibre 6.20  embedded-python: True
macOS-13.3.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.4.0', 'Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.3.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 0, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 0, 0) && KFX metadata reader (from KFX Input) (2, 0, 0) && KFX Input (2, 0, 0) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.65] main UI initialized...
[0.65] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.0.0: Importing /Users/darin/Documents/The Christian in Complete Armor._B09BLNTTWH.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as /var/folders/7z/7y1g881j4ng2klj3g768qp640000gn/C/calibre_6.20.0_tmp_25pvrbo6/zhyz4p3n.kfx-zip
DeDRM v10.0.3: Trying to decrypt zhyz4p3n.kfx-zip
Using Library AlfCrypto Python
Decrypting KFX-ZIP ebook: zhyz4p3n
Got DSN key from database default_key_1686572676
Found 2 keys to try after 0.0 seconds
DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
Found k4Mac kinf2018 file: /Users/darin/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'darin'  on file  /Users/darin/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'337efb46ec2a'
trying IDString: b'337efb46ec35'
trying IDString: b'933b40ebf325'
trying IDString: b'bd9b4a03190a'
Decrypted key file using IDString 'bd9b4a03190a' and UserName 'darin'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: zhyz4p3n
Got DSN key from database key_0
Found 1 keys to try after 0.6 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.0.0: Packaging /var/folders/7z/7y1g881j4ng2klj3g768qp640000gn/C/calibre_6.20.0_tmp_25pvrbo6/zhyz4p3n.kfx-zip
Processing container: The Christian in Complete Armor._B09BLNTTWH.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container The Christian in Complete Armor._B09BLNTTWH.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /var/folders/7z/7y1g881j4ng2klj3g768qp640000gn/C/calibre_6.20.0_tmp_25pvrbo6/iiinn9db_add_books/0/The Christian in Complete Armor._B09BLNTTWH.kfx-zip
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 469, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
    md = YJ_Book(stream).get_metadata()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
    raise Exception("Failed to locate a KFX container with metadata")
Exception: Failed to locate a KFX container with metadata
[11.93] splash screen hidden
[11.93] Started up in 11.93 seconds with 19 books
Added 0 books in 1.1 seconds
Worker Launch took: 0.04 seconds
Job: 0 Convert book 1 of 1 (The Christian in Complete Armor. B09BLNTTWH) finished
Convert book 1 of 1 (The Christian in Complete Armor. B09BLNTTWH)
	DeDRM v10.0.3: Trying to decrypt i_huqra2.kfx-zip
	Using Library AlfCrypto Python
	Decrypting KFX-ZIP ebook: i_huqra2
	Got DSN key from database default_key_1686572676
	Found 2 keys to try after 0.1 seconds
	DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
	Found k4Mac kinf2018 file: /Users/darin/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'darin'  on file  /Users/darin/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'337efb46ec2a'
	trying IDString: b'337efb46ec35'
	trying IDString: b'933b40ebf325'
	trying IDString: b'bd9b4a03190a'
	Decrypted key file using IDString 'bd9b4a03190a' and UserName 'darin'
	DeDRM v10.0.3: Found 1 new key
	Decrypting KFX-ZIP ebook: i_huqra2
	Got DSN key from database key_0
	Found 1 keys to try after 0.6 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
	    self.decrypt_voucher(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
	    self.decrypt_voucher(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
	    self.decrypt_voucher(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  verbose: 2
	  output_profile: 'kindle_pw3'
	  read_metadata_from_opf: '/var/folders/7z/7y1g881j4ng2klj3g768qp640000gn/C/calibre_6.20.0_tmp_25pvrbo6/ce0yqsec.opf'
	Resolved conversion options
	calibre version: 6.20.0
	{'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_max_image_size': 'none',
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11ef58130>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x11ef59150>,
	 'page_breaks_before': '/',
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/7z/7y1g881j4ng2klj3g768qp640000gn/C/calibre_6.20.0_tmp_25pvrbo6/ce0yqsec.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.3: Trying to decrypt i_huqra2.kfx-zip
	Decrypting KFX-ZIP ebook: i_huqra2
	Got DSN key from database default_key_1686572676
	Found 2 keys to try after 0.0 seconds
	DeDRM v10.0.3: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	Found k4Mac kinf2018 file: /Users/darin/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying username  b'darin'  on file  /Users/darin/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
	trying IDString: b'337efb46ec2a'
	trying IDString: b'337efb46ec35'
	trying IDString: b'933b40ebf325'
	trying IDString: b'bd9b4a03190a'
	Decrypted key file using IDString 'bd9b4a03190a' and UserName 'darin'
	DeDRM v10.0.3: Found 1 new key
	Decrypting KFX-ZIP ebook: i_huqra2
	Got DSN key from database key_0
	Found 1 keys to try after 0.5 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
	    self.decrypt_voucher(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
	    self.decrypt_voucher(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
	    self.decrypt_voucher(totalpids)
	  File "/Users/darin/Library/Preferences/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 88, in decrypt_voucher
	    raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on /var/folders/7z/7y1g881j4ng2klj3g768qp640000gn/C/calibre_6.20.0_tmp_25pvrbo6/i_huqra2.kfx-zip
	Software versions: KFX Input 2.0.0, calibre 6.20, macOS-13.3.1-arm64-arm-64bit
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting /var/folders/7z/7y1g881j4ng2klj3g768qp640000gn/C/calibre_6.20.0_tmp_25pvrbo6/i_huqra2.kfx-zip
	Processing container: The Christian in Complete Armor._B09BLNTTWH.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 101, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container The Christian in Complete Armor._B09BLNTTWH.kfx has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 196, in _run_module_as_main
	  File "runpy.py", line 86, in _run_code
	  File "site.py", line 41, in <module>
	  File "site.py", line 37, in main
	  File "calibre/utils/ipc/worker.py", line 215, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
	  File "calibre/customize/conversion.py", line 242, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 121, in convert
	calibre.ebooks.DRMError: This book has DRM!


```

**Comment by ElleKayEm** [comment]
You will not be able to decrypt this kfx format taken directly from the Paperwhite.  Use the download & transfer option from your content & devices page at Amazon to get the book in a format that you can decrypt.
