### ISSUE TITLE
DeDRM for  my ‘azw3’ file  don't working 

### ISSUE THREAD

**Issue by mcjackk777** [noDRM/DeDRM_tools#356]
### Question / bug report

I'm so sorry, i need you help

i download the 'azw3' file from amazon website, got a file name like ‘xxxx.azw3’

because amazon will shut down it's bussines in china,so the only way i can do it's to download all the books i purchased,but the book has DRM limit，i can't read the books in my computer.

so i google it ,installed calibre and DeDRM plugin on my computer,but when i drag book to the calibre,and convert books to EPUB file,it's show me a error message'this book is loccked by DRM'

so i confused ,maybe one of my steps did wrong, so i post the Debug log to this place,if you guys have much free time, please

other tips:  My Kindle Version is Kindle Oasis2,i found it's serial number in amazon website- mydevice ,and then paste it to the calibre-preferences-plugins-DeDRM settings-Kindle eInk ebooks,

sorry for my chiniglish,hope you can understand

### Which version of Calibre are you running?

6.21.0

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Using calibre Qt style: True
calibre Debug log
calibre 6.21  embedded-python: True
macOS-13.4.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.21  embedded-python: True
macOS-13.4.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 109.00000163701577
[0.00] Starting up...
[0.07] Showing splash screen...
[0.29] splash screen shown
[0.29] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
Using proxies: {'http': '127.0.0.1:7890', 'https': '127.0.0.1:7890'}
[0.90] main UI initialized...
[0.90] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt 刀锋（据1944年牛津大学推荐经典版本“全本”呈现，《月亮与六便士》9.4高分译者完整翻译，余华推荐。).azw3
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 刀锋（据1944年牛津大学推荐经典版本“全本”呈现，《月亮与六便士》9.4高分译者完整翻译，余华推荐。)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/macheng/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/macheng/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Using proxies: {'http': '127.0.0.1:7890', 'https': '127.0.0.1:7890'}
[3.08] splash screen hidden
[3.08] Started up in 3.08 seconds with 1 books
Added 刀锋（据1944年牛津大学推荐经典版本“全本”呈现，《月亮与六便士》9.4高分译者完整翻译，余华推荐。) to db in: 0.0
Added 1 books in 0.6 seconds

```

**Comment by ElleKayEm** [comment]
When you downloaded the book from the website, did you select your Kindle Oasis for the device?  After adding the serial number to the DeDRM customization, be sure to click OK and Apply.  Then re-start calibre before adding the book again.

**Comment by mcjackk777** [comment]
> When you downloaded the book from the website, did you select your Kindle Oasis for the device? After adding the serial number to the DeDRM customization, be sure to click OK and Apply. Then re-start calibre before adding the book again.

it's amazing!!

As you said ,i clean the serial number in the DeDRM customization, restart the cailbre, and then re-enter the serial number,click ok and apply,restart applications again,it's just worked!!! i succeed convert my kindle book format from azw3 to the epub,

thanks for your answer, i must have made  a mistake somewhere.

**Comment by ElleKayEm** [comment]
Great!  If you're all set, you can close the issue.
