### ISSUE TITLE
DRM not removed on Import (Linux)

### ISSUE THREAD

**Issue by djm858** [noDRM/DeDRM_tools#364]
**Which version of Calibre are you running?**
6.9.0

**Which version of the DeDRM plugin are you running?**
v10.0.3

**If applicable, which version of the Kindle software are you running?**
No response

**OS**
Linux Mint 20.3
ADE is installed via Wine. Calibre is not through Wine. I'm guessing that's causing a communication problem?

**Log output**
Using calibre Qt style: True
calibre Debug log
calibre 6.9  embedded-python: True
Linux-5.4.0-153-generic-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.4.0-153-generic', '#170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KoboTouchExtended (3, 6, 3) && Standard Ebooks (1, 0, 0)
calibre 6.9  embedded-python: True
Linux-5.4.0-153-generic-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.4.0-153-generic', '#170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KoboTouchExtended (3, 6, 3) && Standard Ebooks (1, 0, 0)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 166.4436860068259 x 166.25454545454545
[0.00] Starting up...
[0.00] Showing splash screen...
[0.07] splash screen shown
[0.07] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
Loaded cached store plugin for: Barnes and Noble at version: 3
Screens currently in system:
{'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': 'Chimei Innolux Corporation',
 'model': '',
 'name': 'eDP-1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1040, 'width': 1920, 'x': 0, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 1009, 'width': 1920, 'x': 0, 'y': 30},
 'maximized': True,
 'normal_geometry': {'height': 1009, 'width': 1920, 'x': 0, 'y': 30},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': 'Chimei Innolux Corporation',
            'model': '',
            'name': 'eDP-1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': 'Chimei Innolux Corporation',
 'model': '',
 'name': 'eDP-1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 1009, 'width': 1920, 'x': 0, 'y': 30}
Restoring widget to maximized
[0.75] main UI initialized...
[0.75] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt The_Lord_Of_The_Rings.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: The_Lord_Of_The_Rings.epub is a secure Adobe Adept ePub for UUID 070fecbe-2c7d-4163-948f-400ba35635f2
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
002c:fixme:winediag:LdrInitializeThunk wine-staging 8.11 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
009c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

00cc:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
00cc:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
00d8:fixme:advapi:RegisterEventSourceW ((null),L"Bonjour Service"): stub
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0004,0x0000,0x00000064,00000000,0x0001,0x00000000,018DFAA4,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0004,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:fixme:winsock:WSAIoctl SIO_UDP_CONNRESET stub
00d8:fixme:winsock:WSAIoctl SIO_UDP_CONNRESET stub
0074:fixme:nsi:ipv6_forward_enumerate_all not implemented
0074:fixme:nsi:ipv6_forward_enumerate_all not implemented
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0004,0x0000,0x00000064,00000000,0x0001,0x00000000,018DFAA4,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0004,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
0050:fixme:service:svcctl_EnumServicesStatusExW resume handle not supported
0050:fixme:service:svcctl_EnumServicesStatusExW resume handle not supported
0050:fixme:service:svcctl_EnumServicesStatusExW resume handle not supported
0050:fixme:service:svcctl_EnumServicesStatusExW resume handle not supported
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0004,0x0000,0x00000064,00000000,0x0001,0x00000000,018DFAA4,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0004,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:fixme:netapi32:NetGetJoinInformation Semi-stub (null) 018DFB5C 018DFB54
0074:fixme:nsi:ipv6_forward_enumerate_all not implemented
0074:fixme:nsi:ipv6_forward_enumerate_all not implemented
00d8:fixme:winsock:WSAIoctl SIO_UDP_CONNRESET stub
00d8:fixme:winsock:WSAIoctl SIO_UDP_CONNRESET stub
0074:fixme:nsi:ipv6_forward_enumerate_all not implemented
0074:fixme:nsi:ipv6_forward_enumerate_all not implemented
[5.14] splash screen hidden
[5.14] Started up in 5.14 seconds with 965 books
['zenity', '--modal', '--file-selection', '--title=Select books', '--separator=\n', '--attach=88080407', '--filename=/home/duncan/Documents/My Digital Editions/.fgdfg.gdfhjdhf*&^839', '--file-filter=Books | *.lrf *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf', '--file-filter=EPUB books | *.epub *.kepub', '--file-filter=Kindle books | *.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4', '--file-filter=PDF books | *.pdf *.azw4', '--file-filter=HTML books | *.htm *.html *.xhtm *.xhtml', '--file-filter=LIT books | *.lit', '--file-filter=Text books | *.txt *.text *.rtf *.md *.markdown *.textile *.txtz', '--file-filter=Comics | *.cbz *.cbr *.cbc', '--file-filter=Archives | *.zip *.rar', '--file-filter=Wordprocessor files | *.odt *.doc *.docx', '--file-filter=All files | *', '--multiple']
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine py.exe -3 is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine python3.exe is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.3: wine python.exe is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Path not found.

DeDRM v10.0.3: wine C:\Python27\python.exe is not python3
DeDRM v10.0.3: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.3: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 1.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,018DF2A0,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Received from 192.168.0.11:5353   45 11.0.168.192.in-addr.arpa. PTR duncan-HP-Spectre-x360-Convertible-17.local."
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,018DF2A8,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Unexpected conflict discarding   45 11.0.168.192.in-addr.arpa. PTR duncan-HP-Spectre-x360-Convertible-13.local."
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,018DF2A0,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Received from 192.168.0.11:5353   45 0.0.c.2.0.2.c.2.5.6.a.0.9.a.a.3.0.8.4.4.0.0.d.8.1.c.2.0.1.0.6.2.ip6.arpa. PTR duncan-HP-Spectre-x360-Convertible-17.local."
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,018DF2A8,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Unexpected conflict discarding   45 0.0.C.2.0.2.C.2.5.6.A.0.9.A.A.3.0.8.4.4.0.0.D.8.1.C.2.0.1.0.6.2.ip6.arpa. PTR duncan-HP-Spectre-x360-Convertible-13.local."
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,018DF2A0,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Received from 192.168.0.11:5353   45 3.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.4.4.0.0.d.8.1.c.2.0.1.0.6.2.ip6.arpa. PTR duncan-HP-Spectre-x360-Convertible-17.local."
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,018DF2A8,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Unexpected conflict discarding   45 3.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.4.4.0.0.D.8.1.C.2.0.1.0.6.2.ip6.arpa. PTR duncan-HP-Spectre-x360-Convertible-13.local."
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,018DF2A0,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Received from 192.168.0.11:5353   45 1.2.1.9.2.2.8.3.1.e.9.8.6.2.5.4.0.8.4.4.0.0.d.8.1.c.2.0.1.0.6.2.ip6.arpa. PTR duncan-HP-Spectre-x360-Convertible-17.local."
00d8:fixme:advapi:ReportEventA (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,018DF2A8,00000000): stub
00d8:fixme:advapi:ReportEventW (CAFE4242,0x0001,0x0000,0x00000064,00000000,0x0001,0x00000000,0035C290,00000000): stub
00d8:err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Unexpected conflict discarding   45 1.2.1.9.2.2.8.3.1.E.9.8.6.2.5.4.0.8.4.4.0.0.D.8.1.C.2.0.1.0.6.2.ip6.arpa. PTR duncan-HP-Spectre-x360-Convertible-13.local."
Added The Lord Of The Rings to db in: 0.6
Added 1 books in 2.5 seconds
Restoring geometry for: preferences dialog geometry
{'frame_geometry': {'height': 751, 'width': 932, 'x': 495, 'y': 145},
 'full_screened': False,
 'geometry': {'height': 720, 'width': 930, 'x': 496, 'y': 175},
 'maximized': False,
 'normal_geometry': {'height': 720, 'width': 930, 'x': 496, 'y': 175},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': 'Chimei Innolux Corporation',
            'model': '',
            'name': 'eDP-1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 24,
 'device_pixel_ratio': 1.0,
 'geometry_in_logical_pixels': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': 'Chimei Innolux Corporation',
 'model': '',
 'name': 'eDP-1',
 'serial': '',
 'size_in_logical_pixels': {'height': 1080, 'width': 1920},
 'virtual_geometry': {'height': 1080, 'width': 1920, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 720, 'width': 930, 'x': 496, 'y': 175}
Saving geometry for: preferences dialog geometry
{'frame_geometry': {'height': 751, 'width': 932, 'x': 495, 'y': 145},
 'full_screened': False,
 'geometry': {'height': 720, 'width': 930, 'x': 496, 'y': 175},
 'maximized': False,
 'normal_geometry': {'height': 720, 'width': 930, 'x': 496, 'y': 175},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': 'Chimei Innolux Corporation',
            'model': '',
            'name': 'eDP-1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}
Saving geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 1040, 'width': 1920, 'x': 0, 'y': 0},
 'full_screened': False,
 'geometry': {'height': 1009, 'width': 1920, 'x': 0, 'y': 30},
 'maximized': True,
 'normal_geometry': {'height': 1009, 'width': 1920, 'x': 0, 'y': 30},
 'screen': {'depth': 24,
            'device_pixel_ratio': 1.0,
            'geometry_in_logical_pixels': {'height': 1080,
                                           'width': 1920,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': 'Chimei Innolux Corporation',
            'model': '',
            'name': 'eDP-1',
            'serial': '',
            'size_in_logical_pixels': {'height': 1080, 'width': 1920},
            'virtual_geometry': {'height': 1080,
                                 'width': 1920,
                                 'x': 0,
                                 'y': 0}}}

**Comment by ElleKayEm** [comment]
A workaround is temporarily installing Windows calibre (with DeDRM) under Wine to grab your key.  Then you can save the key and import it into your Linux calibre/DeDRM setup.  You'll need older versions in order to install under Wine.  Should work with calibre 4.23 and DeDRM 6.8.1.
