### ISSUE TITLE
Cannot DeDRM azw file

### ISSUE THREAD

**Issue by sachama2** [noDRM/DeDRM_tools#368]
### Question / bug report

DeDRM does not work on this azw file. Book is "Nudging choices through media" from Amazon. The version of deDRM has been downloaded as 10.0.3 but appears in Calibre as 10.0.02

### Which version of Calibre are you running?

6.22

### Which version of the DeDRM plugin are you running?

10.0.3 but read as 10.0.2

### Log output

```log
Paste log output here.
```Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
calibre Journal de débogage
calibre 6.22  embedded-python: True
macOS-13.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'arm64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 2) && EpubSplit (3, 6, 0)
calibre 6.22  embedded-python: True
macOS-13.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'arm64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 2) && EpubSplit (3, 6, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 93.50000140422914 x 93.50000140422914
[0.00] Starting up...
[0.05] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[0.60] main UI initialized...
[0.60] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.000) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.86:  0.816) _startup_on_demand listening on port 9090
SMART_DEV (   0.88:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   0.90:  0.000) _startup_on_demand broadcast socket listening on port 54982
2023-07-11 08:20:51.806 calibre-debug[17602:21903911] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-11 08:20:51.806 calibre-debug[17602:21903911] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-11 08:20:51.806 calibre-debug[17602:21903911] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-11 08:20:51.807 calibre-debug[17602:21903911] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2023-07-11 08:20:51.807 calibre-debug[17602:21903911] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
Blacklisting the DeDRM plugin as it is too old and causes crashes
Failed to get text from book_id: 4137 format: AZW3
Blacklisting the DeDRM plugin as it is too old and causes crashes
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre/db/fts/text.py", line 103, in main
  File "calibre/db/fts/text.py", line 90, in extract_text
  File "calibre/ebooks/oeb/iterator/book.py", line 62, in extract_book
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
calibre.ebooks.DRMError: Nudging Choices Through Media

SMART_DEV (   1.92:  1.006) run All IP addresses {'lo0': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'peer': '127.0.0.1'}], 'en1': [{'addr': '192.168.1.13', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}]}
[10.80] splash screen hidden
[10.80] Started up in 10.80 seconds with 3438 books
Added Nudging Choices Through Media to db in: 0.0
Added 1 books in 0.3 seconds
2023-07-11 08:21:17.982 calibre-debug[17602:21903911] +[CATransaction synchronize] called within transaction
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10ead3d90>

**Comment by ElleKayEm** [comment]
Update to 10.0.3.  You definitely still have DeDRM 10.0.2 which calibre blocks from even running at all here.  The log shows:

> ```Blacklisting the DeDRM plugin as it is too old and causes crashes

**Comment by sachama2** [comment]
I did it. #369 uses 10.0.3

Le 11 juil. 2023 à 15:13, ElleKayEm ***@***.***> a écrit :


Update to 10.0.3. You definitely still have DeDRM 10.0.2 which calibre blocks from even running at all here. The log shows:

**Comment by ElleKayEm** [comment]
Close this issue.
