### ISSUE TITLE
Cannot dedrm azw file - modifier since last time

### ISSUE THREAD

**Issue by sachama2** [noDRM/DeDRM_tools#369]
### Question / bug report

Here is a modified version, using 10.0.3 now

### Which version of Calibre are you running?

6.22

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Paste log output here.
```Using calibre Qt style: True
calibre Journal de débogage
calibre 6.22  embedded-python: True
macOS-13.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'arm64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3) && EpubSplit (3, 6, 0)
calibre 6.22  embedded-python: True
macOS-13.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'arm64')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3) && EpubSplit (3, 6, 0)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 93.50000140422914 x 93.50000140422914
[0.00] Starting up...
[0.05] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[0.61] main UI initialized...
[0.61] Hiding splash screen
Starting QuickView
SMART_DEV (   0.00:  0.000) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.86:  0.816) _startup_on_demand listening on port 9090
SMART_DEV (   0.89:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   0.91:  0.000) _startup_on_demand broadcast socket listening on port 54982
DeDRM v10.0.3: Trying to decrypt Nudging Choices Through Media.azw3
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Nudging Choices Through Media
Got DSN key from database kindle_key_1669066540_1
Got DSN key from database kindle_key_1669066540_2
Found 16 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 16 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
Found k4Mac kinf2018 file: /Users/Sacha_1/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
Found k4Mac kinf2018 file: /Users/Sacha_1/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'Sacha'  on file  /Users/Sacha_1/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'99035300d348'
Decrypted key file using IDString '99035300d348' and UserName 'Sacha'
trying username  b'Sacha'  on file  /Users/Sacha_1/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'99035300d348'
Decrypted key file using IDString '99035300d348' and UserName 'Sacha'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Nudging Choices Through Media
Got DSN key from database key_1
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 16 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 16 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
SMART_DEV (   1.93:  1.006) run All IP addresses {'lo0': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'peer': '127.0.0.1'}], 'en1': [{'addr': '192.168.1.13', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}]}
[6.52] splash screen hidden
[6.52] Started up in 6.52 seconds with 3438 books
Added Nudging Choices Through Media to db in: 0.0
Added 1 books in 0.7 seconds
Failed to get text from book_id: 4140 format: AZW3
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 16 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/Sacha_1/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 16 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 41, in <module>
  File "site.py", line 37, in main
  File "calibre/utils/ipc/worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre/db/fts/text.py", line 103, in main
  File "calibre/db/fts/text.py", line 90, in extract_text
  File "calibre/ebooks/oeb/iterator/book.py", line 62, in extract_book
  File "calibre/customize/conversion.py", line 242, in __call__
  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
calibre.ebooks.DRMError: Nudging Choices Through Media

Worker Launch took: 0.01 seconds
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10acbc1c0>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10acbc1c0>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10acbc1c0>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10acbc1c0>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10acbc1c0>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10acbc1c0>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 241, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Device connect failed again, giving up
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10acbc1c0>

**Comment by ElleKayEm** [comment]
Is this an E-ink Kindle - not a Fire?  If so, do you have its serial number entered correctly in DeDRM's customization?

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
