### ISSUE TITLE
Unable to install de-drm plugin 10.0.3 in Calibre

### ISSUE THREAD

**Issue by Gary-81** [noDRM/DeDRM_tools#370]
I'm trying to get Adobe Digital Editions and Calibre 6.22 to run properly in Linux Mint Cinnamon.  I was attempting to install the de-drm plugin 10.0.3 obtained here, and Calibre gave the following error:

calibre, version 6.22.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/home/gary/Downloads/DeDRM_tools-master.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.22  embedded-python: True
Linux-5.15.0-76-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-76-generic', '#83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 513, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 298, in load
  File "calibre/customize/zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: **_The plugin in '/home/gary/Downloads/DeDRM_tools-master.zip' is invalid. It does not contain a top-level __init__.py file_**

Can someone explain why this failed, and how to make it work?

**Comment by ElleKayEm** [comment]
You're trying to install the wrong file.  Download  DeDRM_tools_10.0.3.zip from here:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3  (first link under Assets)

Unzip that file and load DeDRM_plugin.zip into calibre.
