### ISSUE TITLE
DeDRM failed on ADE file

### ISSUE THREAD

**Issue by snapdragon780** [noDRM/DeDRM_tools#373]
### Question / bug report

Running into issues with DeDRM working on an epub from Adobe Digital Editions. ADE version is 4.5.12.85. 

I confirmed the key pulled into the plugin settings for Adobe Digital Editions Keys.

### Which version of Calibre are you running?

6.23

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 6.23  embedded-python: True
macOS-13.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.23  embedded-python: True
macOS-13.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.00000162199728 x 111.00000166705276
[0.00] Starting up...
[0.03] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.52] main UI initialized...
[0.52] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Tress of the Emerald Sea.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Tress of the Emerald Sea.epub is a secure Adobe Adept ePub for UUID 02564a68-4695-1c4c-9830-9c42ccb22555
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
    userkey = codecs.decode(userkeyhex, 'hex')
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[68.84] splash screen hidden
[68.84] Started up in 68.84 seconds with 1 books

Debugging DND event
text/uri-list 88 b'file:///Users/betsy/Documents/Digital%20Editions/Tress%20of%20the%20Emerald%20Sea.epub\r\n' 


Firefox rurl: None None
URLS: ['file:///Users/betsy/Documents/Digital%20Editions/Tress%20of%20the%20Emerald%20Sea.epub']
Paths: ['/Users/betsy/Documents/Digital Editions/Tress of the Emerald Sea.epub']
Extensions: frozenset({'epub'})
Added Tress of the Emerald Sea to db in: 0.0
Added 1 books in 0.3 seconds

```

**Comment by ElleKayEm** [comment]
Delete the Adobe key in DeDRM's customization.  Re-add the book letting DeDRM automatically retrieve the key on its own.

**Comment by snapdragon780** [comment]
Thank you! That's what I get for being an overachiever. :D 
The key looks the same doing it that way, but it definitely worked following your suggestion. Any idea why?

**Comment by ElleKayEm** [comment]
There's a bug which corrupts the key somehow when saving it that way.  The bug has been squashed in the master code, but isn't in the released version.

**Comment by j-howell** [comment]
> The bug has been squashed in the master code, but isn't in the released version.

Not releasing a new version that fixes problems and adds new functionality is getting old.

**Comment by ElleKayEm** [comment]
It might help keep that new functionality working though.  I don't know if that's the thinking.

**Comment by j-howell** [comment]
> It might help keep that new functionality working though. I don't know if that's the thinking.

Possibly. NoDRM doesn’t share the reasoning behind decisions. I believe that it is a mistake.

Regarding the issue raised in here, you are the one helping out people. Solving problems that should have been fixed by a new release. If it was me doing that I would be pissed off.

**Comment by ElleKayEm** [comment]
This is an easy workaround.  I'm surprised that people run into this issue as often as they do.

**Comment by romad275** [comment]
While that may be, the fact that there is a fix to the problem available but it has/will not be released does not bode confidence.

**Comment by ElleKayEm** [comment]
NoDRM briefly set it up so there was an automatic pre-release available every time a change was made.  But they disabled that again when a complaint was made about getting notifications for them.

@snapdragon780 
If you're all set, you can close the issue.

**Comment by andyzukunft** [comment]
NoDrm just added an auto-release feature for every code change (alpha): https://github.com/noDRM/DeDRM_tools_autorelease/releases

He also released a current more tested beta version as v10.0.9.: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
