### ISSUE TITLE
DeDRM fails to decrypt Kindle files

### ISSUE THREAD

**Issue by phxyz12** [noDRM/DeDRM_tools#375]
Hi there

I installed Calibre 6.23 and DeDRM plugin release 10.0.3 on Windows 10. Kindle reader is also installed, version 1.40.65535.

In Calibre, I installed the DeDRM plugin as well as the KFX input/output plugins, nothing else. Both, Calibre and the Kindle reader app are fresh installs.

I downloaded Kindle books in the Kindle reader app and tried to import it into Calibre. The import works, but DRM is not removed. Here is the debug output:

```
calibre 6.23  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 2, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 2, 0) && KFX metadata reader (from KFX Input) (2, 2, 0) && KFX Input (2, 2, 0) && Set KFX metadata (from KFX Output) (2, 1, 0) && KFX Output (2, 1, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 110.83636363636363 x 110.73569482288829
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
[1.39] main UI initialized...
[1.39] Hiding splash screen
Starting QuickView
[1.58] splash screen hidden
[1.58] Started up in 1.58 seconds with 1060 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\'\xc8Vi?i\x9a\xe2\xf2"\x1b\xdc\xbc\xaf\x12TQ\xd8\xe6z\xe2\xc4?\xd8\xbe\xda\x98X9\xf1\xbf\x03', b'C:\\Users\\xxx\\Documents\\My Kindle Content\\B077BZ9DN9_EBOK\\B077BZ9DN9_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 2.2.0: Importing C:\Users\xxx\Documents\My Kindle Content\B077BZ9DN9_EBOK\B077BZ9DN9_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\xxx\AppData\Local\Temp\calibre_2xfmsuwo\7a0req03.kfx-zip
DeDRM v10.0.3: Trying to decrypt 7a0req03.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: 7a0req03
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4ecd5e6b-5ff0-4b33-9630-4207acfde2dc.voucher
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\xxx\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\xxx\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '774424910' and UserName 'xxx'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: 7a0req03
Got DSN key from database key_0
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.4ecd5e6b-5ff0-4b33-9630-4207acfde2dc.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 763, in pkcs7unpad
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.2.0: Packaging C:\Users\xxx\AppData\Local\Temp\calibre_2xfmsuwo\7a0req03.kfx-zip
Processing container: B077BZ9DN9_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B077BZ9DN9_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\xxx\AppData\Local\Temp\calibre_2xfmsuwo\7qex5_0l_add_books\0\B077BZ9DN9_EBOK.kfx-zip
Added Das geschenkte Leben: Roman (German Edition) to db in: 0.1
Added 1 books in 1.3 seconds
```

I read the plugin help but from the log above, I can't figure out whats wrong.

Many thanks in advance and kind regards.

**Comment by ElleKayEm** [comment]
DeDRM 10.0.3 doesn't work with Kindle for PC 1.40.  You can either try the unreleased master code here:  https://github.com/noDRM/DeDRM_tools/actions/runs/5370838206
Click plugin under Artifacts.  You'll need to unzip twice to see the 2 plugin (zip) files and 3 readme (txt) files.

Or use another method to get non-kfx files which can be decypted with DeDRM 10.0.3: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by phxyz12** [comment]
Dear @ElleKayEm 

Thanks a lot for your quick reply. I apologize, I wasn't aware of the incompatibility.

Best, P.
