### ISSUE TITLE
Still DRM locked

### ISSUE THREAD

**Issue by blugoo0405** [noDRM/DeDRM_tools#378]
Trying to unlock the DRM from this book downloaded from Libgen.is

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.23  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.23  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[1.67] main UI initialized...
[1.67] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt Tui T. Sutherland - The Dangerous Gift (Wings of Fire, Book 14) (14).epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Tui T. Sutherland - The Dangerous Gift (Wings of Fire, Book 14) (14).epub is a secure Adobe Adept ePub for UUID 744248d0-c2e7-4be2-a2ce-931fd524142e
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "C:\Users\blugo\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 343, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\blugo\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 346, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[10.23] splash screen hidden
[10.23] Started up in 10.23 seconds with 2 books
Added Dangerous Gift to db in: 0.2

**Comment by noDRM** [comment]
This plugin only works if you have access to the DRM keys - meaning you're running this on a computer that can read the book in ADE. If you got an EPUB / PDF file from elsewhere and it's already DRMed, it is not possible to remove that DRM without having access to the source account's keys.
