### ISSUE TITLE
Kobo book epub added to calibre but text is gibberish

### ISSUE THREAD

**Issue by patchyderms** [noDRM/DeDRM_tools#381]
### Question / bug report

Hi, I was able to import a book purchased on Kobo but although the book metadata (title, author, chapter titles) are present, the content (text and images) all look like corrupted data.
I've tested if I can convert other books from Kobo and it works fine so I'm wondering if it's a specific issue with this book.

My process:
- I use desktop version of kobo app and locate files on my Windows machine at `C:\Users\Angela\AppData\Local\Kobo\Kobo Desktop Edition\kepub`
- I copy and rename the file to be shorter and have extension `.epub`. Without this step I run into issues with Calibre
- I try to add the book from Calibre UI's Add Books
- The book is added but text/images are all corrupted

### Which version of Calibre are you running?

6.23

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.23  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: en_CA
Successfully initialized third party plugins: Obok DeDRM (10, 0, 3)
calibre 6.23  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: en_CA
Successfully initialized third party plugins: Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.96245733788396 x 112.88888888888889
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.75] main UI initialized...
[0.75] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1722, in set_metadata
  File "calibre\db\cache.py", line 1645, in set_cover
  File "calibre\db\backend.py", line 1663, in set_cover
  File "calibre\utils\img.py", line 301, in save_cover_data_to
  File "calibre\utils\img.py", line 209, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
[7.19] splash screen hidden
[7.19] Started up in 7.19 seconds with 13 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x8a\xdd\xbc9\x1a\xb8\xf4\xef^\xa9\xe6\xb1\xf2\xc3\x80G$:\x056"\xd21\x02z^\xfb0\xd3x\xff\x08', b'C:\\Users\\Angela\\Desktop\\yuwu.epub']
Added Remnants of Filth: Yuwu Vol. 1 to db in: 0.0
Added 1 books in 0.5 seconds
```

**Comment by patchyderms** [comment]
I see, I didn't notice the plugin icon. But now when I try and click on that it can't locate the Kobo library
```
calibre, version 6.23.0
ERROR: Obok DeDRM v10.0.3: <p>Could not find Kobo Library
<p>Windows/Mac: do you have Kobo Desktop installed?
<p>Windows/Mac/Linux: In case you have an Kobo eInk device, connect the device.
```
```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.23  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: en_CA
Successfully initialized third party plugins: Obok DeDRM (10, 0, 3)
calibre 6.23  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: en_CA
Successfully initialized third party plugins: Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.96245733788396 x 112.88888888888889
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.72] main UI initialized...
[0.72] Hiding splash screen
Starting QuickView
```

**Comment by ElleKayEm** [comment]
Someone recently mentioned that what works for them is to open both Kobo Desktop and calibre, download the books in the Kobo app, then close the Kobo app before importing the books into calibre with Obok.

I don't know if it will help in this case, but there are some Obok fixes in a pre-release version 10.0.9:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Alternatively, Kobo also has the option to download Adobe DRM epubs with Adobe Digital Editions.  The regular DeDRM plugin can be used on those.

**Comment by patchyderms** [comment]
Thanks, I'll try the ADE if nothing else works.

Opening Kobo and Calibre and redownloading books did not help me.

I tried pre-release 10.0.9 and no difference either.

Is there any info about how to customize the plugin with specifying the folder? I tried playing around with that a bit but it's hard to tell what the folder setting is.

**Comment by ElleKayEm** [comment]
I've never messed with folder settings and Obok finds my Kobo books which are in this folder:  C:\Users\[User Name]\AppData\Local\Kobo\Kobo Desktop Edition\kepub
