### ISSUE TITLE
Error upgrading 10.0.2 to 10.0.3 in Linux Calibre 5.44.0

### ISSUE THREAD

**Issue by gabrielgg** [noDRM/DeDRM_tools#382]
### Question / bug report

See log/traceback attached.

I did some digging myself but couldn't find anything obvious. It surprised me that the line numbers in the actual __init__.py file I have are different than in github's 10.0.3 tag, too.

I did suspect that for some reason __version.py wasn't loaded, but tried it in a separate interpreter and worked just fine.

### Which version of Calibre are you running?

5.44.0

### Which version of the DeDRM plugin are you running?

10.0.2

### If applicable, which version of the Kindle software are you running?

n/a

### Log output

```log
calibre, version 5.44.0
ERROR: Unhandled exception: <b>OSError</b>:[Errno 5] Input/output error

calibre 5.44  embedded-python: False is64bit: True
Linux-6.1.41-gentoo-x86_64-Intel-R-_Core-TM-_i5-3320M_CPU_@_2.60GHz-with-glibc2.37 Linux ('64bit', 'ELF')
('Linux', '6.1.41-gentoo', '#1 SMP PREEMPT_DYNAMIC Fri Jul 28 17:31:31 BST 2023')
Python 3.11.4
Interface language: en_GB
Successfully initialized third party plugins: DeDRM (10, 0, 2) && Obok DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 238, in initialize
    print("{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION))
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 673, in initialize_plugin
    p.initialize()
  File "calibre_plugins.dedrm.__init__", line 257, in initialize
    traceback.print_exc()
  File "/usr/lib/python3.11/traceback.py", line 183, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.11/traceback.py", line 125, in print_exception
    te.print(file=file, chain=chain)
  File "/usr/lib/python3.11/traceback.py", line 982, in print
    print(line, file=file, end="")
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/preferences/plugins.py", line 326, in add_plugin
    plugin = add_plugin(path)
             ^^^^^^^^^^^^^^^^
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 483, in add_plugin
    plugin = initialize_plugin(plugin, path_to_zip_file, PluginInstallationType.EXTERNAL)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/calibre/calibre/customize/ui.py", line 676, in initialize_plugin
    print('Failed to initialize plugin:', plugin.name, plugin.version)
OSError: [Errno 5] Input/output error
```

**Comment by ElleKayEm** [comment]
You got DeDRM_tools_10.0.3.zip from this page: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3

Unzipped it and are loading DeDRM_plugin.zip into calibre?

**Comment by gabrielgg** [comment]
> You got DeDRM_tools_10.0.3.zip from this page: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.3
> 
> Unzipped it and are loading DeDRM_plugin.zip into calibre?

Yes, that's correct.

**Comment by ElleKayEm** [comment]
I don't know why that isn't working.  You might try the official Linux calibre instead of your distribution provided calibre package.

**Comment by ElleKayEm** [comment]
Taking a second look at that log and thinking about your comment that the line numbers don't match, are you sure you're trying to load DeDRM 10.0.3 and not some older version of DeDRM left on your computer from an old download?  That looks like you're trying to load a version that isn't Python 3.

**Comment by gabrielgg** [comment]
What I did to confirm the difference in line numbers is unzip the plugin file and open __init__.py, then compared it to github's 10.0.3 tag - I didn't pay too much attention to it as the release process itself might add comments etc to the file.
I *think* it's the right version (10.0.3) because there's a __version.py (and the "print" line that fails relies on it), while 10.0.2 contains all the required version variables in __init__.py.

Update: I installed Calibre 6 on mac os and it works 🤷 10.0.2 still works well on Calibre 5 on Gentoo Linux, so this might be one of those difficult bugs to troubleshoot. I'll leave this for a rainy day :)
