### ISSUE TITLE
2 ADE problems in windows 10

### ISSUE THREAD

**Issue by Mr-Donz** [noDRM/DeDRM_tools#383]
### Question / bug report

here the 2 logs
thank you for the attention,
i'm also not able to export key .der valueerror:  string argument should contain only ascii characters" 

i also p

### Which version of Calibre are you running?

6.24

### Which version of the DeDRM plugin are you running?

v10.0.2

### Log output

```log
calibre 6.24  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: it
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.45378151260503 x 102.74157303370787
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.28] main UI initialized...
[1.28] Hiding splash screen
Starting QuickView
[1.47] splash screen hidden
[1.47] Started up in 1.47 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'cq\xe4\x14\xdb\x12,\x8c\xd8b\xc9\x12 \xa1\xc7\xb8\xba,\xd6o\xda\x16\xb8\xe8\xbf\x1f\xaa\xf3*>\xc9\xa2', b'C:\\Users\\don\\Documents\\My Digital Editions\\Restare in piedi tra le onde.epub']
DeDRM v10.0.3: Trying to decrypt Restare in piedi tra le onde.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Restare in piedi tra le onde.epub is a secure Adobe Adept ePub for UUID fde83451-7918-4922-bb0f-f28cb8d9cbb0
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Added Restare in piedi tra le onde to db in: 0.1
Added 1 books in 0.5 seconds
Worker Launch took: 0.00 seconds```

**Comment by ElleKayEm** [comment]
Delete the saved Adobe key from DeDRM's customization.  Re-add the book letting DeDRM automatically retrieve the key.

This bug should be fixed in DeDRM pre-release 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by Mr-Donz** [comment]
Thank you very much!
:)
