### ISSUE TITLE
Encryption key cannot be read from kindle app after *fresh* install with version > 10.0.2

### ISSUE THREAD

**Issue by Bleistein** [noDRM/DeDRM_tools#385]
### Question / bug report

After complete fresh installation (Windows 11 64bit arm) the kindle encryption keys are not initialized in the plugin. When trying to read the key manually we get an error message that the key cannot be located.

Downgrading to v10.0.2 eliminates the problem. Keys can be located again. Now it is possible to use these keys with later versions!

### Which version of Calibre are you running?

6.24

### Which version of the DeDRM plugin are you running?

v10.0.3, v10.0.9

### If applicable, which version of the Kindle software are you running?

1.17.1

### Log output

```log
Paste log output here.
```

**Comment by noDRM** [comment]
Interesting. There isn't that much code related to Amazon keys that changed between 10.0.2 and 10.0.3. 

Can you post a log (Right-click on Preferences in Calibre, then choose "Restart in debug mode", then try to read the key, then close Calibre, then post the log file that appears)?

I'll try to reproduce this when I have time - if I can't reproduce this I'll probably post some more test versions with various changes from 10.0.3 undone to figure out which of the changes broke stuff.

**Comment by Bleistein** [comment]
The Debug log for opening "Settings" and trying to read the key with the plugin...

```
Using calibre Qt style: False
calibre Debug log
calibre 6.24  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 3, 0) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0) && Set KFX metadata (from KFX Output) (2, 2, 0) && KFX Output (2, 2, 0)
calibre 6.24  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 3, 0) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0) && Set KFX metadata (from KFX Output) (2, 2, 0) && KFX Output (2, 2, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 110.25322033898304 x 112.00580645161291
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[1.02] main UI initialized...
[1.02] Hiding splash screen
Starting QuickView
Traceback (most recent call last):
  File "C:\Users\US\AppData\Roaming\calibre\plugins\DeDRM.zip\config.py", line 1254, in __init__
  File "C:\Users\US\AppData\Roaming\calibre\plugins\DeDRM.zip\kindlekey.py", line 947, in kindlekeys
  File "C:\Users\US\AppData\Roaming\calibre\plugins\DeDRM.zip\kindlekey.py", line 458, in getDBfromFile
UnboundLocalError: local variable 'version' referenced before assignment
```
