### ISSUE TITLE
DeDRM not working on azw3 files downloaded from Amazon

### ISSUE THREAD

**Issue by leebirdy** [noDRM/DeDRM_tools#387]
### Question / bug report

I downloaded one of my Kindle books directly from Amazon's content management area (so don't think Kindle software applies). It downloaded as an azw3 file. But importing to calibre doesn't remove the DRM. When I try to convert the azw3 file to epub, I get a message that it can't convert the book because it's locked by DRM. I tried first with v10.0.3 of the plugin then updated to 10.0.9. Neither works. 

### Which version of Calibre are you running?

6.24.0

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
Using calibre Qt style: True
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.svg: Cannot open file '/Users/melinda/Library/Preferences/calibre/resources/images/WordDumb/starfish.svg', because: No such file or directory
qt.svg: Cannot open file '/Users/melinda/Library/Preferences/calibre/resources/images/WordDumb/starfish.svg', because: No such file or directory
qt.svg: Cannot open file ':/icons/calibre-default-light/images/WordDumb/starfish.svg', because: No such file or directory
qt.svg: Cannot open file ':/icons/calibre-default-light/images/WordDumb/starfish.svg', because: No such file or directory
calibre Debug log
calibre 6.24  embedded-python: True
macOS-13.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020')
Python 3.10.1
OSX: ('13.5', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 3, 0) && BookFusion Plugin (0, 8, 1) && Category Tags (0, 2, 8) && Find Duplicates (1, 10, 8) && Generate Cover (2, 3, 2) && Goodreads (1, 7, 9) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0) && Set KFX metadata (from KFX Output) (2, 2, 0) && KFX Output (2, 2, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && Manage Series (1, 5, 1) && Mass Search-Replace (1, 7, 3) && Open With (1, 8, 1) && Quality Check (1, 13, 6) && Reading List (1, 15, 1) && View Manager (1, 10, 2) && WordDumb (3, 29, 5)
calibre 6.24  embedded-python: True
macOS-13.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020')
Python 3.10.1
OSX: ('13.5', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 3, 0) && BookFusion Plugin (0, 8, 1) && Category Tags (0, 2, 8) && Find Duplicates (1, 10, 8) && Generate Cover (2, 3, 2) && Goodreads (1, 7, 9) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0) && Set KFX metadata (from KFX Output) (2, 2, 0) && KFX Output (2, 2, 0) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && Manage Series (1, 5, 1) && Mass Search-Replace (1, 7, 3) && Open With (1, 8, 1) && Quality Check (1, 13, 6) && Reading List (1, 15, 1) && View Manager (1, 10, 2) && WordDumb (3, 29, 5)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
Category Tags: User Categories: Import User Catetories: running on_modules_update()
Category Tags: User Categories: Export User Catetories: running on_modules_update()
DEBUG MassSearchReplace: Rebuilding menu
[0.90] main UI initialized...
[0.90] Hiding splash screen
Starting QuickView
2023-08-13 11:35:57.839 calibre-debug[94349:10840181] +[CATransaction synchronize] called within transaction
DeDRM v10.0.9: Trying to decrypt Mother Earth Mythology.azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mother Earth Mythology
Found 2 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
Found k4Mac kinf2018 file: /Users/melinda/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying username  b'melinda'  on file  /Users/melinda/Library/Containers/com.amazon.Kindle/Data/Library/Application Support/Kindle/storage/.kinf2018
trying IDString: b'ff42934bb7da'
trying IDString: b'ff42934bb725'
trying IDString: b'ff42934bb724'
trying IDString: b'932cb1004525'
trying IDString: b'f94cbb4d2abc'
Decrypted key file using IDString 'f94cbb4d2abc' and UserName 'melinda'
DeDRM v10.0.9: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Mother Earth Mythology
Got DSN key from database key_0
Found 4 keys to try after 0.8 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/melinda/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/melinda/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,newkeys.items(),[],[],[],self.starttime)
  File "/Users/melinda/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/melinda/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/melinda/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/melinda/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[19.95] splash screen hidden
[19.95] Started up in 19.95 seconds with 4020 books
Added Mother Earth Mythology to db in: 0.0
Added 1 books in 1.1 seconds
```

**Comment by ElleKayEm** [comment]
Did you choose an E-ink Kindle (not a Fire) when downloading?  If so, make sure you have that Kindle's serial number correctly entered into DeDRM's customization.

**Comment by leebirdy** [comment]
Thanks so much! I recently purchased a new Kindle. Had no idea that would impact downloads from Amazon. I added its serial into DeDRM and it's working now.

**Comment by ElleKayEm** [comment]
Yup, each device/app has a different key even if they're on the same account.  If you're all set, you can close the issue.
