### ISSUE TITLE
plug in download help

### ISSUE THREAD

**Issue by myrabentley** [noDRM/DeDRM_tools#391]
### Question / bug report

sorry this is my first time using Calibre and trying to remove a DRM but I keep getting this error and I'm not sure what I should do. thank you for your help and sorry if I'm missing something really obvious 

### Which version of Calibre are you running?

6.25.0

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Paste log output here.
```calibre, version 6.25.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'C:\\Users\\mbentley\\Downloads\\DeDRM_tools_10.0.3 (1).zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.25  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 325, in add_plugin
  File "calibre\customize\ui.py", line 513, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 298, in load
  File "calibre\customize\zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'C:\\Users\\mbentley\\Downloads\\DeDRM_tools_10.0.3 (1).zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Unzip DeDRM_tools_10.0.3.zip and load DeDRM_plugin.zip into calibre.

**Comment by myrabentley** [comment]
Thank you! that worked. i still cant convert a Kindle book to a PDF though. i googled it and it says as of this year it's not possible to do it anymore. is that true?

**Comment by ElleKayEm** [comment]
Sounds like DRM wasn't removed then.  In most cases, it should be possible.  Easiest solution is probably updating to pre-release version 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
