### ISSUE TITLE
Still having problems with the new DRM protection

### ISSUE THREAD

**Issue by aptekaria** [noDRM/DeDRM_tools#392]
### Question / bug report

After update of Calibre to the latest version and update of the plugin form your rep it's still unable to remove the new DRM protection from Amzn. The book was downloaded by the newer version of Kindle, because older versions do not allow download.

### Which version of Calibre are you running?

6.25.0

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

1.26

### Log output

```log
Paste log output here.
```ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Дебъг регистър
calibre 6.25  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: bg
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 3, 0) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0) && Obok DeDRM (10, 0, 3)
calibre 6.25  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: bg
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 3, 0) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.08521739130434 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.01] main UI initialized...
[1.01] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.3.0: Importing C:\Users\Mitko\Documents\My Kindle Content\B0C12FTHK8_EBOK\B0C12FTHK8_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 3 file(s) as C:\Users\Mitko\AppData\Local\Temp\calibre_anf9v3lm\kgo7uzl1.kfx-zip
DeDRM v10.0.3: Trying to decrypt kgo7uzl1.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: kgo7uzl1
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.45304ba6-9154-4df0-982a-0a7b5d20bf10.voucher
Traceback (most recent call last):
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Mitko\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Mitko\AppData\Local\Amazon\Kindle\storage\.kinf2018
[9.95] splash screen hidden
[9.95] Started up in 9.95 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xf2f\xd7\x86\xf2\xa7~\xe6\x064\xd4\xbbK\x85\xc2\x8c\xb1c\x13d\x93G5\x1f\x18t#\xa2\xf7\xd5\xea\x9e', b'C:\\Users\\Mitko\\Documents\\My Kindle Content\\B0C12FTHK8_EBOK\\B0C12FTHK8_EBOK.azw']
Decrypted key file using IDString '1623864998' and UserName 'Mitko'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: kgo7uzl1
Got DSN key from database key_0
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.45304ba6-9154-4df0-982a-0a7b5d20bf10.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.3.0: Packaging C:\Users\Mitko\AppData\Local\Temp\calibre_anf9v3lm\kgo7uzl1.kfx-zip
Processing container: B0C12FTHK8_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0C12FTHK8_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Mitko\AppData\Local\Temp\calibre_anf9v3lm\0wcuw40o_add_books\0\B0C12FTHK8_EBOK.kfx-zip
Added Red Company: First Strike! to db in: 0.2
Added 1 books in 1.4 seconds
Worker Launch took: 0.02 seconds
Job: 0 Конвертиране на книга 1 от 1 (Red Company: First Strike!) finished
Конвертиране на книга 1 от 1 (Red Company: First Strike!)

	DeDRM v10.0.3: Trying to decrypt qbr1pjos.kfx-zip
	Using Library AlfCrypto DLL/DYLIB/SO
	Decrypting KFX-ZIP ebook: qbr1pjos
	Found 1 keys to try after 0.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.45304ba6-9154-4df0-982a-0a7b5d20bf10.voucher
	Traceback (most recent call last):
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
	searching for kinfoFiles in C:\Users\Mitko\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Mitko\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '1623864998' and UserName 'Mitko'
	DeDRM v10.0.3: Found 1 new key
	Decrypting KFX-ZIP ebook: qbr1pjos
	Got DSN key from database key_0
	Found 1 keys to try after 0.3 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.45304ba6-9154-4df0-982a-0a7b5d20bf10.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt

	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook

	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook

	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1056, in run

	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  cover: 'C:\\Users\\Mitko\\AppData\\Local\\Temp\\calibre_anf9v3lm\\7pxf8fgb.jpeg'

	  verbose: 2

	  read_metadata_from_opf: 'C:\\Users\\Mitko\\AppData\\Local\\Temp\\calibre_anf9v3lm\\0kycg2ea.opf'

	Resolved conversion options

	calibre version: 6.25.0

	{'allow_conversion_with_errors': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': 'C:\\Users\\Mitko\\AppData\\Local\\Temp\\calibre_anf9v3lm\\7pxf8fgb.jpeg',

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_max_image_size': 'none',

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001FD9D4D4130>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x000001FD9D4D4400>,

	 'page_breaks_before': '/',

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Mitko\\AppData\\Local\\Temp\\calibre_anf9v3lm\\0kycg2ea.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	DeDRM v10.0.3: Trying to decrypt qbr1pjos.kfx-zip
	Decrypting KFX-ZIP ebook: qbr1pjos
	Found 1 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.45304ba6-9154-4df0-982a-0a7b5d20bf10.voucher
	Traceback (most recent call last):
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
	Exception: Incorrect padding - Wrong key
	DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\Mitko\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\Mitko\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '1623864998' and UserName 'Mitko'
	DeDRM v10.0.3: Found 1 new key
	Decrypting KFX-ZIP ebook: qbr1pjos
	Got DSN key from database key_0
	Found 1 keys to try after 0.2 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.45304ba6-9154-4df0-982a-0a7b5d20bf10.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
	Exception: Incorrect padding - Wrong key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt

	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook

	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook

	  File "C:\Users\Mitko\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher

	Exception: Failed to decrypt KFX DRM voucher with any key

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1056, in run

	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: KFX Input running

	on C:\Users\Mitko\AppData\Local\Temp\calibre_anf9v3lm\qbr1pjos.kfx-zip

	Software versions: KFX Input 2.3.0, calibre 6.25, Windows-10-10.0.19045-SP0

	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290

	Converting C:\Users\Mitko\AppData\Local\Temp\calibre_anf9v3lm\qbr1pjos.kfx-zip

	Processing container: B0C12FTHK8_EBOK.azw

	Traceback (most recent call last):

	  File "calibre_plugins.kfx_input.__init__", line 101, in convert

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book

	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container

	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0C12FTHK8_EBOK.azw has DRM and cannot be converted

	

	During handling of the above exception, another exception occurred:

	

	Traceback (most recent call last):

	  File "runpy.py", line 196, in _run_module_as_main

	  File "runpy.py", line 86, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1108, in run

	  File "calibre\customize\conversion.py", line 242, in __call__

	  File "calibre_plugins.kfx_input.__init__", line 121, in convert

	calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
You need pre-release 10.0.9 for that: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by aptekaria** [comment]
Thanks! This works!
