### ISSUE TITLE
ISSUE WITH DeDRM

### ISSUE THREAD

**Issue by ccuesta96** [noDRM/DeDRM_tools#393]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Registro de depuración
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 3, 0) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0)
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 3, 0) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0)
QPA platform: windows
devicePixelRatio: 1.1979166666666667
logicalDpi: 96.0 x 96.0
physicalDpi: 131.76763754045308 x 131.6712643678161
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[0.62] main UI initialized...
[0.62] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.3.0: Importing C:\Users\charl\OneDrive\Documentos\My Kindle Content\B0BR678C62_EBOK\B0BR678C62_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\charl\AppData\Local\Temp\calibre_d10w_j49\s7bv4xj5.kfx-zip
DeDRM v10.0.3: Trying to decrypt s7bv4xj5.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: s7bv4xj5
Got DSN key from database default_key_1693557433
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.1b20d27d-e4b0-4cc5-ae5c-8302bd0d4ef8.voucher
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\charl\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\charl\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '651022468' and UserName 'charl'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.3.0: Packaging C:\Users\charl\AppData\Local\Temp\calibre_d10w_j49\s7bv4xj5.kfx-zip
Processing container: B0BR678C62_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0BR678C62_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\charl\AppData\Local\Temp\calibre_d10w_j49\183ujko4_add_books\0\B0BR678C62_EBOK.kfx-zip
[3.20] splash screen hidden
[3.20] Started up in 3.20 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"NJy95\x97\xc1\x1a>q\xf9 \xa1\xa1q\xa7\x91e\x88\xf7~\xf5\x9aP`(j'\xfb\xe0\x8d\xcf", b'C:\\Users\\charl\\OneDrive\\Documentos\\My Kindle Content\\B0BR678C62_EBOK\\B0BR678C62_EBOK.azw']
Added Convence sin abrir la boca (Spanish Added 1 books in 1.1 seconds

### Which version of Calibre are you running?

6.2.1

### Which version of the DeDRM plugin are you running?

v.10.0.3

### If applicable, which version of the Kindle software are you running?

2.0.0

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Registro de depuración
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 3, 0) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0)
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 3, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 3, 0) && KFX metadata reader (from KFX Input) (2, 3, 0) && KFX Input (2, 3, 0)
QPA platform: windows
devicePixelRatio: 1.1979166666666667
logicalDpi: 96.0 x 96.0
physicalDpi: 131.76763754045308 x 131.6712643678161
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
[0.62] main UI initialized...
[0.62] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.3.0: Importing C:\Users\charl\OneDrive\Documentos\My Kindle Content\B0BR678C62_EBOK\B0BR678C62_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\charl\AppData\Local\Temp\calibre_d10w_j49\s7bv4xj5.kfx-zip
DeDRM v10.0.3: Trying to decrypt s7bv4xj5.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: s7bv4xj5
Got DSN key from database default_key_1693557433
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.1b20d27d-e4b0-4cc5-ae5c-8302bd0d4ef8.voucher
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\charl\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\charl\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '651022468' and UserName 'charl'
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\charl\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.3.0: Packaging C:\Users\charl\AppData\Local\Temp\calibre_d10w_j49\s7bv4xj5.kfx-zip
Processing container: B0BR678C62_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 178, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0BR678C62_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\charl\AppData\Local\Temp\calibre_d10w_j49\183ujko4_add_books\0\B0BR678C62_EBOK.kfx-zip
[3.20] splash screen hidden
[3.20] Started up in 3.20 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"NJy95\x97\xc1\x1a>q\xf9 \xa1\xa1q\xa7\x91e\x88\xf7~\xf5\x9aP`(j'\xfb\xe0\x8d\xcf", b'C:\\Users\\charl\\OneDrive\\Documentos\\My Kindle Content\\B0BR678C62_EBOK\\B0BR678C62_EBOK.azw']
Added Convence sin abrir la boca (Spanish Added 1 books in 1.1 seconds
[tmp4_1a5ztw.txt](https://github.com/noDRM/DeDRM_tools/files/12496176/tmp4_1a5ztw.txt)
[tmp4_1a5ztw.txt](https://github.com/noDRM/DeDRM_tools/files/12496179/tmp4_1a5ztw.txt)

**Comment by ElleKayEm** [comment]
For KFX files, use pre-release DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by ccuesta96** [comment]
> For KFX files, use pre-release DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
Thank you very much it works

**Comment by ElleKayEm** [comment]
If  you're all set, you can close the issue.
