### ISSUE TITLE
DRM Not removed on upload - DeDRM blacklisted comment in log

### ISSUE THREAD

**Issue by lavieravissant** [noDRM/DeDRM_tools#395]
### Which version of Calibre are you running?

6.25

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
```Blacklisting the DeDRM plugin as it is too old and causes crashes
Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 6.25  embedded-python: True
macOS-12.6.5-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
calibre 6.25  embedded-python: True
macOS-12.6.5-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.6.5', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 129.00000193738563 x 129.00000193738563
[0.00] Starting up...
[0.03] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
[0.87] main UI initialized...
[0.87] Hiding splash screen
Starting QuickView
Blacklisting the DeDRM plugin as it is too old and causes crashes
[10.88] splash screen hidden
[10.88] Started up in 10.88 seconds with 8 books
Added Kingdom of Ash: 7 (Throne of Glass) to db in: 0.0
Added 1 books in 0.6 seconds
Blacklisting the DeDRM plugin as it is too old and causes crashes
Added Tower of Dawn: 6 (Throne of Glass) to db in: 0.0
Added 1 books in 0.6 seconds
Worker Launch took: 0.02 seconds
Job: 0 Convert book 1 of 1 (Tower of Dawn: 6 (Throne of Glass)) finished
Convert book 1 of 1 (Tower of Dawn: 6 (Throne of Glass))
	Blacklisting the DeDRM plugin as it is too old and causes crashes
	Conversion options changed from defaults:
	  read_metadata_from_opf: '/var/folders/x9/4lk6h33d0955njl7ttbdh2nw0000gn/C/calibre_6.25.0_tmp_jq5op7j8/7h3zickk.opf'
	  output_profile: 'generic_eink'
	  cover: '/var/folders/x9/4lk6h33d0955njl7ttbdh2nw0000gn/C/calibre_6.25.0_tmp_jq5op7j8/nph80js2.jpeg'
	  verbose: 2
	Resolved conversion options
	calibre version: 6.25.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/x9/4lk6h33d0955njl7ttbdh2nw0000gn/C/calibre_6.25.0_tmp_jq5op7j8/nph80js2.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_max_image_size': 'none',
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10f1b3550>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.GenericEink object at 0x10f1b3250>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/x9/4lk6h33d0955njl7ttbdh2nw0000gn/C/calibre_6.25.0_tmp_jq5op7j8/7h3zickk.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/x9/4lk6h33d0955njl7ttbdh2nw0000gn/C/calibre_6.25.0_tmp_jq5op7j8/towqyq_s.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 196, in _run_module_as_main
	  File "runpy.py", line 86, in _run_code
	  File "site.py", line 41, in <module>
	  File "site.py", line 37, in main
	  File "calibre/utils/ipc/worker.py", line 215, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
	  File "calibre/customize/conversion.py", line 242, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
	calibre.ebooks.DRMError: Tower of Dawn: 6 (Throne of Glass)

Worker Launch took: 0.03 seconds
Job: 1 Convert book 1 of 1 (Kingdom of Ash: 7 (Throne of Glass)) finished

**Comment by dreamlibrarian** [comment]
Might want to run against 10.0.9 and see if it behaves for you. https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9 - It's an RC, but seems stable, I just did a bulk conversion and it ran smoothly for me.

**Comment by ElleKayEm** [comment]
Log is showing DeDRM 7.2.1.  Update to 10.0.3 or 10.0.9.
