### ISSUE TITLE
FileOpen encryption 'FOPN_foweb' is unsupported.

### ISSUE THREAD

**Issue by wntrh0lm** [noDRM/DeDRM_tools#398]
### Question / bug report

Hi all,

First of all I have no real experience in programming, I did attempt to find another post on the topic but couldnt find anything. Of course, being a novice I might have just missed it so apologies if I did and this is a repeat question.

I have a PDF that I want to remove the DRM from and its using a FOPN_foweb encryption. The PDF is an Australian Standards document so its a little different to the usual ebook. Was hoping someone could point me to something that might resolve this? So I can remove the DRM protection? 

I have attached the log.

Thanks in advance

### Which version of Calibre are you running?

6.23

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
 calibre, version 6.26.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (AS 4431-2019)

Convert book 1 of 1 (AS 4431-2019)
DeDRM v10.0.3: Trying to decrypt losh_g13.pdf
DeDRM v10.0.3: losh_g13.pdf is a PDF ebook with encryption FOPN_foweb
DeDRM v10.0.3: FileOpen encryption 'FOPN_foweb' is unsupported.
DeDRM v10.0.3: Try the standalone script from the 'Tetrachroma_FileOpen_ineptpdf' folder in the Github repo.
DeDRM v10.0.3: Finished after 0.1 seconds
Conversion options changed from defaults:
  verbose: 2
  pdf_serif_family: 'Arial'
  read_metadata_from_opf: 'C:\\Users\\dylan\\AppData\\Local\\Temp\\calibre__hsypizj\\ovumusdu.opf'
  output_profile: 'generic_eink'
  pdf_mono_family: 'Courier New'
Resolved conversion options
calibre version: 6.26.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000025B34E47190>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x0000025B34E44F70>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier New',
 'pdf_mono_font_size': 16,
 'pdf_no_cover': False,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Helvetica',
 'pdf_serif_family': 'Arial',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\dylan\\AppData\\Local\\Temp\\calibre__hsypizj\\ovumusdu.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt losh_g13.pdf
DeDRM v10.0.3: losh_g13.pdf is a PDF ebook with encryption FOPN_foweb
DeDRM v10.0.3: FileOpen encryption 'FOPN_foweb' is unsupported.
DeDRM v10.0.3: Try the standalone script from the 'Tetrachroma_FileOpen_ineptpdf' folder in the Github repo.
DeDRM v10.0.3: Finished after 0.0 seconds
InputFormatPlugin: PDF Input running
on C:\Users\dylan\AppData\Local\Temp\calibre__hsypizj\losh_g13.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 51, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'FOPN_foweb' security handler
```

**Comment by ElleKayEm** [comment]
The plugin does not support this. But there is a [python script](https://github.com/noDRM/DeDRM_tools/tree/master/Other_Tools/Tetrachroma_FileOpen_ineptpdf) which works with it. Some discussion of it here: https://github.com/noDRM/DeDRM_tools/issues/157

(I don't have any experience using that myself.)
