### ISSUE TITLE
DeDRM non-fonctionnel Version Mac Ventura, Calibre 6.26, 

### ISSUE THREAD

**Issue by larfran** [noDRM/DeDRM_tools#401]
### Question / bug report

calibre, version 6.26.0
ERREUR : Exception non gérée: <b>InvalidPlugin</b>:The plugin in '/Users/tupgss/Downloads/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.26  embedded-python: True
macOS-13.4.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.5.0', 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.4.1', ('', '', ''), 'x86_64')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 5, 0) && Amazon.com Multiple Countries (1, 0, 0) && Barnes & Noble (1, 5, 2) && Clean Metadata (0, 0, 6) && EpubMerge (2, 16, 0) && Find Duplicates (1, 10, 8) && Generate Cover (2, 3, 3) && Goodreads (1, 7, 9) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Set KFX metadata (from KFX Output) (2, 3, 1) && KFX Output (2, 3, 1) && KePub Input (3, 6, 5) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 5) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 0) && KindleUnpack - The Plugin (0, 83, 1) && Kobo Books (1, 9, 2) && Kobo Utilities (2, 16, 10) && KoboTouchExtended (3, 6, 5) && Modify ePub (1, 8, 1) && Obok DeDRM (7, 2, 1) && Search The Internet (1, 10, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 513, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 298, in load
  File "calibre/customize/zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/tupgss/Downloads/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

### Which version of Calibre are you running?

6.26

### Which version of the DeDRM plugin are you running?

7.2.1

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
