### ISSUE TITLE
DeDRM failed: Failed to decrypt user key 

### ISSUE THREAD

**Issue by ThanatosDi** [noDRM/DeDRM_tools#405]
### Which version of Calibre are you running?

6.25

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre 偵錯記錄
calibre 6.25 Portable embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.25 Portable embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: zh_TW
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 87.13433835845896 x 87.08571428571427
[0.00] Starting up...
[0.00] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.45] db initialized
[0.45] Constructing main UI...
[1.05] main UI initialized...
[1.05] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt 不時輕聲地以俄語遮羞的鄰座艾莉同學 5.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: 不時輕聲地以俄語遮羞的鄰座艾莉同學 5.epub is a secure Adobe Adept ePub for UUID 2a053cbe-624e-42ac-83e8-bb861fc2064d
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "E:\Program\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\adobekey.py", line 347, in adeptkeys
  File "E:\Program\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\adobekey.py", line 327, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[157.33] splash screen hidden
[157.33] Started up in 157.33 seconds with 251 books
Added 不時輕聲地以俄語遮羞的鄰座艾莉同學 5 to db in: 1.1
Added 1 books in 1.7 seconds

```

**Comment by ElleKayEm** [comment]
Was this book downloaded with ADE located on the same computer and user where calibre/DeDRM is installed?

**Comment by ThanatosDi** [comment]
> Was this book downloaded with ADE located on the same computer and user where calibre/DeDRM is installed?

yes, then I found this issue [#1938](https://github.com/apprenticeharper/DeDRM_tools/issues/1938)

So, I do these steps.

1. Install DeASCM
2. Use ADE and login user
3. Check `control userpasswords2` username and Adobe device username at regedit, then I can't found Adobe device username at regedit
![image](https://github.com/noDRM/DeDRM_tools/assets/12424898/6945a8bb-a80d-4d8c-aa44-dc41d98b6f93)
4. Use DeASCM plugin login AdobeID and export account encryption key
5. Use DeDRM plugin import the account encryption key at `Adobe Digital Editions ebooks`
6. Reimport epub file.
7. success

**Comment by ElleKayEm** [comment]
Thanks for reporting back with your workaround.
