### ISSUE TITLE
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.

### ISSUE THREAD

**Issue by SniperXKiller** [noDRM/DeDRM_tools#407]
### Which version of Calibre are you running?

6.27

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

Idk if this is the right info but it says firmware version is Kindle 5.16.2.1.1

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.27  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0)
calibre 6.27  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 101.07357512953367
[0.00] Starting up...
[0.00] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
[2.48] main UI initialized...
[2.48] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt The Novice Summoner Book One The-asin_B00OFKKDLW-type_EBOK-v_0.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: The Novice: Summoner: Book One (The Summoner Trilogy 1)
Found 2 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\Username\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Username\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Username\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[13.61] splash screen hidden
[13.61] Started up in 13.61 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x15\x9b\xc5\xefe\xb0\x01{\x81\x92\x7f\xf1\xd1\xbd.\xc4\xb5\xb4\xd1\x04\x93\xb1\xe2\xa9i\xb1\x18\xc5>\x81\x90\xa3', b'C:\\Users\\Username\\Desktop\\Kindle backup\\The Novice Summoner Book One The-asin_B00OFKKDLW-type_EBOK-v_0.azw3']

```

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM's customization.
