### ISSUE TITLE
No calibre plugin `DeDRM_plugin.zip` in a folder called `DeDRM_calibre_plugin` in the unzipped archive

### ISSUE THREAD

**Issue by chrisbamborough** [noDRM/DeDRM_tools#41]
Cloned and attempted to add plugin to calibre. As per the FAQs.md, I am unable to find the calibre plugin `DeDRM_plugin.zip` from a folder called `DeDRM_calibre_plugin` in the unzipped archive. 

I attempted to zip the 'DeDRM_plugin' plugin within the unzipped archive, but got the following message.

calibre, version 5.35.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/smthspce/Dropbox/Mac/Downloads/DeDRM_tools-master/DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.35  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 326, in add_plugin
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 283, in load
  File "calibre/customize/zipplugin.py", line 378, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/smthspce/Dropbox/Mac/Downloads/DeDRM_tools-master/DeDRM_plugin.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
Download the 10.0.2 release from here:  https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2
