### ISSUE TITLE
ACSM eBooks not opening

### ISSUE THREAD

**Issue by atinyteacup** [noDRM/DeDRM_tools#412]
### Question / bug report

Epubs showing as PDFs, not opening correctly. ACSM downloaded from ADE's test library and imported to Calibre with DeACSM. 

### Which version of Calibre are you running?

6.28.1

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
Traceback (most recent call last):
  File "calibre\customize\zipplugin.py", line 48, in get_resources
  File "zipfile.py", line 1464, in read
  File "zipfile.py", line 1503, in open
  File "zipfile.py", line 1430, in getinfo
KeyError: "There is no item named 'commit.txt' in the archive"
calibre Debug log
calibre 6.28.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Extract ISBN (1, 6, 0) && Extract RIS Citations (1, 0, 15) && Obok DeDRM (10, 0, 3) && OverDrive Libby (0, 1, 9) && Zotero Metadata Importer (1, 0, 78)
calibre 6.28.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Extract ISBN (1, 6, 0) && Extract RIS Citations (1, 0, 15) && Obok DeDRM (10, 0, 3) && OverDrive Libby (0, 1, 9) && Zotero Metadata Importer (1, 0, 78)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.6430769230769 x 133.90057803468207
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.58] main UI initialized...
[1.58] Hiding splash screen
Starting QuickView
[3.06] splash screen hidden
[3.06] Started up in 3.06 seconds with 24 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'+mSo?{~8N_\x7f\xb8\x94+Y\x03|\xae\xd7j\xacVY\x0f\xa9\x11\xc9V\xf3&b\xe5', b'C:\\Users\\meg\\Downloads\\URLLink.acsm']
DeDRM v10.0.3: Trying to decrypt y64yqz96.pdf
DeDRM v10.0.3: y64yqz96.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: y64yqz96.pdf is a PDF ebook (EBX) for UUID 43f121d8-5f85-433b-bc84-39b98d216951
DeACSM v0.0.16: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 486, in run
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 923, in PDFDecrypt
  File "calibre_plugins.dedrm.__init__", line 695, in PDFIneptDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
DeACSM v0.0.16: Trying to parse file URLLink.acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server https://contentserver.adobe.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from http://contentserver.adobe.com/media/2d3bea66-b956-454b-86a2-c46b4d4ab10b.pdf
Download took 4998 ms (HTTP 200)
That's a PDF file
DeACSM v0.0.16: Downloaded PDF, adding encryption config ...
Searching for startxref ...
Got startxref: 1286666
Found ENC after 5 attempts - took 0 ms
Found EBX after 1260 attempts - took 16 ms

Encryption handler:
<</Root 1220 0 R/Info 1167 0 R/Encrypt 1249 0 R/ID[<422F3A7D45358F4553750934A7651948><014692920C202E632865CE19E4FBEDAA>]/Size 1250>>
EBX handler:
<</Length 128/EBX_TITLE(Tony Hillerman E-Reader)/Filter/EBX_HANDLER/EBX_AUTHOR(Tony Hillerman)/V 4/ADEPT_ID(urn:uuid:2d3bea66-b956-454b-86a2-c46b4d4ab10b)>>
Trimmed encryption handler:
<</Root 1220 0 R/Info 1167 0 R/Encrypt 1249 0 R/ID[<422F3A7D45358F4553750934A7651948><014692920C202E632865CE19E4FBEDAA>]/Size 1250>>
Updated EBX handler not logged due to sensitive data
Whole DRM patching took 26 milliseconds.
DeACSM v0.0.16: File successfully fulfilled ...
DeACSM v0.0.16: Executing plugin DeDRM ...
DeACSM v0.0.16: Plugin returned nothing - skipping
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1
Traceback (most recent call last):
  File "calibre\gui2\open_with.py", line 98, in icon_for_entry
  File "calibre\utils\open_with\windows.py", line 72, in load_icon_resource
  File "calibre\utils\open_with\windows.py", line 41, in load_icon_resource_as_pixmap
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files (x86)\\Calibre2\\calibre.exe'
Traceback (most recent call last):
  File "calibre\gui2\open_with.py", line 98, in icon_for_entry
  File "calibre\utils\open_with\windows.py", line 72, in load_icon_resource
  File "calibre\utils\open_with\windows.py", line 41, in load_icon_resource_as_pixmap
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files (x86)\\Calibre2\\ebook-viewer.exe'
Traceback (most recent call last):
  File "calibre\gui2\open_with.py", line 98, in icon_for_entry
  File "calibre\utils\open_with\windows.py", line 72, in load_icon_resource
  File "calibre\utils\open_with\windows.py", line 42, in load_icon_resource_as_pixmap
IndexError: no resource found with index: 0 in handle: <Win32 handle of type HMODULE at: 0x0000000009830002 C:\WINDOWS\Installer\{AC76BA86-1033-1033-7760-BC15014EA700}\_PDFFile.ico>

**Comment by ElleKayEm** [comment]
Delete the saved Adobe key from DeDRM's customization and add the book again.  You can also update to DeDRM 10.0.9.  This bug should be fixed in that version.
