### ISSUE TITLE
AZW3 files not opening

### ISSUE THREAD

**Issue by zat1112** [noDRM/DeDRM_tools#413]
### Question / bug report

After installing Calibre and installing DeDRM, I am still unable to open my AZW3 files. Sorry if this is a commonly answered issue.

### Which version of Calibre are you running?

6.28.1

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.28.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 6.28.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 105.21682847896439 x 105.71098265895952
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[0.92] main UI initialized...
[0.92] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt Spa.azw3
[7.00] splash screen hidden
[7.00] Started up in 7.00 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'(t\xf9Y\x88\x0f\xc2\x80\x02E\xaf\x9a\xcd\xb2\x82\xb7\xfd\x15\t\xd5`B6\x01ww1g\x02\xec\xa5z', b'C:\\Users\\Zachary\\Downloads\\Erik Svetoft - Spa (2023, Fantagraphics) - libgen.li\\Spa.azw3']
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Spa
Found 0 keys to try after 2.0 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 2.0 seconds
searching for kinfoFiles in C:\Users\Zachary\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Zachary\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Zachary\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
```

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to enter the Kindle's serial number into DeDRM' customization.

**Comment by selfdocumentingcode** [comment]
If you have multiple Kindle devices, when you download the book files from Amazon you get the option to choose which device to download it for. 
I have 2 versions of Kindle Paperwhite: 7th and 11th generation. Even though I selected the new Kindle device for all the file downloads, I wasn't able to de-DRM the books that were purchased on my old device; it only worked on the books purchased on the new device, even with both serial numbers configured in the plugin. 
After downloading those files again, but by selecting the old device instead this time, I was able to de-DRM those too.

**Comment by ElleKayEm** [comment]
Never seen that happen.  But it is always a good idea to remove DRM as soon after purchase as possible and have some sort of backup.
