### ISSUE TITLE
DRM is not removed from book after Using DeDRM beta

### ISSUE THREAD

**Issue by UserPendslol** [noDRM/DeDRM_tools#419]
### Question / bug report

Hello, the DRM from a magazine was successfully removed, but the DRM from Oxford's dictionary was not. I was trying to read kindle books on my macbook air using calibre. I already installed the latest kfx plug in. The details are listed below. Thank you for reading.

### Which version of Calibre are you running?

6.29

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

e-ink paperwhite

### Log output

```log
Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 6.29  embedded-python: True
macOS-13.5.2-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.5.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (10, 0, 9)
calibre 6.29  embedded-python: True
macOS-13.5.2-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64')
Python 3.10.1
OSX: ('13.5.2', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
[0.00] Starting up...
[0.12] Showing splash screen...
[0.38] splash screen shown
[0.38] Initializing db...
[0.39] db initialized
[0.39] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.44] main UI initialized...
[1.44] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.5.0: Importing /Volumes/Kindle/documents/dictionaries/The_New_Oxford_American_Dictionary.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.9: Trying to decrypt The_New_Oxford_American_Dictionary.azw

{'bsd_drives': {'main': '/dev/disk8'},
 'drives': {'main': '/Volumes/Kindle'},
 'mount_map': {'/dev/disk1s1': '/System/Volumes/Update/mnt1',
               '/dev/disk1s1s1': '/',
               '/dev/disk1s2': '/System/Volumes/Data',
               '/dev/disk1s3': '/System/Volumes/Preboot',
               '/dev/disk1s5': '/System/Volumes/VM',
               '/dev/disk1s6': '/System/Volumes/Update',
               '/dev/disk2s1': '/Volumes/ProtonVPN',
               '/dev/disk3s1': '/Volumes/qBittorrent 4.5.5',
               '/dev/disk4s1': '/Volumes/UTM',
               '/dev/disk6s1': '/Volumes/calibre-6.29.0',
               '/dev/disk7s1': '/Volumes/VLC media player',
               '/dev/disk8': '/Volumes/Kindle',
               'devfs': '/dev',
               'map auto_home': '/System/Volumes/Data/home'}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: /Volumes/Kindle/ documents
DEBUG:    0.0 USBMS: scan from root False /Volumes/Kindle/documents
DEBUG:    0.0 USBMS: count found in cache: 7, count of files in metadata: 7, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 7
DeviceJob: set_books_in_library finished: time= 0.0050640106201171875
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
Job: 1 Set library information finished
No details available.
[85.04] splash screen hidden
[85.04] Started up in 85.04 seconds with 4 books
Job: 3 Prepare files for transfer from device started
DeviceJob: 3 Prepare files for transfer from device done, calling callback
DeviceJob: 3 Prepare files for transfer from device callback returned
Job: 3 Prepare files for transfer from device finished
No details available.
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 7 ebook: The New Oxford American Dictionary
Found 2 keys to try after 2.9 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 2.9 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "/Users/srouples/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/srouples/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
```

**Comment by ElleKayEm** [comment]
If this is the dictionary that comes pre-loaded on your Paperwhite, those can't be decrypted.  If not, then do you have your Paperwhite's serial number entered in DeDRM's customization?

**Comment by UserPendslol** [comment]
It was a preloaded dictionary. Thank you for letting me know.
