### ISSUE TITLE
Caibre 6.29 with DeDRM 10.09 does not recognize or read .kfx files on imported Kindle files

### ISSUE THREAD

**Issue by alh222** [noDRM/DeDRM_tools#421]
### Question / bug report

Am I doing something wrong, or are the latest .kfx formats simply ahead of current DeDRM?
Thanks

### Which version of Calibre are you running?

6.29

### Which version of the DeDRM plugin are you running?

10.09

### If applicable, which version of the Kindle software are you running?

1.40.1

### Log output

```log
Paste log output here.
```ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.29  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
calibre 6.29  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.96531791907513 x 94.07407407407408
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.80] main UI initialized...
[0.80] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt The Secret Hours_B0BP6VZLJG.kfx
Unknown booktype kfx. Passing back to calibre unchanged
Storage number map:
{(7, 0): [(2, 'C')],
 (7, 1): [(2, 'E')],
 (7, 2): [(2, 'G')],
 (7, 3): [(1, 'M')],
 (7, 4): [(1, 'F')],
 (7, 5): [(1, 'H')],
 (7, 6): [(1, 'I')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G8S0T613117302SG&0: StorageDeviceNumber(type=7, number=4, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=18)
{'drive_letters': ['F'],
 'pnp_id_map': {'F': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g8s0t613117302sg&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'F': (4, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Job: 0 Get device information started
DeviceJob: 0 Get device information done, calling callback
DeviceJob: 0 Get device information callback returned
Job: 1 Set library information started
DeviceJob: 1 Set library information done, calling callback
DeviceJob: 1 Set library information callback returned
Job: 2 Get list of books on device started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: F:\ documents
DEBUG:    0.0 USBMS: scan from root False F:\documents
DEBUG:    0.0 USBMS: count found in cache: 27, count of files in metadata: 27, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Get list of books on device done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 27
DeviceJob: set_books_in_library finished: time= 0.0040018558502197266
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Get list of books on device callback returned
Job: 0 Get device information finished
No details available.
Job: 1 Set library information finished
No details available.
Job: 2 Get list of books on device finished
No details available.
[95.12] splash screen hidden
[95.12] Started up in 95.12 seconds with 178 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe9 \xd9\xd9\x92\xa7\x8d\x81\x01?\xd7_\xa8m%\x08\xb16\x89dj#\x03\xfe\x8a\x94\x93\xda\xb1\x13\x1e\xf0', b'F:\\documents\\Downloads\\Items01\\The Secret Hours_B0BP6VZLJG.kfx']
Traceback (most recent call last):
  File "calibre\devices\kindle\driver.py", line 577, in delete_single_book
  File "calibre\devices\kindle\driver.py", line 513, in thumbpath_from_filepath
  File "calibre\ebooks\mobi\reader\headers.py", line 293, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 321, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x81\xc4\xde\x02\x9d\x8c#\x01'

**Comment by ElleKayEm** [comment]
Install the KFX Input plugin.  Is that from an E-ink Kindle?  Do you have its serial number in DeDRM's customization?

**Comment by alh222** [comment]
Did have the serial number entered under DeDRM plug-in customization, and installing the separate KFX input plug-in did the trick.  Thanks!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by alh222** [comment]
appreciate the speedy expertise of ElleKayEm
