### ISSUE TITLE
New book does not open

### ISSUE THREAD

**Issue by fyrehearted** [noDRM/DeDRM_tools#426]
Calibre version: 6.27
deDRM version: 10.0.9
Kindle for PC version: 2.1.0
The book does not open.

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.27  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 6.27  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 126.04011627906975 x 125.69072164948453
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[0.64] main UI initialized...
[0.64] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt B0CH5Q4WZT_EBOK.azw
DeDRM v10.0.9: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Climb\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Climb\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2923976650' and UserName 'Climb'
DeDRM v10.0.9: Found 1 new key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Climb\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\Climb\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Climb\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[4.42] splash screen hidden
[4.42] Started up in 4.42 seconds with 4 books
stdout+stderr from file dialog helper: [b'', b'']
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x8c8\x1a\xda\x08\xf00e9\xf7g7\xba\x0c^\x11\xe3\xe5\xf0\xfe\xeb\xf5]\xa1\xf8\x1d\x8b\x02\xea\x98\nv', b'C:\\Users\\Climb\\OneDrive\\Documents\\My Kindle Content\\B0CH5Q4WZT_EBOK']
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 266, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 503, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 293, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 321, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x81\xc4\xde\x02\x9d\x8c#\x01'

**Comment by ElleKayEm** [comment]
You need the KFX Input plugin: https://www.mobileread.com/forums/showthread.php?t=291290
