### ISSUE TITLE
DRM not getting removed from books

### ISSUE THREAD

**Issue by mtjohnson47** [noDRM/DeDRM_tools#434]
### Question / bug report

I saw that KFX DRM removal was working now, but I can't get it to work.  It seems to be failing to parse the key?  "Electronics Fundamentals" was downloaded using version 2.2 of the Kindle app, the other two which I just included to get you more data were downloaded months ago using an older version.

### Which version of Calibre are you running?

7.0

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

2.2

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.0  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (10, 0, 9)
calibre 7.0  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 5, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 5, 0) && KFX metadata reader (from KFX Input) (2, 5, 0) && KFX Input (2, 5, 0) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.7148288973384 x 92.67567567567568
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.62] main UI initialized...
[0.62] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.5.0: Importing C:/Users/michael/OneDrive/Documents/My Kindle Content/B08QMPZMX1_EBOK/B08QMPZMX1_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\michael\AppData\Local\Temp\calibre_aw186089\060faaol.kfx-zip
DeDRM v10.0.9: Trying to decrypt 060faaol.kfx-zip
Decrypting KFX-ZIP ebook: 060faaol
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.27243a46-2e31-4651-955c-a932f2e9171f.voucher
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\michael\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\michael\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '812689861' and UserName 'michael'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: 060faaol
Got DSN key from database key_0
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.27243a46-2e31-4651-955c-a932f2e9171f.voucher
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.5.0: Packaging C:\Users\michael\AppData\Local\Temp\calibre_aw186089\060faaol.kfx-zip
Processing container: B08QMPZMX1_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08QMPZMX1_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\michael\AppData\Local\Temp\calibre_aw186089\ojv76ay6_add_books\0\B08QMPZMX1_EBOK.kfx-zip
[3.52] splash screen hidden
[3.52] Started up in 3.52 seconds with 1 books
Added George Orwell. The Complete Works (Illustrated): Animal Farm, Nineteen Eighty-Four, The Memoirs, Down and Out in Paris and London to db in: 0.1
Added 1 books in 1.0 seconds
Gather KFX-ZIP (from KFX Input) 2.5.0: Importing C:/Users/michael/OneDrive/Documents/My Kindle Content/B08S762M15_EBOK/B08S762M15_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 43 file(s) as C:\Users\michael\AppData\Local\Temp\calibre_aw186089\5jnepbt3.kfx-zip
DeDRM v10.0.9: Trying to decrypt 5jnepbt3.kfx-zip
Decrypting KFX-ZIP ebook: 5jnepbt3
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.6b486e26-70c7-43ef-8f7f-78c43186ee22.voucher
Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1394, in parse
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 103, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1394, in parse
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 103, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\michael\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\michael\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '812689861' and UserName 'michael'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: 5jnepbt3
Got DSN key from database key_0
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.6b486e26-70c7-43ef-8f7f-78c43186ee22.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1394, in parse
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 103, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1394, in parse
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 103, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.5.0: Packaging C:\Users\michael\AppData\Local\Temp\calibre_aw186089\5jnepbt3.kfx-zip
Processing container: B08S762M15_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08S762M15_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\michael\AppData\Local\Temp\calibre_aw186089\cc9g7wen_add_books\0\B08S762M15_EBOK.kfx-zip
Gather KFX-ZIP (from KFX Input) 2.5.0: Importing C:/Users/michael/OneDrive/Documents/My Kindle Content/B013V6OUBY_EBOK/B013V6OUBY_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\michael\AppData\Local\Temp\calibre_aw186089\fx8m1sox.kfx-zip
DeDRM v10.0.9: Trying to decrypt fx8m1sox.kfx-zip
Decrypting KFX-ZIP ebook: fx8m1sox
Found 1 keys to try after 0.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.3305e926-9ce0-444c-8f56-13f000561ba4.voucher
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\michael\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\michael\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '812689861' and UserName 'michael'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: fx8m1sox
Got DSN key from database key_0
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.3305e926-9ce0-444c-8f56-13f000561ba4.voucher
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1368, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\michael\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.5.0: Packaging C:\Users\michael\AppData\Local\Temp\calibre_aw186089\fx8m1sox.kfx-zip
Processing container: B013V6OUBY_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B013V6OUBY_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\michael\AppData\Local\Temp\calibre_aw186089\y1twxxig_add_books\0\B013V6OUBY_EBOK.kfx-zip
Added Electronics Fundamentals to db in: 0.1
Added 1 books in 1.4 seconds
Added Out of Darkness to db in: 0.1
Added 1 books in 0.9 seconds

```

**Comment by ElleKayEm** [comment]
Were the books downloaded with the current installment of Kindle for PC located on the same computer and Windows user as calibre/DeDRM?

**Comment by mtjohnson47** [comment]
> Were the books downloaded with the current installment of Kindle for PC located on the same computer and Windows user as calibre/DeDRM?

The textbook was, the other two were not.

**Comment by j-howell** [comment]
> The textbook was, the other two were not.

Each instance of Kindle for PC has its own encryption key even if it is registered to the same Amazon account. So it is expected that books copied from elsewhere cannot be decrypted.

Most books downloaded to the current version of Kindle for PC can be decrypted. There are a few cases where decryption is not possible due to different, stronger encryption. Pearson textbooks is one of those cases. Amazon only delivers them to applications for which there is no known DRM removal method.
