### ISSUE TITLE
Not able to remove DRM of Adobe Digital

### ISSUE THREAD

**Issue by steve2379** [noDRM/DeDRM_tools#446]
### Question / bug report

I tried with a few different ebooks, but none of them worked. Any help is much appreciated!

### Which version of Calibre are you running?

7.1

### Which version of the DeDRM plugin are you running?

10.0.9

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.1  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 3)
calibre 7.1  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 157.8252427184466 x 157.65517241379308
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.75] main UI initialized...
[0.75] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt Modern Compressible Flow-2.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Modern Compressible Flow-2.epub is a secure Adobe Adept ePub for UUID 79fe5965-8ca2-455b-9021-eef5ef211ef1
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.5 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.5 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\TilRe\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 293, in adeptkeys
  File "C:\Users\TilRe\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 273, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[15.41] splash screen hidden
[15.41] Started up in 15.41 seconds with 29 books
Added Modern Compressible Flow to db in: 0.1
Added 1 books in 1.0 seconds

```

**Comment by Stuigong** [comment]
Same here! 
Would be nice if i get some help here... PLS

**Comment by ElleKayEm** [comment]
You have ADE used to download the book on the same machine and user as calibre/DeDRM?

**Comment by steve2379** [comment]
> You have ADE used to download the book on the same machine and user as calibre/DeDRM?

Yes, I download a .acsm file, open it in ADE o the same machine, got to the filepath where ADE saves the .epub file and import this into Calibre (all on the same machine)

**Comment by ThanatosDi** [comment]
try this https://github.com/noDRM/DeDRM_tools/issues/405#issuecomment-1732593861

**Comment by ElleKayEm** [comment]
Is this a new installation of calibre 7?  I wonder if there might be an issue there.  If so, you could try uninstalling calibre 7.1...your library, plugins, and settings will remain.  Then install calibre 6.29 and try importing the book again.  If successful, you'd be safe to update back to calibre 7.1.

**Comment by steve2379** [comment]
> try this [#405 (comment)](https://github.com/noDRM/DeDRM_tools/issues/405#issuecomment-1732593861)

This worked for me. Thank you so much for your help!

**Comment by ThanatosDi** [comment]
> Still wonder why DeDRM didn't retrieve the key on its own.

I guess it cause by windows account, maybe we can try to reinstall windows and start by offline account

**Comment by ElleKayEm** [comment]
My experience has always been that if ADE used to download the book is on the same machine and user as calibre/DeDRM, it works.  No need for DeACSM unless you don't want to install ADE.  So I don't know what is different in these cases.
