### ISSUE TITLE
Obook Error

### ISSUE THREAD

**Issue by yasinvs** [noDRM/DeDRM_tools#447]
### Question / bug report

calibre, version 6.29.0
HATA: İşlenmeyen istisna: <b>ConstraintError</b>:ConstraintError: UNIQUE constraint failed: authors.name

calibre 6.29 Portable embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.10.1
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: tr
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.dialogs", line 266, in do_book_action
  File "calibre_plugins.obok_dedrm.action", line 243, in add_new_books
  File "calibre\db\cache.py", line 2051, in add_books
  File "calibre\db\cache.py", line 85, in call_func_with_lock
  File "calibre\db\cache.py", line 2017, in create_book_entry
  File "calibre\db\cache.py", line 1700, in set_metadata
  File "calibre\db\cache.py", line 1686, in set_field
  File "calibre\db\cache.py", line 1499, in set_field
  File "calibre\db\write.py", line 570, in set_books
  File "calibre\db\write.py", line 425, in many_many
  File "calibre\db\write.py", line 288, in get_db_id
  File "calibre\db\backend.py", line 1037, in execute
apsw.ConstraintError: ConstraintError: UNIQUE constraint failed: authors.name

### Which version of Calibre are you running?

6.29

### Which version of the DeDRM plugin are you running?

10.1.0

### Log output

```log
calibre, version 6.29.0
HATA: İşlenmeyen istisna: <b>ConstraintError</b>:ConstraintError: UNIQUE constraint failed: authors.name

calibre 6.29 Portable embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.10.1
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: tr
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.dialogs", line 266, in do_book_action
  File "calibre_plugins.obok_dedrm.action", line 243, in add_new_books
  File "calibre\db\cache.py", line 2051, in add_books
  File "calibre\db\cache.py", line 85, in call_func_with_lock
  File "calibre\db\cache.py", line 2017, in create_book_entry
  File "calibre\db\cache.py", line 1700, in set_metadata
  File "calibre\db\cache.py", line 1686, in set_field
  File "calibre\db\cache.py", line 1499, in set_field
  File "calibre\db\write.py", line 570, in set_books
  File "calibre\db\write.py", line 425, in many_many
  File "calibre\db\write.py", line 288, in get_db_id
  File "calibre\db\backend.py", line 1037, in execute
apsw.ConstraintError: ConstraintError: UNIQUE constraint failed: authors.name

```

**Comment by ElleKayEm** [comment]
What exactly happened?
