### ISSUE TITLE
DeDRM can not be installed on new Mac with Sonoma 14.1.2, DeACSM 0.0.16 is okay there. 

### ISSUE THREAD

**Issue by gsgxnet** [noDRM/DeDRM_tools#449]
I have an installed Calibre 6.29. Tried to install DeDRM. With 10.0.3 when trying to install the plugin into Calibre, I get an error message:
```
calibre, version 6.29.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/Shared/A/DL/Calibre/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file

calibre 6.29  embedded-python: True
macOS-14.1.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.1.0', 'Darwin Kernel Version 23.1.0: Mon Oct  9 21:33:00 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6031')
Python 3.10.1
OSX: ('14.1.2', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 16)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 513, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 298, in load
  File "calibre/customize/zipplugin.py", line 393, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/Shared/A/DL/Calibre/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file
```

same missing `__init.py__` with 1.0.9 and with the current alpha.  

Tried also with calibre 7.1.0. Same error.

**Comment by ElleKayEm** [comment]
You're trying to install the whole archive which contains both plugins and the readme files.   Unzip it and load DeDRM_plugin.zip into calibre.  Recommend using 10.0.9.

**Comment by gsgxnet** [comment]
sorry for that mistake. closed
