### ISSUE TITLE
Trying to remove the DRM from a kindle book and convert it

### ISSUE THREAD

**Issue by DaLeSy** [noDRM/DeDRM_tools#455]
### Question / bug report

I've never done this before and I didn't have any of these programs before so I just downloaded them yesterday (Kindle for PC, Calibre, DRM removal Plugin, and KFX input plugin).

So I found the folder where the kindle for PC put my kindle book.  I opened it in Calibre.  It wouldn't convert to anything because of DRM.  So I downloaded this DRM removal plugin and added it to Calibre.  Then it wouldn't convert because of KFX.  So I read that I need to install the KFX input plugin.  I restarted Calibre.  Added the book back in.  And now when I try to convert it, it says it can't because of DRM again.  Not sure what is going on.  

ElleKayEm said this in someone else's post/issue:

"If the book is from or for an E-ink Kindle (not a Fire), then make sure you enter that Kindle's serial number correctly into DeDRM's customization."  
After reading that, I added in my kindle serial number to DRM plugin, but I'm still getting blocked, now by DRM again.  

### Which version of Calibre are you running?

7.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

2.2.0   Kindle for PC 4

### Log output

```log
Paste log output here.
```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 6, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 6, 0) && KFX metadata reader (from KFX Input) (2, 6, 0) && KFX Input (2, 6, 0)
calibre 7.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 6, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 6, 0) && KFX metadata reader (from KFX Input) (2, 6, 0) && KFX Input (2, 6, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 91.73814898419865 x 91.80722891566265
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.20] main UI initialized...
[1.20] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 2.6.0: Importing C:\Users\kurt2\Documents\My Kindle Content\B004GXAZXO_EBOK\B004GXAZXO_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\kurt2\AppData\Local\Temp\calibre_4m0zefsb\mmc2pq5f.kfx-zip
DeDRM v10.0.3: Trying to decrypt mmc2pq5f.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
[11.02] splash screen hidden
[11.02] Started up in 11.02 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xe9\xa8\x93 \xe6\x8e'iY\xae\x90I\x88w\x13d_\x1c\xbe\x05\xb1\xdb\x12\x80BLdA\xd3\xb6\xa4\xd8", b'C:\\Users\\kurt2\\Documents\\My Kindle Content\\B004GXAZXO_EBOK\\B004GXAZXO_EBOK.azw']
Decrypting KFX-ZIP ebook: mmc2pq5f
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.d45d5a9a-4560-43b8-b76a-721013f72e9e.voucher
Traceback (most recent call last):
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\kurt2\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\kurt2\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2398053341' and UserName 'kurt2'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: mmc2pq5f
Got DSN key from database key_0
Found 1 keys to try after 0.4 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.d45d5a9a-4560-43b8-b76a-721013f72e9e.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 886, in decryptvoucher
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 762, in pkcs7unpad
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\kurt2\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.6.0: Packaging C:\Users\kurt2\AppData\Local\Temp\calibre_4m0zefsb\mmc2pq5f.kfx-zip
Processing container: B004GXAZXO_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 222, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 331, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B004GXAZXO_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\kurt2\AppData\Local\Temp\calibre_4m0zefsb\f6yay88z_add_books\0\B004GXAZXO_EBOK.kfx-zip

**Comment by FoulFoot** [comment]
The DeDRM plugin doesn't work on the latest version of Amazon DRM.  Been that way for a few months now.

**Comment by ElleKayEm** [comment]
Use DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by FoulFoot** [comment]
Yep, tried all that.  No dice.  I've been using calibre and this plugin for many years but they no longer work.  At least on the two files I've tried in the last few months.

**Comment by ElleKayEm** [comment]
If you have DeDRM 10.0.9 and KFX Input, you can still decrypt most Amazon books.  Start your own issue and post a log and we'll take a look.

**Comment by FoulFoot** [comment]
In looking into this a little further, my guess is that calibre itself is blocking any conversion.  This is my log after attempting to convert:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.1  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 87.70489335006272 x 87.60718562874251
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[0.50] main UI initialized...
[0.50] Hiding splash screen
Starting QuickView

... no mention of the convert attempt at all, just the splash screen saying the file is DRM locked.  A little payment from Amazon (or a legal threat) could have caused the calibre author to implement this.  Just guessing of course.

**Comment by FoulFoot** [comment]
The input file is AZW, tied to my Kindle ID of course.

**Comment by ElleKayEm** [comment]
Install the KFX Input plugin: https://www.mobileread.com/forums/showthread.php?t=291290

**Comment by FoulFoot** [comment]
Yeah, same result.

Interestingly, calibre 7.2 was released literally a few minutes ago.  The download link isn't even working yet, but the program prompts you to update.  Suspicious timing.  :)

**Comment by ElleKayEm** [comment]
Works for me.  Let's see a log of adding the book to calibre.

**Comment by FoulFoot** [comment]
Added the book, then tried to covert it to MOBI.

Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 7.2  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 6, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 6, 0) && KFX metadata reader (from KFX Input) (2, 6, 0) && KFX Input (2, 6, 0)
calibre 7.2  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 6, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 6, 0) && KFX metadata reader (from KFX Input) (2, 6, 0) && KFX Input (2, 6, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 87.70489335006272 x 87.60718562874251
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
[0.58] main UI initialized...
[0.58] Hiding splash screen
[0.64] GUI main window shown
[0.67] QuickView starting
[0.67] QuickView started
DeDRM v10.0.9: Trying to decrypt Game Wizards (locked DRM).azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Game Wizards (Game Histories)
Found 2 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\Desktop\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Desktop\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\Desktop\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[3.66] Starting the smartdevice driver
[7.92] splash screen hidden
[7.92] Started up in 7.92 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b' \xe30\x9c\x97i\x1c\t"\x0e\x1a\xc6\xb5c\xa7\xc5I\xa6D\x1b\x1eEMNgQ!\x7f\xfc\x90:0', b'D:\\eBooks\\Peterson, Jon\\Game Wizards (locked DRM).azw3']
Added Game Wizards (Game Histories) to db in: 0.1
Added 1 books in 0.8 seconds

**Comment by FoulFoot** [comment]
And before you ask, the eBook is correctly linked to my Kindle, downloaded it directly from Amazon, and the Kindle serial is entered into the DeDRM plugin (just checked it again in case upgrading calibre deleted it, but it was still there).

**Comment by ElleKayEm** [comment]
An azw3 file isn't even the new DRM.  This book is tied to an E-ink Kindle, not a Fire?  You're sure you have that particular Kindle's serial number entered correctly into DeDRM?

**Comment by FoulFoot** [comment]
Yes, tied to a Kindle.  Triple-checked and re-entered the serial into DeDRM.  And as I mentioned, I've successfully used these tools for many years.  Just recently stopped working.

**Comment by jonathan2183** [comment]
I tried the online version of nodrm and it worked. You will need serial
number though.

**Comment by jonathan2183** [comment]
Dedrm.com

**Comment by FoulFoot** [comment]
That failed too.  No worries.  Maybe it's something on my side or a strange eBook.  Glad it's still working for others.

**Comment by jonathan2183** [comment]
It seems to be with books that don't say simultaneous devices I have found so far.

**Comment by DaLeSy** [comment]
> Use DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Thanks ElleKayEm.  While that did seem to convert the books, it seems like something is still wrong.  

I converted this book to an EPUB so that I can open it in my Firefox browser and use the Read Aloud extension to read the book out loud to me.  That was my reason for converting it.  But, for some reason the converted EPUB that opens in my browser with the help of EPUBreader extension, when it starts to read a chapter, it opens that chapter up in a little window and it doesn't show the same text for that chapter as it does in the browser, nor does it read the same text that the browser shows.  I tried this in multiple chapters and it always shows different text and reads different text for some reason.  Very odd, yet I can see all of the text is there in the EPUB that is open in my browser.  I even compared to the same book opened in Kindle for PC and the text is right.  Anybody know why the Read Aloud extension isn't seeing and reading it right?  

I also converted the book to PDF as Acrobat Reader can read things out loud too, although it only has one voice and no other voice options.  But, when it started reading the text, for some reason it started pausing oddly every few words.  Which was way too annoying and unnatural to listen to.  

I have used both Read Aloud and Acrobat Reader to read stuff out loud to me before and didn't have this problem.  I did have the problem on Amazon's Cloud Reader.  And when I contacted Read Aloud about it, they told me I would have to remove the DRM and convert it to EPUB for it to read it correctly like it does on other websites.  But now that I have done that, it still doesn't read it right, nor does Acrobat Reader.  Anybody know why?

**Comment by jonathan2183** [comment]
Some books come with frames along the edges. This stops text to speech from working. Calibre has a book viewer function, with text to speech. you can also add other voices to windows. with voice packs. you will need to updates windows. as they only come through windows up date. look for voice packs for windows. I use the uk one. and just change speed.

**Comment by jonathan2183** [comment]
Maybe try convert from epub to doc. Then open document. save as pdf and convert back to epub

**Comment by ElleKayEm** [comment]
@DaLeSy If your Kindle is E-ink (not a Fire), try getting the book from your content and devices page at Amazon with the "download & transfer via USB" option.  You will get a file in the older azw3 format.  That format is better for converting into epub then the kfx format you're getting with Kindle for PC.  Maybe that will work better with the text to speech.

@FoulFoot Try downloading again making sure you choose the right Kindle if you have more than one.  Try copy and pasting its serial number from the website into DeDRM.  Your log just shows that the key you have in there is the wrong one for that copy of the book.  That format has the same old DRM that we've been dealing with for years.

**Comment by DaLeSy** [comment]
**> Some books come with frames along the edges. This stops text to speech from working. Calibre has a book viewer function, with text to speech. you can also add other voices to windows.**

Yes that did work.  It had 4 voices options, three male voices and 1 female.  Which were the same "offline voices", not the premium ones, that Read Aloud uses - Auto, David, Mark, and Zira. 


**> Maybe try convert from epub to doc. Then open document. save as pdf and convert back to epub.**

I tried that, but there was no doc option in Calibre, so I instead tried docx.  Then I converted it to pdf.  And then epub.  When I opened it in Firefox with EPUBreader extension, again Read Aloud wasn't reading it right in its little window that it opens up.  But, when I highlight the text and right click and go to Read Aloud, then it does read it right.  It reads everything that I highlight right.  

Then I tried to open the other one I converted to epub in Firefox and see if it would work by highlighting the text.  And it worked too.  So I didn't really need to convert from epub to docx, to pdf, to epub.   You just have to highlight the text you want it to read first - at least with this Read Aloud extension.  


**> If your Kindle is E-ink (not a Fire), try getting the book from your content and devices page at Amazon with the "download & transfer via USB" option. You will get a file in the older azw3 format. That format is better for converting into epub then the kfx format you're getting with Kindle for PC. Maybe that will work better with the text to speech.**

That also did not read right with Read Aloud, until I highlighted the text and right clicked and went to Read Aloud in the pop up menu.  Same as with the other things I tried.  Apparently the only way to get them to read correctly in Read Aloud is if you are highlighting the text first and having it read that out loud.  If you don't want to highlight every page separately, you can change the book view layout at the bottom of the EPUBreader and highlight further and further sections as it scrolls.  Then have it read it.  Which is less convenient than saying "read this section or chapter", but that just doesn't seem to be an option with these two tools (Read Aloud and EpubReader extension).

I also tried it again in Kindle Cloud Reader in case anybody is curious.  This time I tried highlighting the text first and tried to get Read Aloud read it.  It just simply won't read it on Amazon's website.  It has to be downloaded, converted to epub and have the DRM removed.  And you might be right, maybe I wouldn't have needed the KFX input plugin if I had gone to content and devices and choose the "download and transfer via USB" option.  

Thanks Guys, I'm grateful for the help.  Glad I can sit back and listen to books being read to me now.  Maybe this post will help someone else too.

**Comment by ElleKayEm** [comment]
Well, since you can convert, the DeDRM is definitely removed so you can close this issue.
