### ISSUE TITLE
Not reming DRM. Calibre 6.29, DeDRM 10.0.3

### ISSUE THREAD

**Issue by Runisco** [noDRM/DeDRM_tools#456]
### Question / bug report

AFAIK nothing has changed from what worked for me before. I've tried re-extracting the key from an new adb backup, but for some reasons it's stopped removing DRM on some books

### Which version of Calibre are you running?

6.29

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

kindle on android 4.16.0.75 - bluestacks

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 6.29  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Kindle Collections (1, 7, 29)
calibre 6.29  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Kindle Collections (1, 7, 29)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[0.53] main UI initialized...
[0.53] Hiding splash screen
Starting QuickView
DeDRM v10.0.3: Trying to decrypt B0CLKYKQ1M_EBOK.prc
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: God-King of Empyrea: An Isekai Barbarian Fantasy Adventure (Empyrean Chronicles Book 4)
Found 8 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 8 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Username\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Username\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Username\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 8 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[7.58] splash screen hidden
[7.58] Started up in 7.58 seconds with 1167 books
Added God-King of Empyrea: An Isekai Barbarian Fantasy Adventure (Empyrean Chronicles Book 4) to db in: 0.4
Added 1 books in 0.6 seconds
```

**Comment by ElleKayEm** [comment]
Did you redownload the book as well?

**Comment by ElleKayEm** [comment]
How large is your backup file?

**Comment by Runisco** [comment]
> How large is your backup file?
My backup file is 6.8mb



> Did you redownload the book as well?
didn't work.

However, I decided to retry the entire thing again without redownloading either calibre or dedrm, and just use the versions I have. Then get the backup again, and the redownload the book again. I don't know where I made a mistake, but it seems to be working again.

**Comment by ElleKayEm** [comment]
Possible the key changed on you and books that appeared to work were already drm-free.  Glad it's working for you again.
