### ISSUE TITLE
issue with DRM in Calibre

### ISSUE THREAD

**Issue by Berzutti** [noDRM/DeDRM_tools#457]
Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Journal de débogage
calibre 7.2  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.2  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.00] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
[0.62] main UI initialized...
[0.62] Hiding splash screen
[0.66] GUI main window shown
[0.77] QuickView starting
[0.77] QuickView started
DeDRM v10.0.3: Trying to decrypt The New Oxford American Dictionary.azw
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 7 ebook: The New Oxford American Dictionary
Found 0 keys to try after 0.4 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.4 seconds
searching for kinfoFiles in C:\Users\gerar\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\gerar\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1854595164' and UserName 'gerar'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 7 ebook: The New Oxford American Dictionary
Got DSN key from database key_0
Found 4 keys to try after 0.9 seconds
Crypto Type is: 2
[3.67] Starting the smartdevice driver
SMART_DEV (   0.00:  0.000) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.03:  0.858) _startup_on_demand listening on port 9090
SMART_DEV (   1.06:  0.001) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.07:  0.000) _startup_on_demand broadcast socket listening on port 54982
[4.77] Finished starting smartdevice
Storage number map:
{(7, 0): [(3, 'C')], (7, 1): [(1, 'D')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0401\G000PP1310140KGV&0: StorageDeviceNumber(type=7, number=1, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x401 devid=usb\vid_1949&pid_0324&rev_0401 devinst=15)
{'drive_letters': ['D'],
 'pnp_id_map': {'D': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0401#g000pp1310140kgv&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'D': (1, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Lit les informations du périphérique started
DeviceJob: 0 Lit les informations du périphérique done, calling callback
DeviceJob: 0 Lit les informations du périphérique callback returned
Job: 1 Définir l'information de bibliothèque started
DeviceJob: 1 Définir l'information de bibliothèque done, calling callback
DeviceJob: 1 Définir l'information de bibliothèque callback returned
Job: 2 Lit la liste des livres à partir du périphérique connecté started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: D:\ documents
DEBUG:    0.0 USBMS: scan from root False D:\documents
SMART_DEV (   2.11:  1.020) run All IP addresses {'{33B101E0-0DDF-4B3D-B32C-9FF47ABB309B}': [{'addr': '192.168.1.18', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{EE7D6874-D5E8-11EB-AD89-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}], '{96D69E51-5529-47AF-9CCB-3C6F840301D3}': [{'addr': '172.20.96.1', 'netmask': '255.255.240.0', 'broadcast': '172.20.111.255'}]}
DEBUG:    0.2 USBMS: count found in cache: 129, count of files in metadata: 129, need_sync: False
DEBUG:    0.2 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.2 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Lit la liste des livres à partir du périphérique connecté done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 129
DeviceJob: set_books_in_library finished: time= 0.002549409866333008
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Lit la liste des livres à partir du périphérique connecté callback returned
Job: 0 Lit les informations du périphérique finished
Pas de détail disponible.
Job: 2 Lit la liste des livres à partir du périphérique connecté finished
Pas de détail disponible.
Job: 1 Définir l'information de bibliothèque finished
Pas de détail disponible.
[31.73] splash screen hidden
[31.73] Started up in 31.73 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x7f\xd6\xbc\\l\x92\xdf\x0c\xefM\x19\x1f\xe3\xc9\xa5\xe2+\xabE=8AY\x1b\xea\xc0l\x03\xa9\x18)b', b'C:\\Users\\gerar\\Downloads\\The New Oxford American Dictionary.azw']
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\gerar\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gerar\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\gerar\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gerar\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\gerar\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\gerar\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.9 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
If this is the dictionary that comes pre-loaded on your Kindle, those cannot be decrypted.
