### ISSUE TITLE
DRM Help

### ISSUE THREAD

**Issue by cdubb93** [noDRM/DeDRM_tools#459]
Just got a remarkable and trying to get some kindle books converted to EPUB and onto the device. I'm new to utilizing cailbre and the plugins but I think i have done everything correctly. Originally used Calibre 7.x and DeDRM 7.2.1. After reading some issues I now have Calibre 4.23 and DeDRM 10.0.3. Below is the debug log. Please advise. Apologies if it's an obvious issue!

calibre Debug log
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 2.7.16+
Windows: ('10', '10.0.22621', 'SP0', u'Multiprocessor Free')
Interface language: None
Failed to initialize plugin: u'C:\\Users\\Chase W\\AppData\\Roaming\\calibre\\plugins\\KFX Input.zip'
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 703, in initialize_plugins
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 221, in load
InvalidPlugin: The plugin at C:\Users\Chase W\AppData\Roaming\calibre\plugins\KFX Input.zip needs a version of calibre >= 5.0.0
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 4.23 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 2.7.16+
Windows: ('10', '10.0.22621', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.6884422111 x 81.6428571429
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.50] splash screen shown
[0.50] Initializing db...
[0.50] db initialized
[0.50] Constructing main UI...
[1.77] main UI initialized...
[1.77] Hiding splash screen
[4.77] splash screen hidden
[4.77] Started up in 4.77 seconds with 5 books
Failed to initialize plugin: u'C:\\Users\\Chase W\\AppData\\Roaming\\calibre\\plugins\\KFX Input.zip'
DeDRM v10.0.3: Trying to decrypt The Story of the Human Body.azw3
Using Library AlfCrypto Python
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 944, in KindleMobiDecrypt
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 105, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 181, in load_module
  File "calibre_plugins.dedrm.topazextract", line 246
    if debug: print("%d records in header " % nbValues, end=' ')
                                                           ^
SyntaxError: invalid syntax
Added The Story of the Human Body to db in: 2.1
Added 1 books in 2.5 seconds
Worker Launch took: 0.162000179291
Job: 0 Convert book 1 of 1 (The Story of the Human Body) finished
Convert book 1 of 1 (The Story of the Human Body)
	Failed to initialize plugin: u'C:\\Users\\Chase W\\AppData\\Roaming\\calibre\\plugins\\KFX Input.zip'
	DeDRM v10.0.3: Trying to decrypt ycsn_a.azw3
	Using Library AlfCrypto Python
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	  File "calibre_plugins.dedrm.__init__", line 944, in KindleMobiDecrypt
	  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
	  File "calibre_plugins.dedrm.k4mobidedrm", line 105, in <module>
	  File "site-packages\calibre\customize\zipplugin.py", line 181, in load_module
	  File "calibre_plugins.dedrm.topazextract", line 246
	    if debug: print("%d records in header " % nbValues, end=' ')
	                                                           ^
	SyntaxError: invalid syntax
	Conversion options changed from defaults:
	  output_profile: u'kindle'
	  cover: u'C:\\Users\\CHASEW~1\\AppData\\Local\\Temp\\calibre_quowev\\cmq07h.jpeg'
	  read_metadata_from_opf: u'C:\\Users\\CHASEW~1\\AppData\\Local\\Temp\\calibre_quowev\\rdoag6.opf'
	  verbose: 2
	Resolved conversion options
	calibre version: 4.23.0
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': u'original',
	 'chapter': u"//*[((name()='h1' or name()='h2') and re:test(., '\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', 'i')) or @class = 'chapter']",
	 'chapter_mark': u'pagebreak',
	 'comments': None,
	 'cover': u'C:\\Users\\CHASEW~1\\AppData\\Local\\Temp\\calibre_quowev\\cmq07h.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_toc_at_end': False,
	 'epub_version': u'2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': u'',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001B88F7ABA08>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x000001B88F7B0E88>,
	 'page_breaks_before': u"//*[name()='h1' or name()='h2']",
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': u'C:\\Users\\CHASEW~1\\AppData\\Local\\Temp\\calibre_quowev\\rdoag6.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': u'',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.3: Trying to decrypt ycsn_a.azw3
	DeDRM v10.0.3: Failed to decrypt with error: 'module' object has no attribute 'GetDecryptedBook'
	DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
	DeDRM v10.0.3: Exception when getting default Kindle Key after 0.0 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 969, in KindleMobiDecrypt
	  File "calibre_plugins.dedrm.kindlekey", line 945, in kindlekeys
	  File "calibre_plugins.dedrm.kindlekey", line 338, in getKindleInfoFiles
	TypeError: ExpandEnvironmentStrings() argument 1 must be unicode, not str
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1056, in run
	  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
	DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on C:\Users\CHASEW~1\AppData\Local\Temp\calibre_quowev\ycsn_a.azw3
	Found KF8 MOBI of type u'standalone'
	Python function terminated unexpectedly
	  The Story of the Human Body (Error Code: 1)
	 Traceback (most recent call last):
	  File "site.py", line 114, in main
	  File "site.py", line 88, in run_entry_point
	  File "site-packages\calibre\utils\ipc\worker.py", line 209, in main
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 43, in gui_convert_override
	  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 28, in gui_convert
	  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1110, in run
	  File "site-packages\calibre\customize\conversion.py", line 246, in __call__
	  File "site-packages\calibre\ebooks\conversion\plugins\mobi_input.py", line 47, in convert
	  File "site-packages\calibre\ebooks\mobi\reader\mobi8.py", line 86, in __call__
	  File "site-packages\calibre\ebooks\mobi\reader\mobi6.py", line 158, in check_for_drm
	calibre.ebooks.DRMError: The Story of the Human Body

**Comment by ElleKayEm** [comment]
For calibre 4.23, try DeDRM 6.8.1: https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

With calibre 7, try DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9


Was this downloaded from the website for an E-ink Kindle (not a Fire)?  If so, enter the Kindle's serial number into DeDRM's customization.

**Comment by cdubb93** [comment]
Thank you thank you thank you!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
