### ISSUE TITLE
DeDRM not working on specific book

### ISSUE THREAD

**Issue by Jofkos** [noDRM/DeDRM_tools#464]
### Question / bug report

DeDRM is not working on one of my books. When I tried to open the same book in Adobe Digital Editions, I needed to authorize my device first – I don't know whether this is why it does not work.
I tried using the default_key, deleting the key as suggested in #330, clicking the 'plus' seemingly adding my adobe id key. All unsuccessful.

### Which version of Calibre are you running?

7.20

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

Attempt 1, using the 'default_key':
```log
DeDRM v10.0.9: Trying to decrypt The Great Dune Trilogy - Frank Herbert.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: The Great Dune Trilogy - Frank Herbert.epub is a secure Adobe Adept ePub for UUID 56cdeb10-c237-4afa-9ff2-3c0e78bb13c8
DeDRM v10.0.9: Trying Encryption key default_key
gnt_4xc0.epub is a secure Adobe Adept ePub.
Could not decrypt gnt_4xc0.epub because of an exception:
Traceback (most recent call last):
  File "/Users/Jofkos/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 275, in decryptBook
    decryptor = Decryptor(bookkey, encryption)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Jofkos/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 91, in __init__
    self._aes = AES.new(bookkey, AES.MODE_CBC, b'\x00'*16)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Crypto/Cipher/AES.py", line 228, in new
  File "Crypto/Cipher/__init__.py", line 79, in _create_cipher
  File "Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto/Cipher/AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added The Great Dune Trilogy to db in: 0.0
Added 1 books in 2.0 seconds
```

Attempt 2, removing said key and letting DeDRM load a new key:
```log
DeDRM v10.0.9: Trying to decrypt The Great Dune Trilogy - Frank Herbert.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: The Great Dune Trilogy - Frank Herbert.epub is a secure Adobe Adept ePub for UUID 56cdeb10-c237-4afa-9ff2-3c0e78bb13c8
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Trying a new default key
ttd9d4ld.epub is a secure Adobe Adept ePub.
Could not decrypt ttd9d4ld.epub because of an exception:
Traceback (most recent call last):
  File "/Users/Jofkos/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 275, in decryptBook
    decryptor = Decryptor(bookkey, encryption)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Jofkos/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 91, in __init__
    self._aes = AES.new(bookkey, AES.MODE_CBC, b'\x00'*16)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Crypto/Cipher/AES.py", line 228, in new
  File "Crypto/Cipher/__init__.py", line 79, in _create_cipher
  File "Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto/Cipher/AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with new default key after 0.2 seconds
DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added The Great Dune Trilogy to db in: 0.0
Added 1 books in 4.0 seconds
```

Attempt 3, adding key associated with my Adobe ID:
```log
DeDRM v10.0.9: Trying to decrypt The Great Dune Trilogy - Frank Herbert.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: The Great Dune Trilogy - Frank Herbert.epub is a secure Adobe Adept ePub for UUID 56cdeb10-c237-4afa-9ff2-3c0e78bb13c8
DeDRM v10.0.9: Trying Encryption key b11b5929-f886-4617-9800-a684240a410c_AdobeID_myadobe@id
leu4kpqq.epub is a secure Adobe Adept ePub.
Could not decrypt leu4kpqq.epub because of an exception:
Traceback (most recent call last):
  File "/Users/Jofkos/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 275, in decryptBook
    decryptor = Decryptor(bookkey, encryption)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Jofkos/Library/Preferences/calibre/plugins/DeDRM.zip/ineptepub.py", line 91, in __init__
    self._aes = AES.new(bookkey, AES.MODE_CBC, b'\x00'*16)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Crypto/Cipher/AES.py", line 228, in new
  File "Crypto/Cipher/__init__.py", line 79, in _create_cipher
  File "Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto/Cipher/AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key b11b5929-f886-4617-9800-a684240a410c_AdobeID_myadobe@id after 0.1 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
```

**Comment by ElleKayEm** [comment]
Was the book downloaded with ADE on the same computer and user as calibre/DeDRM?

**Comment by Jofkos** [comment]
I just re-downloaded it to make sure (it first refused, only after "authorizing my device" it actually redownloaded), so if it wasn't before – it is now. Still same error.

**Comment by ElleKayEm** [comment]
And you let DeDRM automatically retrieve the key after ADE was authorized with your Adobe ID?  I've seen more people having issues with this since calibre 7 came out.  I don't know if it's just a coincidence, but you might try installing the final version of calibre 6.x.  If that works, then you'd be able to go back to calibre 7.2.  It just seems to be a problem of initially retrieving the Adobe key.  I've had no issues with calibre 7 and DeDRM 10.0.9 decrypting Adobe books, but my key was already there before I updated to calibre 7.x.

**Comment by Jofkos** [comment]
Not sure what made it work, but I tried Calibre 6 – which didn't do it at first. I then reinstalled ADE and then Calibre (6) could suddenly decrypt everything. Oh well. Thanks for pointing me in the right direction!

**Comment by ElleKayEm** [comment]
Thanks for reporting back.
