### ISSUE TITLE
Obok doesn't identify DRM images in manga

### ISSUE THREAD

**Issue by sidchaini** [noDRM/DeDRM_tools#465]
## Obok doesn't identify DRM images in manga
Hi, I'm trying to use Obok with a manga I downloaded on the Kobo app on my MacBook (macOS 14.1.1 - Sonoma). I do not have the ability to download this manga with Adobe digital editions, and can only use Obok.

Obok can correctly see the manga title in the Obok window on Calibre, however, Obok thinks that there is no DRM in the file.

On running Obok on this, I get a window telling me that conversion was successful (check log at the end) - however, I am unable to open the EPUB from Calibre, nor on another EPUB reader on my Mac either.

I did try closing calibre, downloading from kobo, closing kobo  and then opening calibre - however, the lock still remains green.

To further understand the issue, I looked at the book files after unzipping it from `/Users/admin/Library/Application Support/Kobo/Kobo Desktop Edition`. The file consists of an image for each page, but no meaningful text. It has the following directory structure:

<details><summary>Directory Structure</summary>

```
e92f021a-8d20-4ebd-b0b3-4d11daad6680
├── META-INF
│   └── container.xml
├── OEBPS
│   ├── image
│   │   ├── cover.jpg
│   │   ├── i_0000.jpg
│   │   ├── i_0001.jpg
│   │   ├── ...
│   │   └── i_0221.jpg
│   ├── navigation-documents.xhtml
│   ├── standard.opf
│   ├── style
│   │   └── epub3_css_r1.css
│   ├── text
│   │   ├── p_0000.xhtml
│   │   ├── p_0001.xhtml
│   │   ├── ...
│   │   ├── p_0221.xhtml
│   │   └── p_cover.xhtml
│   └── toc.ncx
├── js
│   └── kobo.js
├── mimetype
└── rights.xml
```
</details>

The jpg files are around 0.5 MB for each page, which implies that they are the main manga files. However, when I try to open the jpg files in here, they cannot be opened in an image viewer (implying they are encrypted). I tried dragging these jpg files directly to Calibre as well, but that did not work either.

How can I get this to work? Let me know if you want the manga zip file, I would be happy to send it over.

### Which version of Calibre are you running?

7.20

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Using calibre Qt style: True
2024-01-01 13:15:45.753 calibre-debug[8447:322799] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 7.2  embedded-python: True
macOS-14.1.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.1.0', 'Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.1.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 7, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 7, 0) && KFX metadata reader (from KFX Input) (2, 7, 0) && From KFX (2, 7, 0) && KFX Input (2, 7, 0) && Set KFX metadata (from KFX Output) (2, 5, 0) && KFX Output (2, 5, 0) && Obok DeDRM (10, 0, 3)
calibre 7.2  embedded-python: True
macOS-14.1.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.1.0', 'Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.1.1', ('', '', ''), 'arm64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 7, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 7, 0) && KFX metadata reader (from KFX Input) (2, 7, 0) && From KFX (2, 7, 0) && KFX Input (2, 7, 0) && Set KFX metadata (from KFX Output) (2, 5, 0) && KFX Output (2, 5, 0) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 114.00000171210824 x 114.00000171210822
[0.00] Starting up...
[0.01] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.69] main UI initialized...
[0.69] Hiding splash screen
[0.79] GUI main window shown
[0.84] QuickView starting
[0.84] QuickView started
Traceback (most recent call last):
  File "calibre/db/cache.py", line 1859, in set_metadata
  File "calibre/db/cache.py", line 1782, in set_cover
  File "calibre/db/backend.py", line 1769, in set_cover
  File "calibre/utils/img.py", line 301, in save_cover_data_to
  File "calibre/utils/img.py", line 209, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
[3.95] Starting the smartdevice driver
[13.09] splash screen hidden
[13.09] Started up in 13.09 seconds with 33 books
Running Obok DeDRM v10.0.3
DEBUG:   24.1 didn't find device
Obok v10.0.1
Copyright © 2012-2022 Physisticated et al.
/var/folders/2d/ht34x6mn7hx9d1sv4g_j8nfr0000gn/T/tmpxdxc4cgh
DEBUG:   24.2 got kobodir /Users/admin/Library/Application Support/Kobo/Kobo Desktop Edition
Error parsing Kobo plist: no legacy user key found.
Found 56 possible keys to try.
DEBUG:   29.0 BookListTableWidget:get_books - book_num: 1
DEBUG:   29.0 BookListTableWidget:get_books - book: Space Brothers 8
DEBUG:   29.0 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.3 - Decrypting Space Brothers 8
Trying key:  b'3978929c71ff8607ec05b2acf04d33be'
Success!
DEBUG:   33.8 DecryptAddProgressDialog::do_book_action - decrypted book: 'Space Brothers 8'
Obok DeDRM v10.0.3 - Added Space Brothers
Obok DeDRM v10.0.3 - wrapping up results.
```

**Comment by ElleKayEm** [comment]
Is this a Kobo Plus borrow?  Seem like those might not work.

**Comment by sidchaini** [comment]
> Is this a Kobo Plus borrow? Seem like those might not work.

Yup. Do these use a different DRM?

**Comment by ElleKayEm** [comment]
Apparently so.  I haven't seen anyone able to decrypt those with Obok.  And the fact that you can't get the Adobe DRM versions seems like another indication that they keep those more locked down.
