### ISSUE TITLE
Calibre start each second time with Traceback error

### ISSUE THREAD

**Issue by MoritzSa** [noDRM/DeDRM_tools#466]
### Question / bug report

On a macOS installation of Calibre 6 or 7 (I tried both), I get each second start of Calibre the Traceback error. 
Then the library cannot be loaded and I have to close the Calibre application and restart it. At the second start Calibre opens. Also when I want to import a new ebook, I get a quite similar error each second time. Has anyone an idea what's happened?

Sorry for the partial German Log-Output, but I work with a German UI of my macOS. 

### Which version of Calibre are you running?

7.1.0

### Which version of the DeDRM plugin are you running?

c.10.0.9

### If applicable, which version of the Kindle software are you running?

no

### Log output

```log
calibre, version 7.1.0
FEHLER: Fehler beim Starten: There was an error during calibre startup. Parts of calibre may not function. Click "Show details" to learn more.

Traceback (most recent call last):
  File "calibre/gui2/main.py", line 316, in initialize_db_stage2
  File "calibre/gui2/main.py", line 259, in start_gui
  File "calibre/gui2/ui.py", line 365, in initialize
  File "calibre/gui2/tag_browser/ui.py", line 122, in init_tag_browser_mixin
  File "calibre/gui2/tag_browser/view.py", line 322, in set_database
  File "calibre/gui2/tag_browser/model.py", line 425, in set_database
  File "calibre/db/cache.py", line 88, in call_func_with_lock
  File "calibre/db/cache.py", line 1066, in set_pref
  File "calibre/db/backend.py", line 149, in set
  File "calibre/db/backend.py", line 134, in __setitem__
apsw.ConnectionClosedError: The connection has been closed
```

**Comment by ElleKayEm** [comment]
Since this is a calibre issue, ask over at the Mobileread calibre forum.
