### ISSUE TITLE
Extraer DRM de libro de kindle Amazon

### ISSUE THREAD

**Issue by emarianolc** [noDRM/DeDRM_tools#469]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Registro de depuración
calibre 7.1  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 7, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 7, 0) && KFX metadata reader (from KFX Input) (2, 7, 0) && From KFX (2, 7, 0) && KFX Input (2, 7, 0) && Obok DeDRM (10, 0, 9)
calibre 7.1  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: es
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 7, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 7, 0) && KFX metadata reader (from KFX Input) (2, 7, 0) && From KFX (2, 7, 0) && KFX Input (2, 7, 0) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.14] db initialized
[0.14] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.83] main UI initialized...
[0.83] Hiding splash screen
Starting QuickView
DeDRM v10.0.9: Trying to decrypt Amar es para Valientes (Spanish Edition).azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Amar es para Valientes (Spanish Edition)
Found 0 keys to try after 0.5 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\H. Elton Mariano LC\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\H. Elton Mariano LC\AppData\Local\Amazon\Kindle\storage\.kinf2018
Found K4PC 1.9+ kinf2011 file: C:\Users\H. Elton Mariano LC\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '48263534' and UserName 'H. Elton Mariano LC'
Decrypted key file using IDString '48263534' and UserName 'H. Elton Mariano LC'
DeDRM v10.0.9: Found 2 new keys
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Amar es para Valientes (Spanish Edition)
Got DSN key from database key_0
Got DSN key from database key_1
Found 5 keys to try after 0.7 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\H. Elton Mariano LC\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\H. Elton Mariano LC\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\H. Elton Mariano LC\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\H. Elton Mariano LC\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 5 PIDs tried.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\H. Elton Mariano LC\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\H. Elton Mariano LC\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[9.01] splash screen hidden
[9.01] Started up in 9.01 seconds with 44 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xa4=\xf4\xcep\x06 "\x18\x06{\x93\xb3\xfd\xc58)\xdc\x82\x9d\x1dl\xa8e\x85\xf3\x8f\xd22\xedb\xae', b'C:\\Users\\H. Elton Mariano LC\\Documents\\Libros\\Amar es para Valientes (Spanish Edition).azw3']
Added Amar es para Valientes (Spanish Edition) to db in: 0.0
Added 1 books in 0.9 seconds

### Which version of Calibre are you running?

7

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
If that book is from or for an E-ink Kindle, enter the Kindle's serial number into DeDRM's customization.
