### ISSUE TITLE
DeDRM doesn't work with some Kobo books

### ISSUE THREAD

**Issue by eszter007** [noDRM/DeDRM_tools#47]
### Bug report

I recently tried to convert a manga I got from Kobo to be able to read it in another reader app. However, I get errors and the conversion fails. It is not only the one book, the next one in the sequel gets the same errors.

I have tried it both on macOS 12.2.1 as well as Windows 10. I get the same errors for both. Neither Obok works nor DeDRM via Adobe Digital Editions.

### Which version of Calibre are you running?

5.37

### Which version of the DeDRM plugin are you running?

v.10.0.0

### Log output

```log
calibre, version 5.37.0
ERROR: Loading book failed: Failed to open the book at [Path]. Click "Show details" for more info.
Failed to convert book:  [Path] with error:
DeDRM v10.0.2: Trying to decrypt  [Filename]
DeDRM v10.0.2: Verifying zip archive integrity
DeDRM v10.0.2: “[Filename]” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
DeDRM v10.0.2: Finished after 2.2 seconds
InputFormatPlugin: EPUB Input running
on /var/folders/nf/s70ywbcn4cjcphy4y6m2bgdm0000gn/C/calibre_5.37.0_tmp_0ux1v8ix/jogxy3aw.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre/srv/render_book.py", line 823, in viewer_main
  File "calibre/srv/render_book.py", line 814, in render_for_viewer
  File "calibre/srv/render_book.py", line 792, in render
  File "calibre/srv/render_book.py", line 605, in process_exploded_book
  File "calibre/srv/render_book.py", line 264, in create_cover_page
  File "calibre/srv/render_book.py", line 217, in find_epub_cover
  File "calibre/ebooks/oeb/polish/cover.py", line 284, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 430, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 41, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes
```

**Comment by ElleKayEm** [comment]
Is the book in the log the one from ADE?  Because it doesn't have the info in the file which DeDRM uses to decrypt it.

Can we see a log from Obok?

**Comment by eszter007** [comment]
> Is the book in the log the one from ADE? Because it doesn't have the info in the file which DeDRM uses to decrypt it.
> 
> Can we see a log from Obok?

Yes, it was from ADE. Here it is what I got from Obok:
```
calibre, version 5.37.0
ERROR: Loading book failed: Failed to open the book at [Path]. Click "Show details" for more info.

Failed to convert book: [Filename] with error:
DeDRM v10.0.2: Trying to decrypt [Filename]
DeDRM v10.0.2: Verifying zip archive integrity
DeDRM v10.0.2: [Filename] is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
DeDRM v10.0.2: Finished after 1.7 seconds
InputFormatPlugin: EPUB Input running
on /var/folders/nf/s70ywbcn4cjcphy4y6m2bgdm0000gn/C/calibre_5.37.0_tmp_qoe0l9p_/der2hj2k.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 39, in <module>
  File "site.py", line 35, in main
  File "calibre/utils/ipc/worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre/srv/render_book.py", line 823, in viewer_main
  File "calibre/srv/render_book.py", line 814, in render_for_viewer
  File "calibre/srv/render_book.py", line 792, in render
  File "calibre/srv/render_book.py", line 605, in process_exploded_book
  File "calibre/srv/render_book.py", line 264, in create_cover_page
  File "calibre/srv/render_book.py", line 217, in find_epub_cover
  File "calibre/ebooks/oeb/polish/cover.py", line 284, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 430, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 41, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes
```

**Comment by ElleKayEm** [comment]
Obok isn't showing in that log at all.  Once again we just see DeDRM say it isn't an Adobe DRM or B&N epub.

**Comment by eszter007** [comment]
> Obok isn't showing in that log at all. Once again we just see DeDRM say it isn't an Adobe DRM or B&N epub.

Here again shown in debug mode:
```
calibre 5.37  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2) && EpubSplit (3, 2, 0) && Obok DeDRM (10, 0, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000162950651 x 107.50000161448803
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.90] main UI initialized...
[0.90] Hiding splash screen
Starting QuickView
[1.15] splash screen hidden
[1.15] Started up in 1.15 seconds with 28 books
Running Obok DeDRM v10.0.0
DEBUG:   13.8 didn't find device
Obok v4.0.0
Copyright © 2012-2020 Physisticated et al.
/var/folders/nf/s70ywbcn4cjcphy4y6m2bgdm0000gn/T/tmpv6o_a8w1
DEBUG:   13.8 got kobodir /Users/eszter/Library/Application Support/Kobo/Kobo Desktop Edition
Error parsing Kobo plist: no legacy user key found.
Found 36 possible keys to try.
DEBUG:   16.6 BookListTableWidget:get_books - book_num: 1
DEBUG:   16.6 BookListTableWidget:get_books - book: [Book name]
DEBUG:   16.6 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.0 - Decrypting [Book name]
Trying key:  [key]
Success!
DEBUG:   19.3 DecryptAddProgressDialog::do_book_action - decrypted book: [Book name]
Obok DeDRM v10.0.0 - Added [Book name]
Obok DeDRM v10.0.0 - wrapping up results.
Worker Launch took: 0.01 seconds
```

The weird thing is Oboe shows Success in the log but I still get the error posted above in the previous post when trying to open the book.

**Comment by ElleKayEm** [comment]
Not sure what's going on there, but I have seen Obok think something is decrypted when it isn't.

And DeDRM isn't recognizing the ADE version.  You can read it in ADE okay?

**Comment by eszter007** [comment]
> Not sure what's going on there, but I have seen Obok think something is decrypted when it isn't.
> 
> And DeDRM isn't recognizing the ADE version. You can read it in ADE okay?

Yes, in ADE both books look alright.

**Comment by ElleKayEm** [comment]
Ok, you have ADE authorized with your Adobe ID on the same machine and user as calibre with DeDRM?

Can you delete the copies currently in calibre and let's look at a log of just adding the ADE book to calibre without trying to open or convert it.

**Comment by eszter007** [comment]
> Ok, you have ADE authorized with your Adobe ID on the same machine and user as calibre with DeDRM?
Exactly.
> Can you delete the copies currently in calibre and let's look at a log of just adding the ADE book to calibre without trying to open or convert it.
Here is the log after just adding the book to Calibre (ADE encrypted ePub):
```
calibre 5.37  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.3.0', 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2) && EpubSplit (3, 2, 0) && Obok DeDRM (10, 0, 0)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 108.50000162950651 x 107.50000161448803
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.89] main UI initialized...
[0.89] Hiding splash screen
Starting QuickView
[1.14] splash screen hidden
[1.14] Started up in 1.14 seconds with 27 books
DeDRM v10.0.2: Trying to decrypt [bookname].epub
DeDRM v10.0.2: Verifying zip archive integrity
DeDRM v10.0.2: [bookname].epub is a secure Adobe Adept ePub for UUID [id]
DeDRM v10.0.2: Trying Encryption key default_key
DeDRM v10.0.2: Decrypted with key default_key after 2.3 seconds
DeDRM v10.0.2: Finished after 2.3 seconds
Added [bookname] to db in: 0.0
Added 1 books in 3.6 seconds
```

**Comment by ElleKayEm** [comment]
Hmm, that also shows successful decryption.  Maybe the issue is calibre's ebook viewer.

**Comment by eszter007** [comment]
> Hmm, that also shows successful decryption. Maybe the issue is calibre's ebook viewer.

I tried open the book with another application which can read ePub and while it showed the correct amount of pages, all pages were just white and the content was missing.

**Comment by ElleKayEm** [comment]
Sounds like the pages are all image scans.  A possible workaround might be unzipping the epub and then zipping up just the images to create a cbz file.

I don't know if it's just something about the way these are constructed that other epub viewers don't know how to handle them or what.

**Comment by eszter007** [comment]
You are right - unzipping the book did the trick - the images were all there. So then the problem was not really the decryption but the Calibri ePub viewer (and the other application).
