### ISSUE TITLE
DRM on Amazon azw3 ebook not getting removed in Calibre

### ISSUE THREAD

**Issue by Markl6952** [noDRM/DeDRM_tools#471]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.3  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 7, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 7, 0) && KFX metadata reader (from KFX Input) (2, 7, 0) && From KFX (2, 7, 0) && KFX Input (2, 7, 0) && Set KFX metadata (from KFX Output) (2, 5, 0) && KFX Output (2, 5, 0) && Obok DeDRM (10, 0, 3)
calibre 7.3  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 7, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 7, 0) && KFX metadata reader (from KFX Input) (2, 7, 0) && From KFX (2, 7, 0) && KFX Input (2, 7, 0) && Set KFX metadata (from KFX Output) (2, 5, 0) && KFX Output (2, 5, 0) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.14671814671814 x 94.07407407407408
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.39] GUI main window shown
[1.42] main UI initialized...
[1.42] Hiding splash screen
DeDRM v10.0.3: Trying to decrypt No Plan B (Jack Reacher).azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: No Plan B (Jack Reacher)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\ML_Admin\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\ML_Admin\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '378892693' and UserName 'ML_Admin'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: No Plan B (Jack Reacher)
Got DSN key from database key_0
Found 4 keys to try after 0.4 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\ML_Admin\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\ML_Admin\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\ML_Admin\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\ML_Admin\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\ML_Admin\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\ML_Admin\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[20.56] splash screen hidden
[20.56] Started up in 20.56 seconds with 392 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xb8\xbe>\x821\x8a\x16\xfe:\xf7u\xc5\xcf\xa5\xa9C(\xd2\xb9\xfal\rU\xeaR\xbf\xb9\xe8\xc3}\x8c\xd9', b'C:\\Users\\ML_Admin\\Downloads\\No Plan B (Jack Reacher).azw3']
Added No Plan B (Jack Reacher) to db in: 0.1
Added 1 books in 0.9 seconds

### Which version of Calibre are you running?

7.3

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
If that's from or for an E-ink Kindle (not a Fire), enter that Kindle's serial number into DeDRM's customization.

**Comment by Markl6952** [comment]
Hi,  I have added the serial number for my fire but it still isn't removing
the DRM. I selected to download to usb is that right?

**Comment by symad1959** [comment]
Hi,  I have the same issue but have noticed a quirk.   If I download a book using the Kindle for PC app and then import the book into Calibre it converts to MOBI successfully but if I download the same book form the Amazon site via usb to save the azw file directly to my PC then Calibre won't convert that file

**Comment by ElleKayEm** [comment]
@symad1959 
Did you choose an E-ink Kindle for the device (won't work for a Fire)?  Do you have the E-ink Kindle's serial number correctly entered in DeDRM's customization?

**Comment by symad1959** [comment]
I'm using a Kindle PaperWhite.  I didn't understand the relevance of the serial number having to be in the DeDRM settings but you've given me the solution to the problem and the conversion to mobi worked fine.


Thank you

**Comment by ElleKayEm** [comment]
The key for books for E-ink Kindles is based on the serial number.  Each device/app installation has a unique key.  DeDRM is able to retrieve Kindle for PC's key from where it's stored on your computer.

@Markl6952  If you don't have an E-ink Kindle, update to DeDRM 10.0.9 and use books from Kindle for PC.

**Comment by pgfiore** [comment]
E-Ink Kindle Owners
Hi guys, this is just a quick and mostly useless note. Am I the only one having problems with the Configuration Buttons? I needed eons to understand that my Paperwhite IS NOT managed by "Kindle for Mac/PC". 
The "eink Kindle" is the right one and the place where to put the serial code.
When discovered, it becomes crystal clear (and one feels dumb, too)... But during the process, I made many mistakes.
Stupid suggestion: could a caption like "All E-ink Kindle" help?
However, thanks for the above suggestion. It worked for me too (after I recalled how to switch on my brain).
