### ISSUE TITLE
DeDRM 10.0.9 on Calibre 7.3.0 Flatpak not able to find ADE Keys with  WineGetKeys

### ISSUE THREAD

**Issue by FilBot3** [noDRM/DeDRM_tools#478]
### Question / bug report

I installed Adobe Digital Editions into Lutris in its own WINE Prefix. I was able to download the `.acsm` file from the store, and load it into ADE which,when attempting to open yielded with these errors.

![Screenshot from 2024-01-19 13-34-10](https://github.com/noDRM/DeDRM_tools/assets/3039509/5e1092a8-0354-47f4-93a1-d174ed750b08)

![Screenshot from 2024-01-19 13-34-15](https://github.com/noDRM/DeDRM_tools/assets/3039509/2a3a04a5-8cc4-4e9e-ae3c-619061d02b68)

So, then I added the plugin according to the README in the zip file. Restarted Calibre, and imported the book. However, when double-clicked, the DRM was still there.

### Which version of Calibre are you running?

7.3.0

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
➜  ~ 
> flatpak run com.calibre_ebook.calibre 
Qt: Session management error: Could not open network socket
DeDRM v10.0.9: Trying to decrypt So You Want to be a Game Master.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: So You Want to be a Game Master.epub is a secure Adobe Adept ePub for UUID d7b1113c-bb5b-4412-8bde-04dc30f21caf
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 570, in ePubDecrypt
    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/filbot/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/filbot/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
    self.check_call(["-c", self.py3_test])
  File "/var/home/filbot/.var/app/com.calibre_ebook.calibre/config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 408, in check_call
  File "subprocess.py", line 389, in call
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

➜  ~ 
> flatpak info com.calibre_ebook.calibre 

calibre - The one stop solution to all your e-book needs

          ID: com.calibre_ebook.calibre
         Ref: app/com.calibre_ebook.calibre/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 7.3.0
     License: GPL-3.0
      Origin: flathub-user
  Collection: org.flathub.Stable
Installation: user
   Installed: 487.5 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: b82e82b57478bf1c0cece9727b3405eedad1eb0db2dac1e1dcd31a960a51c89f
      Parent: 1615d664beb663d233280404cde241906f045bc829f3d1d52cba2e07d4058dc7
     Subject: Update 2 modules (7a117a36)
        Date: 2024-01-05 13:34:43 +0000
```

**Comment by FilBot3** [comment]
I'll have to try this on a Windows VM or something.

**Comment by ElleKayEm** [comment]
There are issues retrieving keys from apps under wine.  A workaround is using the ACSM Input plugin in place of ADE:  https://www.mobileread.com/forums/showthread.php?t=341975

DeDRM is suppose to check the ACSM Input plugin for ADE keys.  But if it doesn't, you can import the key into DeDRM manually.

**Comment by FilBot3** [comment]
That may be what I'm not understanding is hwo to do that manually, or where the plugin considers the WINE Prefix to be.

**Comment by FilBot3** [comment]
Would it be easier to do this on Windows instead of trying to use a Calibre Flatpak and a WINE Prefix?

**Comment by ElleKayEm** [comment]
If you use the ACSM Input plugin, you don't have to bother with Adobe Digital Editions.

**Comment by FilBot3** [comment]
> If you use the ACSM Input plugin, you don't have to bother with Adobe Digital Editions.

I will try to figure that out.
