### ISSUE TITLE
Kobo Desktop decryption

### ISSUE THREAD

**Issue by manti-X** [noDRM/DeDRM_tools#484]
### Question / bug report

synced titles from kobo desktop are not getting decrypted

### Which version of Calibre are you running?

6.27

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Fehlerdiagnoseprotokoll
calibre 6.27  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.10.1
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 9) && AZW6 Image Merge (1, 1, 1) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && KePub Input (3, 6, 7) && KePub Metadata Reader (3, 6, 7) && KePub Metadata Writer (3, 6, 7) && KePub Output (3, 6, 7) && KoboTouchExtended (3, 6, 7) && Obok DeDRM (10, 0, 9)
calibre 6.27  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.10.1
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 9) && AZW6 Image Merge (1, 1, 1) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && KePub Input (3, 6, 7) && KePub Metadata Reader (3, 6, 7) && KePub Metadata Writer (3, 6, 7) && KePub Output (3, 6, 7) && KoboTouchExtended (3, 6, 7) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 133.4890510948905 x 133.24590163934425
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.62] main UI initialized...
[1.62] Hiding splash screen
Starting QuickView
[3.75] splash screen hidden
[3.75] Started up in 3.75 seconds with 0 books
Running Obok DeDRM v10.0.9
DEBUG:    6.6 didn't find device
Obok v10.0.9
Copyright © 2012-2023 Physisticated et al.
C:\Users\manti\AppData\Local\Temp\tmpn8ogx11f
DEBUG:    6.6 got kobodir C:/Users/manti/AppData/Local/Kobo/Kobo Desktop Edition
Found 8 possible keys to try.
DEBUG:   12.6 BookListTableWidget:get_books - book_num: 0
DEBUG:   12.6 BookListTableWidget:get_books - book: ゲッサン 2023年12月号(2023年11月10日発売)
DEBUG:   12.6 BookListTableWidget:get_books - book_num: 1
DEBUG:   12.6 BookListTableWidget:get_books - book: ゲッサン 2024年1月号(2023年12月12日発売)
DEBUG:   12.6 BookListTableWidget:get_books - book_num: 2
DEBUG:   12.6 BookListTableWidget:get_books - book: 四つ子ぐらし１
DEBUG:   12.6 BookListTableWidget:get_books - book_num: 3
DEBUG:   12.6 BookListTableWidget:get_books - book: 魔法使いロゼの佐渡ライフ　１巻
DEBUG:   12.6 BookListTableWidget:get_books - book_num: 4
DEBUG:   12.6 BookListTableWidget:get_books - book: 魔法使いロゼの佐渡ライフ　２巻
DEBUG:   12.6 InterfacePluginAction::launchObok - number of books to decrypt: 5
Obok DeDRM v10.0.9 - Decrypting ゲッサン 2023年12月号(2023年11月10日発売)
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'\xa8\x8a|\x1e\xbf=\xf8\x1cB\x83':
Perhaps utf-8 without BOM
Bad character at 0, value 168
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b"\x9cz\x822'\xf4_s4l":
Perhaps utf-8 without BOM
Bad character at 0, value 156
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'}\xb2jxZM\xda\xa6kT':
Perhaps utf-8 without BOM
Bad character at 1, value 178
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'"\x16\x8eTA;\xeff\x91_':
Perhaps utf-8 without BOM
Bad character at 1, value 22
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b"\x99\xab\xc7\xc5'IP\xf4\nU":
Perhaps utf-8 without BOM
Bad character at 0, value 153
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'L9\xf4\xfb\r\xa9N\xef I':
Perhaps utf-8 without BOM
Bad character at 2, value 244
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b'\x89J\x1c\x07\xda\xde\x17\x90w\xa5':
Perhaps utf-8 without BOM
Bad character at 0, value 137
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'\x95*`H\x92\xb5\x90\x08\x8e\x02':
Perhaps utf-8 without BOM
Bad character at 0, value 149
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt ゲッサン 2023年12月号(2023年11月10日発売)
DEBUG:   12.6 DecryptAddProgressDialog::do_book_action - book decryption failed: 'ゲッサン 2023年12月号(2023年11月10日発売)'
Obok DeDRM v10.0.9 - Decrypting ゲッサン 2024年1月号(2023年12月12日発売)
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'l\xdf\xe6\xddA~\x85\xf6\x18"':
Perhaps utf-8 without BOM
Bad character at 1, value 223
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b'Z&\xb11! \xfcA\x96\x98':
Perhaps utf-8 without BOM
Bad character at 2, value 177
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'\xbd\xbcQ-B6\x1a\x1dTL':
Perhaps utf-8 without BOM
Bad character at 0, value 189
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'\xb2?`\x9d\xd8\x17\x84 \x12d':
Perhaps utf-8 without BOM
Bad character at 0, value 178
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b'\xae\xab\xa2\xba3Mn\x17\x00k':
Perhaps utf-8 without BOM
Bad character at 0, value 174
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'JK9K\xe6\x9a\xa6H\xf97':
Perhaps utf-8 without BOM
Bad character at 4, value 230
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b'\xb8\x96\xa9#V0\xf5\xdf\xb4F':
Perhaps utf-8 without BOM
Bad character at 0, value 184
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'1\x815\xf3\xe7\xc8k\r\xd9Z':
Perhaps utf-8 without BOM
Bad character at 1, value 129
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt ゲッサン 2024年1月号(2023年12月12日発売)
DEBUG:   12.7 DecryptAddProgressDialog::do_book_action - book decryption failed: 'ゲッサン 2024年1月号(2023年12月12日発売)'
Obok DeDRM v10.0.9 - Decrypting 四つ子ぐらし１
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'\xeaCH \xb3\x81\xa47\xe7`':
Perhaps utf-8 without BOM
Bad character at 0, value 234
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b'q\xc6u\x97\xf3\xc8-\x04\xa8<':
Perhaps utf-8 without BOM
Bad character at 1, value 198
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'\xaf\xdc\x87GbLl\xf1$M':
Perhaps utf-8 without BOM
Bad character at 0, value 175
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'\x8b?\x87\tBgg.\x80\xc0':
Perhaps utf-8 without BOM
Bad character at 0, value 139
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b'5\xf5\x96\xce\x05y\x97_\xad\xfc':
Perhaps utf-8 without BOM
Bad character at 1, value 245
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'T\x08\xe4\xb3\xcc\x86\x1c\r\x17\xf5':
Perhaps utf-8 without BOM
Bad character at 1, value 8
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b"\xf3V\x074^\xe7\xc8?'{":
Perhaps utf-8 without BOM
Bad character at 0, value 243
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'\xb6\x08\xd600}\xc3\xe5\xa7\xa9':
Perhaps utf-8 without BOM
Bad character at 0, value 182
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt 四つ子ぐらし１
DEBUG:   12.8 DecryptAddProgressDialog::do_book_action - book decryption failed: '四つ子ぐらし１'
Obok DeDRM v10.0.9 - Decrypting 魔法使いロゼの佐渡ライフ　１巻
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'a\xaa\x86\xea\xd6b\xc1\x8cT\xbc':
Perhaps utf-8 without BOM
Bad character at 1, value 170
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b'V\xad\xafO|\x12\xa4\xe2\\\xa6':
Perhaps utf-8 without BOM
Bad character at 1, value 173
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'\x112\x0f\x9c\xd01q\xe3\x06\xe8':
Perhaps utf-8 without BOM
Bad character at 0, value 17
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'\xce\xb2\xb9\x1b\x82\xdf\x80x\xd4\\':
Perhaps utf-8 without BOM
Bad character at 0, value 206
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b'cf\xa4\x10\xd6\x9c\xa4O\xc9<':
Perhaps utf-8 without BOM
Bad character at 2, value 164
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'\xdf\xecWH\x8e\x84\xb7\xa0\x8d+':
Perhaps utf-8 without BOM
Bad character at 0, value 223
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b'\xe9\xd0\xbe\xff\xdb\x00\xc88\xc6\xcc':
Perhaps utf-8 without BOM
Bad character at 0, value 233
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'\x83a\xe8\xed\x9e\x8d\xe0\xbeV~':
Perhaps utf-8 without BOM
Bad character at 0, value 131
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt 魔法使いロゼの佐渡ライフ　１巻
DEBUG:   12.8 DecryptAddProgressDialog::do_book_action - book decryption failed: '魔法使いロゼの佐渡ライフ　１巻'
Obok DeDRM v10.0.9 - Decrypting 魔法使いロゼの佐渡ライフ　２巻
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'+\xcc\xf0\xb5\x8f\xca\x80\x07\xb2\xf8':
Perhaps utf-8 without BOM
Bad character at 1, value 204
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b'\x95\x15\xc5o\xda(\xad\xa0\x11\\':
Perhaps utf-8 without BOM
Bad character at 0, value 149
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'\xd6\xfbL\xe2\xf4F\x13\xd6\x82\x7f':
Perhaps utf-8 without BOM
Bad character at 0, value 214
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'\x90\x86\x00@=F\xf3\x01\xc20':
Perhaps utf-8 without BOM
Bad character at 0, value 144
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b'\t\x04\x92\x9c\xa6\x12Y\x11\xfe\xeb':
Perhaps utf-8 without BOM
Bad character at 0, value 9
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'o\x93<\xdbL\x85"\xe1\x0el':
Perhaps utf-8 without BOM
Bad character at 1, value 147
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b' \xf6?\x861T\xeeXQw':
Perhaps utf-8 without BOM
Bad character at 1, value 246
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'\x02\xbac_W@iP\xa9\xd2':
Perhaps utf-8 without BOM
Bad character at 0, value 2
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt 魔法使いロゼの佐渡ライフ　２巻
DEBUG:   12.8 DecryptAddProgressDialog::do_book_action - book decryption failed: '魔法使いロゼの佐渡ライフ　２巻'
Obok DeDRM v10.0.9 - wrapping up results.
Running Obok DeDRM v10.0.9
DEBUG:   18.1 didn't find device
Obok v10.0.9
Copyright © 2012-2023 Physisticated et al.
C:\Users\manti\AppData\Local\Temp\tmpznecrij4
DEBUG:   18.1 got kobodir C:/Users/manti/AppData/Local/Kobo/Kobo Desktop Edition
Found 8 possible keys to try.
DEBUG:   20.0 BookListTableWidget:get_books - book_num: 0
DEBUG:   20.0 BookListTableWidget:get_books - book: ゲッサン 2023年12月号(2023年11月10日発売)
DEBUG:   20.0 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.9 - Decrypting ゲッサン 2023年12月号(2023年11月10日発売)
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'\xa8\x8a|\x1e\xbf=\xf8\x1cB\x83':
Perhaps utf-8 without BOM
Bad character at 0, value 168
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b"\x9cz\x822'\xf4_s4l":
Perhaps utf-8 without BOM
Bad character at 0, value 156
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'}\xb2jxZM\xda\xa6kT':
Perhaps utf-8 without BOM
Bad character at 1, value 178
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'"\x16\x8eTA;\xeff\x91_':
Perhaps utf-8 without BOM
Bad character at 1, value 22
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b"\x99\xab\xc7\xc5'IP\xf4\nU":
Perhaps utf-8 without BOM
Bad character at 0, value 153
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'L9\xf4\xfb\r\xa9N\xef I':
Perhaps utf-8 without BOM
Bad character at 2, value 244
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b'\x89J\x1c\x07\xda\xde\x17\x90w\xa5':
Perhaps utf-8 without BOM
Bad character at 0, value 137
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'\x95*`H\x92\xb5\x90\x08\x8e\x02':
Perhaps utf-8 without BOM
Bad character at 0, value 149
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt ゲッサン 2023年12月号(2023年11月10日発売)
DEBUG:   20.1 DecryptAddProgressDialog::do_book_action - book decryption failed: 'ゲッサン 2023年12月号(2023年11月10日発売)'
Obok DeDRM v10.0.9 - wrapping up results.
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'mS*|E\x91\xc9\xf3E\xcb\xc6\xe0\xd7\xdfrg\xf1\x84\x8648x\xe6\x12\x04\xca\x92\xf8\x16\xd2\x1b\xf9', b'C:\\Users\\manti\\AppData\\Local\\Kobo\\Kobo Desktop Edition']
Job: 0 Geräteinformationen abrufen started
DeviceJob: 0 Geräteinformationen abrufen done, calling callback
DeviceJob: 0 Geräteinformationen abrufen callback returned
Job: 1 Bibliotheksinformationen festlegen started
DeviceJob: 1 Bibliotheksinformationen festlegen done, calling callback
DeviceJob: 1 Bibliotheksinformationen festlegen callback returned
Job: 2 Gerätebücherliste abrufen started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= FOLDER_DEVICE oncard= None
DEBUG:    0.0 USBMS: dirs are: C:\Users\manti\AppData\Local\Kobo\Kobo Desktop Edition\ 
DEBUG:    0.0 USBMS: scan from root False C:\Users\manti\AppData\Local\Kobo\Kobo Desktop Edition\
DEBUG:    0.1 USBMS: count found in cache: 27, count of files in metadata: 27, need_sync: False
DEBUG:    0.1 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= FOLDER_DEVICE oncard= carda
DEBUG:    0.1 USBMS: Fetching list of books from device. Device= FOLDER_DEVICE oncard= cardb
DeviceJob: 2 Gerätebücherliste abrufen done, calling callback
DeviceJob: metadata_downloaded: Starting set_books_in_library
DeviceJob: set_books_in_library: books to process= 27
DeviceJob: set_books_in_library finished: time= 0.03310441970825195
DeviceJob: metadata_downloaded: updating views
DeviceJob: metadata_downloaded: syncing
DeviceJob: metadata_downloaded: refreshing ondevice
DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Gerätebücherliste abrufen callback returned
Job: 0 Geräteinformationen abrufen finished
Keine Details verfügbar.
Job: 2 Gerätebücherliste abrufen finished
Keine Details verfügbar.
Job: 1 Bibliotheksinformationen festlegen finished
Keine Details verfügbar.
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.16:  0.841) _startup_on_demand listening on port 9090
SMART_DEV (   1.22:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.26:  0.000) _startup_on_demand broadcast socket listening on port 54982
SMART_DEV (   2.34:  1.041) run All IP addresses {'{82BAA945-E03A-4E35-BE9C-2BE24366E418}': [{'addr': '192.168.2.106', 'netmask': '255.255.255.0', 'broadcast': '192.168.2.255'}], '{E7ACDFF7-42A9-11EC-983D-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
Running Obok DeDRM v10.0.9
DEBUG:  481.7 didn't find device
Obok v10.0.9
Copyright © 2012-2023 Physisticated et al.
C:\Users\manti\AppData\Local\Temp\tmp98beig9z
DEBUG:  481.7 got kobodir C:/Users/manti/AppData/Local/Kobo/Kobo Desktop Edition
Found 8 possible keys to try.
DEBUG:  483.9 BookListTableWidget:get_books - book_num: 0
DEBUG:  483.9 BookListTableWidget:get_books - book: ゲッサン 2023年12月号(2023年11月10日発売)
DEBUG:  483.9 BookListTableWidget:get_books - book_num: 1
DEBUG:  483.9 BookListTableWidget:get_books - book: ゲッサン 2024年1月号(2023年12月12日発売)
DEBUG:  483.9 BookListTableWidget:get_books - book_num: 2
DEBUG:  483.9 BookListTableWidget:get_books - book: 四つ子ぐらし１
DEBUG:  483.9 BookListTableWidget:get_books - book_num: 3
DEBUG:  483.9 BookListTableWidget:get_books - book: 'NoneType' object has no attribute 'get_file'

Traceback (most recent call last):
  File "calibre\gui2\device.py", line 104, in run
  File "calibre\gui2\device.py", line 687, in _view_book
AttributeError: 'NoneType' object has no attribute 'get_file'

魔法使いロゼの佐渡ライフ　１巻
DEBUG:  483.9 BookListTableWidget:get_books - book_num: 4
DEBUG:  483.9 BookListTableWidget:get_books - book: 魔法使いロゼの佐渡ライフ　２巻
DEBUG:  483.9 InterfacePluginAction::launchObok - number of books to decrypt: 5
Obok DeDRM v10.0.9 - Decrypting ゲッサン 2023年12月号(2023年11月10日発売)
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'\xa8\x8a|\x1e\xbf=\xf8\x1cB\x83':
Perhaps utf-8 without BOM
Bad character at 0, value 168
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b"\x9cz\x822'\xf4_s4l":
Perhaps utf-8 without BOM
Bad character at 0, value 156
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'}\xb2jxZM\xda\xa6kT':
Perhaps utf-8 without BOM
Bad character at 1, value 178
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'"\x16\x8eTA;\xeff\x91_':
Perhaps utf-8 without BOM
Bad character at 1, value 22
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b"\x99\xab\xc7\xc5'IP\xf4\nU":
Perhaps utf-8 without BOM
Bad character at 0, value 153
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'L9\xf4\xfb\r\xa9N\xef I':
Perhaps utf-8 without BOM
Bad character at 2, value 244
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b'\x89J\x1c\x07\xda\xde\x17\x90w\xa5':
Perhaps utf-8 without BOM
Bad character at 0, value 137
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'\x95*`H\x92\xb5\x90\x08\x8e\x02':
Perhaps utf-8 without BOM
Bad character at 0, value 149
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt ゲッサン 2023年12月号(2023年11月10日発売)
DEBUG:  484.0 DecryptAddProgressDialog::do_book_action - book decryption failed: 'ゲッサン 2023年12月号(2023年11月10日発売)'
Obok DeDRM v10.0.9 - Decrypting ゲッサン 2024年1月号(2023年12月12日発売)
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'l\xdf\xe6\xddA~\x85\xf6\x18"':
Perhaps utf-8 without BOM
Bad character at 1, value 223
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b'Z&\xb11! \xfcA\x96\x98':
Perhaps utf-8 without BOM
Bad character at 2, value 177
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'\xbd\xbcQ-B6\x1a\x1dTL':
Perhaps utf-8 without BOM
Bad character at 0, value 189
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'\xb2?`\x9d\xd8\x17\x84 \x12d':
Perhaps utf-8 without BOM
Bad character at 0, value 178
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b'\xae\xab\xa2\xba3Mn\x17\x00k':
Perhaps utf-8 without BOM
Bad character at 0, value 174
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'JK9K\xe6\x9a\xa6H\xf97':
Perhaps utf-8 without BOM
Bad character at 4, value 230
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b'\xb8\x96\xa9#V0\xf5\xdf\xb4F':
Perhaps utf-8 without BOM
Bad character at 0, value 184
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'1\x815\xf3\xe7\xc8k\r\xd9Z':
Perhaps utf-8 without BOM
Bad character at 1, value 129
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt ゲッサン 2024年1月号(2023年12月12日発売)
DEBUG:  484.1 DecryptAddProgressDialog::do_book_action - book decryption failed: 'ゲッサン 2024年1月号(2023年12月12日発売)'
Obok DeDRM v10.0.9 - Decrypting 四つ子ぐらし１
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'\xeaCH \xb3\x81\xa47\xe7`':
Perhaps utf-8 without BOM
Bad character at 0, value 234
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b'q\xc6u\x97\xf3\xc8-\x04\xa8<':
Perhaps utf-8 without BOM
Bad character at 1, value 198
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'\xaf\xdc\x87GbLl\xf1$M':
Perhaps utf-8 without BOM
Bad character at 0, value 175
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'\x8b?\x87\tBgg.\x80\xc0':
Perhaps utf-8 without BOM
Bad character at 0, value 139
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b'5\xf5\x96\xce\x05y\x97_\xad\xfc':
Perhaps utf-8 without BOM
Bad character at 1, value 245
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'T\x08\xe4\xb3\xcc\x86\x1c\r\x17\xf5':
Perhaps utf-8 without BOM
Bad character at 1, value 8
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b"\xf3V\x074^\xe7\xc8?'{":
Perhaps utf-8 without BOM
Bad character at 0, value 243
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'\xb6\x08\xd600}\xc3\xe5\xa7\xa9':
Perhaps utf-8 without BOM
Bad character at 0, value 182
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt 四つ子ぐらし１
DEBUG:  484.1 DecryptAddProgressDialog::do_book_action - book decryption failed: '四つ子ぐらし１'
Obok DeDRM v10.0.9 - Decrypting 魔法使いロゼの佐渡ライフ　１巻
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'a\xaa\x86\xea\xd6b\xc1\x8cT\xbc':
Perhaps utf-8 without BOM
Bad character at 1, value 170
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b'V\xad\xafO|\x12\xa4\xe2\\\xa6':
Perhaps utf-8 without BOM
Bad character at 1, value 173
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'\x112\x0f\x9c\xd01q\xe3\x06\xe8':
Perhaps utf-8 without BOM
Bad character at 0, value 17
Decryption failed, trying next key.
Trying key:  b'b690a6ae24e27df354fe2f672599902b'
Checking text:b'\xce\xb2\xb9\x1b\x82\xdf\x80x\xd4\\':
Perhaps utf-8 without BOM
Bad character at 0, value 206
Decryption failed, trying next key.
Trying key:  b'68b5a443a8a044d88434dc5d5526ac5e'
Checking text:b'cf\xa4\x10\xd6\x9c\xa4O\xc9<':
Perhaps utf-8 without BOM
Bad character at 2, value 164
Decryption failed, trying next key.
Trying key:  b'6e791a67c328e65a64c16d761337e7ee'
Checking text:b'\xdf\xecWH\x8e\x84\xb7\xa0\x8d+':
Perhaps utf-8 without BOM
Bad character at 0, value 223
Decryption failed, trying next key.
Trying key:  b'152a81d46e01cc4ed677fefb6ddd35a5'
Checking text:b'\xe9\xd0\xbe\xff\xdb\x00\xc88\xc6\xcc':
Perhaps utf-8 without BOM
Bad character at 0, value 233
Decryption failed, trying next key.
Trying key:  b'26fb99e2df545a49013cb70e43a51fd1'
Checking text:b'\x83a\xe8\xed\x9e\x8d\xe0\xbeV~':
Perhaps utf-8 without BOM
Bad character at 0, value 131
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt 魔法使いロゼの佐渡ライフ　１巻
DEBUG:  484.2 DecryptAddProgressDialog::do_book_action - book decryption failed: '魔法使いロゼの佐渡ライフ　１巻'
Obok DeDRM v10.0.9 - Decrypting 魔法使いロゼの佐渡ライフ　２巻
Trying key:  b'dec1cdcde83b1eec9cbdca470187830e'
Checking text:b'+\xcc\xf0\xb5\x8f\xca\x80\x07\xb2\xf8':
Perhaps utf-8 without BOM
Bad character at 1, value 204
Decryption failed, trying next key.
Trying key:  b'b83dac8cfc520190ebec5cdea072a2c5'
Checking text:b'\x95\x15\xc5o\xda(\xad\xa0\x11\\':
Perhaps utf-8 without BOM
Bad character at 0, value 149
Decryption failed, trying next key.
Trying key:  b'35806a14fb2c4f4060a42dbb45ca7f00'
Checking text:b'\xd6\xfbL\xe2\xf4F\x13\xd6\x82\x7f':

```

**Comment by ElleKayEm** [comment]
Are you adding several books at once?  Have you tried adding just one?
