### ISSUE TITLE
Kobo desktop app drm not removed after "success" being reported by app

### ISSUE THREAD

**Issue by lennartgithub123** [noDRM/DeDRM_tools#485]
### Question / bug report

I have installed the kobo desktop app on my mac and use calibre with the obok dedrm plugin to remove drm. All seems to work fine, but when I try to open the ebook, it is not decrypted.

### Which version of Calibre are you running?

7.4

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

calibre 7.4  embedded-python: True
macOS-14.3-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.3.0', 'Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.3', ('', '', ''), 'arm64')
Interface language: nl
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
Using calibre Qt style: True
[0.00] Starting up...
2024-02-05 08:56:25.774 calibre-debug[16406:652287] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[0.01] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.64] GUI main window shown
Key 'B' for shortcut Doorblader annotaties is already used by Boeken bijschaven, ignoring
[0.67] main UI initialized...
[0.67] Hiding splash screen
[0.93] splash screen hidden
[0.93] Started up in 0.93 seconds with 9 books
Running Obok DeDRM v10.0.9
DEBUG:    6.9 didn't find device
Obok v10.0.9
Copyright © 2012-2023 Physisticated et al.
/var/folders/fw/6d5v973s237g27jmrnf4j5sh0000gn/T/tmpnganwpfg
DEBUG:    6.9 got kobodir /Users/xxxx/Library/Application Support/Kobo/Kobo Desktop Edition
Error parsing Kobo plist: no legacy user key found.
Found 44 possible keys to try.
DEBUG:   21.0 BookListTableWidget:get_books - book_num: 34
DEBUG:   21.0 BookListTableWidget:get_books - book: The art of war
DEBUG:   21.0 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.9 - Decrypting The art of war
Trying key:  b'a376be40dafd162827a1c99c5e03efd2'
Success!
DEBUG:   21.1 DecryptAddProgressDialog::do_book_action - decrypted book: 'The art of war'
Traceback (most recent call last):
  File "calibre/db/cache.py", line 1859, in set_metadata
  File "calibre/db/cache.py", line 1782, in set_cover
  File "calibre/db/backend.py", line 1769, in set_cover
  File "calibre/utils/img.py", line 301, in save_cover_data_to
  File "calibre/utils/img.py", line 209, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
Obok DeDRM v10.0.9 - Added The Art of War
Obok DeDRM v10.0.9 - wrapping up results.
Added README to db in: 0.0
Added 1 books in 0.3 seconds
Added README to db in: 0.0
Added 1 books in 4.3 seconds
Added 0 books in 4.2 seconds

**Comment by ElleKayEm** [comment]
Book won't open in calibre at all?

**Comment by lennartgithub123** [comment]
Nope, only shows weird symbols. However when I load the ebooks in my kobo reader and then try to decrypt them it does work as expected. It seems that the desktop app has a different type of encryption/protection than the books that are stored on the e-reader itself.

**Comment by ElleKayEm** [comment]
Okay, I've occassionally had Obok mistakenly show something as DRM-free (open green lock in Obok's list).  Restarting Kobo Desktop and calibre has resolved it for me.  The book will then show as having DRM (red closed lock) and Obok successfully removes the DRM.  Someone else here said closing the Kobo app after downloading their book kept them from having the issue.

**Comment by lennartgithub123** [comment]
Thanks for you replies and help! I restarted the apps, but it still shows as DRM-free and decryption does not work.

**Comment by ElleKayEm** [comment]
Glad it works from your Kobo at least.  And there's also the option of downloading via Adobe Digital Editions and DeDRM.
