### ISSUE TITLE
Can't open a DRM protected book ePub (imported as a .lcpl file) in Calibre 64bit

### ISSUE THREAD

**Issue by Fugue4all** [noDRM/DeDRM_tools#490]
### Question / bug report

Hi-have tried all the recommendations re DRM 7.2.1 plugin not working-no joy.,,, help appreciated

### Which version of Calibre are you running?

6.10

### Which version of the DeDRM plugin are you running?

v7.2.1

### Log output

```log
Paste log output here.
```ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: LCPL Input (0, 0, 5) && Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && Set KFX metadata (from KFX Output) (2, 6, 1) && KFX Output (2, 6, 1)
calibre 6.10  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: LCPL Input (0, 0, 5) && Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && Set KFX metadata (from KFX Output) (2, 6, 1) && KFX Output (2, 6, 1)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 93.2912482065997 x 93.3061224489796
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.12] db initialized
[0.12] Constructing main UI...
Loaded cached store plugin for: Amazon DE Kindle at version: 16
Loaded cached store plugin for: Barnes and Noble at version: 4
Loaded cached store plugin for: Ebookpoint at version: 9
Loaded cached store plugin for: eBooks.com at version: 4
Loaded cached store plugin for: Empik at version: 10
Loaded cached store plugin for: Legimi at version: 12
Loaded cached store plugin for: Nexto at version: 7
Loaded cached store plugin for: Virtualo at version: 12
Loaded cached store plugin for: Wolne Lektury at version: 4
Screens currently in system:
{'depth': 32,
 'device_pixel_ratio': 1.5,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0}}
Restoring geometry for: calibre_main_window_geometry
{'frame_geometry': {'height': 770, 'width': 1227, 'x': 56, 'y': 377},
 'full_screened': False,
 'geometry': {'height': 740, 'width': 1227, 'x': 56, 'y': 407},
 'maximized': False,
 'normal_geometry': {'height': 740, 'width': 1227, 'x': 56, 'y': 407},
 'screen': {'depth': 32,
            'device_pixel_ratio': 1.5,
            'geometry_in_logical_pixels': {'height': 1440,
                                           'width': 2560,
                                           'x': 0,
                                           'y': 0},
            'index_in_screens_list': 0,
            'manufacturer': '',
            'model': '',
            'name': '\\\\.\\DISPLAY2',
            'serial': '',
            'size_in_logical_pixels': {'height': 1440, 'width': 2560},
            'virtual_geometry': {'height': 1440,
                                 'width': 2560,
                                 'x': 0,
                                 'y': 0}}}
Matching screen: {'depth': 32,
 'device_pixel_ratio': 1.5,
 'geometry_in_logical_pixels': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0},
 'index_in_screens_list': 0,
 'manufacturer': '',
 'model': '',
 'name': '\\\\.\\DISPLAY2',
 'serial': '',
 'size_in_logical_pixels': {'height': 1440, 'width': 2560},
 'virtual_geometry': {'height': 1440, 'width': 2560, 'x': 0, 'y': 0}}
Setting widget geometry to: {'height': 740, 'width': 1227, 'x': 56, 'y': 407}
[1.14] main UI initialized...
[1.14] Hiding splash screen
Starting QuickView
[22.98] splash screen hidden
[22.98] Started up in 22.98 seconds with 1 books

Debugging DND event
application/x-qt-windows-mime;value="Shell IDList Array" 228 b'\x01\x00\x00\x00\x0c\x00\x00\x00\\\x00\x00\x00\x14\x00\x1fP\xe0O\xd0 \xea:i\x10\xa2\xd8\x08\x00+00\x9d:\x00.\x80\x059\x8e\x08#\x03\x02K\x98&]\x99B\x8e\x11_&\x00\x01\x00&\x00\xef\xbe\x11\x00\x00\x00j\x93\xc5\x06~\x82\xd7\x01\x14\xb7\xe8\x0c/]\xda\x01\x1f\xf1\xdb\x10/]\xda\x01\x14\x00\x00\x00\x86\x002\x00\x9a\n\x00\x00KXP\xab \x00isbn_9780847831470.lcpl\x00`\x00\t\x00\x04\x00\xef\xbeKXP\xabKXP\xab.\x00\x00\x00Q,\r\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Th\x0b\x01i\x00s\x00b\x00n\x00_\x009\x007\x008\x000\x008\x004\x007\x008\x003\x001\x004\x007\x000\x00.\x00l\x00c\x00p\x00l\x00\x00\x00&\x00\x00\x00' 

application/x-qt-windows-mime;value="UsingDefaultDragImage" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="DragImageBits" 82968 b'\x90\x00\x00\x00\x90\x00\x00\x00H\x00\x00\x00\x85\x00\x00\x00\xe3\x0f\x05\xb5\xff\xff\xff\xff\x00\x00\x00\x02\x00\x00\x00\x11\x00\x00\x00\x1b\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c\x00\x00\x00\x1c' 

application/x-qt-windows-mime;value="DragContext" 16 b'\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 

application/x-qt-windows-mime;value="DragSourceHelperFlags" 4 b'\x01\x00\x00\x00' 

application/x-qt-windows-mime;value="InShellDragLoop" 4 b'\x01\x00\x00\x00' 

text/uri-list 66 b'file:///C:/Users/Paul%20Dingle/Downloads/isbn_9780847831470.lcpl\r\n' 

application/x-qt-windows-mime;value="FileName" 51 b'C:\\Users\\PAULDI~1\\DOWNLO~1\\isbn_9780847831470.lcpl\x00' 

application/x-qt-windows-mime;value="FileContents" 0 b'' 

application/x-qt-windows-mime;value="FileNameW" 110 b'C\x00:\x00\\\x00U\x00s\x00e\x00r\x00s\x00\\\x00P\x00a\x00u\x00l\x00 \x00D\x00i\x00n\x00g\x00l\x00e\x00\\\x00D\x00o\x00w\x00n\x00l\x00o\x00a\x00d\x00s\x00\\\x00i\x00s\x00b\x00n\x00_\x009\x007\x008\x000\x008\x004\x007\x008\x003\x001\x004\x007\x000\x00.\x00l\x00c\x00p\x00l\x00\x00\x00' 

application/x-qt-windows-mime;value="FileGroupDescriptorW" 596 b'\x01\x00\x00\x00l\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\xf4}\xfb0]\xda\x01\x00\x00\x00\x00\x00\x00\x00\x00\xac\x8br\xfa0]\xda\x01\x00\x00\x00\x00\x9a\n\x00\x00i\x00s\x00b\x00n\x00_\x009\x007\x008\x000\x008\x004\x007\x008\x003\x001\x004\x007\x000\x00.\x00l\x00c\x00p\x00l\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' 


Firefox rurl: None None
URLS: ['file:///C:/Users/XX%20XX/Downloads/isbn_9780847831470.lcpl']
Paths: ['C:/Users/XX/Downloads/isbn_9780847831470.lcpl']
Extensions: frozenset({'lcpl'})
DeDRM v7.2.1: Trying to decrypt lutwlhh0.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: “lutwlhh0.epub” is neither an Adobe Adept nor a Barnes & Noble encrypted ePub
LCPL Input v0.0.5: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.lcplinput.__init__", line 368, in run
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 420, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Couldn't decrypt after 0.3 seconds. DRM free perhaps?
LCPL Input v0.0.5: Trying to parse file isbn_9780847831470.lcpl
LCPL Input v0.0.5: Looks like this is a LCPL license file
LCPL Input v0.0.5: Found LCPL for book ID a2904395-1770-4eba-8f98-1a5bcd2131e9
LCPL Input v0.0.5: Downloading book from https://archive.org/download/isbn_9780847831470/isbn_9780847831470_lcp.epub with default UA ...
LCPL Input v0.0.5: Executing plugin DeDRM ...
LCPL Input v0.0.5: Plugin returned nothing - skipping

**Comment by ElleKayEm** [comment]
DeDRM does not support removal of this type of DRM.  It did briefly but Readium issued a DMCA takedown request.  So GitHub closed this repo until that part of the code was removed.  See this post for more details: https://github.com/noDRM/DeDRM_tools/issues/18
