### ISSUE TITLE
Obok DeDRM error when clicked on the button

### ISSUE THREAD

**Issue by horieva** [noDRM/DeDRM_tools#492]
### Question / bug report

Hello, I have the error when I click to Obok DeDRM button in the Calibre.
Adobe isn't installed only latest Kobo Desktop. 
How I can fix that? 
Thank you.

### Which version of Calibre are you running?

7.5.1

### Which version of the DeDRM plugin are you running?

7.2.1

### Log output

```log
calibre, version 7.5.1
ERROR: Unhandled Expection:: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 7.5.1  embedded-python: True
macOS-14.3.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.3.0', 'Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.3.1', ('', '', ''), 'arm64')
Interface language: ru
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
    dlg = SelectionDialog(self.gui, self, books)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
    self.books_table.populate_table(self.books)
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
    self.populate_table_row(row, book)
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
    status_cell = IconWidgetItem(None, icon, val)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
    ReadOnlyTableWidgetItem.__init__(self, text)
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
    QTableWidgetItem.__init__(self, text, QTableWidgetItem.UserType)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

```

**Comment by ElleKayEm** [comment]
Try Obok 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by horieva** [comment]
It works, thank you!
