### ISSUE TITLE
Unable to drm file

### ISSUE THREAD

**Issue by fedex-bermu** [noDRM/DeDRM_tools#495]
### Question / bug report

I'm trying to dedrm an epub ADE file and although keys are imported on the config it still shows an error

### Which version of Calibre are you running?

7.5.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Failed to initialize plugin: 'C:\\Users\\feder\\AppData\\Roaming\\calibre\\plugins\\Goodreads_Rating.zip'
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 777, in initialize_plugins
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 308, in load
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 200, in exec_module
  File "calibre\customize\zipplugin.py", line 196, in get_code
  File "calibre_plugins.goodreads_rating.__init__", line 29
    	version = (3, 0, 0 )
    ^
TabError: inconsistent use of tabs and spaces in indentation
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.5.1  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 8, 1) && Find Duplicates (1, 10, 8) && Goodreads (1, 7, 9) && Goodreads Sync (1, 16, 4) && Job Spy (1, 0, 239) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && KePub Input (3, 6, 6) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 6) && Kobo Books (1, 9, 2) && Kobo Metadata (1, 4, 0) && Kobo Utilities (2, 16, 13) && KoboTouchExtended (3, 6, 7) && Obok DeDRM (7, 2, 1) && Smashwords Metadata (1, 0, 2)
calibre 7.5.1  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 8, 1) && Find Duplicates (1, 10, 8) && Goodreads (1, 7, 9) && Goodreads Sync (1, 16, 4) && Job Spy (1, 0, 239) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && KePub Input (3, 6, 6) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 6) && Kobo Books (1, 9, 2) && Kobo Metadata (1, 4, 0) && Kobo Utilities (2, 16, 13) && KoboTouchExtended (3, 6, 7) && Obok DeDRM (7, 2, 1) && Smashwords Metadata (1, 0, 2)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 121.11258278145695 x 120.95238095238095
[0.00] Starting up...
[0.01] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.11] GUI main window shown
Job Spy has begun initialization...
Calibre, and hence Job Spy, was gracefully shut down last time?  True
Last time daemon started:  never
Last time daemon failed:  never
Total daemon starts inception_to_date:  0
Total daemon failures inception-to-date:  0
JS: ===>>> change_gui_alternating_row_colors()
Job Spy has finished initialization...
DEBUG:    0.5 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.5 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.5 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.5 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
[1.28] main UI initialized...
[1.28] Hiding splash screen
Failed to initialize plugin: 'C:\\Users\\feder\\AppData\\Roaming\\calibre\\plugins\\Goodreads_Rating.zip'
DeDRM v10.0.3: Trying to decrypt Historia económica de la Argentina.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Historia económica de la Argentina.epub is a secure Adobe Adept ePub for UUID 02696a06-d0e7-11ee-8a68-ef0712f85452
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
[4.00] splash screen hidden
[4.00] Started up in 4.00 seconds with 500 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"db2\xa9\xdb^v\x9e:\xc7,@'\xa4r\x99R\xf5\xdd~\x96%\xdf=\xcf\n\xb3\xee\xe4\xba1\xd3", b'C:\\Users\\feder\\Desktop\\Historia econ\xc3\xb3mica de la Argentina.epub']
Added Historia económica de la Argentina to db in: 0.1
Added 1 books in 0.5 seconds
Worker Launch took: 0.03 seconds

```

**Comment by ElleKayEm** [comment]
Delete the saved Adobe key from DeDRM's customization.  Re-add the book letting DeDRM automatically retrieve the key.  You may also want to try DeDRM 10.0.9.
