### ISSUE TITLE
Obok DeDRM says successfully, but it is impossible to open, there is no cover and the name is made of random letters

### ISSUE THREAD

**Issue by Dantobine** [noDRM/DeDRM_tools#497]
### Question / bug report

![image_2024-02-23_15-36-32](https://github.com/noDRM/DeDRM_tools/assets/131992403/47dacd92-71ca-4d66-a604-787b32bf875a)
*I bought the book*

### Which version of Calibre are you running?

7.5.1

### Which version of the DeDRM plugin are you running?

10.0.9

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Журнал зневаджування
calibre 7.5.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: uk
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
calibre 7.5.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: uk
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 76.83781388478582 x 76.86052009456264
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.50] GUI main window shown
[0.83] main UI initialized...
[0.83] Hiding splash screen
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 176, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 217, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 155, in read_bytes
  File "calibre\utils\zipfile.py", line 1005, in read
  File "calibre\utils\zipfile.py", line 1033, in open
  File "calibre\utils\zipfile.py", line 994, in getinfo
KeyError: "There is no item named 'OPS/advanced.opf' in the archive"

**Comment by Dantobine** [comment]
Hmm, it appears with red lock, but after it's looks like that,, Before that, it worked, I have already reinstalled both the kobo app and calibre,, changed accounts in kobo and adobe id🤔☹️

**Comment by ElleKayEm** [comment]
Obok worked before with other books?  If that's the case, I'd say it's an issue with the book itself.  Have you tried downloading it via Adobe Digital Editions and using regular DeDRM?

**Comment by Dantobine** [comment]
Ok, so, I put this file in Adobe Digital Editions and it works, but now what I need to do to get book?

**Comment by Dantobine** [comment]
It's still with the same name end it's epub, I don't know where is acsm stores, and in appdata of kobo only kepubs

**Comment by Dantobine** [comment]
So sorry for the spam! That's what calibre says

calibre, version 7.5.1
ПОМИЛКА: Не вдалося завантажити книгу: Не вдалося відкрити книгу D:\CALIBRE\Nievidomii\nufszg7s (37)\nufszg7s - Nievidomii.epub. Натисніть кнопку «Показати подробиці», щоб дізнатися більше.

Failed to convert book: D:\CALIBRE\Nievidomii\nufszg7s (37)\nufszg7s - Nievidomii.epub with error:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 175, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 237, in get_quick_metadata
  File "calibre\ebooks\metadata\epub.py", line 217, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 155, in read_bytes
  File "calibre\utils\zipfile.py", line 1005, in read
  File "calibre\utils\zipfile.py", line 1033, in open
  File "calibre\utils\zipfile.py", line 994, in getinfo
KeyError: "There is no item named 'OPS/advanced.opf' in the archive"
DeDRM v10.0.9: Trying to decrypt nufszg7s - Nievidomii.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 1.8 seconds
InputFormatPlugin: EPUB Input running
on C:\Users\valor\AppData\Local\Temp\calibre_3ginxyqd\1a9vysva.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 95, in <module>
  File "site.py", line 90, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 952, in viewer_main
  File "calibre\srv\render_book.py", line 943, in render_for_viewer
  File "calibre\srv\render_book.py", line 921, in render
  File "calibre\srv\render_book.py", line 718, in process_exploded_book
  File "calibre\srv\render_book.py", line 261, in create_cover_page
  File "calibre\srv\render_book.py", line 214, in find_epub_cover
  File "calibre\ebooks\oeb\polish\cover.py", line 284, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 430, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 41, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes

**Comment by ElleKayEm** [comment]
Seeing that same error here:

> KeyError: "There is no item named 'OPS/advanced.opf' in the archive"

Seems like it is some internal issue with the book itself.  I don't know how to resolve that.
