### ISSUE TITLE
DeDRM doesn't work

### ISSUE THREAD

**Issue by naoki223tani** [noDRM/DeDRM_tools#499]
### Question / bug report

After setting up DeDRM, I successfully imported the file. However, when attempting to convert it to PDF, I encountered a DRM warning indicating that the book is locked. I had previously been able to convert AZW3 files without any issues. I'm uncertain about what might have changed. The Kindle file extension is .azw3.

### Which version of Calibre are you running?

7.51

### Which version of the DeDRM plugin are you running?

7.2.1 & 10.0.9

### Log output

```log
Blacklisting the DeDRM plugin as it is too old and causes crashes
ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-02-24 08:21:52.691 calibre-debug[2044:35714] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
calibre Debug log
calibre 7.5.1  embedded-python: True
macOS-14.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.2', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
calibre 7.5.1  embedded-python: True
macOS-14.2-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.2', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (7, 2, 1) && Obok DeDRM (7, 2, 1)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.47] GUI main window shown
[0.52] main UI initialized...
[0.52] Hiding splash screen
Blacklisting the DeDRM plugin as it is too old and causes crashes
[11.31] splash screen hidden
[11.31] Started up in 11.31 seconds with 2574 books
Added このビジネスモデルがすごい！―――グレートカンパニー研究からわかった優秀企業の条件 to db in: 0.0
Added 1 books in 0.4 seconds
Blacklisting the DeDRM plugin as it is too old and causes crashes
2024-02-24 08:22:13.617 calibre-parallel[2063:36241] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
2024-02-24 08:22:15.414 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.414 QtWebEngineProcess[2067:36304] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2024-02-24 08:22:15.415 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.415 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.415 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.415 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.415 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.416 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.417 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.418 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.419 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.419 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2024-02-24 08:22:15.419 QtWebEngineProcess[2067:36304] CoreText note: Client requested name ".HiraKakuInterface-W4", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
qt.qpa.fonts: Populating font family aliases took 86 ms. Replace uses of missing font family "Times" with one that exists to avoid this cost. 
Failed to request permission for showing notification: The operation couldn’t be completed. (UNErrorDomain error 1.)
Worker Launch took: 0.03 seconds
Worker Launch took: 0.03 seconds
Job: 1 Convert book 1 of 1 (このビジネスモデルがすごい！―――グレートカンパニー研究からわかった優秀企業の条件) finished
Convert book 1 of 1 (このビジネスモデルがすごい！―――グレートカンパニー研究からわかった優秀企業の条件)
	Blacklisting the DeDRM plugin as it is too old and causes crashes
	Conversion options changed from defaults:
	  pdf_mono_family: 'Menlo'
	  pdf_serif_family: 'Symbol'
	  cover: '/var/folders/27/8k5hyfnn3zgb28ntllq4p8zm0000gn/C/calibre_7.5.1_tmp_1o0q9xe_/mr8_47y_.jpeg'
	  read_metadata_from_opf: '/var/folders/27/8k5hyfnn3zgb28ntllq4p8zm0000gn/C/calibre_7.5.1_tmp_1o0q9xe_/fj8mmydv.opf'
	  verbose: 2
	  output_profile: 'kindle'
	Resolved conversion options
	calibre version: 7.5.1
	{'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/27/8k5hyfnn3zgb28ntllq4p8zm0000gn/C/calibre_7.5.1_tmp_1o0q9xe_/mr8_47y_.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11af8c290>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindleOutput object at 0x11c134290>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Menlo',
	 'pdf_mono_font_size': 16,
	 'pdf_no_cover': False,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Helvetica',
	 'pdf_serif_family': 'Symbol',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/27/8k5hyfnn3zgb28ntllq4p8zm0000gn/C/calibre_7.5.1_tmp_1o0q9xe_/fj8mmydv.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	InputFormatPlugin: MOBI Input running
	on /var/folders/27/8k5hyfnn3zgb28ntllq4p8zm0000gn/C/calibre_7.5.1_tmp_1o0q9xe_/01azweuc.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 41, in <module>
	  File "site.py", line 37, in main
	  File "calibre/utils/ipc/worker.py", line 215, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1108, in run
	  File "calibre/customize/conversion.py", line 242, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 44, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 85, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 162, in check_for_drm
	calibre.ebooks.DRMError: このビジネスモデルがすごい！―――グレートカンパニー研究からわかった優秀企業の条件


```

**Comment by ElleKayEm** [comment]
Use DeDRM 10.0.9.  As the log says, 7.2.1 is too old for this version of calibre.
