### ISSUE TITLE
Python issue with DeDRM

### ISSUE THREAD

**Issue by benedictgoodman** [noDRM/DeDRM_tools#500]
### Question / bug report

Hi Team. I've run into an issue with importing .azw files into Calibre since switching to Calibre 7. Specifically I'm getting an 'ImportError: attempted relative import with no known parent package' python error. Am I doing something obviously wrong? See attached log output.

### Which version of Calibre are you running?

7.5.1

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

Kindle for PC v1.17

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.5.1  embedded-python: True
Linux-5.15.0-10091-tuxedo-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.15.0-10091-tuxedo', '#101~20.04.1tux3 SMP Fri Dec 8 12:19:54 UTC 2023')
Python 3.11.5
Interface language: None
EXE path: /home/bd/calibre-bin/calibre/bin/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 3)
calibre 7.5.1  embedded-python: True
Linux-5.15.0-10091-tuxedo-x86_64-with-glibc2.31 Linux ('64bit', 'ELF')
('Linux', '5.15.0-10091-tuxedo', '#101~20.04.1tux3 SMP Fri Dec 8 12:19:54 UTC 2023')
Python 3.11.5
Interface language: None
EXE path: /home/bd/calibre-bin/calibre/bin/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 3)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.7674418604651 x 142.13471502590673
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.59] GUI main window shown
[0.64] main UI initialized...
[0.64] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt B07DQVZY1X_EBOK.azw
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1019, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 904, in KindleMobiDecrypt
    import k4mobidedrm
  File "/home/bd/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 85, in <module>
    import mobidedrm
  File "/home/bd/.config/calibre/plugins/DeDRM.zip/mobidedrm.py", line 88, in <module>
    from .alfcrypto import Pukall_Cipher
ImportError: attempted relative import with no known parent package
[7.77] splash screen hidden
[7.77] Started up in 7.77 seconds with 186 books
['zenity', '--modal', '--file-selection', '--title=Select root folder', '--separator=\n', '--attach=62914585', '--directory', '--filename', '/home/bd']
Added Name of Book to db in: 0.3
Added 1 books in 0.6 seconds

**Comment by noDRM** [comment]
This error happens when you're running the plugin from source. You'll either need to download the actual plugin file, or if you want to build from source, run the make_release.py script.
