### ISSUE TITLE
Wont delete DRM

### ISSUE THREAD

**Issue by nhermis** [noDRM/DeDRM_tools#501]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-02-25 14:57:17.381 calibre-debug[50766:4710547] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 7.5.1  embedded-python: True
macOS-14.2.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1)
calibre 7.5.1  embedded-python: True
macOS-14.2.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 94.00000141173837 x 95.00000142675685
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.15] db initialized
[0.15] Constructing main UI...
[0.63] GUI main window shown
[0.66] main UI initialized...
[0.66] Hiding splash screen
DeDRM v10.0.3: Trying to decrypt Steppenwolf.azw3
Using Library AlfCrypto Python
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Steppenwolf
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ninoshermis/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/ninoshermis/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[2.91] splash screen hidden
[2.91] Started up in 2.91 seconds with 11 books
Added Steppenwolf to db in: 0.0
Added 1 books in 0.3 seconds

### Which version of Calibre are you running?

7.5.1

### Which version of the DeDRM plugin are you running?

v10.0.03

### If applicable, which version of the Kindle software are you running?

5.16.6

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Is that an E-ink Kindle book?  Not a Fire?  If so, enter the E-ink Kindle's serial number into DeDRM's customization.

**Comment by nhermis** [comment]
I did. Still didnt work. Its an Kindle Oasis

**Comment by ElleKayEm** [comment]
Make sure you choose your Oasis when downloading.  Try copy pasting the serial number from the website.  Click ok and apply on your way out of the dialog boxes after adding your serial number.  Then restart calibre before re-adding your book.

**Comment by nhermis** [comment]
Sorry downloading what? The DeDRM software?

**Comment by ElleKayEm** [comment]
Downloading the book.  Copying the serial number of your Oasis from your content and device page at Amazon.
