### ISSUE TITLE
Problems with Adobe/ACSM 

### ISSUE THREAD

**Issue by couldwenot** [noDRM/DeDRM_tools#504]
### Question / bug report

I used DeACSM/DeDRM to open an ACSM file a few days ago, but today it isn't working. Nothing had changed from when I opened the file the first time, and today I updated both calibre and DeDRM to the latest versions. A friend sent me the actual epub, too, but that epub gives the error message "this book is locked by DRM." 

### Which version of Calibre are you running?

7.51

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
DeDRM v10.0.9: Trying to decrypt Funny_Story.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Funny_Story.epub is a secure Adobe Adept ePub for UUID 99ca7a08-24ef-408a-81e7-1d3153855678
DeDRM v10.0.9: Trying Encryption key adobe_uuid_f984749f-d533-4d24-9b65-771bd4f8b1e2
fqv3q52b.epub is a secure Adobe Adept ePub.
Could not decrypt fqv3q52b.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\[NAME]\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\[NAME]\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key adobe_uuid_f984749f-d533-4d24-9b65-771bd4f8b1e2 after 0.1 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "C:\Users\[NAME]\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 289, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\[NAME]\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 292, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[17.97] splash screen hidden
[17.97] Started up in 17.97 seconds with 203 books
```

**Comment by ElleKayEm** [comment]
Your friend's copy of the book is presumably tied to their Adobe ID.  They would have to decrypt it on the computer where they downloaded it.

You downloaded your epub with DeACSM?  Try manually saving the Adobe Key from DeACSM and then importing it into DeDRM's customization.

**Comment by couldwenot** [comment]
No, I got the epub version from the same person (I couldn't get the epub out of the ACSM). I assume that means they're both locked to their ID? Or is there a way I can get the Adobe Key from the epub I received?

**Comment by ElleKayEm** [comment]
They would need to decrypt the epub.  The key would be on their computer and also encrypted.
