### ISSUE TITLE
DrDRM not removing DRM from an Adobe epub file

### ISSUE THREAD

**Issue by jgvallejo2018** [noDRM/DeDRM_tools#510]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.6  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.6  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.58503401360545 x 110.83636363636363
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[0.91] GUI main window shown
[1.05] main UI initialized...
[1.05] Hiding splash screen
[2.42] splash screen hidden
[2.42] Started up in 2.42 seconds with 1 books
DeDRM v10.0.3: Trying to decrypt Guia contable y fiscal de la industria del cine y audiovisual.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Guia contable y fiscal de la industria del cine y audiovisual.epub is a secure Adobe Adept ePub for UUID 43f15eed-9ecd-440e-a078-d097e8060dc9
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "C:\Users\student\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 344, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\student\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 346, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'J\x0er\xe6\xc8\x19\n\xc2|\xadqB\x8a\x84U\x0b+5\xddw\xba\xc8\x18\xa7\xa9\x968\x19OA\x1b\xb6', b'C:\\Users\\student\\Desktop\\Guia contable y fiscal de la industria del cine y audiovisual.epub']
Added Guia contable y fiscal de la industria del cine y audiovisual to db in: 0.1

### Which version of Calibre are you running?

7.6.0

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Paste log output here.
```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.6  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.6  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.58503401360545 x 110.83636363636363
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[0.91] GUI main window shown
[1.05] main UI initialized...
[1.05] Hiding splash screen
[2.42] splash screen hidden
[2.42] Started up in 2.42 seconds with 1 books
DeDRM v10.0.3: Trying to decrypt Guia contable y fiscal de la industria del cine y audiovisual.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Guia contable y fiscal de la industria del cine y audiovisual.epub is a secure Adobe Adept ePub for UUID 43f15eed-9ecd-440e-a078-d097e8060dc9
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "C:\Users\student\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 344, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\student\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 346, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'J\x0er\xe6\xc8\x19\n\xc2|\xadqB\x8a\x84U\x0b+5\xddw\xba\xc8\x18\xa7\xa9\x968\x19OA\x1b\xb6', b'C:\\Users\\student\\Desktop\\Guia contable y fiscal de la industria del cine y audiovisual.epub']
Added Guia contable y fiscal de la industria del cine y audiovisual to db in: 0.1

**Comment by ElleKayEm** [comment]
DeDRM is unable to find your Adobe key.  Do you not have ADE installed on this computer?

**Comment by jgvallejo2018** [comment]
I do have ADE installed. I reínstalled it, but no success

**Comment by jgvallejo2018** [comment]
> DeDRM is unable to find your Adobe key. Do you not have ADE installed on this computer?

When I reinstalled it, this debug log appeared, which did change:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.6  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.6  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.58503401360545 x 110.83636363636363
[0.00] Starting up...
[0.00] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
[1.09] GUI main window shown
[1.17] main UI initialized...
[1.17] Hiding splash screen
[2.34] splash screen hidden
[2.34] Started up in 2.34 seconds with 1 books
DeDRM v10.0.3: Trying to decrypt Guia contable y fiscal de la industria del cine y audiovisual.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: Guia contable y fiscal de la industria del cine y audiovisual.epub is a secure Adobe Adept ePub for UUID 43f15eed-9ecd-440e-a078-d097e8060dc9
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "C:\Users\student\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 344, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
  File "C:\Users\student\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 346, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x80\xa0\xe4\x90\x91HZ\xf6\xfd\xf3\xe6$;w\xe8$\x8d\x87\xba\xa5\xd2\xc0\x11\xfc\x81\xfa\xd6)\xf4\xda\x9e\x10', b'C:\\Users\\student\\Desktop\\Guia contable y fiscal de la industria del cine y audiovisual.epub']
Added Guia contable y fiscal de la industria del cine y audiovisual to db in: 0.1

**Comment by ElleKayEm** [comment]
Can you open and read the book with ADE on this computer?  Did you originally download the epub with a different installation of ADE?
