### ISSUE TITLE
My books arent getting their DRM removed

### ISSUE THREAD

**Issue by AadityaShyam** [noDRM/DeDRM_tools#511]
### Question / bug report

My books aren't getting their DRM removed, but it was working perfectly fine before. 

### Which version of Calibre are you running?

6.29.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
Failed to initialize plugin: '/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip'
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 782, in initialize_plugins
  File "calibre/customize/ui.py", line 715, in initialize_plugin
calibre.customize.InvalidPlugin: Initialization of plugin Traceback (most recent call last):
  File "calibre/customize/ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
 failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 710, in initialize_plugin
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)

Using calibre Qt style: True
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
ApplicationPaletteChange event received
calibre Debug log
calibre 6.29  embedded-python: True
macOS-12.7.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.7.1', ('', '', ''), 'x86_64')
Interface language: None
Failed to initialize plugin: DeACSM (0, 0, 16)
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 6.29  embedded-python: True
macOS-12.7.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.7.1', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 128.00000192236715
[0.00] Starting up...
[0.03] Showing splash screen...
[0.32] splash screen shown
[0.32] Initializing db...
[0.32] db initialized
[0.32] Constructing main UI...
[1.04] main UI initialized...
[1.04] Hiding splash screen
Starting QuickView
[3.20] splash screen hidden
[3.20] Started up in 3.20 seconds with 0 books
Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
Failed to initialize plugin: '/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip'
Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 226, in initialize
    from libadobe import createDeviceKeyFile, update_account_path, sendHTTPRequest
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip/libadobe.py", line 59, in <module>
    from oscrypto import keys
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/keys.py", line 5, in <module>
    from ._asymmetric import parse_certificate, parse_private, parse_public
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_asymmetric.py", line 27, in <module>
    from .kdf import pbkdf1, pbkdf2, pkcs12_kdf
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/kdf.py", line 9, in <module>
    from .util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/util.py", line 10, in <module>
    from ._mac.util import rand_bytes
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_mac/util.py", line 208, in <module>
    from .._openssl._libcrypto import libcrypto
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto.py", line 24, in <module>
    from ._libcrypto_ctypes import (
  File "/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM/modules/oscrypto/oscrypto/_openssl/_libcrypto_ctypes.py", line 30, in <module>
    libcrypto = CDLL(libcrypto_path, use_errno=True)
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/usr/local/lib/libcrypto.dylib, 0x0006): tried: '/usr/local/lib/libcrypto.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' (code signature in <15D36922-90F9-35BF-8339-165FDCD6B4C7> '/usr/local/Cellar/openssl@3/3.2.0/lib/libcrypto.3.dylib' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)
Failed to initialize plugin: '/Users/aadityashyam/Library/Preferences/calibre/plugins/DeACSM.zip'
Failed to initialize plugin: DeACSM (0, 0, 16)
Failed to initialize plugin: DeACSM (0, 0, 16)
Added An Introduction to the EU Legal Order-pdf to db in: 0.0
Added An Introduction to the EU Legal Order-epub to db in: 0.0
Added 2 books in 0.7 seconds

**Comment by ElleKayEm** [comment]
DeDRM is not in use at all here.  What exactly are you trying to do?
