### ISSUE TITLE
Ebook epub DRM

### ISSUE THREAD

**Issue by MANLEFEU** [noDRM/DeDRM_tools#516]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Journal de débogage
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
[0.00] Starting up...
[0.02] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[0.92] GUI main window shown
[0.98] main UI initialized...
[0.98] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Ciao Bella.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Ciao Bella.epub is a secure Adobe Adept ePub for UUID f1710981-65fd-4802-867a-c1ccff3dcbd5
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v10.0.9: Trying a new default key
5h78_87a.epub is a secure Adobe Adept ePub.
Could not decrypt 5h78_87a.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\Manon\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\Manon\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with new default key after 0.5 seconds
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[6.55] splash screen hidden
[6.55] Started up in 6.55 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xffg\x1e?c\xb6q\x8a\x1e^[\x8c\xf3\xc8\xbd\xeb\x18\xb7L\xa0\x9e\xcc\x11\xc5\x8e\xe8\xed\xd1\xd4\xb2\xa6\x81', b'D:\\Users\\Manon\\Documents\\My Digital Editions\\Ciao Bella.epub']

### Which version of Calibre are you running?

7.7

### Which version of the DeDRM plugin are you running?

v10.0.9 (RC1 for 10.1.0)

### If applicable, which version of the Kindle software are you running?

Kindle 5.16.7

### Log output

```ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Journal de débogage
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
[0.00] Starting up...
[0.02] Showing splash screen...
[0.27] splash screen shown
[0.27] Initializing db...
[0.28] db initialized
[0.28] Constructing main UI...
[0.92] GUI main window shown
[0.98] main UI initialized...
[0.98] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Ciao Bella.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Ciao Bella.epub is a secure Adobe Adept ePub for UUID f1710981-65fd-4802-867a-c1ccff3dcbd5
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
Found 1 keys
DeDRM v10.0.9: Trying a new default key
5h78_87a.epub is a secure Adobe Adept ePub.
Could not decrypt 5h78_87a.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\Manon\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\Manon\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with new default key after 0.5 seconds
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[6.55] splash screen hidden
[6.55] Started up in 6.55 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xffg\x1e?c\xb6q\x8a\x1e^[\x8c\xf3\xc8\xbd\xeb\x18\xb7L\xa0\x9e\xcc\x11\xc5\x8e\xe8\xed\xd1\xd4\xb2\xa6\x81', b'D:\\Users\\Manon\\Documents\\My Digital Editions\\Ciao Bella.epub']

```

**Comment by ElleKayEm** [comment]
Was the book downloaded with ADE on the same computer and user as calibre/DeDRM?

**Comment by MANLEFEU** [comment]
The book was downloaded from public library numeric document forùat epub yes on the same computer and calibre

**Comment by ElleKayEm** [comment]
If there is a saved Adobe key in DeDRM's customization, delete it.  Restart calibre and re-add your book letting DeDRM automatically retrieve the key.

**Comment by Thisio** [comment]
Hi,
I just had this same issue, because i tried to remove DRM from another PC than the one that downloaded to .epub file.
I tried to directly convert from the initial PC, and it works ! Thanks a lot :)
