### ISSUE TITLE
ADE DRM not removed

### ISSUE THREAD

**Issue by Thaoden** [noDRM/DeDRM_tools#526]
### Question / bug report

DRM removal from ADE 4.5 stopped working suddenly. I tried removing the key and letting DeDRM find the default key, I also tried adding the current key, neither solved the problem.

### Which version of Calibre are you running?

7.7

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
Using calibre Qt style: False
calibre Debug log
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Copy Cover To Device (2, 0, 4) && Find Duplicates (1, 10, 8) && Generate Cover (2, 3, 2) && Kindle Collections (1, 7, 29) && Reading List (1, 15, 1)
calibre 7.7  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Copy Cover To Device (2, 0, 4) && Find Duplicates (1, 10, 8) && Generate Cover (2, 3, 2) && Kindle Collections (1, 7, 29) && Reading List (1, 15, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 90.0253164556962 x 90.10135135135135
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.92] GUI main window shown
[0.95] main UI initialized...
[0.95] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt file.pdf
DeDRM v10.0.9: file.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.9: file.pdf is a PDF ebook (EBX) for UUID 3659de7a-03ff-40d0-b7b3-32e17faxxxxx
DeDRM v10.0.9: Trying UUID-matched encryption key 3659de7a-03ff-40d0-b7b3-32e17faxxxxx_AdobeID_yyyyyy@yyyyy.yy
error writing pdf: 'utf-8' codec can't decode byte 0xa7 in position 5: invalid start byte
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 2367, in decryptBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 2181, in dump
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1908, in getobj
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 712, in nextobject
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 586, in nexttoken
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 425, in parse_literal
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 246, in intern
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 205, in __init__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 5: invalid start byte
DeDRM v10.0.9: Trying encryption key 3659de7a-03ff-40d0-b7b3-32e17faxxxxx_AdobeID_yyyyyy@yyyyy.yy
[15.98] splash screen hidden
[15.98] Started up in 15.98 seconds with 543 books
error writing pdf: 'utf-8' codec can't decode byte 0xa7 in position 5: invalid start byte
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 2367, in decryptBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 2181, in dump
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1908, in getobj
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 712, in nextobject
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 586, in nexttoken
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 425, in parse_literal
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 246, in intern
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 205, in __init__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 5: invalid start byte
DeDRM v10.0.9: Failed to decrypt with key 3659de7a-03ff-40d0-b7b3-32e17faxxxxx_AdobeID_yyyyyy@yyyyy.yy after 0.8 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.8 seconds
Found 1 keys
DeDRM v10.0.9: Trying a new default key
error writing pdf: 'utf-8' codec can't decode byte 0xa7 in position 5: invalid start byte
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 2367, in decryptBook
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 2181, in dump
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1908, in getobj
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 712, in nextobject
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 586, in nexttoken
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 425, in parse_literal
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 246, in intern
  File "C:\Users\xxx\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 205, in __init__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 5: invalid start byte
DeDRM v10.0.9: Failed to decrypt with new default key after 1.3 seconds
DeDRM v10.0.9: Finished after 1.3 seconds
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo errored out with return code: 1

```

**Comment by ElleKayEm** [comment]
Try deauthorizing and reauthorizing ADE with your Adobe ID.  See this page: https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

And scroll down to the instructions under TROUBLESHOOTING REAUTHORIZATION AND DEAUTHORIZATION ISSUES ON WINDOWS.

**Comment by Thaoden** [comment]
I tried removing the ADE authorization via the reg editor and reauthorizing, still the book can't be imported in Calibre. The log is the same.

**Comment by ElleKayEm** [comment]
The book can be opened and read in ADE on the same computer and user as calibre/DeDRM?

Can I ask the source of the book?

**Comment by Thaoden** [comment]
> The book can be opened and read in ADE on the same computer and user as calibre/DeDRM?

Yes

> Can I ask the source of the book?

It's an online service of our local library.

**Comment by Thaoden** [comment]
I just tried with a different book, this time in `.epub` format - DeDRM works as usual here.

**Comment by ElleKayEm** [comment]
Ok, something with pdfs or at least that particular pdf.  @noDRM will probably need to take a look.

**Comment by tntturtl** [comment]
> I just tried with a different book, this time in `.epub` format - DeDRM works as usual here.

Same here. Calibre in version 7.10. Importing acsm file did nothing. Importing epub from ADE worked just fine.

**Comment by ElleKayEm** [comment]
You would need to open the acsm file in ADE to download the epub (or pdf).  Or use the DeACSM plugin.

**Comment by tntturtl** [comment]
> You would need to open the acsm file in ADE to download the epub (or pdf). Or use the DeACSM plugin.

That;s what I did. Opened acsm file in ADE. This created protected epub which I imported to Calibre with plugin already installed. I removed ADE key from the plugin prior to importing encrypted epub.

**Comment by ElleKayEm** [comment]
I was responding to this:

> Importing acsm file did nothing.

It wouldn't do anything unless you were using the DeACSM plugin (which replaces using ADE to download the actual book file.)

**Comment by sebasarena** [comment]
I guess that I have the same problem.

It was also with ADE 4.5 for Windows, and it's a PDF from Internet Archive.

**Comment by sebasarena** [comment]
This is my log:

```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Registro de depuración
calibre 7.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: es
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: es
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
[0.00] Starting up...
[0.00] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[0.98] GUI main window shown
[1.06] main UI initialized...
[1.06] Hiding splash screen
[2.52] splash screen hidden
[2.52] Started up in 2.52 seconds with 2 books
DeDRM v10.0.3: Trying to decrypt Bosie  a biography of Lord Alfred Douglas.pdf
DeDRM v10.0.3: Bosie  a biography of Lord Alfred Douglas.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: Bosie  a biography of Lord Alfred Douglas.pdf is a PDF ebook (EBX) for UUID bc2d5ff9-0fbf-4dde-a628-092b9372a657
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 923, in PDFDecrypt
  File "calibre_plugins.dedrm.__init__", line 695, in PDFIneptDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xc3s\xc3\xe2"P\xf7\xf9lI\xcc\x94\x8a\xf8\xf2\x94\xb5L\xe4\x01\t\x0f\x81\x92\x9bV\xaa\x1e\x13a,\xad', b'C:\\Users\\User\\Documents\\My Digital Editions\\Bosie  a biography of Lord Alfred Douglas.pdf']
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 325, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
```

**Comment by ElleKayEm** [comment]
@sebasarena 
Delete the Adobe Key from DeDRM customization.  Re-add your book letting DeDRM automatically retrieve the key.
