### ISSUE TITLE
Fail removing DRM for Kindle

### ISSUE THREAD

**Issue by Vivreausoleil** [noDRM/DeDRM_tools#527]
### Question / bug report

Hi, I'm unable to remove DRM from epub "L'Effondrement du capitalisme et du modèle américain". Any help will be welcome. This is Calibre's log:
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Journal de débogage
calibre 7.8  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Find Duplicates (1, 10, 9) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 1)
calibre 7.8  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Find Duplicates (1, 10, 9) && Kindle Collections (1, 7, 29) && Kindle hi-res covers (0, 5, 1)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 81.68844221105527 x 81.64285714285714
[0.00] Starting up...
[0.00] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.33] db initialized
[0.33] Constructing main UI...
[0.78] GUI main window shown
[0.84] main UI initialized...
[0.84] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Effondrement du capitalisme et du modèle américain. Nouvelle de collapsologie, L' - Tzvetan Zimovsky.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Effondrement du capitalisme et du modèle américain. Nouvelle de collapsologie, L' - Tzvetan Zimovsky.epub is a secure Adobe Adept ePub for UUID 9764c197-2b89-46b6-8051-b024fa8481b4
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 289, in adeptkeys
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\admin\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 292, in adeptkeys
adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[13.74] splash screen hidden
[13.74] Started up in 13.74 seconds with 7844 books
Added L'Effondrement du capitalisme et du modèle américain. Nouvelle de collapsologie to db in: 0.0
Added 1 books in 0.4 seconds

### Which version of Calibre are you running?

7.80

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

5.16.7

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Says that ADE is not activated.  Was this epub downloaded on a different computer?

**Comment by Vivreausoleil** [comment]
Hi,

I think so, but this computer is no longer available. And I don't remember whose organization I got it from. Hence my problem.
Any clue?

9 avr. 2024 00:00:22 ElleKayEm ***@***.***>:

**Comment by ElleKayEm** [comment]
Would it have been tied to an Adobe ID?  If so, you could install Adobe Digital Editions and authorize it with the same Adobe ID.  You need to be able to open the book in ADE.  Then DeDRM can get the key and unlock it.
