### ISSUE TITLE
Didn't manage to decrypt PDF. Make sure the correct password is entered in the settings.

### ISSUE THREAD

**Issue by skyejer** [noDRM/DeDRM_tools#531]
### Question / bug report

Can't remove DRM using the v10.0.9. Could anyone help please?

### Which version of Calibre are you running?

6.29.0

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
Paste log output here.
```Using calibre Qt style: True
calibre Debug log
calibre 6.29  embedded-python: True
macOS-11.7.10-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('11.7.10', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 6.29  embedded-python: True
macOS-11.7.10-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '20.6.0', 'Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('11.7.10', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
[0.00] Starting up...
[0.02] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[1.08] main UI initialized...
[1.08] Hiding splash screen
Starting QuickView
[7.49] splash screen hidden
[7.50] Started up in 7.50 seconds with 2 books
DeDRM v10.0.9: Trying to decrypt MAR PMP Exam Prep Study Notes 2024.pdf
DeDRM v10.0.9: Trying to decrypt NEW MAR PMP Exam Cheat Sheet 2024.pdf
DeDRM v10.0.9: MAR PMP Exam Prep Study Notes 2024.pdf is a PDF ebook with encryption Standard
DeDRM v10.0.9: Trying empty password ... exception
DeDRM v10.0.9: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 844, in PDFStandardDecrypt
    result = ineptpdf.decryptBook(userpassword, path_to_ebook, of.name)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2324, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2118, in __init__
    doc.initialize(userkey, inept)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1243, in initialize
    return self.initialize_standard(password, docid, param)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1525, in initialize_standard
    retval = self.check_owner_password(password, docid, param)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1316, in check_owner_password
    return self.check_owner_password_V5(password, param)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1336, in check_owner_password_V5
    if self.hash_V5(password, salt, userdata, param) == ownerdata:
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1396, in hash_V5
    E = self.process_with_aes(K[:16], True, K1, 64, K[16:32])
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1376, in process_with_aes
    aes = AES.new(key, AES.MODE_CBC, iv, False)
  File "Crypto/Cipher/AES.py", line 232, in new
  File "Crypto/Cipher/__init__.py", line 71, in _create_cipher
TypeError: Too many arguments for this mode
DeDRM v10.0.9: Didn't manage to decrypt PDF. Make sure the correct password is entered in the settings.
DeDRM v10.0.9: Finished after 0.2 seconds
DeDRM v10.0.9: NEW MAR PMP Exam Cheat Sheet 2024.pdf is a PDF ebook with encryption Standard
DeDRM v10.0.9: Trying empty password ... exception
DeDRM v10.0.9: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 844, in PDFStandardDecrypt
    result = ineptpdf.decryptBook(userpassword, path_to_ebook, of.name)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2324, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 2118, in __init__
    doc.initialize(userkey, inept)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1243, in initialize
    return self.initialize_standard(password, docid, param)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1525, in initialize_standard
    retval = self.check_owner_password(password, docid, param)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1316, in check_owner_password
    return self.check_owner_password_V5(password, param)
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1336, in check_owner_password_V5
    if self.hash_V5(password, salt, userdata, param) == ownerdata:
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1396, in hash_V5
    E = self.process_with_aes(K[:16], True, K1, 64, K[16:32])
  File "/Users/skylar/Library/Preferences/calibre/plugins/DeDRM.zip/ineptpdf.py", line 1376, in process_with_aes
    aes = AES.new(key, AES.MODE_CBC, iv, False)
  File "Crypto/Cipher/AES.py", line 232, in new
  File "Crypto/Cipher/__init__.py", line 71, in _create_cipher
TypeError: Too many arguments for this mode
DeDRM v10.0.9: Didn't manage to decrypt PDF. Make sure the correct password is entered in the settings.
DeDRM v10.0.9: Finished after 0.2 seconds

**Comment by ElleKayEm** [comment]
Looks like it has password protection.  I think you're out of luck if you don't know the password.
