### ISSUE TITLE
Can't add Kindle for Android Key

### ISSUE THREAD

**Issue by jbusnengo** [noDRM/DeDRM_tools#532]
I've been using Kindle for PC 1.17 for older books and Kindle for Android (via BlueStacks) for newer books for a while now. Recently, for some unknown reason, my Kindle for Android app updated itself to a current version, and I had to uninstall it and reinstall the old version. Unfortunately, that generated a new Kindle for Android key that I needed to add to NoDRM. I've managed to create the backup file using ADB, but whenever I try to add it to NoDRM, I get an odd file access error:

calibre, version 7.8.0
ERROR: Cannot open file or folder as it is in use: <p>Could not open the file: "C:\Users\Joe\AppData\Local\Temp\tmpkwpun56p". It is already opened in the following programs:<div>The main calibre program: C:\Program Files\Calibre2\calibre.exe

calibre 7.8  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && Count Pages (1, 13, 6) && Goodreads Sync (1, 16, 5) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && KePub Input (3, 6, 6) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 6) && Kindle hi-res covers (0, 5, 1) && Kobo Books (1, 9, 2) && Obok DeDRM (10, 0, 9) && Quality Check (1, 13, 10) && Save Composite Custom Columns (1, 1, 1) && Smashwords Metadata (1, 0, 2) && Unplugged (1, 0, 0)
Traceback (most recent call last):
  File "C:\Users\Joe\AppData\Roaming\calibre\plugins\DeDRM.zip\config.py", line 1424, in get_android_file
  File "C:\Users\Joe\AppData\Roaming\calibre\plugins\DeDRM.zip\androidkindlekey.py", line 251, in get_serials
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Joe\\AppData\\Local\\Temp\\tmpkwpun56p'

I've tried restarting both Calibre and my computer, but nothing seems to help. Does anyone have any ideas why or how to fix the key import? Thanks!

**Comment by ElleKayEm** [comment]
It's an issue that began with the update to calibre 7.  The alpha version of DeDRM has a fix: https://github.com/noDRM/DeDRM_tools_autorelease/releases/tag/autorelease_3373d938749117989dfd0a42cc947bf338d3ffda

**Comment by ElleKayEm** [comment]
Not too much different between this and 10.0.9.  See this section of the changelog here: https://github.com/noDRM/DeDRM_tools/blob/master/CHANGELOG.md#fixes-on-master-not-yet-released

**Comment by NotTradingAdvice** [comment]
Hi!
I downloaded and installed the alpha, but I am still not able to upload the .ab backup. Any clues? I am on Debian 12 and running calibre 7.12
Thanks!

**Comment by ElleKayEm** [comment]
First, double-check that you actually have the auto-release installed and didn't reinstall regular DeDRM 10.0.9.  Next, did you restart calibre before trying to add your backup file to DeDRM's Kindle for Android customization?

**Comment by NotTradingAdvice** [comment]
Hey!
I installed the auto-release from here https://github.com/noDRM/DeDRM_tools_autorelease/releases and I did restart calibre before trying to add the backup. I also tried to power off just in case 🤷

**Comment by j-howell** [comment]
What version of Kindle for Android did you use to create the backup? Version 4.17 (released in 2015) is a newest version that can produce a usable backup file.

How large is your .ab file? A very small or empty file is a sign of failure.
