### ISSUE TITLE
Cannot remove DMR

### ISSUE THREAD

**Issue by Emiliecd123** [noDRM/DeDRM_tools#544]
### Question / bug report

Trying to remove DMR on a book i bought on Rakuten. I need to convert it to epub or PDF to view on my ipad.
I followed all this  but still not working and Calibre keep telling me it's protect:

Make sure the DeDRM plugin is installed in Calibre

Customize the plugin (Preferences -> Plugins > File Types > DeDRM) and click on the button called Adobe Digital Edition

Make sure your ADE key is there in the list. If not, click on the green + button to automatically add it from your ADE installation

Save changes and restart Calibre

Import the protected ePub into Calibre. During the import process, the protection will be removed

Now you can export the unprotected ePub from Calibre to your computer. The resulting ePub file can now be opened in Books or any (e)Reader

### Which version of Calibre are you running?

7.9.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-04-29 15:10:15.624 calibre-debug[6026:460645] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
calibre Debug log
calibre 7.9  embedded-python: True
macOS-14.2.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /private/var/folders/gc/smjhv53d1jj7yjl1ljz2bqxw0000gn/T/AppTranslocation/CF28A610-4939-4DF1-8CB2-EB7B12C76BF4/d/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.9  embedded-python: True
macOS-14.2.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.2.0', 'Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64')
Python 3.11.5
OSX: ('14.2.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /private/var/folders/gc/smjhv53d1jj7yjl1ljz2bqxw0000gn/T/AppTranslocation/CF28A610-4939-4DF1-8CB2-EB7B12C76BF4/d/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 128.00000192236715 x 127.50000191485789
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.21] db initialized
[0.21] Constructing main UI...
[1.06] GUI main window shown
[1.14] main UI initialized...
[1.14] Hiding splash screen
DeDRM v10.0.3: Trying to decrypt Bien débuter - Prise en charge de la douleur.epub
DeDRM v10.0.3: Verifying zip archive integrity
[5.06] splash screen hidden
[5.06] Started up in 5.06 seconds with 0 books
DeDRM v10.0.3: Bien débuter - Prise en charge de la douleur.epub is a secure Adobe Adept ePub for UUID ae46234d-19b9-4b2d-87ae-af05281fc247
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings/hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
    userkey = codecs.decode(userkeyhex, 'hex')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)

**Comment by ElleKayEm** [comment]
Delete your Adobe key from DeDRM customization.  Add the book letting DeDRM automatically retrieve the key on its own.

Where did you see those instructions?

**Comment by Emiliecd123** [comment]
> Delete your Adobe key from DeDRM customization. Add the book letting DeDRM automatically retrieve the key on its own.
> 
> Where did you see those instructions?

Thank you so much ! The key was the problem. I found those instructions a multiple time on Reddit. Not my field of practice as you can see, just a nurse here lol

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by Emiliecd123** [comment]
Perfect
