### ISSUE TITLE
Dederm does not work on new notebook

### ISSUE THREAD

**Issue by Erdbeerhexe** [noDRM/DeDRM_tools#546]
### Question / bug report

Hello everyone!

I need your help.

I installed Calibre and DeDrm on my new Notebook (Win 11) and now I can't open the ADE books.
I always get the message "This book is locked by DRM."
The books are from my local library, but on my old setup it works very well. 

So some setting must be wrong, but I can't figure it out...

I use ADE V 4.5.11.187212.

Thanks a lot!

### Which version of Calibre are you running?

7.4

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
pplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
DEBUG - calibre_plugins.pocketbook_tools.ui:64:genesis - Starting v0.9.6
DEBUG - calibre_plugins.pocketbook_tools.ui:65:genesis - prefs: {'bk_include_emptybookdb': False, 'debug': True, 'hl_sortdate': 0, 'up_acsmtocard': False, 'up_alwaysreplace': True, 'up_deletemode': 0, 'up_zipenabled': True}
DEBUG - calibre_plugins.pocketbook_tools.ui:125:menu_build - Building menu
calibre Fehlerdiagnoseprotokoll
calibre 7.4  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && Find Duplicates (1, 10, 9) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && KOReader Sync (0, 5, 2) && Modify ePub (1, 8, 3) && Obok DeDRM (10, 0, 9) && PocketBook Improved Device Interface (1, 0, 3) && Pocketbook Tools (0, 9, 6) && Quality Check (1, 13, 10) && Resize Cover (1, 2, 1)
calibre 7.4  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && Find Duplicates (1, 10, 9) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && KOReader Sync (0, 5, 2) && Modify ePub (1, 8, 3) && Obok DeDRM (10, 0, 9) && PocketBook Improved Device Interface (1, 0, 3) && Pocketbook Tools (0, 9, 6) && Quality Check (1, 13, 10) && Resize Cover (1, 2, 1)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 114.09947368421052 x 101.6
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.0 koreader:action:KoreaderAction:genesis:start
[1.22] GUI main window shown
[1.25] main UI initialized...
[1.25] Hiding splash screen
```

**Comment by ElleKayEm** [comment]
Let's see a log of adding a book: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Erdbeerhexe** [comment]
I've tested it with 2 books... 
both didn't work
bla bla bla - there was an Code for ade, so i deleted it. if you need it, please tell me. 

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
DEBUG - calibre_plugins.pocketbook_tools.ui:64:genesis - Starting v0.9.6
DEBUG - calibre_plugins.pocketbook_tools.ui:65:genesis - prefs: {'bk_include_emptybookdb': False, 'debug': True, 'hl_sortdate': 0, 'up_acsmtocard': False, 'up_alwaysreplace': True, 'up_deletemode': 0, 'up_zipenabled': True}
DEBUG - calibre_plugins.pocketbook_tools.ui:125:menu_build - Building menu
calibre Fehlerdiagnoseprotokoll
calibre 7.4  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && Find Duplicates (1, 10, 9) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && KOReader Sync (0, 5, 2) && Modify ePub (1, 8, 3) && Obok DeDRM (10, 0, 9) && PocketBook Improved Device Interface (1, 0, 3) && Pocketbook Tools (0, 9, 6) && Quality Check (1, 13, 10) && Resize Cover (1, 2, 1)
calibre 7.4  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 10, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 10, 0) && Find Duplicates (1, 10, 9) && KFX metadata reader (from KFX Input) (2, 10, 0) && From KFX (2, 10, 0) && KFX Input (2, 10, 0) && Set KFX metadata (from KFX Output) (2, 7, 0) && KFX Output (2, 7, 0) && KOReader Sync (0, 5, 2) && Modify ePub (1, 8, 3) && Obok DeDRM (10, 0, 9) && PocketBook Improved Device Interface (1, 0, 3) && Pocketbook Tools (0, 9, 6) && Quality Check (1, 13, 10) && Resize Cover (1, 2, 1)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 114.09947368421052 x 101.6
[0.00] Starting up...
[0.00] Showing splash screen...
[0.14] splash screen shown
[0.14] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.0 koreader:action:KoreaderAction:genesis:start
[1.19] GUI main window shown
[1.20] main UI initialized...
[1.20] Hiding splash screen
[3.86] splash screen hidden
[3.86] Started up in 3.86 seconds with 5129 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\x9a\xcer\xaaB\xe5\xb4\x88'o:\xd7\xad\xfc\xbc\x16\xba\xcd\xc9D0Db\x18\xff8d9`\xd5\x0c\xbe", b'C:\\Users\\User_Name\\Downloads\\B\xc3\xbccher\\Viper \xe2\x80\x93 Buch 1.epub', b'C:\\Users\\User_Name\\Downloads\\B\xc3\xbccher\\Positiv f\xc3\xbchren.epub']
DeDRM v10.0.9: Trying to decrypt Buch 1.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Buch 1.epub is a secure Adobe Adept ePub for UUID Bla Bla Bla 
DeDRM v10.0.9: Trying Encryption key default_key
yxhneyeb.epub is a secure Adobe Adept ePub.
Could not decrypt yxhneyeb.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\User_Name\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\User_Name\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\User_Name\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 293, in adeptkeys
  File "C:\Users\User_Name\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 273, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.9: Trying to decrypt Positiv führen.epub
DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Positiv führen.epub is a secure Adobe Adept ePub for UUID bla bla bla
DeDRM v10.0.9: Trying Encryption key default_key
mq6p21kf.epub is a secure Adobe Adept ePub.
Could not decrypt mq6p21kf.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\User_Name\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\User_Name\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key default_key after 0.1 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 565, in ePubDecrypt
  File "C:\Users\User_Name\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 293, in adeptkeys
  File "C:\Users\User_Name\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 273, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Buch 1 to db in: 0.0
Added Positiv führen to db in: 0.0
Added 2 books in 0.5 seconds
```

**Comment by ElleKayEm** [comment]
These books were downloaded with ADE on your new computer?  Is ADE authorized with your Adobe ID?

Assuming both of those are yes, delete the Adobe key from DeDRM's customization.  Re-add a book letting DeDRM automatically retrieve the key.

**Comment by Erdbeerhexe** [comment]
Yes, they are.

It's without ID authorized, but it worked on my old computer.

**Comment by ElleKayEm** [comment]
Okay, try what I suggested anyway.  If the books were downloaded with this current installation of ADE, it should work.

**Comment by Erdbeerhexe** [comment]
I've tried and it doesn't work.
  
I tried a workaround:
Delete everything including my library, restart computer

Than I did the following:
- opened ADE on my old computer and authorized with an new created ID.
- Downloaded one new book on my old computer - it worked

On my new computer:
Install Calibre 7.10, Install ADE v 4.5.11.187212, Opened ADE and authorized with the ID I've created on my old computer.
Opened Calibre, installed DeDrm 10.0.9, restart the computer.

Downloaded the book, opened in calibre - it doesn't work!

Then checked the Adobe Key - it was called "deafult-key" or something like that, i can't remember. Deleted it, like you said - tried the new book again - It didn't work either.

Than I checked the key on my old computer - i was called default with a very long sequence of numbers and letters - saved it, transferred it to my new one and installed.
Than I tried the book and some other books - surprise: it work!!

my question is:
Is this problem related to Windows 11 or the ADE version?
Does DeDrm use graphic boards for decryption?
Why doesn't it retrieve the correct key?
Or is the fault, that i used Windows Package Manager to install every update, excluded plugins?

My new computer is only 3 weeks old - and had a lot of updates. Iit's a i9 with an 4060 rtx. 
Maybe there is an update that caused my problem?

So thank you so much for helping me to fix this annoying problem.

**Comment by ElleKayEm** [comment]
Not sure what exactly happened.  I think it's always a good idea to authorize Adobe with your Adobe ID so that the DRM isn't just tied to one installation of ADE.  Now even if you download a book on a different machine as long as ADE is authorized with your Adobe ID, this key will unlock it.  If you're all set, you can close the issue.
