### ISSUE TITLE
Cannot deDRM azw3 file

### ISSUE THREAD

**Issue by fsa317** [noDRM/DeDRM_tools#547]
### Question / bug report

Hi, new to all this. I was able to download an azw3 file from the amazon site under my content.  When I try to load it with Calibre and the plugin nothing happens and I see this in the logs.  I entered a serial number for a Fire tablet I had that shows up under devices, but that device isn't actually being used.

I also have kindle for mac but cant seem to find any files to mess with from there.

### Which version of Calibre are you running?

7.0.10

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Zero to Sold: How to Start, Run, and Sell a Bootstrapped Business
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frankapap/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 261, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/frankapap/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 501, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[7.41] splash screen hidden
[7.41] Started up in 7.41 seconds with 2 books
Added Zero to Sold: How to Start, Run, and Sell a Bootstrapped Business to db in: 0.0
Added 1 books in 0.6 seconds
```

**Comment by ElleKayEm** [comment]
Won't work with a Fire.  If you have an E-ink Kindle, choose that and enter its serial number.  Otherwise you could use Kindle Classic for Mac (not the App store version).  For that, you would also need to update to DeDRM 10.0.9 and have the KFX Input plugin.
https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
https://www.mobileread.com/forums/showthread.php?t=291290

**Comment by fsa317** [comment]
Thanks this pointed me in the right direction!
