### ISSUE TITLE
Missing Parentheses in Call to Print on plugin install - OS X, Calibre 6.11

### ISSUE THREAD

**Issue by perrykperry** [noDRM/DeDRM_tools#548]
### Question / bug report

I'm getting a "SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?" error when attempting to install the DeDRM plugin into Calibre 6.11. I also tried Calibre 6.29, as well. 

### Which version of Calibre are you running?

6.11 (same error also on 6.29)

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
calibre 6.11  embedded-python: True
macOS-12.7.4-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.6.0', 'Darwin Kernel Version 21.6.0: Mon Feb 19 20:24:34 PST 2024; root:xnu-8020.240.18.707.4~1/RELEASE_X86_64')
Python 3.10.1
OSX: ('12.7.4', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (6, 7, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 325, in add_plugin
  File "calibre/customize/ui.py", line 479, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 307, in load
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 199, in exec_module
  File "calibre/customize/zipplugin.py", line 195, in get_code
  File "calibre_plugins.dedrm.__init__", line 168
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Comment by ElleKayEm** [comment]
Looks like you are trying to install an older version of DeDRM.  Delete older downloads to make sure you are installing the correct one.  Recommend using DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by perrykperry** [comment]
Mistake - I'd downloaded both an old and the new version, and (indeed) grabbed the wrong folder.
