### ISSUE TITLE
Can't remove DeDRM from mobi book 

### ISSUE THREAD

**Issue by wilfy2004** [noDRM/DeDRM_tools#551]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-05-17 10:13:10.225 calibre-debug[4588:29450819] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
calibre Debug log
calibre 7.10  embedded-python: True
macOS-14.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.4.0', 'Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.4.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.10  embedded-python: True
macOS-14.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.4.0', 'Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.4.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 108.00000162199726
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[0.39] GUI main window shown
[0.42] main UI initialized...
[0.42] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt The Novice - Trudi Canavan.mobi
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
DeDRM v10.0.9: Failed to decrypt with error: Invalid file format
DeDRM v10.0.9: Looking for new default Kindle Key after 0.4 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaclarke/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 179, in GetDecryptedBook
    mb = mobidedrm.MobiBook(infile)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaclarke/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 169, in __init__
    raise DrmException("Invalid file format")
mobidedrm.DrmException: Invalid file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 481, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 267, in get_metadata
  File "calibre/ebooks/metadata/mobi.py", line 502, in get_metadata
  File "calibre/ebooks/mobi/reader/headers.py", line 295, in __init__
  File "calibre/ebooks/mobi/reader/headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x00\x00\x00\x00\x00\x00\x00\x00'
Failed to check for plugin update: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)
[3.29] splash screen hidden
[3.29] Started up in 3.29 seconds with 0 books
Added The Novice to db in: 0.0
Added 1 books in 0.7 seconds
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10fd50410>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 250, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...

### Which version of Calibre are you running?

7.10

### Which version of the DeDRM plugin are you running?

10.0.9

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-05-17 10:13:10.225 calibre-debug[4588:29450819] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
calibre Debug log
calibre 7.10  embedded-python: True
macOS-14.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.4.0', 'Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.4.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.10  embedded-python: True
macOS-14.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.4.0', 'Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.4.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 109.00000163701577 x 108.00000162199726
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[0.39] GUI main window shown
[0.42] main UI initialized...
[0.42] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt The Novice - Trudi Canavan.mobi
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
DeDRM v10.0.9: Failed to decrypt with error: Invalid file format
DeDRM v10.0.9: Looking for new default Kindle Key after 0.4 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaclarke/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 179, in GetDecryptedBook
    mb = mobidedrm.MobiBook(infile)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaclarke/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 169, in __init__
    raise DrmException("Invalid file format")
mobidedrm.DrmException: Invalid file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 481, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 267, in get_metadata
  File "calibre/ebooks/metadata/mobi.py", line 502, in get_metadata
  File "calibre/ebooks/mobi/reader/headers.py", line 295, in __init__
  File "calibre/ebooks/mobi/reader/headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x00\x00\x00\x00\x00\x00\x00\x00'
Failed to check for plugin update: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)
[3.29] splash screen hidden
[3.29] Started up in 3.29 seconds with 0 books
Added The Novice to db in: 0.0
Added 1 books in 0.7 seconds
Unable to open device <calibre.devices.kindle.driver.KINDLE2 object at 0x10fd50410>
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 728, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/gui2/device.py", line 250, in do_connect
  File "calibre/devices/usbms/device.py", line 731, in open
  File "calibre/devices/usbms/device.py", line 393, in open_osx
  File "calibre/devices/usbms/device.py", line 382, in osx_bsd_names
  File "calibre/devices/usbms/device.py", line 341, in _osx_bsd_names
calibre.devices.errors.DeviceError: Could not detect BSD names for Kindle 2/3/4/Touch/PaperWhite/Voyage Device Interface. Try rebooting.
Output from osx_get_usb_drives():
[]

Connect to device failed, retrying in 5 seconds...

**Comment by ElleKayEm** [comment]
How was this downloaded? Log says "invalid file format" several times.
