### ISSUE TITLE
PDF from ADE

### ISSUE THREAD

**Issue by sebasarena** [noDRM/DeDRM_tools#554]
I can't delete the DRM from a PDF downloaded through ADE 4.5 in Windows 11.

Here it's the log:

```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Registro de depuración
calibre 7.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: es
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.11  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: es
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 100.86162790697674 x 100.55257731958763
[0.00] Starting up...
[0.00] Showing splash screen...
[0.28] splash screen shown
[0.28] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[0.98] GUI main window shown
[1.06] main UI initialized...
[1.06] Hiding splash screen
[2.52] splash screen hidden
[2.52] Started up in 2.52 seconds with 2 books
DeDRM v10.0.3: Trying to decrypt Bosie  a biography of Lord Alfred Douglas.pdf
DeDRM v10.0.3: Bosie  a biography of Lord Alfred Douglas.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: Bosie  a biography of Lord Alfred Douglas.pdf is a PDF ebook (EBX) for UUID bc2d5ff9-0fbf-4dde-a628-092b9372a657
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 923, in PDFDecrypt
  File "calibre_plugins.dedrm.__init__", line 695, in PDFIneptDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xc3s\xc3\xe2"P\xf7\xf9lI\xcc\x94\x8a\xf8\xf2\x94\xb5L\xe4\x01\t\x0f\x81\x92\x9bV\xaa\x1e\x13a,\xad', b'C:\\Users\\User\\Documents\\My Digital Editions\\Bosie  a biography of Lord Alfred Douglas.pdf']
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 325, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
```

**Comment by noDRM** [comment]
Looks like your user key got corrupted somehow, please try to delete it from the key list in the plugin settings and try again to have it auto-retrieve the new key. 

Also, please try if the issue is still present with 10.0.9: https://github.com/noDRM/DeDRM_tools_autorelease/releases
