### ISSUE TITLE
 .kfx DRMION file cannot be decrypted by itself

### ISSUE THREAD

**Issue by rich-coe** [noDRM/DeDRM_tools#558]
### Question / bug report

I have been using the old DeDRM tools, then migrated to noDRM tools to get the python3 version.
I had to upgrade k4pc from 1.26 to 2.3 because 2024 ebooks use a new format. 
My old version of DeDRM had this patch, I don't know where I got it from, which fixes the error: .kfx DRMION file cannot be decrypted by itself

After applying the patch I can decode my book.
I'm not using the plugins.

### Which version of Calibre are you running?

n/a

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
python.exe k4mobidedrm.py -k kindlekey1.k4i ../My\ Documents/My\ Kindle\ Content/B0D5HX9DWP_EBOK/B0D5HX9DWP_EBOK.azw   /m/c/kbooks/
K4MobiDeDrm v6.0.
Copyright ▒ 2008-2020 Apprentice Harper et al.
Error decrypting book after 0.0 seconds: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
Traceback (most recent call last):
  File "k4mobidedrm.py", line 229, in decryptBook
    book = GetDecryptedBook(infile, kDatabases, androidFiles, serials, pids, starttime)
  File "k4mobidedrm.py", line 170, in GetDecryptedBook
    raise DrmException("The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.")
DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
```

**Comment by rich-coe** [comment]
```patch
diff -r -c old/k4mobidedrm.py new/k4mobidedrm.py
*** old/k4mobidedrm.py  2021-05-25 14:35:22.892497000 -0500
--- new/k4mobidedrm.py  2021-05-31 08:56:13.813855300 -0500
***************
*** 203,218 ****
          raise DrmException("Input file does not exist.")
  
      mobi = True
      magic8 = open(infile,'rb').read(8)
      if magic8 == b'\xeaDRMION\xee':
!         raise DrmException("The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.")
! 
!     magic3 = magic8[:3]
!     if magic3 == b'TPZ':
!         mobi = False
  
!     if magic8[:4] == b'PK\x03\x04':
!         mb = kfxdedrm.KFXZipBook(infile)
      elif mobi:
          mb = mobidedrm.MobiBook(infile)
      else:
--- 203,222 ----
          raise DrmException("Input file does not exist.")
  
      mobi = True
+     unzipd = False
      magic8 = open(infile,'rb').read(8)
      if magic8 == b'\xeaDRMION\xee':
!         ## raise DrmException("The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.")
!         unzipd = True
!     else:
!         magic3 = magic8[:3]
!         if magic3 == b'TPZ':
!             mobi = False
  
!     if unzipd:
!         mb = kfxdedrm.KFXZipBook(infile, False)
!     elif magic8[:4] == b'PK\x03\x04':
!         mb = kfxdedrm.KFXZipBook(infile, True)
      elif mobi:
          mb = mobidedrm.MobiBook(infile)
      else:
```

```patch
diff -r -c old/kfxdedrm.py new/kfxdedrm.py
*** old/kfxdedrm.py     2021-05-25 14:35:22.892497000 -0500
--- new/kfxdedrm.py     2021-05-31 10:10:29.859810100 -0500
***************
*** 25,32 ****
  
  
  class KFXZipBook:
!     def __init__(self, infile):
          self.infile = infile
          self.voucher = None
          self.decrypted = {}
  
--- 25,33 ----
  
  
  class KFXZipBook:
!     def __init__(self, infile, zipd):
          self.infile = infile
+         self.zipd = zipd
          self.voucher = None
          self.decrypted = {}
  
***************
*** 34,71 ****
          return (None, None)
  
      def processBook(self, totalpids):
!         with zipfile.ZipFile(self.infile, 'r') as zf:
!             for filename in zf.namelist():
!                 with zf.open(filename) as fh:
!                     data = fh.read(8)
!                     if data != b'\xeaDRMION\xee':
!                         continue
!                     data += fh.read()
!                     if self.voucher is None:
!                         self.decrypt_voucher(totalpids)
!                     print("Decrypting KFX DRMION: {0}".format(filename))
!                     outfile = BytesIO()
!                     DrmIon(BytesIO(data[8:-8]), lambda name: self.voucher).parse(outfile)
!                     self.decrypted[filename] = outfile.getvalue()
  
          if not self.decrypted:
              print("The .kfx-zip archive does not contain an encrypted DRMION file")
  
      def decrypt_voucher(self, totalpids):
!         filename = ''
!         if not self.zipd:
!             import fnmatch
!             dname = os.path.dirname(self.infile)
!             for file in os.listdir(dname):
!                 if fnmatch.fnmatch(file, '*.voucher'):
!                     filename = file
  
!             if filename is None:
!                 raise Exception('Cannot find voucher file in ' + dname)
! 
!             with open(os.path.join(dname, filename), "rb") as fh:
!                 data = fh.read()
!         else:
!             with zipfile.ZipFile(self.infile, 'r') as zf:
!                 for info in zf.infolist():
!                     with zf.open(info.filename) as fh:
!                         data = fh.read(4)
!                         if data != b'\xe0\x01\x00\xea':
!                             continue
! 
!                         data += fh.read()
!                         filename = info.filename
!                         if b'ProtectedData' in data:
!                             break   # found DRM voucher
!                 else:
!                     raise Exception("The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher")
! 
!         print("Decrypting KFX DRM voucher: {0}".format(filename))
  
          for pid in [''] + totalpids:
              # Belt and braces. PIDs should be unicode strings, but just in case...
***************
*** 113,119 ****
          if not self.decrypted:
              shutil.copyfile(self.infile, outpath)
          else:
!             with zipfile.ZipFile(self.infile, 'r') as zif:
!                 with zipfile.ZipFile(outpath, 'w') as zof:
!                     for info in zif.infolist():
!                         zof.writestr(info, self.decrypted.get(info.filename, zif.read(info.filename)))
--- 141,154 ----
          if not self.decrypted:
              shutil.copyfile(self.infile, outpath)
          else:
!             if not self.zipd:
!                 dname = os.path.dirname(self.infile)
!                 with zipfile.ZipFile( outpath, 'w') as zof:
!                     for file in os.listdir(dname):
!                         with open(os.path.join(dname, file), "rb") as fh:
!                             zof.writestr(file, self.decrypted.get(file, fh.read()))
!             else:
!                 with zipfile.ZipFile(self.infile, 'r') as zif:
!                     with zipfile.ZipFile(outpath, 'w') as zof:
!                         for info in zif.infolist():
!                             zof.writestr(info, self.decrypted.get(info.filename, zif.read(info.filename)))

```

**Comment by rich-coe** [comment]
I can submit a pr if you prefer.

**Comment by ElleKayEm** [comment]
You can already decrypt books from the current Kindle for PC with DeDRM 10.0.9 and the KFX Input plugin.
