### ISSUE TITLE
Unable to decrypt ADM 4.5 ebooks

### ISSUE THREAD

**Issue by Smith8154** [noDRM/DeDRM_tools#559]
### Question / bug report

I am trying to remove the DRM from some ebooks I bought from Kobo that were delivered through Adobe Digital Editions. When I import the epub and try to read the book, Calibre warns me that the book has DRM. I have tried using version 10.0.3 and 10.0.9, but I have the same issue with both versions. I have deleted and re-imported the book at least 10 times now.

### Which version of Calibre are you running?

7.9

### Which version of the DeDRM plugin are you running?

10.0.9

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.9  embedded-python: True
Linux-6.6.26-linuxkit-aarch64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '6.6.26-linuxkit', '#1 SMP Sat Apr 27 04:13:19 UTC 2024')
Python 3.11.5
Interface language: None
EXE path: /opt/calibre/bin/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Quality Check (1, 13, 10)
calibre 7.9  embedded-python: True
Linux-6.6.26-linuxkit-aarch64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '6.6.26-linuxkit', '#1 SMP Sat Apr 27 04:13:19 UTC 2024')
Python 3.11.5
Interface language: None
EXE path: /opt/calibre/bin/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Quality Check (1, 13, 10)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.05042016806722 x 95.94453125
[0.00] Starting up...
[0.00] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.58] GUI main window shown
[0.61] main UI initialized...
[0.61] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Throne of Glass Ebook Bundle (8 Books in 1).epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Throne of Glass Ebook Bundle (8 Books in 1).epub is a secure Adobe Adept ePub for UUID 4582a294-4eb8-4065-b482-8e22e8800f55
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.7 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.7 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 570, in ePubDecrypt
    defaultkeys, defaultnames = WineGetKeys(scriptpath, ".der",dedrmprefs['adobewineprefix'])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 96, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 59, in __init__
    self.check_call(["-c", self.py3_test])
  File "/config/.config/calibre/plugins/DeDRM.zip/wineutils.py", line 84, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 408, in check_call
  File "subprocess.py", line 389, in call
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[14.55] splash screen hidden
[14.55] Started up in 14.55 seconds with 48 books
Added Throne of Glass Ebook Bundle (8 Books in 1) to db in: 0.5
Added 1 books in 1.4 seconds
/usr/bin/xdg-open: 882: x-www-browser: not found
/usr/bin/xdg-open: 882: firefox: not found
/usr/bin/xdg-open: 882: iceweasel: not found
/usr/bin/xdg-open: 882: seamonkey: not found
/usr/bin/xdg-open: 882: mozilla: not found
/usr/bin/xdg-open: 882: epiphany: not found
/usr/bin/xdg-open: 882: konqueror: not found
/usr/bin/xdg-open: 882: chromium: not found
/usr/bin/xdg-open: 882: chromium-browser: not found
/usr/bin/xdg-open: 882: google-chrome: not found
/usr/bin/xdg-open: 882: www-browser: not found
/usr/bin/xdg-open: 882: links2: not found
/usr/bin/xdg-open: 882: elinks: not found
/usr/bin/xdg-open: 882: links: not found
/usr/bin/xdg-open: 882: lynx: not found
/usr/bin/xdg-open: 882: w3m: not found
xdg-open: no method available for opening 'file:///tmp/tmpdazcp621.txt'
```

**Comment by ElleKayEm** [comment]
This is tough with Linux.  Suggest trying to download the books with the ACSM Input plugin.  You may also need to manually save the Adobe key from ACSM Input and import it into DeDRM.

https://www.mobileread.com/forums/showthread.php?t=341975

**Comment by Fanotec** [comment]
Same issue for me.  I am using windows 11. ADM 4.5. epub books purchased on google play store.
Which version of Calibre are you running?
7.13
Which version of the DeDRM plugin are you running?
10.0.9
Let me know if sending the ebook file will help.

**Comment by ElleKayEm** [comment]
@Fanotec 
With Windows, you should be good.  Is ADE which was used to download the book on the same computer and user as calibre/DeDRM?

**Comment by ElleKayEm** [comment]
Don't think so.  Post a log and we'll take a look: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by Fanotec** [comment]
I solved the issue by using DeACSM_0.0.16 for importing the ebook.

**Comment by Smith8154** [comment]
Thanks! The DeACSM plugin was able to fix my issue!
