### ISSUE TITLE
DeDRM 10.0.9 not working for KFX-ZIP format book downloaded from Kindle for PC 1.26 in Wine

### ISSUE THREAD

**Issue by rytrot** [noDRM/DeDRM_tools#561]
### Question / bug report

I have the KFX Input plugin as well (v2.12.0). The "cannot convert" popup shows up saying it cannot convert due to DRM.

### Which version of Calibre are you running?

7.12

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

1.26 (Kindle for PC 1.26.55076 running in Wine)

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 7.12  embedded-python: True
Linux-6.1.0-21-amd64-x86_64-with-glibc2.36 Linux ('64bit', 'ELF')
('Linux', '6.1.0-21-amd64', '#1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)')
Python 3.11.5
Interface language: None
EXE path: /opt/calibre/bin/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 12, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 12, 0) && KFX metadata reader (from KFX Input) (2, 12, 0) && From KFX (2, 12, 0) && KFX Input (2, 12, 0)
calibre 7.12  embedded-python: True
Linux-6.1.0-21-amd64-x86_64-with-glibc2.36 Linux ('64bit', 'ELF')
('Linux', '6.1.0-21-amd64', '#1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)')
Python 3.11.5
Interface language: None
EXE path: /opt/calibre/bin/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 12, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 12, 0) && KFX metadata reader (from KFX Input) (2, 12, 0) && From KFX (2, 12, 0) && KFX Input (2, 12, 0)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 215.1529411764706 x 216.56842105263158
[0.00] Starting up...
[0.00] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.71] GUI main window shown
[1.78] main UI initialized...
[1.78] Hiding splash screen
[23.06] splash screen hidden
[23.06] Started up in 23.06 seconds with 94 books
Gather KFX-ZIP (from KFX Input) 2.12.0: Importing /home/ryan/.wine/drive_c/users/ryan/Documents/My Kindle Content/B002FL3JA0_EBOK/B002FL3JA0_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 9 file(s) as /tmp/calibre_7.12.0_tmp_rscucnoh/r5phdw0a.kfx-zip
DeDRM v10.0.9: Trying to decrypt r5phdw0a.kfx-zip
Decrypting KFX-ZIP ebook: r5phdw0a
Found 0 keys to try after 1.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.9030eca2-a8dd-4a82-8f65-1d68c164fbfa.voucher
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "/home/ryan/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/home/ryan/.config/calibre/plugins/DeDRM.zip/ion.py", line 1368, in decryptvoucher
    raise ex
          ^^
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 1.1 seconds
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.9: wine py.exe -3 is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.9: wine python3.exe is not python3
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

DeDRM v10.0.9: wine python.exe is not python3
wine: failed to open "C:\\Python27\\python.exe": c0000135
DeDRM v10.0.9: wine C:\Python27\python.exe does not exist
DeDRM v10.0.9: Unable to find python3 executable in WINEPREFIX=""
DeDRM v10.0.9: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/.config/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/home/ryan/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 67, in processBook
    self.decrypt_voucher(totalpids)
  File "/home/ryan/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 111, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.12.0: Packaging /tmp/calibre_7.12.0_tmp_rscucnoh/r5phdw0a.kfx-zip
Processing container: B002FL3JA0_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
    return self.package_kfx(path_to_ebook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
    container = self.get_container(datafile)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B002FL3JA0_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /tmp/calibre_7.12.0_tmp_rscucnoh/dw8ovco5_add_books/0/B002FL3JA0_EBOK.kfx-zip
Added The Real Book - Volume I: C Edition to db in: 0.4
Added 1 books in 8.8 seconds

```

**Comment by ElleKayEm** [comment]
> Unable to find python3 executable in WINEPREFIX=""

DeDRM isn't able to run the Kindle key retrieval script under Wine.  I don't know if this is something that needs to be fixed in DeDRM or if it would work if only you had the right versions of Python and Pycrytodome or what-have-you installed under Wine.

You wouldn't have to worry about Python etc if you install Windows calibre under Wine -- the scripts can use calibre's built in Python.  But you probably need an older version of calibre to get it to install.

First, since this is an older book and you can download it with an older version of Kindle for PC, I'd suggest avoiding the KFX format.  See the methods under the spoiler in this post: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by ElleKayEm** [comment]
(Didn't mean to hit post yet)

Then you could install Windows calibre 4.23 and load DeDRM 6.8.1 which would work with a non-kfx format copy of the book.  (DeDRM 10.0.9 is suppose to be compatible with previous versions of calibre, but DeDRM 6.8.1 definitely is.)  If you can successfully decrypt your book there, then you could save the key from Windows calibre/DeDRM and import it into your Linux calibre/DeDRM setup.  Then you could decrypt future downloads from that Kindle for PC installation with Linux calibre/DeDRM.

**Comment by rytrot** [comment]
Thanks for the reply.

Installing windows calibre using wine is not working. I'm running wine msiexec /i `wine msiexec /i calibre-64bit-4.23.0.msi` but the installer is ending prematurely. Is there any way to get this working or do I need to use a windows PC?

**Comment by ElleKayEm** [comment]
I haven't tried it myself (no Linux), but I've seen others say they were able to.  If you have access to a Windows machine, that would definitely be easier.

**Comment by Geremia** [comment]
@rytrot 
I had a similar, `No installed Python found!` issue, which was fixed by checking the "py launcher" and add to `PATH` 🗹 boxes when installing Python. (I installed the latest [python-3.12.4-amd64.exe](https://www.python.org/ftp/python/3.12.4/python-3.12.4-amd64.exe).) In my case, it looked for the Python executable at `C:\\users\\geremia\\AppData\\Local\\Programs\\Python\\Launcher\\py.exe`.

I had to run `wine pip install pycryptodome`, too.

Then it can successfully import "Kindle for Mac and PC Keys" from within Calibre, in the DeDRM "Customize plugin" dialog box.

Then you can import KFX *.azw files, DeDRM should decrypt them, and the Calibre [KFX Conversion Input Plugin](https://www.mobileread.com/forums/showthread.php?t=291290) can convert KFX-ZIP to a KFX.

I'm using:
 - Wine 9.10
 - Slackware64-current Linux
 - 64-bit–only WINEPREFIX
 - [KindleForPC-installer-1.40.65535.exe](https://kindleforpc.s3.amazonaws.com/65535/KindleForPC-installer-1.40.65535.exe) (which avoids the ["KRFDynamic.dll failed to initialize" issue](https://forum.winehq.org/viewtopic.php?t=38402) and is late enough a version to download newer KFX format e-books (so I doesn't give a popup saying you need to install a WINE-incompatible version of Kindle for PC).<br><sub>🎩-tip: "[Kindle のインストール](https://qiita.com/nanbuwks/items/03cd51f32c48e82f750b#kindle-%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB)"</sub>

**Comment by Geremia** [comment]
Following up on [what I wrote above](https://github.com/noDRM/DeDRM_tools/issues/561#issuecomment-2159534650), I now get:
```
kindlekey.py v3.1
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\geremia\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
Could not retrieve Kindle for Mac/PC key.
DeDRM v10.0.9: Found and decrypted 0 key files
Traceback (most recent call last):
  File "/home/geremia/.config/calibre/plugins/DeDRM.zip/config.py", line 1262, in __init__
    self.default_key = defaultkeys[0]
                       ~~~~~~~~~~~^^^
```
I've installed Kindle for PC [KindleForPC-installer-2.3.70840.exe](https://appdb.winehq.org/objectManager.php?bShowAll=true&bIsQueue=false&bIsRejected=false&sClass=version&sTitle=&sReturnTo=&iId=41975#testdata) under WINE.

Update: [Satsuoni's 🍴helped](https://github.com/Satsuoni/DeDRM_tools/releases) ([with WINE, too](https://appdb.winehq.org/objectManager.php?sClass=application&iId=10597) 🤓)
<sub>🎩-tip: [ElleKayEm](https://github.com/ElleKayEm), https://github.com/noDRM/DeDRM_tools/issues/1015#issuecomment-4524883654 https://github.com/noDRM/DeDRM_tools/issues/998#issuecomment-4337309066</sub>
