### ISSUE TITLE
ERROR: Unhandled exception caused while installing DeDRM_tools_10.0.3.zip 

### ISSUE THREAD

**Issue by vishalvvr** [noDRM/DeDRM_tools#564]
### Question / bug report

ERROR: Unhandled exception caused while installing DeDRM_tools_10.0.3.zip 

### Which version of Calibre are you running?

7.13

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
calibre, version 7.13.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/home/vishalvvr/Downloads/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file


calibre 7.13  embedded-python: True
Linux-6.9.5-200.fc40.x86_64-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
('Linux', '6.9.5-200.fc40.x86_64', '#1 SMP PREEMPT_DYNAMIC Sun Jun 16 15:47:09 UTC 2024')
Python 3.11.5
Interface language: None
EXE path: /opt/calibre/bin/calibre
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 322, in add_plugin
  File "calibre/customize/ui.py", line 525, in add_plugin
  File "calibre/customize/ui.py", line 76, in load_plugin
  File "calibre/customize/zipplugin.py", line 297, in load
  File "calibre/customize/zipplugin.py", line 392, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/home/vishalvvr/Downloads/DeDRM_tools_10.0.3.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by vishalvvr** [comment]
I tried to install the main zip instead of extracting it and then install it.
This is not an issue/bug, hence closing this issue.
Sorry for the mess.

**Comment by ElleKayEm** [comment]
Recommend DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
