### ISSUE TITLE
Obok DeDRM not able to open or convert newer Kobo book

### ISSUE THREAD

**Issue by uo93** [noDRM/DeDRM_tools#565]
### Question / bug report

Not sure if there has been a change to the DRM in newer Kobo books, but a book I recently purchased on June 19th that released on June 19th is giving me issues when removing the DRM and converting the file. When I click on the Obok DeDRM button, it recognizes the new book and it gives me a success message saying that it has been added to Calibre. The issue is that unlike other eBook conversions with Obok, the recently added book gives a random series of characters as the title instead of the title itself (example in the log "r495cang"). Another issue is that the metadata, thumbnails, and author information don't get imported at all. Also when I click on the EPUB file, it gives me the error when I open it (see the first log below). I tried to convert the EPUB file to a ZIP file which I usually do to backup each page as a jpg, but when I convert it, it gives me the error shown in the second log. This hasn't happened at all with any of my previous Kobo books with the most recent successful DeDRM/conversion being from a book that released on May 31st. Hoping to get clarity on whether it's a Kobo DRM issue, or an issue with Calibre/Obok DeDRM.

### Which version of Calibre are you running?

7.13

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

**First Log: Opening EPUB File**

```log
calibre, version 7.13.0
ERROR: Loading book failed: Failed to open the book at C:\Users\USER\Calibre Library\Unknown\r495cang (105)\r495cang - Unknown.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\USER\Calibre Library\Unknown\r495cang (105)\r495cang - Unknown.epub with error:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 176, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 236, in get_quick_metadata
  File "calibre\ebooks\metadata\epub.py", line 216, in get_metadata
  File "calibre\ebooks\metadata\epub.py", line 154, in read_bytes
  File "calibre\utils\zipfile.py", line 1005, in read
  File "calibre\utils\zipfile.py", line 1033, in open
  File "calibre\utils\zipfile.py", line 994, in getinfo
KeyError: "There is no item named 'OPS/advanced.opf' in the archive"
DeDRM v10.0.9: Trying to decrypt r495cang - Unknown.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 2.1 seconds
InputFormatPlugin: EPUB Input running
on C:\Users\USER~1\AppData\Local\Temp\calibre_njkw6k08\mz6wxzui.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 948, in viewer_main
  File "calibre\srv\render_book.py", line 939, in render_for_viewer
  File "calibre\srv\render_book.py", line 917, in render
  File "calibre\srv\render_book.py", line 714, in process_exploded_book
  File "calibre\srv\render_book.py", line 257, in create_cover_page
  File "calibre\srv\render_book.py", line 210, in find_epub_cover
  File "calibre\ebooks\oeb\polish\cover.py", line 286, in find_cover_image_in_page
  File "src/lxml/xpath.pxi", line 415, in lxml.etree.XPath.__call__
  File "src/lxml/apihelpers.pxi", line 48, in lxml.etree._documentOrRaise
TypeError: Invalid input object: bytes
```

**Second Log: Converting EPUB File to ZIP**

```log
calibre, version 7.13.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (r495cang)

Convert book 1 of 1 (r495cang)
DeDRM v10.0.9: Trying to decrypt 5w5oik67.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 2.1 seconds
Conversion options changed from defaults:
  read_metadata_from_opf: 'C:\\Users\\USER~1\\AppData\\Local\\Temp\\calibre_wiqzdbnt\\bo4n8yrq.opf'
  output_profile: 'tablet'
  verbose: 2
Resolved conversion options
calibre version: 7.13.0
{'add_alt_text_to_img': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002108F7B90D0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.TabletOutput object at 0x000002108F7A6290>,
 'page_breaks_before': '/',
 'prefer_metadata_cover': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\USER~1\\AppData\\Local\\Temp\\calibre_wiqzdbnt\\bo4n8yrq.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'template_css': None,
 'template_html': None,
 'template_html_index': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.9: Trying to decrypt 0t3l3h74.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 2.0 seconds
InputFormatPlugin: EPUB Input running
on C:\Users\USER~1\AppData\Local\Temp\calibre_wiqzdbnt\1by052cp.epub
Parsing all content...
Parsing OPS/navigation_standard.xhtml ...
The item OPS/images/08X10000000046599600_cover.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_dorigin_01_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_001_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_002_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_003_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_4_004_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_4_005_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_006_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_007_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_008_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_009_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_010_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_011_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_012_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_013_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_014_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_015_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_016_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_017_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_018_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_019_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_020_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_021_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_022_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_023_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_024_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_025_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_026_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_027_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_028_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_4_029_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_030_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_031_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_032_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_033_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_4_034_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_4_035_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_036_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_037_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_038_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_039_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_040_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_041_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_042_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_043_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_044_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_045_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_046_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_047_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_048_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_049_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_050_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_051_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_052_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_053_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_054_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_055_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_056_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_057_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_058_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_059_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_060_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_061_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_062_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_063_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_064_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_065_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_066_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_067_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_068_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_069_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_070_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_071_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_072_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_073_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_074_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_075_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_076_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_077_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_078_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_079_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_080_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_081_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_082_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_083_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_084_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_085_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_086_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_087_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_088_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_089_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_090_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_091_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_092_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_093_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_094_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_095_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_096_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_097_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_098_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_099_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_100_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_101_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_102_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_103_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_104_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_105_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_106_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_107_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_108_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_109_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_110_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_111_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_112_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_113_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_114_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_115_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_116_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_117_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_118_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_119_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_120_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_121_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_122_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_123_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_124_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_125_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_126_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_127_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_128_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_129_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_130_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_131_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_132_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_133_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_134_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_135_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_136_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_137_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_138_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_139_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_140_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_4_141_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_142_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_143_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_144_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_145_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_146_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_147_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_148_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_149_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_150_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_151_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_152_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_153_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_154_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_155_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_156_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_157_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_158_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_159_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_160_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_161_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_162_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_163_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_164_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_165_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_166_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_167_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_168_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_169_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_170_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_171_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_172_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_4_173_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_4_174_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_175_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_176_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_177_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_178_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_179_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_180_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_181_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_182_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_183_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_184_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_185_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_1_186_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08X10000000046599600_copyright.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_3_ill_01_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_3_ill_02_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_3_ill_03_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000046_3_ill_04_001.jpg is not a XML document. Removing it from spine.
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1137, in run
  File "calibre\ebooks\conversion\plumber.py", line 1347, in create_oebbook
  File "calibre\ebooks\oeb\reader.py", line 97, in __call__
  File "calibre\ebooks\oeb\reader.py", line 724, in _all_from_opf
  File "calibre\ebooks\oeb\reader.py", line 369, in _spine_from_opf
calibre.ebooks.oeb.base.OEBError: Spine is empty
```

**Comment by ElleKayEm** [comment]
When you are adding the book does it show a red closed lock in Obok?  Try closing Kobo Desktop before using Obok.

FYI, epub files are zip files.  Either change the extension or use a program like 7-Zip that recognizes they are zip files.

**Comment by uo93** [comment]
> When you are adding the book does it show a red closed lock in Obok? Try closing Kobo Desktop before using Obok.
> 
> FYI, epub files are zip files. Either change the extension or use a program like 7-Zip that recognizes they are zip files.

It shows a red closed lock in Obok, but it doesn't seem to import like a regular eBook does. I'll have to say thank you very much for mentioning that epubs are zip files! This was a helpful workaround. After changing the extension I was able to extract the images from the epub despite it not opening in the epub reader.

**Comment by ElleKayEm** [comment]
Sounds like it was decrypted.  May just be calibre's ebook viewer not able to display it correctly.

**Comment by PropFault** [comment]
I have the same issue. Is there any way to "fix" the epub so i can upload it to something like calibre-web or use it in calibre proper?

**Comment by SSoM** [comment]
Here (and hopefully bumping) to report that I have nearly the exact issue. Nearly because two ebooks I bought off of Japanese Kobo last week failed to decrypt properly while one I purchased today did without incident. An epub file did generate but no metadata whatsoever and opening with Sumatra and MuPDF shows me blank white pages.

That being said, changing the extension to .zip and unpacking it that way worked. Not the case with the latter, which displays on MuPDF and Sumatra without issue. Do different ebooks have different DRM?

**Comment by ElleKayEm** [comment]
Sounds like formatting and display issues rather than DRM.

Post a log and we can see what that shows: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by G0ldenSp00n** [comment]
I have been looking into this, because a book I have has a very similar issue.  It seems like the deDRM is working, and correctly decrypting the book.  Just to outputted format is extremely weird,  I am wondering if Kobo is just storing these in a very weird format.

There is no HTML in the outputted book, just a bunch of files that calibre thinks should be text, but they are actually JPG images.  If you export them or manually add an XHTML page you will be able to display all these image files.  They are all added to the spine of the book too, which is what causes normal EPUB reader apps to display tons of white pages, as they don't expect to be reading jpg they expect a spine filled with XHTML pages.  

I am wondering if there needs to be some new converter tool for this, seems like it is probably not actually an issue with decryption since the images are actually correct but the outputted book format is messed up.  Seems like Kobo is doing something royally messed up and stuffing EPUB books full of images without any actual XHTML and there reader app maybe can display that monstrosity?

Here is the log from when I decrypted.   You can see the same issue about "There is no item named 'OPS/advanced.opf' in the archive", and I imagine if I converted to zip I would have the same issue of all the images not actually being XHTML even though they are in the spine and they would all be removed causing the empty spine issue that ultimately fails the zip conversion.
```Using calibre Qt style: True
2024-08-06 22:29:25.141 calibre-debug[91039:13966036] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
calibre Debug log
calibre 7.16  embedded-python: True
macOS-14.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.4.0', 'Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.4.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: KePub Input (3, 6, 6) && KePub Metadata Reader (3, 4, 3) && Obok DeDRM (10, 0, 9)
calibre 7.16  embedded-python: True
macOS-14.4.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.4.0', 'Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('14.4.1', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: KePub Input (3, 6, 6) && KePub Metadata Reader (3, 4, 3) && Obok DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 1.0
logicalDpi: 72.0 x 72.0
physicalDpi: 110.00000165203426 x 111.00000166705276
[0.00] Starting up...
[0.02] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.44] GUI main window shown
[0.47] main UI initialized...
[0.47] Hiding splash screen
2024-08-06 22:29:43.083 calibre-debug[91039:13966036] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 481, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 177, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 216, in get_metadata
  File "calibre/ebooks/metadata/epub.py", line 154, in read_bytes
  File "calibre/utils/zipfile.py", line 1005, in read
  File "calibre/utils/zipfile.py", line 1033, in open
  File "calibre/utils/zipfile.py", line 994, in getinfo
KeyError: "There is no item named 'OPS/advanced.opf' in the archive"
2024-08-06 22:29:48.236 calibre-debug[91039:13966036] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
```

**Comment by G0ldenSp00n** [comment]
Welp, I figured out the actually issue.  THESE ARE EPUBS.  I guess for Japanese Manga Kobo is storing cbz files.  Not sure if there is some way to detect that when they are downloaded and automatically import them in the correct format?

**Comment by ElleKayEm** [comment]
In the meantime, it should be fairly easy once the images are decrypted to unzip them and make a cbz.  That what I used to do with B&N comics which had similar issues because they were formatted to work with the Nook app's panel by panel zoom feature.

**Comment by matsumurae** [comment]
> Welp, I figured out the actual issue. THESE AREN'T EPUBS. I guess for Japanese Manga Kobo is storing cbz files. Not sure if there is some way to detect that when they are downloaded and automatically import them in the correct format?

Not sure about the ones you have, but at least what I bought aren't cbz. When import with obok, it shows as epub (and I have multiple mangas).

**Comment by ElleKayEm** [comment]
I think they were just saying the epub was structured more like a cbz.  Both formats are zip files, but a cbz only has image files.
