### ISSUE TITLE
can't customize plugin

### ISSUE THREAD

**Issue by purplebowl** [noDRM/DeDRM_tools#566]
MacOS 13.5.  Brand new installs of Calibre (7.13.0) and DeDRM (10.0.3).  When I click "customize plugin", I get

```
calibre, version 7.13.0
ERROR: Unhandled exception: <b>TypeError</b>:ConfigWidget.__init__() takes 2 positional arguments but 3 were given

calibre 7.13  embedded-python: True
macOS-13.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000')
Python 3.11.5
OSX: ('13.5', ('', '', ''), 'arm64')
Interface language: None
EXE path: /private/var/folders/5x/tc5dz00x2ds_nhg52r_282gc0000gn/T/AppTranslocation/97074F32-FD5C-4BB0-B03F-6BFAEE8B4244/d/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 298, in customize_plugin
  File "calibre/gui2/preferences/plugins.py", line 375, in modify_plugin
  File "calibre/customize/__init__.py", line 160, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 1080, in config_widget
    return config.ConfigWidget(self.plugin_path, self.alfdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigWidget.__init__() takes 2 positional arguments but 3 were given
```

**Comment by ZolaLa9** [comment]
Try v10.0.9 https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
