### ISSUE TITLE
Need help with removing DRM.

### ISSUE THREAD

**Issue by averagePedestrian** [noDRM/DeDRM_tools#571]
### Question / bug report

I need help with DeDRMing an ebook called ```How the Internet Really Works: An Illustrated Guide to Protocols, Privacy, Censorship, and Governance```. I downloaded it using the Kindle PC app version ```2.4.0 (70904)```. I have installed the DeDRM plugin version ```10.0.9``` (the automatic alpha release with the latest changes) and the KFX Input plugin version ```2.15.0```, both of which are enabled.

These are the files that were present inside the folder named after the book's ASIN:

```https://imgbox.com/WCTbLb5D```

I imported the book using the ```Add books from a single folder``` option and selected the file with the ```.azw``` extension. Calibre imported the book, but it won't convert or open in the Calibre ebook viewer.

### Which version of Calibre are you running?

7.14

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

2.4.0 (70904) for PC

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
Failed to load resource: 'commit.txt' from the plugin zip file: C:\Users\<redacted>\AppData\Roaming\calibre\plugins\OverDrive Libby.zip
Traceback (most recent call last):
  File "calibre\customize\zipplugin.py", line 46, in get_resources
  File "zipfile.py", line 1510, in read
  File "zipfile.py", line 1547, in open
  File "zipfile.py", line 1476, in getinfo
KeyError: "There is no item named 'commit.txt' in the archive"
[overdrive_libby/0.1.9] Loaded 21 items from file cache C:\Users\<redacted>\AppData\Roaming\calibre\plugins\overdrive_libby.libraries.json
[overdrive_libby/0.1.9] Loaded 0 items from file cache C:\Users\<redacted>\AppData\Roaming\calibre\plugins\overdrive_libby.media.json
calibre Debug log
calibre 7.14  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: D:\Portable Apps\Calibre Portable\Calibre\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && OverDrive Libby (0, 1, 9)
calibre 7.14  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: D:\Portable Apps\Calibre Portable\Calibre\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && OverDrive Libby (0, 1, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.36363636363636
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.27] GUI main window shown
[1.36] main UI initialized...
[1.36] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\<redacted>\Documents\My Kindle Content\B07ZC7GYCS_EBOK\B07ZC7GYCS_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 12 file(s) as C:\Users\<redacted>\AppData\Local\Temp\calibre_ahecrx_s\wgzwr005.kfx-zip
DeDRM v10.0.9: Trying to decrypt wgzwr005.kfx-zip
[3.98] splash screen hidden
[3.98] Started up in 3.98 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'2,\xbd9\x99\xba\x8a\xf7`\xdf\xd4{\xa2\x14\x18gF_\x80\xcf$\x0c4\x8eS\x98&$%\x8f\x88\x02', b'C:\\Users\\<redacted>\\Documents\\My Kindle Content\\B07ZC7GYCS_EBOK\\B07ZC7GYCS_EBOK.azw']
Decrypting KFX-ZIP ebook: wgzwr005
Got DSN key from database kindle_key_1721034677_1
Found 1 keys to try after 0.4 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e8b8f82a-e84a-48b6-a6b7-a7d6712b45ce.voucher
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Decryption failed, trying next fallback 
Traceback (most recent call last):
  File "C:\Users\<redacted>\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 106, in decrypt_voucher
  File "C:\Users\<redacted>\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1391, in decryptvoucher
UnboundLocalError: cannot access local variable 'ex' where it is not associated with a value
Decryption failed, trying next fallback 
Decryption succeeded
KFX DRM voucher successfully decrypted
Warning: This book is licensed as PublicLibraryLending. These tools are intended for use on purchased books. Continuing ...
Decrypting KFX DRMION: B07ZC7GYCS_EBOK.azw
Decryption succeeded after 0.4 seconds
DeDRM v10.0.9: Finished after 0.5 seconds
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\<redacted>\AppData\Local\Temp\calibre_ahecrx_s\drzj7_ts.kfx-zip
Processing container: B07ZC7GYCS_EBOK.azw
Processing container: CR!3VW9YSQTKS63Q90SY6EXJPZWXT4R.azw.res
Processing container: CR!4W253P7VZX4617B84G608T3W8Z63.azw.res
Processing container: CR!784622JXKN0KS5P19Y3SDAP9RS9N.azw.res
Processing container: CR!DENNWJH6FN01NDVTGYG80AT8DHDT.azw.res
Processing container: CR!E5BRC3TBQ108ZB20PKMDB926C6BK.azw.res
Processing container: CR!FCJH42H8WS44XEP0BSJ4ATFC45CY.azw.md
Processing container: CR!SC9EQ8FNHH26QCRCPPZP6YZMC186.azw.res
Processing container: CR!TYHGB11K7H3K5BZ8HWGY1FW6VWH6.azw.res
Processing container: CR!V6GTWVX2SS26SFN9V5B0AANNZJ9P.azw.res
Processing container: CR!VCDNMT09C537S2906F24SXGMGCF1.azw.res
Features: CanonicalFormat-2, max_id-787, yj_jpg_rst_marker_present-1, yj_non_pdf_fixed_layout-2, yj_thumbnails_present-1
Metadata: ASIN=B07ZC7GYCS, asset_id=CR!R6BDH8AFX1741BHWV9FZJ0DKZYYZ, author="Article 19", book_id=QtCnAWbVQVeSjdhx-K_syg0, book_orientation_lock=portrait, cde_content_type=EBOK, content_id=B07ZC7GYCS, continuous_popup_progression=0, cover_image=1200x1500, creator_version=2.15.0, file_creator=YJConversionTools, is_sample=False, issue_date=2020-12-08, kfxgen=20.12.238.0, language=en, publisher="No Starch Press", reading_orders=1, title="How the Internet Really Works", yj_fixed_layout=1
KFX container created may be too large for some devices (26106014 bytes)
Package KFX (from KFX Input): Imported as KFX
KFX metadata reader (from KFX Input) activated for C:\Users\<redacted>\AppData\Local\Temp\calibre_ahecrx_s\7hwdd01s_add_books\0\B07ZC7GYCS_EBOK.kfx
```

**Comment by j-howell** [comment]
That is a fixed-layout print replica book. See the section **"From KFX" toolbar action** in the [KFX Input plugin documentation](https://www.mobileread.com/forums/showthread.php?t=291290) for information on how you can convert it to PDF format.
