### ISSUE TITLE
Can't remove drm from Kindle book 

### ISSUE THREAD

**Issue by Veelya** [noDRM/DeDRM_tools#572]
### Question / bug report

Is there anything that can be done? thanks in advance.

### Which version of Calibre are you running?

7.15.0

### Which version of the DeDRM plugin are you running?

10.0.3

### If applicable, which version of the Kindle software are you running?

Kindle for PC 2.4.0

### Log output

```log
Paste log output here.
```ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Journal de débogage
calibre 7.15  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 15, 0) && Calibre Power Search Plugin (2, 2, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
calibre 7.15  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (2, 15, 0) && Calibre Power Search Plugin (2, 2, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
[0.00] Starting up...
[0.02] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.16] GUI main window shown
[1.22] main UI initialized...
[1.22] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\4ambr\Documents\My Kindle Content\B0068OR4B0_EBOK\B0068OR4B0_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\4ambr\AppData\Local\Temp\calibre_j1ogzoys\db12r1u1.kfx-zip
DeDRM v7.2.1: Trying to decrypt db12r1u1.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: db12r1u1
Found 0 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5414c618-60b9-45c1-993c-d831ed05b21d.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v7.2.1: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\4ambr\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\4ambr\AppData\Local\Amazon\Kindle\storage\.kinf2018
[73.42] splash screen hidden
[73.42] Started up in 73.42 seconds with 41 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x02\xd7-\xb4\x1b\xf8+\xa0_\x01\x10\x90\xf1AE<k\xbf\xd6\xa2\x95\xf3Lw\x18Vq\xfc\xb1\x91c\xd2', b'C:\\Users\\4ambr\\Documents\\My Kindle Content\\B0068OR4B0_EBOK\\B0068OR4B0_EBOK.azw']
Decrypted key file using IDString '317007822' and UserName 'Ambre'
DeDRM v7.2.1: Found 1 new key
Decrypting KFX-ZIP ebook: db12r1u1
Got DSN key from database default_key_1
Found 1 keys to try after 1.8 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5414c618-60b9-45c1-993c-d831ed05b21d.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\4ambr\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v7.2.1: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 540, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 238, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 633, in run
  File "calibre_plugins.dedrm.__init__", line 583, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 1.8 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\4ambr\AppData\Local\Temp\calibre_j1ogzoys\db12r1u1.kfx-zip
Processing container: B0068OR4B0_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0068OR4B0_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\4ambr\AppData\Local\Temp\calibre_j1ogzoys\3qyiaxk4_add_books\0\B0068OR4B0_EBOK.kfx-zip

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by Veelya** [comment]
> Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

I usually don't install beta releases, but in this case it solved my problem. Thanks a lot for answering me so fast. Have a great day!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
