### ISSUE TITLE
Can't remove DRM from KFX

### ISSUE THREAD

**Issue by jbmangan** [noDRM/DeDRM_tools#574]
I'm using Kindle for PC, 2.4.0 70904
I'm using Calibre 7.15
I have installed DeDRM Tools 10.0.3
I have installed KFX Input 2.15.0

The book is imported into Calibre but cannot be opened in the Reader due to DRM.

Thanks.

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by jbmangan** [comment]
Thanks. I tried that. Removed DEDRM 10.0.3 from Calibre, installed DeDRM 10.0.9, restarted Calibre.

Once I've imported the book it still says it can't be opened because it is locked by DRM.

Am I out of luck?

**Comment by ElleKayEm** [comment]
Let's see a log of adding the book: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#i-cannot-solve-my-problem-with-the-dedrm-plugin-and-now-i-need-to-post-a-log-how-do-i-do-that

**Comment by jbmangan** [comment]
On your head be it :-)

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.15  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
calibre 7.15  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
[0.00] Starting up...
[0.00] Showing splash screen...
[0.17] splash screen shown
[0.17] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.03] GUI main window shown
[1.09] main UI initialized...
[1.09] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\John\Documents\My Kindle Content\Meru\B09YH1L9CW_EBOK.azw
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\John\AppData\Local\Temp\calibre_75vxk6sw\8qfk6yz0.kfx-zip
DeDRM v10.0.9: Trying to decrypt 8qfk6yz0.kfx-zip
[8.12] splash screen hidden
[8.12] Started up in 8.12 seconds with 84 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xb8\xbeOB\xe4n\x99\x12\x06\x89Ai^~\xb3ro\xcc\xef\xd8$\xd4=\x0b:JQ\x90\xd6$d\xb8', b'C:\\Users\\John\\Documents\\My Kindle Content\\Meru\\B09YH1L9CW_EBOK.azw']
Decrypting KFX-ZIP ebook: 8qfk6yz0
Got DSN key from database default_key
Found 1 keys to try after 0.5 seconds
DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\John\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\John\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3156250346' and UserName 'John'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: 8qfk6yz0
Got DSN key from database key_0
Found 1 keys to try after 0.7 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\John\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\John\AppData\Local\Temp\calibre_75vxk6sw\8qfk6yz0.kfx-zip
Processing container: B09YH1L9CW_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09YH1L9CW_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\John\AppData\Local\Temp\calibre_75vxk6sw\jgcbdfre_add_books\0\B09YH1L9CW_EBOK.kfx-zip
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in get_metadata
Exception: Failed to locate a KFX container with metadata

Once again, many thanks.

**Comment by ElleKayEm** [comment]
Here's your issue:
Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import.
