### ISSUE TITLE
Unable to remove DRM

### ISSUE THREAD

**Issue by mskyi** [noDRM/DeDRM_tools#580]
### Question / bug report

Unable to remove DRM from kindle e-book

### Which version of Calibre are you running?

7.15.0

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

5.16.10.0.01

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-07-26 16:25:32.345 calibre-debug[36901:1614919] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 7.15  embedded-python: True
macOS-14.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.5.0', 'Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112')
Python 3.11.5
OSX: ('14.5', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Obok DeDRM (10, 0, 9)
calibre 7.15  embedded-python: True
macOS-14.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.5.0', 'Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112')
Python 3.11.5
OSX: ('14.5', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Obok DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 133.00000199745963 x 133.0000019974596
[0.00] Starting up...
[0.01] Showing splash screen...
[0.16] splash screen shown
[0.16] Initializing db...
[0.18] db initialized
[0.18] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.79] GUI main window shown
[0.82] main UI initialized...
[0.82] Hiding splash screen
qt.qpa.fonts: Populating font family aliases took 216 ms. Replace uses of missing font family "Times" with one that exists to avoid this cost. 
Failed to request permission for showing notification: The operation couldn’t be completed. (UNErrorDomain error 1.)
[2.84] splash screen hidden
[2.84] Started up in 2.84 seconds with 3 books
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Evidence-Based Practice of Palliative Medicine - E-Book) finished
Convert book 1 of 1 (Evidence-Based Practice of Palliative Medicine - E-Book)
	DeDRM v10.0.9: Trying to decrypt 8y1zikat.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Evidence-Based Practice of Palliative Medicine - E-Book
	Found 0 keys to try after 0.3 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
	No k4Mac kindle-info/rainier/kinf2011 files have been found.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/Users/mabelkyinn/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/Users/mabelkyinn/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	mobidedrm.DrmException: No key found in 0 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  pdf_serif_family: 'Symbol'
	  verbose: 2
	  cover: '/var/folders/nb/nnj033qs0wbbt8xcy29f4scw0000gn/C/calibre_7.15.0_tmp_19t9ustk/aaluddhe.jpeg'
	  read_metadata_from_opf: '/var/folders/nb/nnj033qs0wbbt8xcy29f4scw0000gn/C/calibre_7.15.0_tmp_19t9ustk/oz6puaq9.opf'
	  output_profile: 'kindle_pw3'
	  pdf_mono_family: 'Menlo'
	Resolved conversion options
	calibre version: 7.15.0
	{'add_alt_text_to_img': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': '/var/folders/nb/nnj033qs0wbbt8xcy29f4scw0000gn/C/calibre_7.15.0_tmp_19t9ustk/aaluddhe.jpeg',
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x10f132950>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x10f145a10>,
	 'page_breaks_before': "//*[name()='h1' or name()='h2']",
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Menlo',
	 'pdf_mono_font_size': 16,
	 'pdf_no_cover': False,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Helvetica',
	 'pdf_serif_family': 'Symbol',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/nb/nnj033qs0wbbt8xcy29f4scw0000gn/C/calibre_7.15.0_tmp_19t9ustk/oz6puaq9.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	DeDRM v10.0.9: Trying to decrypt 8y1zikat.azw3
	MobiDeDrm v1.1.
	Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
	Decrypting Kindle Format 8 ebook: Evidence-Based Practice of Palliative Medicine - E-Book
	Found 0 keys to try after 0.0 seconds
	Crypto Type is: 2
	DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	No k4Mac kindle-info/rainier/kinf2011 files have been found.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/Users/mabelkyinn/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
	    mb.processBook(totalpids)
	  File "/Users/mabelkyinn/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
	    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
	mobidedrm.DrmException: No key found in 0 PIDs tried.
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: MOBI Input running
	on /var/folders/nb/nnj033qs0wbbt8xcy29f4scw0000gn/C/calibre_7.15.0_tmp_19t9ustk/8y1zikat.azw3
	Found KF8 MOBI of type 'standalone'
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 42, in <module>
	  File "site.py", line 38, in main
	  File "calibre/utils/ipc/worker.py", line 215, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1129, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre/ebooks/conversion/plugins/mobi_input.py", line 45, in convert
	  File "calibre/ebooks/mobi/reader/mobi8.py", line 87, in __call__
	  File "calibre/ebooks/mobi/reader/mobi6.py", line 163, in check_for_drm
	calibre.ebooks.DRMError: Evidence-Based Practice of Palliative Medicine - E-Book

```

**Comment by ElleKayEm** [comment]
If that is from or for an E-ink Kindle (not a Fire), then enter the Kindle's serial number in DeDRM's customization.

**Comment by mskyi** [comment]
Thank you! That solved the issue.
