### ISSUE TITLE
'make_release.py' script not working

### ISSUE THREAD

**Issue by SatyrTheTablecloth** [noDRM/DeDRM_tools#582]
### Question / bug report

when I try to launch the make_repease.py to create the plugins, I get this error: FileNotFoundError: [Errno 2] No such file or directory: 'DeDRM_plugin' .  There is a folder with this name in the directory.  I am also running Python 3.12.4.  I also notice the .zip archive unzips into two folders: 'DeDRM-tools_master' and 'DeDRM-tools_master 2'. Could this have something to do with it?

### Which version of Calibre are you running?

7.14

### Which version of the DeDRM plugin are you running?

10.1.0

### Log output

Traceback (most recent call last):
  File "/Users/ ... /Desktop/DeDRM_tools-master/make_release.py", line 105, in <module>
    print(make_release(version))
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ ... /Desktop/DeDRM_tools-master/make_release.py", line 59, in make_release
    shutil.copytree(DEDRM_SRC_DIR, DEDRM_SRC_TMP_DIR)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py", line 598, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'DeDRM_plugin'

**Comment by ElleKayEm** [comment]
If you want the latest code, it's here: https://github.com/noDRM/DeDRM_tools_autorelease/releases

**Comment by SatyrTheTablecloth** [comment]
> If you want the latest code, it's here: https://github.com/noDRM/DeDRM_tools_autorelease/releases

thanks! they work

**Comment by ElleKayEm** [comment]
You can probably close this issue since make_release.py isn't really needed at this point.  Anytime any change is made a new auto release is created.

**Comment by SatyrTheTablecloth** [comment]
> You can probably close this issue since make_release.py isn't really needed at this point. Anytime any change is made a new auto release is created.

thanks
