### ISSUE TITLE
Unable to remove DRM

### ISSUE THREAD

**Issue by BowieRas** [noDRM/DeDRM_tools#583]
### Question / bug report

Same error comes up for any Kindle book I try to open/convert

### Which version of Calibre are you running?

7.15

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

2.4.0

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.15  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 137.37464788732393 x 137.6169312169312
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[0.53] GUI main window shown
[0.64] main UI initialized...
[0.64] Hiding splash screen
[5.31] splash screen hidden
[5.31] Started up in 5.31 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b".\xf7\x94&&\x87\xe5#\x0fMp\x0c\x17\xa1\xaa\xe2hK ;\x80(\xadmA\xa1 \xad\xdd'c\x15", b'C:\\Users\\Bowie\\Documents\\My Kindle Content\\B09Y95BP6W_EBOK\\B09Y95BP6W_EBOK.azw', b'C:\\Users\\Bowie\\Documents\\My Kindle Content\\B09Y95BP6W_EBOK\\CR!QAQHA2MYT16YDCCTZAD3W1WJC5HJ.azw.md']
DeDRM v10.0.9: Trying to decrypt B09Y95BP6W_EBOK.azw
DeDRM v10.0.9: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.9 seconds
searching for kinfoFiles in C:\Users\Bowie\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Bowie\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1995080121' and UserName 'Bowie'
DeDRM v10.0.9: Found 1 new key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Bowie\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\Bowie\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.9: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\Bowie\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 481, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 267, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 502, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x81\xc4\xde\x02\x9d\x8c#\x01'
```

**Comment by j-howell** [comment]
You need the KFX Input plugin.
