### ISSUE TITLE
DeDRM not working

### ISSUE THREAD

**Issue by mrspraz** [noDRM/DeDRM_tools#589]
### Which version of Calibre are you running?

4.23

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
Paste log output here.
``calibre Debug log
calibre 4.23  embedded-python: True is64bit: True
Darwin-23.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.6.0', 'Darwin Kernel Version 23.6.0: Sun Jun 30 19:42:22 PDT 2024; root:xnu-10063.140.33~20/RELEASE_ARM64_T8103')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 4.23  embedded-python: True is64bit: True
Darwin-23.6.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '23.6.0', 'Darwin Kernel Version 23.6.0: Sun Jun 30 19:42:22 PDT 2024; root:xnu-10063.140.33~20/RELEASE_ARM64_T8103')
Python 2.7.16
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.500001915 x 127.500001915
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.16] db initialized
[0.16] Constructing main UI...
[1.62] main UI initialized...
[1.62] Hiding splash screen
DeDRM v10.0.3: Trying to decrypt (Tags of Honor) Reese 06 - Annabella Stone.azw3
Using Library AlfCrypto Python
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages/calibre/customize/ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 944, in KindleMobiDecrypt
  File "site-packages/calibre/customize/zipplugin.py", line 185, in load_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 105, in <module>
  File "site-packages/calibre/customize/zipplugin.py", line 181, in load_module
  File "calibre_plugins.dedrm.topazextract", line 246
    if debug: print("%d records in header " % nbValues, end=' ')
                                                           ^
SyntaxError: invalid syntax
[10.89] splash screen hidden
[10.89] Started up in 10.89 seconds with 0 books

Debugging DND event
text/uri-list 90 'file:///Users/Bree/Desktop/(Tags%20of%20Honor)%20Reese%2006%20-%20Annabella%20Stone.azw3\r\n' 


Firefox rurl: None None
URLS: [u'file:///Users/Bree/Desktop/(Tags%20of%20Honor)%20Reese%2006%20-%20Annabella%20Stone.azw3']
Paths: [u'/Users/Bree/Desktop/(Tags of Honor) Reese 06 - Annabella Stone.azw3']
Extensions: frozenset([u'azw3'])
Added Reese: MM Military Suspense (Tags of Honor: Red Squadron Book 6) to db in: 0.0
Added 1 books in 0.4 seconds

**Comment by noDRM** [comment]
This particular issue is definitely fixed in the newer alpha versions, so i'm going to close this. If there's other error messages with the alpha, please re-open and post a new log.
