### ISSUE TITLE
Can not remove dedrm from lcpl

### ISSUE THREAD

**Issue by Anze167** [noDRM/DeDRM_tools#590]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Dnevnik odpravljanja napak
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: sl
Successfully initialized third party plugins: LCPL Input (0, 0, 5) && Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && Set KFX metadata (from KFX Output) (2, 6, 1) && KFX Output (2, 6, 1) && Obok DeDRM (10, 0, 3)
calibre 6.2.1  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.10.1
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: sl
Successfully initialized third party plugins: LCPL Input (0, 0, 5) && Gather KFX-ZIP (from KFX Input) (2, 8, 1) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 8, 1) && KFX metadata reader (from KFX Input) (2, 8, 1) && From KFX (2, 8, 1) && KFX Input (2, 8, 1) && Set KFX metadata (from KFX Output) (2, 6, 1) && KFX Output (2, 6, 1) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.08521739130434 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.81] main UI initialized...
[1.81] Hiding splash screen
Starting QuickView
[8.81] splash screen hidden
[8.81] Started up in 8.81 seconds with 19 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xdb\xa1n\xaetE\xda \xe0\xdeI\xbf\xc0\xf7S\x1e4f\x04i\x84\x10\xde\x84O\xdb\x95*\x14\xf0SS', b'C:\\Users\\Admin\\Downloads\\lcpl_p_130317.lcpl']
DeDRM v10.0.3: Trying to decrypt ihmj0390.epub
DeDRM v10.0.3: Verifying zip archive integrity
LCP: Found LCP-encrypted book 18ac5fe1-c3e0-4cd6-a1ab-675389bdd48f
Looks like that didn't work:
LCPL Input v0.0.5: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.lcplinput.__init__", line 368, in run
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 345, in ePubDecrypt
  File "C:\Users\Admin\AppData\Roaming\calibre\plugins\DeDRM.zip\lcpdedrm.py", line 318, in decryptLCPbook
lcpdedrm.LCPError: Book is using an unknown LCP encryption standard: http://readium.org/lcp/profile-2.7
LCPL Input v0.0.5: Trying to parse file lcpl_p_130317.lcpl
LCPL Input v0.0.5: Looks like this is a LCPL license file
LCPL Input v0.0.5: Found LCPL for book ID 18ac5fe1-c3e0-4cd6-a1ab-675389bdd48f
LCPL Input v0.0.5: Downloading book from https://storage.googleapis.com/ink-lcp-books-biblos-prod/8adfc511-5672-4900-8ebc-7ba9536d3a44 with custom UA ...
LCPL Input v0.0.5: Executing plugin DeDRM ...
LCPL Input v0.0.5: Plugin returned nothing - skippAdded Znanost_mirnega_zivljenja to db in: 0.2
Added 1 books in 1.7 seconds

### Which version of Calibre are you running?

6.2.1

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
No longer supported.  See here: https://github.com/noDRM/DeDRM_tools/issues/18
