### ISSUE TITLE
Cannot add dedrm zip plug in

### ISSUE THREAD

**Issue by eggstaticmunchkin** [noDRM/DeDRM_tools#593]
### Question / bug report

calibre, version 7.16.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/kiarawhite/Downloads/DeDRM_tools-master.zip' is invalid. It does not contain a top-level __init__.py file

calibre 7.16  embedded-python: True
macOS-14.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.5.0', 'Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.5', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 322, in add_plugin
  File "calibre/customize/ui.py", line 525, in add_plugin
  File "calibre/customize/ui.py", line 76, in load_plugin
  File "calibre/customize/zipplugin.py", line 297, in load
  File "calibre/customize/zipplugin.py", line 392, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/kiarawhite/Downloads/DeDRM_tools-master.zip' is invalid. It does not contain a top-level __init__.py file

### Which version of Calibre are you running?

6.23

### Which version of the DeDRM plugin are you running?

v10.02

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Download DeDRM_tools_10.0.9.zip from the first link under Assets here: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Unzip that file and load DeDRM_plugin.zip into calibre.

Or the latest code is available here:  https://github.com/noDRM/DeDRM_tools_autorelease/releases/tag/autorelease_3373d938749117989dfd0a42cc947bf338d3ffda

**Comment by eggstaticmunchkin** [comment]
Now I have trouble removing DRM from an Epub file:

ApplicationPaletteChange event ignored
Using calibre Qt style: True
2024-08-06 16:21:27.211 calibre-debug[80725:23320889] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre Debug log
calibre 7.16  embedded-python: True
macOS-14.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.5.0', 'Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.5', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Obok DeDRM (10, 0, 3)
calibre 7.16  embedded-python: True
macOS-14.5-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.5.0', 'Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.5', ('', '', ''), 'arm64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0) && Obok DeDRM (10, 0, 3)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.04] Showing splash screen...
[0.18] splash screen shown
[0.18] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[0.83] GUI main window shown
[0.85] main UI initialized...
[0.85] Hiding splash screen
DeDRM v10.0.3: Trying to decrypt With You Forever - Chloe Liese.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: With You Forever - Chloe Liese.epub is a secure Adobe Adept ePub for UUID 0b04afa0-543a-11ef-b22c-b5eeab3a73fd
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.3 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
    defaultkeys, defaultnames = adeptkeys()
                                ^^^^^^^^^^^
  File "/Users/kiarawhite/Library/Preferences/calibre/plugins/DeDRM.zip/adobekey.py", line 439, in adeptkeys
    raise ADEPTError("Could not find ADE activation.dat file.")
adobekey.ADEPTError: Could not find ADE activation.dat file.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[7.30] splash screen hidden
[7.30] Started up in 7.30 seconds with 1 books
Added With You Forever to db in: 0.0
Added 1 books in 1.1 seconds
qt.qpa.fonts: Populating font family aliases took 69 ms. Replace uses of missing font family "Times" with one that exists to avoid this cost. 
Failed to request permission for showing notification: The operation couldn’t be completed. (UNErrorDomain error 1.)
Worker Launch took: 0.02 seconds
Job: 0 Convert book 1 of 1 (With You Forever) finished
Convert book 1 of 1 (With You Forever)
	DeDRM v10.0.3: Trying to decrypt c4dnxh75.epub
	DeDRM v10.0.3: Verifying zip archive integrity
	DeDRM v10.0.3: c4dnxh75.epub is a secure Adobe Adept ePub for UUID 0b04afa0-543a-11ef-b22c-b5eeab3a73fd
	DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
	DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
	    defaultkeys, defaultnames = adeptkeys()
	                                ^^^^^^^^^^^
	  File "/Users/kiarawhite/Library/Preferences/calibre/plugins/DeDRM.zip/adobekey.py", line 439, in adeptkeys
	    raise ADEPTError("Could not find ADE activation.dat file.")
	adobekey.ADEPTError: Could not find ADE activation.dat file.
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1067, in run
	    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  pdf_serif_family: 'Symbol'
	  read_metadata_from_opf: '/var/folders/nt/lvgt4shs32lds71vpm82fnfr0000gn/C/calibre_7.16.0_tmp_htq1w0x5/2zj8s734.opf'
	  pdf_mono_family: 'Menlo'
	  verbose: 2
	  output_profile: 'kindle_pw3'
	Resolved conversion options
	calibre version: 7.16.0
	{'add_alt_text_to_img': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'custom_size': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x11aa70f90>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x11aa63b10>,
	 'page_breaks_before': '/',
	 'paper_size': 'letter',
	 'pdf_add_toc': False,
	 'pdf_default_font_size': 20,
	 'pdf_footer_template': None,
	 'pdf_header_template': None,
	 'pdf_hyphenate': False,
	 'pdf_mark_links': False,
	 'pdf_mono_family': 'Menlo',
	 'pdf_mono_font_size': 16,
	 'pdf_no_cover': False,
	 'pdf_odd_even_offset': 0.0,
	 'pdf_page_margin_bottom': 72.0,
	 'pdf_page_margin_left': 72.0,
	 'pdf_page_margin_right': 72.0,
	 'pdf_page_margin_top': 72.0,
	 'pdf_page_number_map': None,
	 'pdf_page_numbers': False,
	 'pdf_sans_family': 'Helvetica',
	 'pdf_serif_family': 'Symbol',
	 'pdf_standard_font': 'serif',
	 'pdf_use_document_margins': False,
	 'prefer_metadata_cover': False,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': '/var/folders/nt/lvgt4shs32lds71vpm82fnfr0000gn/C/calibre_7.16.0_tmp_htq1w0x5/2zj8s734.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'uncompressed_pdf': False,
	 'unit': 'inch',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'use_profile_size': False,
	 'verbose': 2}
	DeDRM v10.0.3: Trying to decrypt c4dnxh75.epub
	DeDRM v10.0.3: Verifying zip archive integrity
	DeDRM v10.0.3: c4dnxh75.epub is a secure Adobe Adept ePub for UUID 0b04afa0-543a-11ef-b22c-b5eeab3a73fd
	DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
	DeDRM v10.0.3: Exception when getting default Adobe Key after 0.0 seconds
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 591, in ePubDecrypt
	    defaultkeys, defaultnames = adeptkeys()
	                                ^^^^^^^^^^^
	  File "/Users/kiarawhite/Library/Preferences/calibre/plugins/DeDRM.zip/adobekey.py", line 439, in adeptkeys
	    raise ADEPTError("Could not find ADE activation.dat file.")
	adobekey.ADEPTError: Could not find ADE activation.dat file.
	DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre/customize/ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1067, in run
	    decrypted_ebook = self.ePubDecrypt(path_to_ebook)
	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
	    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: EPUB Input running
	on /var/folders/nt/lvgt4shs32lds71vpm82fnfr0000gn/C/calibre_7.16.0_tmp_htq1w0x5/c4dnxh75.epub
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 42, in <module>
	  File "site.py", line 38, in main
	  File "calibre/utils/ipc/worker.py", line 215, in main
	  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
	  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
	  File "calibre/ebooks/conversion/plumber.py", line 1129, in run
	  File "calibre/customize/conversion.py", line 245, in __call__
	  File "calibre/ebooks/conversion/plugins/epub_input.py", line 293, in convert
	calibre.ebooks.DRMError: c4dnxh75.epub

**Comment by ElleKayEm** [comment]
Do you have Adobe Digital Editions on this computer?  Is it authorized with your Adobe ID?  Looks like DeDRM isn't able to find your key.  Also recommend DeDRM 10.0.9.
