### ISSUE TITLE
DeDRM not working (Adobe Digital Editions)

### ISSUE THREAD

**Issue by BigFurryMonster** [noDRM/DeDRM_tools#594]
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.19] db initialized
[0.19] Constructing main UI...
[0.56] GUI main window shown
[0.59] main UI initialized...
[0.59] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Percy Jackson and the Olympians The Chalice of the Gods.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Percy Jackson and the Olympians The Chalice of the Gods.epub is a secure Adobe Adept ePub for UUID ac3aa437-0958-4688-8991-3b7b009ded5e
DeDRM v10.0.9: Trying Encryption key 2b663c1a-bf02-41c0-8128-ab06c3af40bb_AdobeID_rutgermooy@gmail.com
_7p1fm8l.epub is a secure Adobe Adept ePub.
Could not decrypt _7p1fm8l.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
  File "Crypto\Cipher\AES.py", line 228, in new
  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)

DeDRM v10.0.9: Failed to decrypt with key 2b663c1a-bf02-41c0-8128-ab06c3af40bb_AdobeID_rutgermooy@gmail.com after 0.1 seconds
DeDRM v10.0.9: Trying Encryption key DeACSM_uuid_2b663c1a-bf02-41c0-8128-ab06c3af40bb
_7p1fm8l.epub is a secure Adobe Adept ePub.
Could not decrypt _7p1fm8l.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 253, in decryptBook
  File "Crypto\PublicKey\RSA.py", line 820, in import_key
  File "Crypto\PublicKey\RSA.py", line 719, in _import_keyDER
ValueError: RSA key format is not supported

DeDRM v10.0.9: Failed to decrypt with key DeACSM_uuid_2b663c1a-bf02-41c0-8128-ab06c3af40bb after 0.1 seconds
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
Found 1 keys
DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1041, in run
  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[10.58] splash screen hidden
[10.58] Started up in 10.58 seconds with 27 books
Added Percy Jackson and the Olympians: The Chalice of the Gods to db in: 0.1
Added 1 books in 0.7 seconds
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (Percy Jackson and the Olympians: The Chalice of the Gods) finished
Convert book 1 of 1 (Percy Jackson and the Olympians: The Chalice of the Gods)

	DeDRM v10.0.9: Trying to decrypt dnui0odw.epub
	DeDRM v10.0.9: Verifying zip archive integrity
	DeDRM v10.0.9: dnui0odw.epub is a secure Adobe Adept ePub for UUID ac3aa437-0958-4688-8991-3b7b009ded5e
	DeDRM v10.0.9: Trying Encryption key 2b663c1a-bf02-41c0-8128-ab06c3af40bb_AdobeID_rutgermooy@gmail.com
	4ph1uj5j.epub is a secure Adobe Adept ePub.
	Could not decrypt 4ph1uj5j.epub because of an exception:
	Traceback (most recent call last):
	  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
	  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
	  File "Crypto\Cipher\AES.py", line 228, in new
	  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
	  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
	  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
	ValueError: Incorrect AES key length (0 bytes)
	
	DeDRM v10.0.9: Failed to decrypt with key 2b663c1a-bf02-41c0-8128-ab06c3af40bb_AdobeID_rutgermooy@gmail.com after 0.1 seconds
	DeDRM v10.0.9: Trying Encryption key DeACSM_uuid_2b663c1a-bf02-41c0-8128-ab06c3af40bb
	4ph1uj5j.epub is a secure Adobe Adept ePub.
	Could not decrypt 4ph1uj5j.epub because of an exception:
	Traceback (most recent call last):
	  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 253, in decryptBook
	  File "Crypto\PublicKey\RSA.py", line 820, in import_key
	  File "Crypto\PublicKey\RSA.py", line 719, in _import_keyDER
	ValueError: RSA key format is not supported
	
	DeDRM v10.0.9: Failed to decrypt with key DeACSM_uuid_2b663c1a-bf02-41c0-8128-ab06c3af40bb after 0.1 seconds
	DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
	Found 1 keys
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1041, in run

	  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	Conversion options changed from defaults:

	  output_profile: 'kobo'

	  read_metadata_from_opf: 'C:\\Users\\Rutger\\AppData\\Local\\Temp\\calibre_tp6_zaa8\\x9vrxlyo.opf'

	  verbose: 2

	Resolved conversion options

	calibre version: 7.16.0

	{'add_alt_text_to_img': False,

	 'asciiize': False,

	 'author_sort': None,

	 'authors': None,

	 'base_font_size': 0.0,

	 'book_producer': None,

	 'change_justification': 'original',

	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "

	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "

	            "'i')) or @class = 'chapter']",

	 'chapter_mark': 'pagebreak',

	 'comments': None,

	 'cover': None,

	 'debug_pipeline': None,

	 'dehyphenate': True,

	 'delete_blank_paragraphs': True,

	 'disable_font_rescaling': False,

	 'dont_split_on_page_breaks': False,

	 'duplicate_links_in_toc': False,

	 'embed_all_fonts': False,

	 'embed_font_family': None,

	 'enable_heuristics': False,

	 'epub_flatten': False,

	 'epub_inline_toc': False,

	 'epub_max_image_size': 'none',

	 'epub_toc_at_end': False,

	 'epub_version': '2',

	 'expand_css': False,

	 'extra_css': None,

	 'extract_to': None,

	 'filter_css': '',

	 'fix_indents': True,

	 'flow_size': 260,

	 'font_size_mapping': None,

	 'format_scene_breaks': True,

	 'html_unwrap_factor': 0.4,

	 'input_encoding': None,

	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000017B1B6D7450>,

	 'insert_blank_line': False,

	 'insert_blank_line_size': 0.5,

	 'insert_metadata': False,

	 'isbn': None,

	 'italicize_common_cases': True,

	 'keep_ligatures': False,

	 'language': None,

	 'level1_toc': None,

	 'level2_toc': None,

	 'level3_toc': None,

	 'line_height': 0.0,

	 'linearize_tables': False,

	 'margin_bottom': 5.0,

	 'margin_left': 5.0,

	 'margin_right': 5.0,

	 'margin_top': 5.0,

	 'markup_chapter_headings': True,

	 'max_toc_links': 50,

	 'minimum_line_height': 120.0,

	 'no_chapters_in_toc': False,

	 'no_default_epub_cover': False,

	 'no_inline_navbars': False,

	 'no_svg_cover': False,

	 'output_profile': <calibre.customize.profiles.KoboReaderOutput object at 0x0000017B1B694050>,

	 'page_breaks_before': '/',

	 'prefer_metadata_cover': False,

	 'preserve_cover_aspect_ratio': False,

	 'pretty_print': True,

	 'pubdate': None,

	 'publisher': None,

	 'rating': None,

	 'read_metadata_from_opf': 'C:\\Users\\Rutger\\AppData\\Local\\Temp\\calibre_tp6_zaa8\\x9vrxlyo.opf',

	 'remove_fake_margins': True,

	 'remove_first_image': False,

	 'remove_paragraph_spacing': False,

	 'remove_paragraph_spacing_indent_size': 1.5,

	 'renumber_headings': True,

	 'replace_scene_breaks': '',

	 'search_replace': '[]',

	 'series': None,

	 'series_index': None,

	 'smarten_punctuation': False,

	 'sr1_replace': None,

	 'sr1_search': None,

	 'sr2_replace': None,

	 'sr2_search': None,

	 'sr3_replace': None,

	 'sr3_search': None,

	 'start_reading_at': None,

	 'subset_embedded_fonts': False,

	 'tags': None,

	 'timestamp': None,

	 'title': None,

	 'title_sort': None,

	 'toc_filter': None,

	 'toc_threshold': 6,

	 'toc_title': None,

	 'transform_css_rules': '[]',

	 'transform_html_rules': '[]',

	 'unsmarten_punctuation': False,

	 'unwrap_lines': True,

	 'use_auto_toc': False,

	 'verbose': 2}

	DeDRM v10.0.9: Trying to decrypt dnui0odw.epub
	DeDRM v10.0.9: Verifying zip archive integrity
	DeDRM v10.0.9: dnui0odw.epub is a secure Adobe Adept ePub for UUID ac3aa437-0958-4688-8991-3b7b009ded5e
	DeDRM v10.0.9: Trying Encryption key 2b663c1a-bf02-41c0-8128-ab06c3af40bb_AdobeID_rutgermooy@gmail.com
	rey7ul_n.epub is a secure Adobe Adept ePub.
	Could not decrypt rey7ul_n.epub because of an exception:
	Traceback (most recent call last):
	  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 275, in decryptBook
	  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 91, in __init__
	  File "Crypto\Cipher\AES.py", line 228, in new
	  File "Crypto\Cipher\__init__.py", line 79, in _create_cipher
	  File "Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
	  File "Crypto\Cipher\AES.py", line 90, in _create_base_cipher
	ValueError: Incorrect AES key length (0 bytes)
	
	DeDRM v10.0.9: Failed to decrypt with key 2b663c1a-bf02-41c0-8128-ab06c3af40bb_AdobeID_rutgermooy@gmail.com after 0.0 seconds
	DeDRM v10.0.9: Trying Encryption key DeACSM_uuid_2b663c1a-bf02-41c0-8128-ab06c3af40bb
	rey7ul_n.epub is a secure Adobe Adept ePub.
	Could not decrypt rey7ul_n.epub because of an exception:
	Traceback (most recent call last):
	  File "C:\Users\Rutger\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 253, in decryptBook
	  File "Crypto\PublicKey\RSA.py", line 820, in import_key
	  File "Crypto\PublicKey\RSA.py", line 719, in _import_keyDER
	ValueError: RSA key format is not supported
	
	DeDRM v10.0.9: Failed to decrypt with key DeACSM_uuid_2b663c1a-bf02-41c0-8128-ab06c3af40bb after 0.0 seconds
	DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
	Found 1 keys
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:

	Traceback (most recent call last):

	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins

	  File "calibre_plugins.dedrm.__init__", line 1041, in run

	  File "calibre_plugins.dedrm.__init__", line 639, in ePubDecrypt

	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

	InputFormatPlugin: EPUB Input running

	on C:\Users\Rutger\AppData\Local\Temp\calibre_tp6_zaa8\dnui0odw.epub

	Traceback (most recent call last):

	  File "runpy.py", line 198, in _run_module_as_main

	  File "runpy.py", line 88, in _run_code

	  File "site.py", line 83, in <module>

	  File "site.py", line 78, in main

	  File "site.py", line 50, in run_entry_point

	  File "calibre\utils\ipc\worker.py", line 215, in main

	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override

	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert

	  File "calibre\ebooks\conversion\plumber.py", line 1129, in run

	  File "calibre\customize\conversion.py", line 245, in __call__

	  File "calibre\ebooks\conversion\plugins\epub_input.py", line 293, in convert

	calibre.ebooks.DRMError: dnui0odw.epub

**Comment by ElleKayEm** [comment]
Looks like it's failing to find a key.  Did you use ADE on this computer to download the book?  Or DeASCM?  Is either or both authorized with your Adobe ID?

**Comment by BigFurryMonster** [comment]
Played around with AdobeIDs and finally succeeded to get this book. Thanks for pointing out that a key is actually needed!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by BigFurryMonster** [comment]
closing!
