### ISSUE TITLE
Cannot Convert

### ISSUE THREAD

**Issue by bluerazzxxl** [noDRM/DeDRM_tools#596]
### Question / bug report

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.16  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: [Calibre Installation Path]\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.16  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: [Calibre Installation Path]\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 104.20512820512819 x 104.20512820512819
[0.00] Starting up...
[0.00] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[1.09] GUI main window shown
[1.14] main UI initialized...
[1.14] Hiding splash screen
[72.25] splash screen hidden
[72.25] Started up in 72.25 seconds with 2 books
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide) finished
Convert book 1 of 1 (CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide)
    DeDRM v10.0.9: Trying to decrypt [file_id].azw3
    MobiDeDrm v1.1.
    Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide
    Found 0 keys to try after 1.0 seconds
    Crypto Type is: 2
    DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
    DeDRM v10.0.9: Looking for new default Kindle Key after 1.0 seconds
    searching for kinfoFiles in [user_path]\AppData\Local
    Found K4PC 1.25+ kinf2018 file: [user_path]\AppData\Local\Amazon\Kindle\storage\.kinf2018
    Decrypted key file using IDString '[IDString]' and UserName '[user]'
    DeDRM v10.0.9: Found 1 new key
    MobiDeDrm v1.1.
    Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide
    Got DSN key from database key_0
    Found 4 keys to try after 1.3 seconds
    Crypto Type is: 2
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 0 PIDs tried.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 4 PIDs tried.
    DeDRM v10.0.9: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
    Running file type plugin DeDRM failed with traceback:
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 0 PIDs tried.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
      File "calibre_plugins.dedrm.__init__", line 1030, in run
      File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
    Conversion options changed from defaults:
      output_profile: 'kindle_pw3'
      pdf_sans_family: 'Tahoma'
      pdf_mono_family: 'Courier New'
      verbose: 2
      pdf_serif_family: 'Tahoma'
      read_metadata_from_opf: '[user_path]\AppData\Local\Temp\[temp_folder]\[file_id].opf'
      cover: '[user_path]\AppData\Local\Temp\[temp_folder]\[cover_image].jpeg'
    Resolved conversion options
    calibre version: 7.16.0
    {'add_alt_text_to_img': False,
     'asciiize': False,
     'author_sort': None,
     'authors': None,
     'base_font_size': 0.0,
     'book_producer': None,
     'change_justification': 'original',
     'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
                "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
                "'i')) or @class = 'chapter']",
     'chapter_mark': 'pagebreak',
     'comments': None,
     'cover': '[user_path]\AppData\Local\Temp\[temp_folder]\[cover_image].jpeg',
     'custom_size': None,
     'debug_pipeline': None,
     'dehyphenate': True,
     'delete_blank_paragraphs': True,
     'disable_font_rescaling': False,
     'duplicate_links_in_toc': False,
     'embed_all_fonts': False,
     'embed_font_family': None,
     'enable_heuristics': False,
     'expand_css': False,
     'extra_css': None,
     'filter_css': '',
     'fix_indents': True,
     'font_size_mapping': None,
     'format_scene_breaks': True,
     'html_unwrap_factor': 0.4,
     'input_encoding': None,
     'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000135243E0B90>,
     'insert_blank_line': False,
     'insert_blank_line_size': 0.5,
     'insert_metadata': False,
     'isbn': None,
     'italicize_common_cases': True,
     'keep_ligatures': False,
     'language': None,
     'level1_toc': None,
     'level2_toc': None,
     'level3_toc': None,
     'line_height': 0.0,
     'linearize_tables': False,
     'margin_bottom': 5.0,
     'margin_left': 5.0,
     'margin_right': 5.0,
     'margin_top': 5.0,
     'markup_chapter_headings': True,
     'max_toc_links': 50,
     'minimum_line_height': 120.0,
     'no_chapters_in_toc': False,
     'no_inline_navbars': False,
     'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x00000135243D7890>,
     'page_breaks_before': "//*[name()='h1' or name()='h2']",
     'paper_size': 'letter',
     'pdf_add_toc': False,
     'pdf_default_font_size': 20,
     'pdf_footer_template': None,
     'pdf_header_template': None,
     'pdf_hyphenate': False,
     'pdf_mark_links': False,
     'pdf_mono_family': 'Courier New',
     'pdf_mono_font_size': 16,
     'pdf_no_cover': False,
     'pdf_odd_even_offset': 0.0,
     'pdf_page_margin_bottom': 72.0,
     'pdf_page_margin_left': 72.0,
     'pdf_page_margin_right': 72.0,
     'pdf_page_margin_top': 72.0,
     'pdf_page_number_map': None,
     'pdf_page_numbers': False,
     'pdf_sans_family': 'Tahoma',
     'pdf_serif_family': 'Tahoma',
     'pdf_standard_font': 'serif',
     'pdf_use_document_margins': False,
     'prefer_metadata_cover': False,
     'preserve_cover_aspect_ratio': False,
     'pretty_print': False,
     'pubdate': None,
     'publisher': None,
     'rating': None,
     'read_metadata_from_opf': '[user_path]\AppData\Local\Temp\[temp_folder]\[file_id].opf',
     'remove_fake_margins': True,
     'remove_first_image': False,
     'remove_paragraph_spacing': False,
     'remove_paragraph_spacing_indent_size': 1.5,
     'renumber_headings': True,
     'replace_scene_breaks': '',
     'search_replace': '[]',
     'series': None,
     'series_index': None,
     'smarten_punctuation': False,
     'sr1_replace': None,
     'sr1_search': None,
     'sr2_replace': None,
     'sr2_search': None,
     'sr3_replace': None,
     'sr3_search': None,
     'start_reading_at': None,
     'subset_embedded_fonts': False,
     'tags': None,
     'timestamp': None,
     'title': None,
     'title_sort': None,
     'toc_filter': None,
     'toc_threshold': 6,
     'toc_title': None,
     'transform_css_rules': '[]',
     'transform_html_rules': '[]',
     'uncompressed_pdf': False,
     'unit': 'inch',
     'unsmarten_punctuation': False,
     'unwrap_lines': True,
     'use_auto_toc': False,
     'use_profile_size': False,
     'verbose': 2}
    DeDRM v10.0.9: Trying to decrypt [file_id].azw3
    MobiDeDrm v1.1.
    Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide
    Found 0 keys to try after 0.1 seconds
    Crypto Type is: 2
    DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
    DeDRM v10.0.9: Looking for new default Kindle Key after 0.1 seconds
    searching for kinfoFiles in [user_path]\AppData\Local
    Found K4PC 1.25+ kinf2018 file: [user_path]\AppData\Local\Amazon\Kindle\storage\.kinf2018
    Decrypted key file using IDString '[IDString]' and UserName '[user]'
    DeDRM v10.0.9: Found 1 new key
    MobiDeDrm v1.1.
    Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide
    Got DSN key from database key_0
    Found 4 keys to try after 0.4 seconds
    Crypto Type is: 2
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 0 PIDs tried.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 4 PIDs tried.
    DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
    Running file type plugin DeDRM failed with traceback:
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 0 PIDs tried.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
      File "calibre_plugins.dedrm.__init__", line 1030, in run
      File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
    InputFormatPlugin: MOBI Input running
    on [user_path]\AppData\Local\Temp\[temp_folder]\[file_id].azw3
    Found KF8 MOBI of type 'standalone'
    Traceback (most recent call last):
      File "runpy.py", line 198, in _run_module_as_main
      File "runpy.py", line 88, in _run_code
      File "site.py", line 83, in <module>
      File "site.py", line 78, in main
      File "site.py", line 50, in run_entry_point
      File "calibre\utils\ipc\worker.py", line 215, in main
      File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
      File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
      File "calibre\ebooks\conversion\plumber.py", line 1129, in run
      File "calibre\customize\conversion.py", line 245, in __call__
      File "calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
      File "calibre\ebooks\mobi\reader\mobi8.py", line 87, in __call__
      File "calibre\ebooks\mobi\reader\mobi6.py", line 163, in check_for_drm
    calibre.ebooks.DRMError: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide

### Which version of Calibre are you running?

7.16

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

2.4

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.16  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: [Calibre Installation Path]\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.16  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: [Calibre Installation Path]\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 104.20512820512819 x 104.20512820512819
[0.00] Starting up...
[0.00] Showing splash screen...
[0.23] splash screen shown
[0.23] Initializing db...
[0.30] db initialized
[0.30] Constructing main UI...
[1.09] GUI main window shown
[1.14] main UI initialized...
[1.14] Hiding splash screen
[72.25] splash screen hidden
[72.25] Started up in 72.25 seconds with 2 books
Worker Launch took: 0.03 seconds
Job: 0 Convert book 1 of 1 (CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide) finished
Convert book 1 of 1 (CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide)
    DeDRM v10.0.9: Trying to decrypt [file_id].azw3
    MobiDeDrm v1.1.
    Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide
    Found 0 keys to try after 1.0 seconds
    Crypto Type is: 2
    DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
    DeDRM v10.0.9: Looking for new default Kindle Key after 1.0 seconds
    searching for kinfoFiles in [user_path]\AppData\Local
    Found K4PC 1.25+ kinf2018 file: [user_path]\AppData\Local\Amazon\Kindle\storage\.kinf2018
    Decrypted key file using IDString '[IDString]' and UserName '[user]'
    DeDRM v10.0.9: Found 1 new key
    MobiDeDrm v1.1.
    Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide
    Got DSN key from database key_0
    Found 4 keys to try after 1.3 seconds
    Crypto Type is: 2
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 0 PIDs tried.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 4 PIDs tried.
    DeDRM v10.0.9: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
    Running file type plugin DeDRM failed with traceback:
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 0 PIDs tried.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
      File "calibre_plugins.dedrm.__init__", line 1030, in run
      File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
    Conversion options changed from defaults:
      output_profile: 'kindle_pw3'
      pdf_sans_family: 'Tahoma'
      pdf_mono_family: 'Courier New'
      verbose: 2
      pdf_serif_family: 'Tahoma'
      read_metadata_from_opf: '[user_path]\AppData\Local\Temp\[temp_folder]\[file_id].opf'
      cover: '[user_path]\AppData\Local\Temp\[temp_folder]\[cover_image].jpeg'
    Resolved conversion options
    calibre version: 7.16.0
    {'add_alt_text_to_img': False,
     'asciiize': False,
     'author_sort': None,
     'authors': None,
     'base_font_size': 0.0,
     'book_producer': None,
     'change_justification': 'original',
     'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
                "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
                "'i')) or @class = 'chapter']",
     'chapter_mark': 'pagebreak',
     'comments': None,
     'cover': '[user_path]\AppData\Local\Temp\[temp_folder]\[cover_image].jpeg',
     'custom_size': None,
     'debug_pipeline': None,
     'dehyphenate': True,
     'delete_blank_paragraphs': True,
     'disable_font_rescaling': False,
     'duplicate_links_in_toc': False,
     'embed_all_fonts': False,
     'embed_font_family': None,
     'enable_heuristics': False,
     'expand_css': False,
     'extra_css': None,
     'filter_css': '',
     'fix_indents': True,
     'font_size_mapping': None,
     'format_scene_breaks': True,
     'html_unwrap_factor': 0.4,
     'input_encoding': None,
     'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000135243E0B90>,
     'insert_blank_line': False,
     'insert_blank_line_size': 0.5,
     'insert_metadata': False,
     'isbn': None,
     'italicize_common_cases': True,
     'keep_ligatures': False,
     'language': None,
     'level1_toc': None,
     'level2_toc': None,
     'level3_toc': None,
     'line_height': 0.0,
     'linearize_tables': False,
     'margin_bottom': 5.0,
     'margin_left': 5.0,
     'margin_right': 5.0,
     'margin_top': 5.0,
     'markup_chapter_headings': True,
     'max_toc_links': 50,
     'minimum_line_height': 120.0,
     'no_chapters_in_toc': False,
     'no_inline_navbars': False,
     'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x00000135243D7890>,
     'page_breaks_before': "//*[name()='h1' or name()='h2']",
     'paper_size': 'letter',
     'pdf_add_toc': False,
     'pdf_default_font_size': 20,
     'pdf_footer_template': None,
     'pdf_header_template': None,
     'pdf_hyphenate': False,
     'pdf_mark_links': False,
     'pdf_mono_family': 'Courier New',
     'pdf_mono_font_size': 16,
     'pdf_no_cover': False,
     'pdf_odd_even_offset': 0.0,
     'pdf_page_margin_bottom': 72.0,
     'pdf_page_margin_left': 72.0,
     'pdf_page_margin_right': 72.0,
     'pdf_page_margin_top': 72.0,
     'pdf_page_number_map': None,
     'pdf_page_numbers': False,
     'pdf_sans_family': 'Tahoma',
     'pdf_serif_family': 'Tahoma',
     'pdf_standard_font': 'serif',
     'pdf_use_document_margins': False,
     'prefer_metadata_cover': False,
     'preserve_cover_aspect_ratio': False,
     'pretty_print': False,
     'pubdate': None,
     'publisher': None,
     'rating': None,
     'read_metadata_from_opf': '[user_path]\AppData\Local\Temp\[temp_folder]\[file_id].opf',
     'remove_fake_margins': True,
     'remove_first_image': False,
     'remove_paragraph_spacing': False,
     'remove_paragraph_spacing_indent_size': 1.5,
     'renumber_headings': True,
     'replace_scene_breaks': '',
     'search_replace': '[]',
     'series': None,
     'series_index': None,
     'smarten_punctuation': False,
     'sr1_replace': None,
     'sr1_search': None,
     'sr2_replace': None,
     'sr2_search': None,
     'sr3_replace': None,
     'sr3_search': None,
     'start_reading_at': None,
     'subset_embedded_fonts': False,
     'tags': None,
     'timestamp': None,
     'title': None,
     'title_sort': None,
     'toc_filter': None,
     'toc_threshold': 6,
     'toc_title': None,
     'transform_css_rules': '[]',
     'transform_html_rules': '[]',
     'uncompressed_pdf': False,
     'unit': 'inch',
     'unsmarten_punctuation': False,
     'unwrap_lines': True,
     'use_auto_toc': False,
     'use_profile_size': False,
     'verbose': 2}
    DeDRM v10.0.9: Trying to decrypt [file_id].azw3
    MobiDeDrm v1.1.
    Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide
    Found 0 keys to try after 0.1 seconds
    Crypto Type is: 2
    DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
    DeDRM v10.0.9: Looking for new default Kindle Key after 0.1 seconds
    searching for kinfoFiles in [user_path]\AppData\Local
    Found K4PC 1.25+ kinf2018 file: [user_path]\AppData\Local\Amazon\Kindle\storage\.kinf2018
    Decrypted key file using IDString '[IDString]' and UserName '[user]'
    DeDRM v10.0.9: Found 1 new key
    MobiDeDrm v1.1.
    Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
    Decrypting Kindle Format 8 ebook: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide
    Got DSN key from database key_0
    Found 4 keys to try after 0.4 seconds
    Crypto Type is: 2
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 0 PIDs tried.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 4 PIDs tried.
    DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
    Running file type plugin DeDRM failed with traceback:
    Traceback (most recent call last):
      File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
      File "[user_path]\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
    mobidedrm.DrmException: No key found in 0 PIDs tried.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
      File "calibre_plugins.dedrm.__init__", line 1030, in run
      File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
    InputFormatPlugin: MOBI Input running
    on [user_path]\AppData\Local\Temp\[temp_folder]\[file_id].azw3
    Found KF8 MOBI of type 'standalone'
    Traceback (most recent call last):
      File "runpy.py", line 198, in _run_module_as_main
      File "runpy.py", line 88, in _run_code
      File "site.py", line 83, in <module>
      File "site.py", line 78, in main
      File "site.py", line 50, in run_entry_point
      File "calibre\utils\ipc\worker.py", line 215, in main
      File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
      File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
      File "calibre\ebooks\conversion\plumber.py", line 1129, in run
      File "calibre\customize\conversion.py", line 245, in __call__
      File "calibre\ebooks\conversion\plugins\mobi_input.py", line 45, in convert
      File "calibre\ebooks\mobi\reader\mobi8.py", line 87, in __call__
      File "calibre\ebooks\mobi\reader\mobi6.py", line 163, in check_for_drm
    calibre.ebooks.DRMError: CompTIA Security+ Get Certified Get Ahead: SY0-601 Study Guide

**Comment by ElleKayEm** [comment]
If the book is from or for an E-ink Kindle (not a Fire), then you need to add that Kindle's serial number to DeDRM's customization.
