### ISSUE TITLE
ADE Decryption not work

### ISSUE THREAD

**Issue by abyssdaisy** [noDRM/DeDRM_tools#598]
### Question / bug report

Hi, the ade key seems have some trouble.
Could you help me, plz QAQ

### Which version of Calibre are you running?

6.14.1

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

```log
EpubMerge: DEBUG: 2024-08-12 16:58:51,410: calibre_plugins.epubmerge.epubmerge_plugin(156): macmenuhack file_path:C:\Users\endlessicy\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[1.39] main UI initialized...
[1.39] Hiding splash screen
Starting QuickView
[1.52] splash screen hidden
[1.52] Started up in 1.52 seconds with 10 books
Using proxies: {'http': '127.0.0.1:2080', 'https': '127.0.0.1:2080', 'ftp': '127.0.0.1:2080'}
DeDRM v10.0.3: Trying to decrypt Catholic nostalgia in Joyce and company .pdf
DeDRM v10.0.3: Catholic nostalgia in Joyce and company .pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: Catholic nostalgia in Joyce and company .pdf is a PDF ebook (EBX) for UUID 6108def2-a8c8-4385-ac00-aca277f6a8f3
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.3: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 753, in PDFIneptDecrypt
  File "C:\Users\endlessicy\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 347, in adeptkeys
  File "C:\Users\endlessicy\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 327, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.3: Finished after 0.1 seconds
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 469, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Added Catholic nostalgia in Joyce and company to db in: 0.1
Added 1 books in 0.5 seconds
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
```

**Comment by ElleKayEm** [comment]
Did you mean to close this issue?

If not, suggest trying DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by abyssdaisy** [comment]
> Did you mean to close this issue?
> 
> If not, suggest trying DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

tyvm, seems there are too many books in my ADE account, then I change the Install folder and rename it,  then log in with another new Adobe account.

work fianlly.

**Comment by ElleKayEm** [comment]
I know you can run into issues when you have too many devices/apps logged into the same Adobe ID at once.  But I've downloaded hundreds of books with the same Adobe ID which I've had for at least 15 years or so.  All the more reason to get the DRM off though!
