### ISSUE TITLE
Won't Convert

### ISSUE THREAD

**Issue by calfmu** [noDRM/DeDRM_tools#599]
### Question / bug report

I am using Kindle for PC and downloaded an ebook whose _EBOK.azw file is 40 KB and the rest of the directory has many 2~3 MB .azw.res files. When importing to Calibre this turns into KFX-ZIP and cannot convert.

### Which version of Calibre are you running?

7.16.0

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

2.4.1

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 94.07407407407408 x 95.25
[0.00] Starting up...
[0.00] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.20] db initialized
[0.20] Constructing main UI...
[1.86] GUI main window shown
[2.31] main UI initialized...
[2.31] Hiding splash screen
[6.16] splash screen hidden
[6.16] Started up in 6.16 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\x86\xbc\x1e\x88\x884\xc2'=\x1c\xa4\xa2O*\xf5#x/\xa1fy\xaf\x16\xec_x\xe8(\xf1\xcfv\xb2", b'C:\\Users\\calfmu\\Documents\\My Kindle Content\\B09DJQDHTC_EBOK\\B09DJQDHTC_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\calfmu\Documents\My Kindle Content\B09DJQDHTC_EBOK\B09DJQDHTC_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 23 file(s) as C:\Users\calfmu\AppData\Local\Temp\calibre_5r_5oalt\6bnoa62a.kfx-zip
DeDRM v10.0.9: Trying to decrypt 6bnoa62a.kfx-zip
Decrypting KFX-ZIP ebook: 6bnoa62a
Got DSN key from database kindle_key_1723450651_1
Found 1 keys to try after 1.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.ae845f6b-6023-422e-8ecc-50e20f5e2605.voucher
Traceback (most recent call last):
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1394, in parse
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 103, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1394, in parse
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 103, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 1.0 seconds
searching for kinfoFiles in C:\Users\calfmu\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\calfmu\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3435385873' and UserName 'calfmu'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: 6bnoa62a
Got DSN key from database key_0
Found 1 keys to try after 1.3 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.ae845f6b-6023-422e-8ecc-50e20f5e2605.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1394, in parse
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 103, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1394, in parse
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 103, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\calfmu\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\calfmu\AppData\Local\Temp\calibre_5r_5oalt\6bnoa62a.kfx-zip
Processing container: B09DJQDHTC_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09DJQDHTC_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\calfmu\AppData\Local\Temp\calibre_5r_5oalt\aqmo3k45_add_books\0\B09DJQDHTC_EBOK.kfx-zip
```

**Comment by ElleKayEm** [comment]
Books from Kindle for PC 2.4.1 cannot be decrypted.  Use at least 2.4.0.

**Comment by romad275** [comment]
Ah, the phrasing of “at least 2.4.0 implies  "2.4.0 and newer” which would include 2.4.1. I suggest something like “no newer than 2.4.0” or “Use 2.4.0 only” whichever is appropriate.

Sincerely,
Dennis B. Swaney

Cogito Ergo Mac

**Comment by jonnyboybbc** [comment]
> Yes, I mean no newer than Kindle for PC 2.4.0. DeDRM 10.0.9 works up to 2.4.0 and stops working with 2.4.1. So if you have 2.4.1, you need to go back to at least 2.4.0 or older. Hopefully that makes it clearer.

Is there any idea on getting a fix for 2.4.1? I’m guessing they changed the encryption mechanism?

**Comment by ElleKayEm** [comment]
Yes, this unremovable (yet) DRM was only seen on certain books like expensive etextbooks before.  Now it is all books if they are downloaded with Kindle for PC 2.4.1 -- even on books which would otherwise be DRM-free.

As far as a timeline on a fix, no idea.  When someone with the skills, time, and desire figures it out and is willing to share.  Sharing has the risk of it not working again sooner.  And in most cases there are still methods of getting decryptable books so there isn't as much motivation as there might be.

**Comment by calfmu** [comment]
Downversioning (I used 2.3.5) got it to work, thank you!
