### ISSUE TITLE
Cant remove DRM

### ISSUE THREAD

**Issue by quibler** [noDRM/DeDRM_tools#604]
`ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.16  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0)
calibre 7.16  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.70777202072539
[0.00] Starting up...
[0.02] Showing splash screen...
[0.19] splash screen shown
[0.19] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[2.09] GUI main window shown
[2.19] main UI initialized...
[2.19] Hiding splash screen
[3.39] splash screen hidden
[3.39] Started up in 3.39 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xc7\x8a\xa4B\x9b\xf6\xac\x93\xb1,\x8c\xa5\xbb\xa5\x86\x84[ 4=\x82\xe1\xcb\xfc\xaf\xe5\xd8\x10\xd3uEG', b'C:\\Users\\ashwi\\Documents\\My Kindle Content\\B08KWLFW2H_EBOK\\B08KWLFW2H_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\ashwi\Documents\My Kindle Content\B08KWLFW2H_EBOK\B08KWLFW2H_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 6 file(s) as C:\Users\ashwi\AppData\Local\Temp\calibre_xjginerm\4_iu6_a0.kfx-zip
DeDRM v10.0.9: Trying to decrypt 4_iu6_a0.kfx-zip
Decrypting KFX-ZIP ebook: 4_iu6_a0
Found 0 keys to try after 0.6 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e359c44d-ec01-4790-a502-102110bbcdb1.voucher
Traceback (most recent call last):
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\ashwi\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\ashwi\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3326109569' and UserName 'ashwi'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: 4_iu6_a0
Got DSN key from database key_0
Found 1 keys to try after 1.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e359c44d-ec01-4790-a502-102110bbcdb1.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 974, in KindleMobiDecrypt
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1039, in run
  File "calibre_plugins.dedrm.__init__", line 990, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\ashwi\AppData\Local\Temp\calibre_xjginerm\4_iu6_a0.kfx-zip
Processing container: B08KWLFW2H_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08KWLFW2H_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\ashwi\AppData\Local\Temp\calibre_xjginerm\1qo6ksci_add_books\0\B08KWLFW2H_EBOK.kfx-zip
Added Odoo 15 Development Essentials: Enhance your Odoo development skills to create powerful business applications, 5th Edition to db in: 0.1
Added 1 books in 2.9 seconds
Worker Launch took: 0.05 seconds
Job: 0 Convert book 1 of 1 (Odoo 15 Development Essentials: Enhance your Odoo development skills to create powerful business applications, 5th Edition) finished
Convert book 1 of 1 (Odoo 15 Development Essentials: Enhance your Odoo development skills to create powerful business applications, 5th Edition)
	DeDRM v10.0.9: Trying to decrypt u1okhxh4.kfx-zip
	Decrypting KFX-ZIP ebook: u1okhxh4
	Found 0 keys to try after 0.6 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e359c44d-ec01-4790-a502-102110bbcdb1.voucher
	Traceback (most recent call last):
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.7 seconds
	searching for kinfoFiles in C:\Users\ashwi\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\ashwi\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3326109569' and UserName 'ashwi'
	DeDRM v10.0.9: Found 1 new key
	Decrypting KFX-ZIP ebook: u1okhxh4
	Got DSN key from database key_0
	Found 1 keys to try after 1.1 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e359c44d-ec01-4790-a502-102110bbcdb1.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 974, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1039, in run
	  File "calibre_plugins.dedrm.__init__", line 990, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  output_profile: 'kindle_pw3'
	  verbose: 2
	  read_metadata_from_opf: 'C:\\Users\\ashwi\\AppData\\Local\\Temp\\calibre_xjginerm\\ogmllmvj.opf'
	  cover: 'C:\\Users\\ashwi\\AppData\\Local\\Temp\\calibre_xjginerm\\6dmmiqml.jpeg'
	  prefer_metadata_cover: True
	Resolved conversion options
	calibre version: 7.16.0
	{'add_alt_text_to_img': False,
	 'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': 'C:\\Users\\ashwi\\AppData\\Local\\Temp\\calibre_xjginerm\\6dmmiqml.jpeg',
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_split_on_page_breaks': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'epub_flatten': False,
	 'epub_inline_toc': False,
	 'epub_max_image_size': 'none',
	 'epub_toc_at_end': False,
	 'epub_version': '2',
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'flow_size': 260,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000002BD1A4D4450>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'no_chapters_in_toc': False,
	 'no_default_epub_cover': False,
	 'no_inline_navbars': False,
	 'no_svg_cover': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x000002BD1A4EAC10>,
	 'page_breaks_before': '/',
	 'prefer_metadata_cover': True,
	 'preserve_cover_aspect_ratio': False,
	 'pretty_print': True,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\ashwi\\AppData\\Local\\Temp\\calibre_xjginerm\\ogmllmvj.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.9: Trying to decrypt u1okhxh4.kfx-zip
	Decrypting KFX-ZIP ebook: u1okhxh4
	Found 0 keys to try after 0.0 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e359c44d-ec01-4790-a502-102110bbcdb1.voucher
	Traceback (most recent call last):
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\ashwi\AppData\Local
	Found K4PC 1.25+ kinf2018 file: C:\Users\ashwi\AppData\Local\Amazon\Kindle\storage\.kinf2018
	Decrypted key file using IDString '3326109569' and UserName 'ashwi'
	DeDRM v10.0.9: Found 1 new key
	Decrypting KFX-ZIP ebook: u1okhxh4
	Got DSN key from database key_0
	Found 1 keys to try after 0.4 seconds
	Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.e359c44d-ec01-4790-a502-102110bbcdb1.voucher
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1417, in parse
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 126, in _assert
	Exception: Unknown type encountered in envelope, expected VoucherEnvelope
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 974, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 937, in KindleMobiDecrypt
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
	  File "C:\Users\ashwi\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
	Exception: Failed to decrypt KFX DRM voucher with any key
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1039, in run
	  File "calibre_plugins.dedrm.__init__", line 990, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on C:\Users\ashwi\AppData\Local\Temp\calibre_xjginerm\u1okhxh4.kfx-zip
	Software versions: KFX Input 2.15.0, calibre 7.16, Windows-10-10.0.22631-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\ashwi\AppData\Local\Temp\calibre_xjginerm\u1okhxh4.kfx-zip
	Processing container: B08KWLFW2H_EBOK.azw
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 102, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08KWLFW2H_EBOK.azw has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 83, in <module>
	  File "site.py", line 78, in main
	  File "site.py", line 50, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1129, in run
	  File "calibre\customize\conversion.py", line 245, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 122, in convert
	calibre.ebooks.DRMError: This book has DRM!
`

**Comment by ElleKayEm** [comment]
Try downloading with Kindle for PC 2.4.0 or older.  2.4.1 delivers DRM that cannot be removed at this time.

**Comment by josh3io** [comment]
> Try downloading with Kindle for PC 2.4.0 or older. 2.4.1 delivers DRM that cannot be removed at this time.

using kindle for PC 2.4.0, did not work for me.

**Comment by ElleKayEm** [comment]
Let's see a new log.
