### ISSUE TITLE
Cant remove DRM

### ISSUE THREAD

**Issue by fab64443** [noDRM/DeDRM_tools#606]
### Question / bug report

Can't convert Amazon Kindle awz3 to epub.

### Which version of Calibre are you running?

7.16

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Journal de débogage
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0)
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 157.8252427184466 x 157.65517241379308
[0.00] Starting up...
[0.02] Showing splash screen...
[0.20] splash screen shown
[0.20] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.69] GUI main window shown
[1.77] main UI initialized...
[1.77] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Every Life Is on Fire_ How Thermodynamics Explains the Origins of Living Things.azw3
[12.30] splash screen hidden
[12.30] Started up in 12.30 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'"\t:\xac\xc9\xb2\x92\xe1M\xcc\xbc\x86\x9a\xbe\xc3#\xa2\x1a\xab\xdd\xd7G\x95\xddQ\xa1\xaf\xa8\xf8\x86\xe7`', b'C:\\Users\\presentation\\Downloads\\Every Life Is on Fire_ How Thermodynamics Explains the Origins of Living Things.azw3']
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Every Life Is on Fire: How Thermodynamics Explains the Origins of Living Things
Found 2 keys to try after 1.0 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 1.0 seconds
searching for kinfoFiles in C:\Users\presentation\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\presentation\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\presentation\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
```

**Comment by ElleKayEm** [comment]
If that is from or for an E-ink Kindle (not a Fire), make sure you have that Kindle's setial number correctly entered into DeDRM.

**Comment by fab64443** [comment]
I'm sure the serial number is entered into the plugin. Is there a special format ?

**Comment by ElleKayEm** [comment]
Log says it isn't the right one for this copy of the book.  When you download from the website, be sure you chose the correct device (if you have more than one).  It must be an E-ink Kindle; this won't work for a Fire.  Try copy and paste of the Kindle's serial number from the website into DeDRM's customization.  Click ok and apply as you work your way out of the dialog boxes.  Then restart calibre before adding the book.

**Comment by fab64443** [comment]
I redid all the steps from the beginning. It works.
Thanks
