### ISSUE TITLE
Book is encrypted but it isn't

### ISSUE THREAD

**Issue by 10b14224cc** [noDRM/DeDRM_tools#607]
### Question / bug report

When I use DeDRM Tools on my book, here is the log I obtain by running Calibre in debug mode:

```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.13  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0)
calibre 7.13  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 9, 0) && KFX Output (2, 9, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.0 x 95.9160839160839
[0.00] Starting up...
[0.06] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[0.89] GUI main window shown
[0.91] main UI initialized...
[0.91] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Music Theory for Guitarists Boo - Tom Kolb.azw4
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 4 ebook: Music Theory for Guitarists Book/Online Audio
Got DSN key from database kindle_key_1720239591_1
Found 4 keys to try after 0.3 seconds
Crypto Type is: 0
This book is not encrypted.
Decryption succeeded after 0.3 seconds
DeDRM v10.0.9: Finished after 0.3 seconds
[62.49] splash screen hidden
[62.49] Started up in 62.49 seconds with 3 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xb2\xb8\xf9\x0es\xaf;#;\x19P\xd9@F\x98\x88J\xa1\x94\xad\xfb\xc3\xcd\x9a&Z\xbf\xf6{\xfd\xf8\x94', b'C:\\Users\\admin\\Documents\\My Kindle Content\\Music Theory for Guitarists Boo - Tom Kolb.azw4']
Added Music Theory for Guitarists Book/Online Audio to db in: 0.1
Added 1 books in 0.6 seconds
```

It says ***"This book is not encrypted"***.

However, when I open the imported book with calibre ebookviewer, the ebook has been flattened to text only.
The layout of the elements on the page is completely gone.

Then when I use [KindleUnpack](https://github.com/kevinhendricks/KindleUnpack) or [mobi](https://github.com/iscc/mobi) on the raw AZW4, it turns out the book is indeed encrypted:

```
Conversion Log 

Input Path = "/home/USERNAME/Documents/B0B966DHN5_EBOK.azw4"
Output Path = "/home/USERNAME/Documents"
Epub Output Type Set To: Auto-detect


Please Wait ...

Palm DB type: BOOKMOBI, 1423 sections.
Warning: Bad key, size, value combination detected in EXTH  406 16 0000000000000000
Unpacking a Mobipocket 4 book...
Processing Mobipocket 4 section of book...
Mobi Version: 4
Codec: windows-1252
Title: tmp-1660091792372bd3112ad-6876-426a-a9fb-68a2228ff8133535918308033946286
EXTH Title: Music Theory for Guitarists Book/Online Audio
No compression
Error: Book is encrypted
Traceback (most recent call last):
  File "/home/USERNAME/progetti_altrui/KindleUnpack/./KindleUnpack.pyw", line 370, in unpackEbook
    kindleunpack.unpackBook(infile, outdir, apnxfile, epubversion, use_hd, dodump=dump, dowriteraw=writeraw, dosplitcombos=splitcombos)
  File "/home/USERNAME/progetti_altrui/KindleUnpack/lib/kindleunpack.py", line 947, in unpackBook
    process_all_mobi_headers(files, apnxfile, sect, mhlst, K8Boundary, False, epubver, use_hd)
  File "/home/USERNAME/progetti_altrui/KindleUnpack/lib/kindleunpack.py", line 785, in process_all_mobi_headers
    raise unpackException('Book is encrypted')
lib.kindleunpack.unpackException: Book is encrypted



Error: Unpacking Failed
```

### Which version of Calibre are you running?

7.13.0

### Which version of the DeDRM plugin are you running?

3373d938749117989dfd0a42cc947bf338d3ffda

### If applicable, which version of the Kindle software are you running?

1.17.0

### Log output

See above

**Comment by ElleKayEm** [comment]
An azw4 is a pdf so I'm not surprised it doesn't work with the calibre ebook viewer.  Try the KindleUnpack calibre plugin to extract the pdf.

**Comment by 10b14224cc** [comment]
Oh it worked.

Here is the plugin: https://github.com/dougmassay/kindleunpack-calibre-plugin

You need to import the file into calibre.

Apparently, while the calibre's ebook viewer displays the file flattened into text, the PDF is still inside the file. So I assume calibre just extracts the text from the PDF and displays that.

After importing you need to select the file and lick KindleUnpack -> Extract PDF from the toolbar.
