### ISSUE TITLE
Debug issue

### ISSUE THREAD

**Issue by Tinca00** [noDRM/DeDRM_tools#611]
### Question / bug report

Hi. I tried to DEDRM a book, but it is not working.
Can you help?

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Dnevnik odpravljanja napak
calibre 7.17  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: sl
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KePub Output (3, 6, 11)
calibre 7.17  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: sl
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KePub Output (3, 6, 11)
QPA platform: windows
devicePixelRatio: 2.5
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.41395348837209
[0.00] Starting up...
[0.02] Showing splash screen...
[1.17] splash screen shown
[1.17] Initializing db...
[1.17] db initialized
[1.17] Constructing main UI...
[1.48] GUI main window shown
[1.50] main UI initialized...
[1.50] Hiding splash screen
[1.50] splash screen hidden
[1.50] Started up in 1.50 seconds with 35 books
DeDRM v10.0.3: Trying to decrypt Kraljestvo.epub
DeDRM v10.0.3: Verifying zip archive integrity
LCP: LCP DRM removal no longer supported due to a DMCA takedown request.
LCP: The takedown request can be found here: 
LCP: https://github.com/github/dmca/blob/master/2022/01/2022-01-04-readium.md 
LCP: More information can be found in the Github repository: 
LCP: https://github.com/noDRM/DeDRM_tools/issues/18 
Looks like that didn't work:
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 345, in ePubDecrypt
  File "C:\Users\tinak\AppData\Roaming\calibre\plugins\DeDRM.zip\lcpdedrm.py", line 70, in decryptLCPbook
lcpdedrm.LCPError: LCP DRM removal no longer supported
Added Kraljestvo to db in: 0.1
Added 1 books in 0.4 seconds

### Which version of Calibre are you running?

7.17

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Dnevnik odpravljanja napak
calibre 7.17  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: sl
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KePub Output (3, 6, 11)
calibre 7.17  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: sl
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && KePub Output (3, 6, 11)
QPA platform: windows
devicePixelRatio: 2.5
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.41395348837209
[0.00] Starting up...
[0.02] Showing splash screen...
[1.17] splash screen shown
[1.17] Initializing db...
[1.17] db initialized
[1.17] Constructing main UI...
[1.48] GUI main window shown
[1.50] main UI initialized...
[1.50] Hiding splash screen
[1.50] splash screen hidden
[1.50] Started up in 1.50 seconds with 35 books
DeDRM v10.0.3: Trying to decrypt Kraljestvo.epub
DeDRM v10.0.3: Verifying zip archive integrity
LCP: LCP DRM removal no longer supported due to a DMCA takedown request.
LCP: The takedown request can be found here: 
LCP: https://github.com/github/dmca/blob/master/2022/01/2022-01-04-readium.md 
LCP: More information can be found in the Github repository: 
LCP: https://github.com/noDRM/DeDRM_tools/issues/18 
Looks like that didn't work:
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 345, in ePubDecrypt
  File "C:\Users\tinak\AppData\Roaming\calibre\plugins\DeDRM.zip\lcpdedrm.py", line 70, in decryptLCPbook
lcpdedrm.LCPError: LCP DRM removal no longer supported
Added Kraljestvo to db in: 0.1
Added 1 books in 0.4 seconds

**Comment by ElleKayEm** [comment]
As the log says, this type of DRM removal is no longer supported.
