### ISSUE TITLE
DeDRM isn't working

### ISSUE THREAD

**Issue by Greeter8930** [noDRM/DeDRM_tools#615]
### Question / bug report

The book is called BIBLIA DE LA EDUCACIÓN FINANCIERA_ CÓMO JUBILARTE J(Spanish Edition), LA - SVETOSLAV TIHOMIROV NIKOLOV

[CR!6ZK32CMBWN7CD85TM8DERW0Q0JYH.azw.md](https://github.com/user
[BIBLIA DE LA EDUCACIÓN FINANCIERA_ CÓMRTE JOVEN Y RICO (Spanish Edition), LA.zip](https://github.com/user-attachments/files/16753475/BIBLIA.DE.LA.EDUCACION.FINANCIERA_.COMRTE.JOVEN.Y.RICO.Spanish.Edition.LA.zip)
-attachments/files/16753469/CR.6ZK32CMBWN7CD85TM8DERW0Q0JYH.azw.md)

### Which version of Calibre are you running?

7.17.0

### Which version of the DeDRM plugin are you running?

v10.0.3

### If applicable, which version of the Kindle software are you running?

2.4.70946

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Registre de depuració
calibre 7.17  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: ca
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
calibre 7.17  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: ca
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 3) && Package KFX (from KFX Input) (2, 15, 0) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 109.21999999999998 x 109.18208955223879
[0.00] Starting up...
[0.00] Showing splash screen...
[1.23] splash screen shown
[1.23] Initializing db...
[1.25] db initialized
[1.25] Constructing main UI...
[3.00] GUI main window shown
[3.25] main UI initialized...
[3.25] Hiding splash screen
[3.26] splash screen hidden
[3.26] Started up in 3.26 seconds with 3 books
[3.97] Starting the smartdevice driver
SMART_DEV (   0.00:  0.002) _attach_to_port try ip address "" on port 9090
SMART_DEV (   0.46:  0.000) _attach_to_port socket error on port 9090
SMART_DEV (   0.49:  0.000) _attach_to_port try ip address "" on port 17575
SMART_DEV (   1.42:  0.904) _startup_on_demand listening on port 17575
SMART_DEV (   1.47:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.49:  0.000) _startup_on_demand broadcast socket listening on port 54982
[5.48] Finished starting smartdevice
SMART_DEV (   2.53:  1.016) run All IP addresses {'{9D6C5D4F-3A9D-4D99-9A62-1A0817C96026}': [{'addr': '192.168.68.101', 'netmask': '255.255.255.0', 'broadcast': '192.168.68.255'}], '{D4FAB85B-F18A-1222-80D1-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'6\x0b\t\xdd\xe3RD8\xa93\x06t\xc9\x07\x87R\xa8I\xc4g"z\x92\xa7\x95\xd6\xe6\x8a\xf3y\x9e\xfb', b'C:\\Users\\Viktor\\Documents\\My Kindle Content\\B0CZBG2322_EBOK\\B0CZBG2322_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 2.15.0: Importing C:\Users\Viktor\Documents\My Kindle Content\B0CZBG2322_EBOK\B0CZBG2322_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as C:\Users\Viktor\AppData\Local\Temp\calibre_ecwdi6ti\vrlrel56.kfx-zip
DeDRM v10.0.3: Trying to decrypt vrlrel56.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: vrlrel56
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.f7422879-7e58-4a8a-8374-606765071336.voucher
Traceback (most recent call last):
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 918, in parse
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
DeDRM v10.0.3: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Viktor\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Viktor\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2087772247' and UserName 'Viktor'
DeDRM v10.0.3: Found 1 new key
Decrypting KFX-ZIP ebook: vrlrel56
Got DSN key from database key_0
Found 1 keys to try after 0.4 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.f7422879-7e58-4a8a-8374-606765071336.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 918, in parse
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 104, in decrypt_voucher
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 918, in parse
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 102, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\Viktor\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 111, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.4 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.15.0: Packaging C:\Users\Viktor\AppData\Local\Temp\calibre_ecwdi6ti\vrlrel56.kfx-zip
Processing container: B0CZBG2322_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0CZBG2322_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\Viktor\AppData\Local\Temp\calibre_ecwdi6ti\rflmx5ox_add_books\0\B0CZBG2322_EBOK.kfx-zip

```

**Comment by ElleKayEm** [comment]
You need an older version of Kindle for PC and a newer version of DeDRM.

DeDRM stopped working with the version you have.  You'll need Kindle for PC 2.3.5 or 2.4.0 (aka 2.3.70840 and 2.4.70904).

You also need DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9
