### ISSUE TITLE
Can't run Obok DeDRM plugin on Calibre.

### ISSUE THREAD

**Issue by PictoNoMii** [noDRM/DeDRM_tools#617]
### Question / bug report

When I try to run the Obok plugin, I get a DatabaseError:database disk image is malformed

### Which version of Calibre are you running?

7.17.0

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
calibre, version 7.17.0
ERROR: Unhandled exception: <b>DatabaseError</b>:database disk image is malformed

calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 108, in launchObok
  File "calibre_plugins.obok_dedrm.action", line 211, in build_book_list
  File "calibre_plugins.obok_dedrm.obok.obok", line 409, in books
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by ElleKayEm** [comment]
Looks like the issue is with your Kobo database.  Are you using Kobo Desktop or a Kobo ereader?

**Comment by PictoNoMii** [comment]
Desktop.

**Comment by ElleKayEm** [comment]
You try reinstalling Kobo Desktop?

**Comment by PictoNoMii** [comment]
I just did, and it worked. Thank you.
