### ISSUE TITLE
Error : the book couldn't be decrypted

### ISSUE THREAD

**Issue by Villard** [noDRM/DeDRM_tools#618]
**Question / bug report**
When I try to use obok,  I get the error : the book couldn't be decrypted". I get this error on all books of my Kobo account.
Thank you for the support

**Which version of Calibre are you running?**
7.17.0

**Which version of the DeDRM plugin are you running?**
v10.0.3

**Log output**
_(I've replaced my Windows account and the book title by generic terms)_
Microsoft Windows [version 10.0.19045.4780]
(c) Microsoft Corporation. Tous droits réservés.

C:\Windows\system32>calibre-debug -g
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && EpubMerge (3, 1, 0) && EpubSplit (3, 9, 0) && Find Duplicates (1, 10, 9) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && KOReader Sync (0, 6, 7) && Obok DeDRM (10, 0, 3) && Quality Check (1, 13, 14)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.58503401360545 x 110.83636363636363
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.17] splash screen shown
[1.17] Initializing db...
[1.19] db initialized
[1.19] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
DEBUG:    0.0 koreader:action:KoreaderAction:genesis:start
[2.81] GUI main window shown
EpubMerge: DEBUG: 2024-08-31 10:36:15,279: calibre_plugins.epubmerge.epubmerge_plugin(156): macmenuhack file_path:C:\Users\MyName\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[2.89] main UI initialized...
[2.89] Hiding splash screen
[2.91] splash screen hidden
[2.91] Started up in 2.91 seconds with 0 books
[2.97] Starting the smartdevice driver
SMART_DEV (   0.00:  0.001) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.29:  0.867) _startup_on_demand listening on port 9090
SMART_DEV (   1.34:  0.000) _attach_to_port try ip address "" on port 54982
SMART_DEV (   1.36:  0.000) _startup_on_demand broadcast socket listening on port 54982
[4.36] Finished starting smartdevice
SMART_DEV (   2.40:  1.013) run All IP addresses {'{C50EF815-DDAB-4568-B20E-985B99D67A38}': [{'addr': '192.168.1.17', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{0DB9F600-CB16-11EE-9C30-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
Running Obok DeDRM v10.0.3
DEBUG:    4.7 didn't find device
Obok v10.0.1
Copyright © 2012-2022 Physisticated et al.
C:\Users\MyName\AppData\Local\Temp\tmpmnnfp8d4
DEBUG:    4.7 got kobodir C:\Users\MyName\AppData\Local\Kobo\Kobo Desktop Edition
Found 8 possible keys to try.
DEBUG:    7.2 BookListTableWidget:get_books - book_num: 0
DEBUG:    7.2 BookListTableWidget:get_books - book: BookTitle
DEBUG:    7.2 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.3 - Decrypting BookTitle
Trying key:  b'a6403671933e7b634013ab317696da6a'
Checking text:b'\x85\x9b)@\xae \xf1C\xfd5':
Perhaps utf-8 without BOM
Bad character at 0, value 133
Decryption failed, trying next key.
Trying key:  b'3d1d7fa3724cbf4529c3139f2c26d226'
Checking text:b'4C"\xe7\xf6[\x10\xde@\xc4':
Perhaps utf-8 without BOM
Bad character at 3, value 231
Decryption failed, trying next key.
Trying key:  b'82113867c3d93291703fd13c669d8056'
Checking text:b'\xfb\xaf\xdf\xb8\xa4\xd8\xdcjw\xdf':
Perhaps utf-8 without BOM
Bad character at 0, value 251
Decryption failed, trying next key.
Trying key:  b'bff032b1ec36138b229cbe1c05fbf055'
Checking text:b'+\x9f"\n\x05\xd8L)\xd4K':
Perhaps utf-8 without BOM
Bad character at 1, value 159
Decryption failed, trying next key.
Trying key:  b'baf11b92d7f9a10ae5aa46c564365a54'
Checking text:b'i=O"\xf7a\xd3\xb1\x9a\x14':
Perhaps utf-8 without BOM
Bad character at 4, value 247
Decryption failed, trying next key.
Trying key:  b'092c09b13832e3f64ce335393fe00617'
Checking text:b'\x04\xcb\xcaG\xe46\xacp\x84q':
Perhaps utf-8 without BOM
Bad character at 0, value 4
Decryption failed, trying next key.
Trying key:  b'613e14604f56dd1a97338ef9a5ee74bb'
Checking text:b'\x87\x8e\xea\x9b\xb1%/S\x0b\xdf':
Perhaps utf-8 without BOM
Bad character at 0, value 135
Decryption failed, trying next key.
Trying key:  b'4bb66b6d7e01e0b73b5eedfe8f38804d'
Checking text:b'T\xdb\xf0g\xbce\xceVx\xf5':
Perhaps utf-8 without BOM
Bad character at 1, value 219
Decryption failed, trying next key.
Obok DeDRM v10.0.3 - Couldn't decrypt BookTitle
DEBUG:    7.3 DecryptAddProgressDialog::do_book_action - book decryption failed: 'BookTitle'
Obok DeDRM v10.0.3 - wrapping up results.

**Comment by ElleKayEm** [comment]
Are they Kobo Plus books?  Or do you have a Japanese account?  I've seen reports of those not working.

Try Obok 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by Villard** [comment]
Thank you
I'd got the same issue with Obok 10.0.9, so I went back to the stable version Obok 10.0.3.
I've no Kobo Plus books, neither a japanese account. 
The problem seems related to my Calibre configuration, because I've installed Calibre and Obok on a other PC and I could decrypt the books without any problem.

**Comment by ElleKayEm** [comment]
The problem might be in that installation of Kobo Desktop then.  Have you tried reinstalling it?  I would stick with Obok 10.0.9 since there are a few bug fixes.

**Comment by Villard** [comment]
I've just uninstalled and reinstalled Kobo Desktop, but there is still the same problem

**Comment by ElleKayEm** [comment]
Must be something about that setup, but I have no clue what might resolve it.

**Comment by ElleKayEm** [comment]
Can you post a log of a successful import from your other PC to compare?

**Comment by Villard** [comment]
Here is the log on the other PC.
Thank you for your time and expertise


Microsoft Windows [version 10.0.19045.4780]
(c) Microsoft Corporation. Tous droits réservés.




C:\Users\MyName>calibre-debug -g
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 131.52103559870548 x 131.3793103448276
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[1.30] splash screen shown
[1.30] Initializing db...
[1.31] db initialized
[1.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.81] GUI main window shown
[1.86] main UI initialized...
[1.86] Hiding splash screen
[1.86] splash screen hidden
[1.86] Started up in 1.86 seconds with 4 books
Running Obok DeDRM v10.0.9
DEBUG:    8.6 didn't find device
Obok v10.0.9
Copyright © 2012-2023 Physisticated et al.
C:\Users\MyName\AppData\Local\Temp\tmp0jesm5z6
DEBUG:    8.6 got kobodir C:\Users\MyName\AppData\Local\Kobo\Kobo Desktop Edition
Found 16 possible keys to try.
DEBUG:   13.1 BookListTableWidget:get_books - book_num: 0
DEBUG:   13.1 BookListTableWidget:get_books - book: BookTitle
DEBUG:   13.1 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.9 - Decrypting BookTitle
Trying key:  b'a60694c8244b27867a32d4892225dd89'
Success!
DEBUG:   13.3 DecryptAddProgressDialog::do_book_action - decrypted book: 'BookTitle'
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1857, in set_metadata
  File "calibre\db\cache.py", line 1780, in set_cover
  File "calibre\db\backend.py", line 1791, in set_cover
  File "calibre\utils\img.py", line 302, in save_cover_data_to
  File "calibre\utils\img.py", line 205, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
Obok DeDRM v10.0.9 - Added BookTitle
Obok DeDRM v10.0.9 - wrapping up results.

**Comment by ElleKayEm** [comment]
Hmm, well, this time it finds 16 keys and it works on the first one it tries.  Other one only found 8 keys and none of them worked.  Are you sure you tried 10.0.9?  A couple tips: always restart calibre after loading a new plugin.  Also, Obok seems to have less issues if you close Kobo Desktop before importing books into calibre.  Beyond that, I'm stumped.

**Comment by Villard** [comment]
Yes I'd tried with 10.0.9. (see below) and I follow the 2 tips ! Yes , it's quite strange. 
I run python on this PC. Would that create a dependancy ? 


Microsoft Windows [version 10.0.19045.4780]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\MyName>calibre-debug -g
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: fr
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: EpubMerge (3, 1, 0) && EpubSplit (3, 9, 0) && Find Duplicates (1, 10, 9) && KOReader Sync (0, 6, 7) && Obok DeDRM (10, 0, 9) && Quality Check (1, 13, 14)
QPA platform: windows
devicePixelRatio: 1.5
logicalDpi: 96.0 x 96.0
physicalDpi: 110.58503401360545 x 110.83636363636363
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[1.20] splash screen shown
[1.20] Initializing db...
[2.31] db initialized
[2.31] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
DEBUG:    0.0 koreader:action:KoreaderAction:genesis:start
[3.86] GUI main window shown
EpubMerge: DEBUG: 2024-08-31 23:15:46,609: calibre_plugins.epubmerge.epubmerge_plugin(156): macmenuhack file_path:C:\Users\MyName\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[4.11] main UI initialized...
[4.11] Hiding splash screen
[4.12] splash screen hidden
[4.12] Started up in 4.12 seconds with 18259 books
[4.61] Starting the smartdevice driver
SMART_DEV (   0.00:  0.002) _attach_to_port try ip address "" on port 9090
SMART_DEV (   1.84:  0.901) _startup_on_demand listening on port 9090
SMART_DEV (   2.07:  0.001) _attach_to_port try ip address "" on port 54982
SMART_DEV (   2.13:  0.000) _startup_on_demand broadcast socket listening on port 54982
[6.78] Finished starting smartdevice
SMART_DEV (   3.19:  1.014) run All IP addresses {'{C50EF815-DDAB-4568-B20E-985B99D67A38}': [{'addr': '192.168.1.17', 'netmask': '255.255.255.0', 'broadcast': '192.168.1.255'}], '{0DB9F600-CB16-11EE-9C30-806E6F6E6963}': [{'addr': '127.0.0.1', 'netmask': '255.0.0.0', 'broadcast': '127.255.255.255'}]}
Running Obok DeDRM v10.0.9
DEBUG:    7.5 didn't find device
Obok v10.0.9
Copyright © 2012-2023 Physisticated et al.
C:\Users\MyName\AppData\Local\Temp\tmpbxf35plr
DEBUG:    7.6 got kobodir C:\Users\MyName\AppData\Local\Kobo\Kobo Desktop Edition
Found 8 possible keys to try.
DEBUG:   13.8 BookListTableWidget:get_books - book_num: 0
DEBUG:   13.8 BookListTableWidget:get_books - book: BookTitle
DEBUG:   13.8 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.9 - Decrypting BookTitle
Trying key:  b'a6403671933e7b634013ab317696da6a'
Checking text:b'\x85\x9b)@\xae \xf1C\xfd5':
Perhaps utf-8 without BOM
Bad character at 0, value 133
Decryption failed, trying next key.
Trying key:  b'3d1d7fa3724cbf4529c3139f2c26d226'
Checking text:b'4C"\xe7\xf6[\x10\xde@\xc4':
Perhaps utf-8 without BOM
Bad character at 3, value 231
Decryption failed, trying next key.
Trying key:  b'82113867c3d93291703fd13c669d8056'
Checking text:b'\xfb\xaf\xdf\xb8\xa4\xd8\xdcjw\xdf':
Perhaps utf-8 without BOM
Bad character at 0, value 251
Decryption failed, trying next key.
Trying key:  b'bff032b1ec36138b229cbe1c05fbf055'
Checking text:b'+\x9f"\n\x05\xd8L)\xd4K':
Perhaps utf-8 without BOM
Bad character at 1, value 159
Decryption failed, trying next key.
Trying key:  b'baf11b92d7f9a10ae5aa46c564365a54'
Checking text:b'i=O"\xf7a\xd3\xb1\x9a\x14':
Perhaps utf-8 without BOM
Bad character at 4, value 247
Decryption failed, trying next key.
Trying key:  b'092c09b13832e3f64ce335393fe00617'
Checking text:b'\x04\xcb\xcaG\xe46\xacp\x84q':
Perhaps utf-8 without BOM
Bad character at 0, value 4
Decryption failed, trying next key.
Trying key:  b'613e14604f56dd1a97338ef9a5ee74bb'
Checking text:b'\x87\x8e\xea\x9b\xb1%/S\x0b\xdf':
Perhaps utf-8 without BOM
Bad character at 0, value 135
Decryption failed, trying next key.
Trying key:  b'4bb66b6d7e01e0b73b5eedfe8f38804d'
Checking text:b'T\xdb\xf0g\xbce\xceVx\xf5':
Perhaps utf-8 without BOM
Bad character at 1, value 219
Decryption failed, trying next key.
Obok DeDRM v10.0.9 - Couldn't decrypt BookTitle
DEBUG:   14.0 DecryptAddProgressDialog::do_book_action - book decryption failed: 'BookTitle'
Obok DeDRM v10.0.9 - wrapping up results.

**Comment by ElleKayEm** [comment]
Shouldn't matter about Python because the plugins are running on calibre's embedded Python.

**Comment by Villard** [comment]
OK Thank you anyway
