### ISSUE TITLE
Dedrm not work for Kobo 

### ISSUE THREAD

**Issue by kevinkwok6208** [noDRM/DeDRM_tools#623]
### Question / bug report

The Jump Comics from Japan Kobo after 2023 cannot remove drm normally. Import book by Obok plugin, sure that red lock present. Although a message show that the book is successfully dedrmed, it returns only blank content. Other books from Japan Kobo is fine except jump comics

### Which version of Calibre are you running?

7.17

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

Not applicable

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
calibre 偵錯記錄
calibre 7.17  embedded-python: True
macOS-14.6.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.6.0', 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.6.1', ('', '', ''), 'arm64')
Interface language: zh_HK
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && Ebook Translator (2, 3, 3) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && KePub Input (3, 6, 6) && KePub Output (3, 6, 11) && Obok DeDRM (10, 0, 9)
calibre 7.17  embedded-python: True
macOS-14.6.1-arm64-arm-64bit Darwin ('64bit', '')
('Darwin', '23.6.0', 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103')
Python 3.11.5
OSX: ('14.6.1', ('', '', ''), 'arm64')
Interface language: zh_HK
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 15, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 15, 0) && Ebook Translator (2, 3, 3) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && KePub Input (3, 6, 6) && KePub Output (3, 6, 11) && Obok DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 127.50000191485789 x 127.50000191485789
[0.00] Starting up...
[0.01] Showing splash screen...
[1.22] splash screen shown
[1.22] Initializing db...
[1.23] db initialized
[1.23] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.83] GUI main window shown
[1.85] main UI initialized...
[1.85] Hiding splash screen
[1.91] splash screen hidden
[1.91] Started up in 1.91 seconds with 0 books
2024-09-06 21:25:19.465 calibre-debug[5365:38104] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
2024-09-06 21:25:19.465 calibre-debug[5365:38104] TSMSendMessageToUIServer: CFMessagePortSendRequest FAILED(-1) to send to port com.apple.tsm.uiserver
```

**Comment by ElleKayEm** [comment]
May just be an issue with formatting that the calibre viewer doesn't handle.  If you unzip the epub, are the page images actually still encrypted?

**Comment by kevinkwok6208** [comment]
> May just be an issue with formatting that the calibre viewer doesn't handle. If you unzip the epub, are the page images actually still encrypted?

Yes, I can open the epub, but each page is blank. I am not sure whether each is encrypted or not. But when I try to convert it to another format by calibre, it returns the following error:

DeDRM v10.0.9: Trying to decrypt x5f4o7sn.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 4.2 seconds
Conversion options changed from defaults:
  verbose: 2
  read_metadata_from_opf: '/var/folders/5d/vc3jv4256bz23ndtvcbx658h0000gn/C/calibre_7.17.0_tmp_kc3ox92n/40mfxkvo.opf'
  cover: '/var/folders/5d/vc3jv4256bz23ndtvcbx658h0000gn/C/calibre_7.17.0_tmp_kc3ox92n/4q1lhce7.jpeg'
  output_profile: 'ipad3'
Resolved conversion options
calibre version: 7.17.0
{'add_alt_text_to_img': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/var/folders/5d/vc3jv4256bz23ndtvcbx658h0000gn/C/calibre_7.17.0_tmp_kc3ox92n/4q1lhce7.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_max_image_size': 'none',
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x1101121d0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x11015aa10>,
 'page_breaks_before': '/',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/var/folders/5d/vc3jv4256bz23ndtvcbx658h0000gn/C/calibre_7.17.0_tmp_kc3ox92n/40mfxkvo.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.9: Trying to decrypt v00zk039.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Post-processing took 0.0 seconds
DeDRM v10.0.9: Finished after 4.1 seconds
InputFormatPlugin: EPUB Input running
on /var/folders/5d/vc3jv4256bz23ndtvcbx658h0000gn/C/calibre_7.17.0_tmp_kc3ox92n/0i0803st.epub
Parsing all content...
Parsing OPS/navigation_standard.xhtml ...
The item OPS/images/08X10000000048678600_cover.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_dorigin_01_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_001_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_002_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_003_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_004_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_005_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_006_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_007_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_008_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_009_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_010_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_011_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_012_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_013_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_014_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_015_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_016_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_017_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_018_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_019_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_020_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_021_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_022_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_023_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_024_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_025_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_026_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_027_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_028_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_029_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_030_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_031_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_032_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_033_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_034_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_035_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_036_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_037_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_038_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_039_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_040_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_041_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_042_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_043_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_044_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_045_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_046_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_047_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_048_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_049_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_050_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_051_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_052_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_053_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_054_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_055_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_056_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_057_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_058_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_059_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_060_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_061_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_062_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_063_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_064_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_065_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_066_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_067_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_068_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_069_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_070_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_071_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_072_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_073_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_074_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_075_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_076_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_077_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_078_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_079_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_080_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_081_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_082_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_083_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_084_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_085_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_086_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_087_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_088_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_089_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_090_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_091_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_092_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_093_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_094_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_095_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_096_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_097_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_098_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_099_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_100_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_101_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_102_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_103_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_104_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_105_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_106_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_107_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_108_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_109_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_110_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_111_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_112_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_113_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_114_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_115_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_116_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_117_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_118_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_119_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_120_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_121_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_122_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_123_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_124_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_125_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_126_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_127_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_128_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_129_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_130_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_131_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_132_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_133_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_134_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_135_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_136_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_137_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_138_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_139_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_140_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_141_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_142_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_143_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_144_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_145_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_146_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_147_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_148_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_149_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_150_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_151_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_152_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_153_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_154_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_155_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_156_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_157_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_158_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_159_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_160_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_161_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_162_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_163_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_164_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_165_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_166_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_167_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_168_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_169_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_170_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_171_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_172_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_173_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_174_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_175_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_176_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_177_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_178_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_179_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_180_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_181_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_182_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_183_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_184_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_185_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_186_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_187_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_188_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_189_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_190_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_191_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_192_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_193_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_194_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_195_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_196_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_197_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_198_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_199_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_1_200_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08X10000000048678600_copyright.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_3_ill_01_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_3_ill_02_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_3_ill_03_001.jpg is not a XML document. Removing it from spine.
The item OPS/images/08_X10000_000048_3_ill_04_001.jpg is not a XML document. Removing it from spine.
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 42, in <module>
  File "site.py", line 38, in main
  File "calibre/utils/ipc/worker.py", line 215, in main
  File "calibre/gui2/convert/gui_conversion.py", line 38, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1139, in run
  File "calibre/ebooks/conversion/plumber.py", line 1349, in create_oebbook
  File "calibre/ebooks/oeb/reader.py", line 97, in __call__
  File "calibre/ebooks/oeb/reader.py", line 724, in _all_from_opf
  File "calibre/ebooks/oeb/reader.py", line 369, in _spine_from_opf
calibre.ebooks.oeb.base.OEBError: Spine is empty

**Comment by ElleKayEm** [comment]
It doesn't look like there is an issue with DRM.  I'd guess that these are non-standard epubs that calibre doesn't know how to handle.  Again I suggest unzipping the epub (the one in calibre, not the original) and taking a look.

**Comment by kevinkwok6208** [comment]
> It doesn't look like there is an issue with DRM. I'd guess that these are non-standard epubs that calibre doesn't know how to handle. Again I suggest unzipping the epub (the one in calibre, not the original) and taking a look.

Sorry, I not sure what this sentence means "I suggest unzipping the epub (the one in calibre, not the original) and taking a look.". Coz after added books by Obok Plugins, the books will auto start decryption, and the folder in calibre only get three files, they are "cover.jpg", "metadata.opf" and "bookname.epub", no zip file created by calibre. Sorry, I am not quite familiar with that.

**Comment by ElleKayEm** [comment]
An epub is a zip file.

You're not missing anything for removing DRM from this book.  It appears to have the DRM removed.

KFX Input is for Amazon books.

Not surprising that Epubor gives the same result as it likely based on the code here.

**Comment by kevinkwok6208** [comment]
> An epub is a zip file.
> 
> You're not missing anything for removing DRM from this book. It appears to have the DRM removed.
> 
> KFX Input is for Amazon books.
> 
> Not surprising that Epubor gives the same result as it likely based on the code here.

Big thanks, after unzip the epub. I got the image, thanks for your patience

**Comment by Reindears** [comment]
> An epub is a zip file.
> 
> You're not missing anything for removing DRM from this book. It appears to have the DRM removed.
> 
> KFX Input is for Amazon books.
> 
> Not surprising that Epubor gives the same result as it likely based on the code here.

hi @ElleKayEm can you share your email address i have a doubt

**Comment by ElleKayEm** [comment]
Go ahead and ask here.

**Comment by Reindears** [comment]
https://www.mediafire.com/file/0xowhugqvkuzvfw/B0CDLT6XY5_EBOK.azw/file

can you please convert it into pdf file
i tried many times and showing drm encrypted

**Comment by ElleKayEm** [comment]
No, I cannot.  It requires being logged in to your account.  See method 2 under this post: https://www.mobileread.com/forums/showthread.php?t=361503
