### ISSUE TITLE
Failed to decrypt ADE book

### ISSUE THREAD

**Issue by DSGriff** [noDRM/DeDRM_tools#627]
### Question / bug report

Can't seem to remove DRM of a book from Google Play downloaded to ADE. Worked on the PDF version, not on ePub.

### Which version of Calibre are you running?

7.17

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.17  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.17  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.36363636363636 x 92.36363636363636
[0.00] Starting up...
[0.00] Showing splash screen...
[1.16] splash screen shown
[1.16] Initializing db...
[1.38] db initialized
[1.38] Constructing main UI...
[1.66] GUI main window shown
[1.72] main UI initialized...
[1.72] Hiding splash screen
[1.72] splash screen hidden
[1.72] Started up in 1.72 seconds with 65 books
DeDRM v10.0.3: Trying to decrypt A Beginners Guide to Consonants.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: A Beginners Guide to Consonants.epub is a secure Adobe Adept ePub for UUID a168c2e5-cda2-4893-ba16-4e466b30f2fe
DeDRM v10.0.3: Trying UUID-matched encryption key default_ade_key_uuid_a168c2e5-cda2-4893-ba16-4e466b30f2fe
2oel79on.epub is a secure Adobe Adept ePub.
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xa6\xcc\xa2\x0f+\xa9$<\xed/E\x1bE\xc8Eye\xdb\xdb\xd7\xd3\xc9\xbf\xc2/\xc8\xa7\xf0\x96\xf3\x83\xfd', b'E:\\Users\\[REDACTED]\\Documents\\My Digital Editions\\A Beginners Guide to Consonants.epub']
Could not decrypt 2oel79on.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 342, in decryptBook
  File "C:\Users\[REDACTED]\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 180, in get_xml
AttributeError: 'Decryptor' object has no attribute '_encryption'

DeDRM v10.0.3: Trying Encryption key default_ade_key_uuid_a168c2e5-cda2-4893-ba16-4e466b30f2fe
2oel79on.epub is a secure Adobe Adept ePub.
Could not decrypt 2oel79on.epub because of an exception:
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 342, in decryptBook
  File "C:\Users\[REDACTED]\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptepub.py", line 180, in get_xml
AttributeError: 'Decryptor' object has no attribute '_encryption'

DeDRM v10.0.3: Failed to decrypt with key default_ade_key_uuid_a168c2e5-cda2-4893-ba16-4e466b30f2fe after 1.8 seconds
DeDRM v10.0.3: Looking for new default Adobe Digital Editions Keys after 1.8 seconds
Found 1 keys
DeDRM v10.0.3: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 665, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 1.9 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by DSGriff** [comment]
Worked, thank you.
