### ISSUE TITLE
DeDRM_plugin: ModuleNotFoundError: No module named '__version'

### ISSUE THREAD

**Issue by gideonfisk** [noDRM/DeDRM_tools#63]
Can't install the DeDRM_plugin. I get: ModuleNotFoundError: No module named '__version'

Details:
calibre, version 5.40.0
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named '__version'

calibre 5.40 [64bit]  embedded-python: True is64bit: True
Windows-8.1-6.3.9600 Windows ('64bit', 'WindowsPE')
('Windows', '8.1', '6.3.9600')
Python 3.8.5
Windows: ('8.1', '6.3.9600', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (10, 0, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 326, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 292, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 191, in exec_module
  File "calibre_plugins.dedrm.__init__", line 98, in <module>
ModuleNotFoundError: No module named '__version'

**Comment by ElleKayEm** [comment]
Looks like you're trying to install from the source code (without first running makerelease.py) instead of the latest 10.0.2 release.

**Comment by gideonfisk** [comment]
> Looks like you're trying to install from the source code (without first running makerelease.py) instead of the latest 10.0.2 release.

Ah gotcha. Didn't realize I had to do that. Will look at that in the morning. I don't suppose there's some pre-compiles somewhere?

Thanks for your help.

**Comment by noDRM** [comment]
If you go to the Releases page ( https://github.com/noDRM/DeDRM_tools/releases ) you can download the [DeDRM_tools_10.0.2.zip](https://github.com/noDRM/DeDRM_tools/releases/download/v10.0.2/DeDRM_tools_10.0.2.zip) and that should work.

**Comment by ElleKayEm** [comment]
If you are looking for something that's closer to the current code, there's this:  https://github.com/noDRM/DeDRM_tools/pull/48#issuecomment-1072589825

**Comment by gideonfisk** [comment]
Ok got it all compiled from current just fine and works well so far.
Thanks everyone for you patience with my noob-ish mistakes :-D
