### ISSUE TITLE
Can't insall DeDRM-Tools plug-in

### ISSUE THREAD

**Issue by annasmithforos** [noDRM/DeDRM_tools#638]
### Question / bug report

I have downloaded the Calibre plug-in but it gives me an error when adding it. I can't install it. I downloaded it from https://github.com/noDRM/DeDRM_tools/releases, it shouldn't give me any problems...

### Which version of Calibre are you running?

7.18

### Which version of the DeDRM plugin are you running?

DeDRM_tools_10.0.9

### If applicable, which version of the Kindle software are you running?

Kindle 5.16.6 (2022) 

### Log output

calibre, version 7.18.0
ERROR: Excepción no considerada: <b>InvalidPlugin</b>:The plugin in '/home/****/Descargas/herramientas libros/DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

calibre 7.18  embedded-python: True
Linux-6.8.0-45-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '6.8.0-45-generic', '#45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2')
Python 3.11.5
Interface language: es
EXE path: /opt/calibre/bin/calibre
Successfully initialized third party plugins: DeACSM (0, 0, 16) && Gather KFX-ZIP (from KFX Input) (2, 15, 0) && Package KFX (from KFX Input) (2, 15, 0) && Find Duplicates (1, 10, 9) && KFX metadata reader (from KFX Input) (2, 15, 0) && From KFX (2, 15, 0) && KFX Input (2, 15, 0) && Set KFX metadata (from KFX Output) (2, 10, 0) && KFX Output (2, 10, 0) && Kindle hi-res covers (0, 5, 1)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 322, in add_plugin
  File "calibre/customize/ui.py", line 525, in add_plugin
  File "calibre/customize/ui.py", line 76, in load_plugin
  File "calibre/customize/zipplugin.py", line 297, in load
  File "calibre/customize/zipplugin.py", line 392, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/home/****/Descargas/herramientas libros/DeDRM_tools_10.0.9.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by ElleKayEm** [comment]
That's the whole archive, not the plugin.  Unzip it and load DeDRM_plugin.zip into calibre.

**Comment by annasmithforos** [comment]
Ups! thank you very much!
It was my fault, sorry.
Best regards.

**Comment by MamaBear5839** [comment]
I unzipped the file but can't don't have DeDRM_plugin.zip.  Is it because I'm on a Mac

**Comment by ElleKayEm** [comment]
Inside the main zip file there are the 2 plugin zip files and 3 txt readme files.  Make sure your browser isn't unzipping everything on download.
