### ISSUE TITLE
[Arch Linux] The default encryption key could not be found

### ISSUE THREAD

**Issue by TheLongestRose** [noDRM/DeDRM_tools#642]
### Question / bug report

I'm trying to extract the encryption keys for a Wine install of Kindle, and DeDRM keeps throwing the "The default encryption key could not be found" error. I tried versions 1.40, 1.39, and 1.17 of the Kindle app, but I've had no luck with any of them.

### Which version of Calibre are you running?

7.17

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1.40, 1.39, 1.17

**Comment by ElleKayEm** [comment]
You have Python and Pycryptodome installed under Wine?

Update to DeDRM 10.0.9.

**Comment by TheLongestRose** [comment]
Just did both of those, no change.

**Comment by ElleKayEm** [comment]
Maybe the last comment on this issue will help: https://github.com/noDRM/DeDRM_tools/issues/561

**Comment by TheLongestRose** [comment]
That gets it further! It can find Python now, but the script is erroring out.
`DeDRM v10.0.9: wine python3.exe is not python3
DeDRM v10.0.9: Python3 exec found as wine python.exe
DeDRM v10.0.9: Running kindlekey.py under Wine
Traceback (most recent call last):
  File "Z:\home\rose\.config\calibre\plugins\DeDRM\libraryfiles\kindlekey.py", line 67, in <module>
    from .utilities import SafeUnbuffered
ImportError: attempted relative import with no known parent package
DeDRM v10.0.9: Wine subprocess call error: 1
DeDRM v10.0.9: Found and decrypted 0 key files
Traceback (most recent call last):
  File "/home/rose/.config/calibre/plugins/DeDRM.zip/config.py", line 1262, in __init__
    self.default_key = defaultkeys[0]
                       ~~~~~~~~~~~^^^
IndexError: list index out of range
`

**Comment by ElleKayEm** [comment]
That's beyond me.  Hopefully someone with experience setting this up on Linux will chime in.

**Comment by TheLongestRose** [comment]
I did get it working, essentially through brute force - I copied over the contents of utilities.py and argv_utils.py into kindlekey.py, and I ran the script in Wine. This did successfully get a keyfile out!

**Comment by ElleKayEm** [comment]
And you got your books decrypted?

**Comment by TheLongestRose** [comment]
Yes, successfully got the books decrypted and into a sensible format!
