### ISSUE TITLE
Import backup.ab to get android keys failed

### ISSUE THREAD

**Issue by Bobbe94** [noDRM/DeDRM_tools#651]
### Question / bug report

I've created the backup with ADB using kindle application 4.16.0.75 on android phone, before i've also downloaded some books with DRM on the phone.
When I try to get the keys with the backup I get this error:

calibre 7.19 Portable embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: it
EXE path: D:\Desktop\CALIBRE\Calibre Portable\Calibre\calibre.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 16, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 16, 0) && Epub Metaguider output format (intellireading.com) (1, 0, 2) && KFX metadata reader (from KFX Input) (2, 16, 0) && From KFX (2, 16, 0) && KFX Input (2, 16, 0) && KePub Input (3, 6, 6) && KePub Metadata Reader (3, 4, 3) && KePub Metadata Writer (3, 4, 3) && KePub Output (3, 6, 11) && Kobo Utilities (2, 17, 1)
Traceback (most recent call last):
  File "D:\Desktop\CALIBRE\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\config.py", line 1424, in get_android_file
  File "D:\Desktop\CALIBRE\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\androidkindlekey.py", line 251, in get_serials
PermissionError: [WinError 32] Impossibile accedere al file. Il file è utilizzato da un altro processo: 'C:\\Users\\RBAIST~1\\AppData\\Local\\Temp\\tmpnj2875ji'

### Which version of Calibre are you running?

7.19

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

Android 4.16.0.75

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Use the alpha release of DeDRM: https://github.com/noDRM/DeDRM_tools_autorelease/releases/tag/autorelease_3373d938749117989dfd0a42cc947bf338d3ffda

**Comment by Bobbe94** [comment]
> Use the alpha release of DeDRM: https://github.com/noDRM/DeDRM_tools_autorelease/releases/tag/autorelease_3373d938749117989dfd0a42cc947bf338d3ffda

Now the backup is loaded but it doesn't give the key
![Cattura](https://github.com/user-attachments/assets/ceb40019-2ff3-4a27-971d-d2ddc50ee791)

**Comment by Bobbe94** [comment]
Now it works. Thank you!

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
