### ISSUE TITLE
OBOK Doesn't convert Kobo eBook

### ISSUE THREAD

**Issue by another4til7** [noDRM/DeDRM_tools#655]
### Question / bug report

When I tried importing my first book with oBok, it thinks it succeeds but when I open the file I have giberish:

$���r�7�O�ϝ��3\�LP}���i�b���L�D�w����u[��5�U�t�ؐ=P��S�xe��W��2��~�� X55��I��l_,��i���Y�$� 

FWIW, the book is a brand-new release (yesterday?)

### Which version of Calibre are you running?

7.19

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

Microsoft Windows [Version 10.0.19045.5011]
(c) Microsoft Corporation. All rights reserved.

C:\Users\twood>calibre-debug -g
calibre 7.19  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.07217630853994 x 96.08765957446808
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.01] Showing splash screen...
[1.23] splash screen shown
[1.23] Initializing db...
[1.33] db initialized
[1.33] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.5 obok::action_err.py - loading translations
[2.56] GUI main window shown
[2.64] main UI initialized...
[2.64] Hiding splash screen
[2.64] splash screen hidden
[2.64] Started up in 2.64 seconds with 3 books
Running Obok DeDRM v10.0.3
DEBUG:    8.7 didn't find device
Obok v10.0.1
Copyright © 2012-2022 Physisticated et al.
C:\Users\twood\AppData\Local\Temp\tmpzvpyypje
DEBUG:    8.7 got kobodir C:\Users\twood\AppData\Local\Kobo\Kobo Desktop Edition
Found 8 possible keys to try.
DEBUG:   10.6 BookListTableWidget:get_books - book_num: 0
DEBUG:   10.6 BookListTableWidget:get_books - book: Playing Possum
DEBUG:   10.6 InterfacePluginAction::launchObok - number of books to decrypt: 1
Obok DeDRM v10.0.3 - Decrypting Playing Possum
Trying key:  b'5eebf61423d4de2a709c7e5f6e2662a6'
Success!
DEBUG:   11.1 DecryptAddProgressDialog::do_book_action - decrypted book: 'Playing Possum'
Traceback (most recent call last):
  File "calibre\db\cache.py", line 1859, in set_metadata
  File "calibre\db\cache.py", line 1782, in set_cover
  File "calibre\db\backend.py", line 1791, in set_cover
  File "calibre\utils\img.py", line 302, in save_cover_data_to
  File "calibre\utils\img.py", line 205, in image_to_data
ValueError: Failed to export image as JPEG with error: Image is empty
Obok DeDRM v10.0.3 - Added Playing Possum: How Animals Understand Death
Obok DeDRM v10.0.3 - wrapping up results.
Worker Launch took: 0.03 seconds

**Comment by ElleKayEm** [comment]
Give Obok 10.0.9 a try.  Also close Kobo Desktop before using Obok.  Obok should show a red closed lock on books with DRM.

**Comment by another4til7** [comment]
@ElleKayEm wow. That was easy. Thanks for being the key part of the howto article no one seems to have written.

**Comment by ElleKayEm** [comment]
Glad to hear that did the trick!
