### ISSUE TITLE
DRM Removal Not Working

### ISSUE THREAD

**Issue by Marquinhus0** [noDRM/DeDRM_tools#665]
### Question / bug report

DRM isn't working when i tried to remove the DRM from the book my friend bought on amazon

### Which version of Calibre are you running?

7.16

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

didnt use the kindle software

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Log de Debug
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: pt_BR
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 16, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 16, 0) && KFX metadata reader (from KFX Input) (2, 16, 0) && From KFX (2, 16, 0) && KFX Input (2, 16, 0) && Obok DeDRM (10, 0, 9)
calibre 7.16  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: pt_BR
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 16, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 16, 0) && KFX metadata reader (from KFX Input) (2, 16, 0) && From KFX (2, 16, 0) && KFX Input (2, 16, 0) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.53889943074003 x 92.67567567567568
[0.00] Starting up...
[0.02] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.25] db initialized
[0.25] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.28] GUI main window shown
[1.41] main UI initialized...
[1.41] Hiding splash screen
Gather KFX-ZIP (from KFX Input) 2.16.0: Importing C:/Users/victo/Downloads/Earthed.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.9: Trying to decrypt Earthed.azw
[17.25] splash screen hidden
[17.25] Started up in 17.25 seconds with 21 books
MobiDeDrm v1.1.
Copyright Â© 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Mobipocket 6 ebook: Earthed: A Sci-Fi Sentient Object Romance
Found 2 keys to try after 0.7 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.7 seconds
searching for kinfoFiles in C:\Users\victo\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\victo\AppData\Local\Amazon\Kindle\storage\.kinf2011
Couldn't decrypt file.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\victo\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\victo\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

**Comment by ElleKayEm** [comment]
How was the book downloaded?

**Comment by Marquinhus0** [comment]
> How was the book downloaded?

"my friend downloaded through kindle on her phone and then sent it to me through WhatsApp"

**Comment by ElleKayEm** [comment]
That won't work.  This post covers the ways you can get a copy that can be decrypted: https://www.mobileread.com/forums/showthread.php?t=361503
