### ISSUE TITLE
Problem removing DRV even with the plugin installed

### ISSUE THREAD

**Issue by tinhomaranholi** [noDRM/DeDRM_tools#668]
### Question / bug report

So, I followed the step-by-step tutorial on giuthub in my Calibre, but the problem persisted. Here is the log below. 

Ps: I downloaded the e-book through my Kindle and imported it into Calibre. 

### Which version of Calibre are you running?

7.21.0

### Which version of the DeDRM plugin are you running?

10.0.9

### If applicable, which version of the Kindle software are you running?

Kindle 5.16.21 (4289750037)

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Log de Debug
calibre 7.21  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: pt_BR
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 16, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 16, 0) && KFX metadata reader (from KFX Input) (2, 16, 0) && From KFX (2, 16, 0) && KFX Input (2, 16, 0)
calibre 7.21  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: pt_BR
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 16, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 16, 0) && KFX metadata reader (from KFX Input) (2, 16, 0) && From KFX (2, 16, 0) && KFX Input (2, 16, 0)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 69.86819484240687 x 69.80152671755725
[0.00] Starting up...
[0.02] Showing splash screen...
[1.20] splash screen shown
[1.20] Initializing db...
[1.20] db initialized
[1.20] Constructing main UI...
[1.97] GUI main window shown
[2.00] main UI initialized...
[2.00] Hiding splash screen
[2.00] splash screen hidden
[2.00] Started up in 2.00 seconds with 4 books
Gather KFX-ZIP (from KFX Input) 2.16.0: Importing D:\Documentos\Arquivos\50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition).kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\pox41f7e.kfx-zip
DeDRM v10.0.9: Trying to decrypt pox41f7e.kfx-zip
Storage number map:
{(7, 0): [(3, 'C')], (7, 1): [(2, 'D')], (7, 2): [(1, 'E')]}
Storage number for USBSTOR\DISK&VEN_KINDLE&PROD_INTERNAL_STORAGE&REV_0409\G001PX11225305XL&0: StorageDeviceNumber(type=7, number=2, partition_number=0)
Drive letters for USBDevice(vendor_id=0x1949 product_id=0x324 bcd=0x409 devid=usb\vid_1949&pid_0324&rev_0409 devinst=21)
{'drive_letters': ['E'],
 'pnp_id_map': {'E': '\\\\?\\usbstor#disk&ven_kindle&prod_internal_storage&rev_0409#g001px11225305xl&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'},
 'readonly_drives': set(),
 'sort_map': {'E': (2, 1)}}
Syncing cover thumbnails to workaround amazon cover bug
Restored 0 cover thumbnails that were destroyed by Amazon
Job: 0 Obter informações do dispositivo started
DeviceJob: 0 Obter informações do dispositivo done, calling callback
DeviceJob: 0 Obter informações do dispositivo callback returned
Job: 1 Definir informações da biblioteca started
DeviceJob: 1 Definir informações da biblioteca done, calling callback
DeviceJob: 1 Definir informações da biblioteca callback returned
Job: 2 Obter listagem de livros do dispositivo started
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= None
DEBUG:    0.0 USBMS: dirs are: E:\ documents
DEBUG:    0.0 USBMS: scan from root False E:\documents
DEBUG:    0.0 USBMS: count found in cache: 37, count of files in metadata: 37, need_sync: False
DEBUG:    0.0 USBMS: Finished fetching list of books from device. oncard= None
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= carda
DEBUG:    0.0 USBMS: Fetching list of books from device. Device= KINDLE2 oncard= cardb
DeviceJob: 2 Obter listagem de livros do dispositivo done, calling callback
DEBUG:    0.0 DeviceJob: metadata_downloaded: Starting set_books_in_library
DEBUG:    0.0 DeviceJob: set_books_in_library: books to process= 37
DEBUG:    0.0 DeviceJob: set_books_in_library finished: time= 0.0025453567504882812
DEBUG:    0.0 DeviceJob: metadata_downloaded: updating views
DEBUG:    0.0 DeviceJob: metadata_downloaded: syncing
DEBUG:    0.0 DeviceJob: metadata_downloaded: refreshing ondevice
DEBUG:    0.0 DeviceJob: metadata_downloaded: sending metadata_available signal
DeviceJob: 2 Obter listagem de livros do dispositivo callback returned
Job: 0 Obter informações do dispositivo finished
Nenhum detalhe disponível.
Job: 2 Obter listagem de livros do dispositivo finished
Nenhum detalhe disponível.
Job: 1 Definir informações da biblioteca finished
Nenhum detalhe disponível.
Job: 3 Visualizar livro no dispositivo started
DeviceJob: 3 Visualizar livro no dispositivo done, calling callback
DeviceJob: 3 Visualizar livro no dispositivo callback returned
Job: 3 Visualizar livro no dispositivo finished
Nenhum detalhe disponível.
Job: 4 Visualizar livro no dispositivo started
DeviceJob: 4 Visualizar livro no dispositivo done, calling callback
DeviceJob: 4 Visualizar livro no dispositivo callback returned
Job: 4 Visualizar livro no dispositivo finished
Nenhum detalhe disponível.
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\x93\x80`)\xec\\\xd3\xa2\x1e\x81\x89\xf6\x06\xbe\xa6\x8f9F\x07\xe6\xc3?q,\x83\xde\xc3d\x0em\t\xd2', b'D:\\Documentos\\Arquivos']
Job: 5 Baixar livros do dispositivo started
DeviceJob: 5 Baixar livros do dispositivo done, calling callback
DeviceJob: 5 Baixar livros do dispositivo callback returned
Job: 5 Baixar livros do dispositivo finished
Nenhum detalhe disponível.
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe0\x8cjn\xd6\xc5\xf7\x86\x83\x19\xf6\xfaS&;Q\xf1\xeb\xf9\xea\x11\xdc\x9c&\xee>\xe1\xc19\xe4\xc4\x97', b'D:\\Documentos\\Arquivos']
Job: 6 Baixar livros do dispositivo started
DeviceJob: 6 Baixar livros do dispositivo done, calling callback
DeviceJob: 6 Baixar livros do dispositivo callback returned
Job: 6 Baixar livros do dispositivo finished
Nenhum detalhe disponível.
Decrypting KFX-ZIP ebook: pox41f7e
Found 0 keys to try after 0.5 seconds
DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.9: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\tinho\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.16.0: Packaging C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\pox41f7e.kfx-zip
Processing container: 50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition).kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container 50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition).kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\zl6iy5vs_add_books\0\50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition).kfx-zip
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 483, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in get_metadata
Exception: Failed to locate a KFX container with metadata
Gather KFX-ZIP (from KFX Input) 2.16.0: Importing D:\Documentos\Arquivos\50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition)_B0BW4F49RR.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\8rn91676.kfx-zip
DeDRM v10.0.9: Trying to decrypt 8rn91676.kfx-zip
Added 50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) to db in: 0.1
Added 1 books in 1.4 seconds
Decrypting KFX-ZIP ebook: 8rn91676
Found 0 keys to try after 0.6 seconds
DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.9: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\tinho\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.6 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.16.0: Packaging C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\8rn91676.kfx-zip
Processing container: 50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition)_B0BW4F49RR.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container 50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition)_B0BW4F49RR.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\7ungkxfz_add_books\0\50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition)_B0BW4F49RR.kfx-zip
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 483, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in get_metadata
Exception: Failed to locate a KFX container with metadata
Gather KFX-ZIP (from KFX Input) 2.16.0: Importing D:\Documentos\Arquivos\50 Obras-Primas Que Voce Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) B0BW4F49RR - Desconhecido.kfx
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\ob8d4g83.kfx-zip
DeDRM v10.0.9: Trying to decrypt ob8d4g83.kfx-zip
Added 50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) B0BW4F49RR to db in: 0.1
Added 1 books in 1.5 seconds
Decrypting KFX-ZIP ebook: ob8d4g83
Found 0 keys to try after 0.5 seconds
DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\tinho\AppData\Local
No K4PC kindle.info/kinf/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.16.0: Packaging C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\ob8d4g83.kfx-zip
Processing container: 50 Obras-Primas Que Voce Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) B0BW4F49RR - Desconhecido.kfx
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container 50 Obras-Primas Que Voce Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) B0BW4F49RR - Desconhecido.kfx has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\2yfpkv7l_add_books\0\50 Obras-Primas Que Voce Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) B0BW4F49RR - Desconhecido.kfx-zip
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 483, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 150, in get_metadata
Exception: Failed to locate a KFX container with metadata
Added 50 Obras-Primas Que Voce Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) B0BW4F49RR to db in: 0.1
Added 1 books in 1.5 seconds
Worker Launch took: 0.00 seconds
Worker Launch took: 0.02 seconds
Worker Launch took: 0.00 seconds
Job: 9 Converter livro 1 de 1 (50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) B0BW4F49RR) finished
Converter livro 1 de 1 (50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol 1 (Portuguese Edition) B0BW4F49RR)
	DeDRM v10.0.9: Trying to decrypt t2jy7_dm.kfx-zip
	Decrypting KFX-ZIP ebook: t2jy7_dm
	Found 0 keys to try after 0.5 seconds
	DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
	searching for kinfoFiles in C:\Users\tinho\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Conversion options changed from defaults:
	  read_metadata_from_opf: 'C:\\Users\\tinho\\AppData\\Local\\Temp\\calibre_r07o7xta\\a5admx2p.opf'
	  verbose: 2
	  output_profile: 'kindle_pw3'
	Resolved conversion options
	calibre version: 7.21.0
	{'add_alt_text_to_img': False,
	 'allow_conversion_with_errors': False,
	 'asciiize': False,
	 'author_sort': None,
	 'authors': None,
	 'base_font_size': 0.0,
	 'book_producer': None,
	 'change_justification': 'original',
	 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
	            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
	            "'i')) or @class = 'chapter']",
	 'chapter_mark': 'pagebreak',
	 'comments': None,
	 'cover': None,
	 'debug_pipeline': None,
	 'dehyphenate': True,
	 'delete_blank_paragraphs': True,
	 'disable_font_rescaling': False,
	 'dont_compress': False,
	 'duplicate_links_in_toc': False,
	 'embed_all_fonts': False,
	 'embed_font_family': None,
	 'enable_heuristics': False,
	 'expand_css': False,
	 'extra_css': None,
	 'extract_to': None,
	 'filter_css': '',
	 'fix_indents': True,
	 'font_size_mapping': None,
	 'format_scene_breaks': True,
	 'html_unwrap_factor': 0.4,
	 'input_encoding': None,
	 'input_profile': <calibre.customize.profiles.InputProfile object at 0x0000020CF5F33F10>,
	 'insert_blank_line': False,
	 'insert_blank_line_size': 0.5,
	 'insert_metadata': False,
	 'isbn': None,
	 'italicize_common_cases': True,
	 'keep_ligatures': False,
	 'language': None,
	 'level1_toc': None,
	 'level2_toc': None,
	 'level3_toc': None,
	 'line_height': 0.0,
	 'linearize_tables': False,
	 'margin_bottom': 5.0,
	 'margin_left': 5.0,
	 'margin_right': 5.0,
	 'margin_top': 5.0,
	 'markup_chapter_headings': True,
	 'max_toc_links': 50,
	 'minimum_line_height': 120.0,
	 'mobi_file_type': 'old',
	 'mobi_ignore_margins': False,
	 'mobi_keep_original_images': False,
	 'mobi_toc_at_start': False,
	 'no_chapters_in_toc': False,
	 'no_inline_navbars': True,
	 'no_inline_toc': False,
	 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x0000020CF5F43090>,
	 'page_breaks_before': '/',
	 'personal_doc': '[PDOC]',
	 'prefer_author_sort': False,
	 'prefer_metadata_cover': False,
	 'pretty_print': False,
	 'pubdate': None,
	 'publisher': None,
	 'rating': None,
	 'read_metadata_from_opf': 'C:\\Users\\tinho\\AppData\\Local\\Temp\\calibre_r07o7xta\\a5admx2p.opf',
	 'remove_fake_margins': True,
	 'remove_first_image': False,
	 'remove_paragraph_spacing': False,
	 'remove_paragraph_spacing_indent_size': 1.5,
	 'renumber_headings': True,
	 'replace_scene_breaks': '',
	 'search_replace': '[]',
	 'series': None,
	 'series_index': None,
	 'share_not_sync': False,
	 'smarten_punctuation': False,
	 'sr1_replace': None,
	 'sr1_search': None,
	 'sr2_replace': None,
	 'sr2_search': None,
	 'sr3_replace': None,
	 'sr3_search': None,
	 'start_reading_at': None,
	 'subset_embedded_fonts': False,
	 'tags': None,
	 'timestamp': None,
	 'title': None,
	 'title_sort': None,
	 'toc_filter': None,
	 'toc_threshold': 6,
	 'toc_title': None,
	 'transform_css_rules': '[]',
	 'transform_html_rules': '[]',
	 'unsmarten_punctuation': False,
	 'unwrap_lines': True,
	 'use_auto_toc': False,
	 'verbose': 2}
	DeDRM v10.0.9: Trying to decrypt t2jy7_dm.kfx-zip
	Decrypting KFX-ZIP ebook: t2jy7_dm
	Found 0 keys to try after 0.0 seconds
	DeDRM v10.0.9: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	DeDRM v10.0.9: Looking for new default Kindle Key after 0.0 seconds
	searching for kinfoFiles in C:\Users\tinho\AppData\Local
	No K4PC kindle.info/kinf/kinf2011 files have been found.
	DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	Running file type plugin DeDRM failed with traceback:
	Traceback (most recent call last):
	  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
	  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
	  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 67, in processBook
	  File "C:\Users\tinho\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 88, in decrypt_voucher
	Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
	  File "calibre_plugins.dedrm.__init__", line 1030, in run
	  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
	calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
	InputFormatPlugin: KFX Input running
	on C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\t2jy7_dm.kfx-zip
	Software versions: KFX Input 2.16.0, calibre 7.21, Windows-10-10.0.22631-SP0
	KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
	Converting C:\Users\tinho\AppData\Local\Temp\calibre_r07o7xta\t2jy7_dm.kfx-zip
	Processing container: 50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition)_B0BW4F49RR.kfx
	Traceback (most recent call last):
	  File "calibre_plugins.kfx_input.__init__", line 102, in convert
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 212, in decode_book
	  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 321, in get_container
	calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container 50 Obras-Primas Que Você Deve Ler Antes De Morrer Vol_ 1 (Portuguese Edition)_B0BW4F49RR.kfx has DRM and cannot be converted
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "runpy.py", line 198, in _run_module_as_main
	  File "runpy.py", line 88, in _run_code
	  File "site.py", line 83, in <module>
	  File "site.py", line 78, in main
	  File "site.py", line 50, in run_entry_point
	  File "calibre\utils\ipc\worker.py", line 215, in main
	  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
	  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
	  File "calibre\ebooks\conversion\plumber.py", line 1129, in run
	  File "calibre\customize\conversion.py", line 245, in __call__
	  File "calibre_plugins.kfx_input.__init__", line 122, in convert
	calibre.ebooks.DRMError: This book has DRM!```

**Comment by ElleKayEm** [comment]
You will not be able to decrypt a book downloaded directly to your Kindle.  Is it an E-ink Kindle and not one of the brand new 2024 releases?  Then go to your Content Library on the website and use the "Download & transfer via USB" option choosing that Kindle.  You will also need to have that Kindle's serial number entered into DeDRM's customization.
