### ISSUE TITLE
Can the plugin work with an unpacked KFX container?

### ISSUE THREAD

**Issue by RastislavKish** [noDRM/DeDRM_tools#674]
### Question / bug report

Reading the DeDRM documentation it seems KFX is a file format, some kind of ZIP archive. However, the recent version of Kindle PC seems not to use it directly anymore. I have a book which got extracted into the My Kindle Content directory. Everything seems to be present i.e. the book itself in a .azw format, the .voucher file, a file with resources and few other metadata files. But no .KFX file. The Kindle cache folder in AppData has a book_temp_dl directory, which I assume is likely used for downloading the KFXs, but they're apparently flushed immediately after extraction.

Can DeDRM import these separate parts as one book, or is there a way to re-create the KFX file?

### Which version of Calibre are you running?

7.21.0

### Which version of the DeDRM plugin are you running?

DeDRM_alpha_7379b453199ed1ba91bf3a4ce4875d5ed3c309a9

### If applicable, which version of the Kindle software are you running?

2.5.0 (70951)

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
Kindle for PC uses the AZW extension for the main book file regardless of file format.  If it is KFX, the KFX Input plugin gathers all the needed files into KFX-ZIP.  If DeDRM is successful then you will see a KFX file in calibre.

You need to go back to Kindle for PC 2.4.0 (70904) aka 2.4.70904 for this to work though.

**Comment by RastislavKish** [comment]
Thanks for the quick response! Maybe it would be good to update the FAQ with the hashes of the 2.4.0 version? As far as I understand, the 1.17 which is promoted currently can not work with KFX and I would assume it's going to stop working sooner or later if it didn't already.

**Comment by ElleKayEm** [comment]
Yeah, the FAQs hasn't been updated in a couple years.  Kindle for PC 1.17 stopped downloading books published in 2023 and newer.  (And it stopped working at all for me when I updated to Windows 11.)  This post has the current info: https://www.mobileread.com/forums/showthread.php?t=361503

**Comment by RastislavKish** [comment]
I've uninstalled Kindle 2.5, removed My Kindle content and the Amazon AppData dir, and installed 2.4.0 (70904), the digital signature seems to be valid, so the installer should be ok.

However, when trying to import the .azw file into Calibre after re-downloading the book, DeDRM keeps being unable to locate the voucher. Which is weird, since I can see the .voucher file literally next to the .azw file. could this be a problem with KFXInput? I've installed it through the Calibre interface.

Here is the log:

```
calibre, version 7.21.0
ERROR: Loading book failed: Failed to open the book at C:\Users\Quickemu\Documents\My Kindle Content\B00TZFEERQ_EBOK\B00TZFEERQ_EBOK.azw. Click "Show details" for more info.

Failed to convert book: C:\Users\Quickemu\Documents\My Kindle Content\B00TZFEERQ_EBOK\B00TZFEERQ_EBOK.azw with error:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 483, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 267, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 502, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'
DeDRM v10.0.9: Trying to decrypt B00TZFEERQ_EBOK.azw
DeDRM v10.0.9: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\Quickemu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 171, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.9: Looking for new default Kindle Key after 2.8 seconds
searching for kinfoFiles in C:\Users\Quickemu\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Quickemu\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2591473375' and UserName 'Quickemu'
DeDRM v10.0.9: Found 1 new key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\Quickemu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 171, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 987, in KindleMobiDecrypt
  File "C:\Users\Quickemu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 171, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.9: Ultimately failed to decrypt after 3.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\Quickemu\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 171, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1052, in run
  File "calibre_plugins.dedrm.__init__", line 1003, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 3.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: MOBI Input running
on C:\Users\Quickemu\Documents\My Kindle Content\B00TZFEERQ_EBOK\B00TZFEERQ_EBOK.azw
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 28, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 90, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 847, in viewer_main
  File "calibre\srv\render_book.py", line 838, in render_for_viewer
  File "calibre\srv\render_book.py", line 815, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 64, in extract_book
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\mobi_input.py", line 34, in convert
  File "calibre\ebooks\mobi\reader\mobi6.py", line 90, in __init__
calibre.ebooks.mobi.reader.mobi6.KFXError: This is an Amazon KFX book. It cannot be processed. See https://www.mobileread.com/forums/showthread.php?t=283371 for information on how to handle KFX books.
```

**Comment by ElleKayEm** [comment]
The KFX Input plugin should gather all needed files and pass it to DeDRM for decryption.  Did you restart calibre after installing the KFX Input plugin?

**Comment by RastislavKish** [comment]
I've checked out the KFX Input release notes and learned it's possible to zip up the directory content, rename the extension to kfx-zip and load the file in calibre. I tried this approach instead of opening the .azw file in Calibre ebook viewer, and it works like a charm!

Truly incredible work!

**Comment by ElleKayEm** [comment]
That's exactly what KFX Input does for you when you add the book to calibre.  No need to zip it up yourself.
