### ISSUE TITLE
Failure to Decrypt ADE eBook: "Decoding with Hex codec failed"

### ISSUE THREAD

**Issue by Vermenthruaxx** [noDRM/DeDRM_tools#681]
### Question / bug report

Hello!
I am trying to use a mixture of DeACSM and DeDRM to have a one stop download and DeDRM for my eBooks.
When I am trying to import an ADE eBook, i get the following output in the debug log:

DeDRM successfully detected my ADE key and imported it, and i've already authorized DeACSM with my AdobeID. so i am unsure what the issue is.

### Which version of Calibre are you running?

7.21

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
[0.00] Starting up...
[0.00] Showing splash screen...
[1.19] splash screen shown
[1.19] Initializing db...
[1.19] db initialized
[1.19] Constructing main UI...
[1.48] GUI main window shown
[1.55] main UI initialized...
[1.55] Hiding splash screen
[1.56] splash screen hidden
[1.56] Started up in 1.56 seconds with 2 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xbfz\xda\x9e;1:\x1c\x85\x81\xaf\r7c\xfb,\x89a\xeax\xce \x05l\xb4UVn\\o/\x04', b'C:\\Users\\Chris\\Downloads\\URLLink.acsm']
DeDRM v10.0.3: Trying to decrypt gwqkm4ks.epub
DeDRM v10.0.3: Verifying zip archive integrity
DeDRM v10.0.3: gwqkm4ks.epub is a secure Adobe Adept ePub for UUID 12612816-1051-4ef0-94ae-1930938a33f1
DeACSM v0.0.16: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 486, in run
  File "calibre_plugins.dedrm.__init__", line 1067, in run
  File "calibre_plugins.dedrm.__init__", line 533, in ePubDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Added The Last Dragon Chronicles: The Fire Within to db in: 0.1
Added 1 books in 3.3 seconds
```

**Comment by ElleKayEm** [comment]
Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

Delete the currently saved key from DeDRM's customization.

**Comment by Vermenthruaxx** [comment]
Cool, thank you. That worked.
