### ISSUE TITLE
BookLive decryption

### ISSUE THREAD

**Issue by IntelMiner** [noDRM/DeDRM_tools#685]
### Question / bug report

Hi team, purchased a Japanese art book for my artist roommate. Trying to strip the DRM so she can read it just as a PDF.

The DeDRM plugin seems to complain "file is not a zip file" when attempting to decrypt it. 

Running `file` on it from a Linux machine spits out

`0_EB100027174500100101502021.epub: ISO Media, OMA DCF DRM Format 2.0 (OMA-TS-DRM-DCF-V2_0-20060303-A)`

For fun I also tried running `strings` on it. There's a string that reports back `application/vnd.oma.drm.dcf` which seems to reinforce that it's using "OMA" (Open Media Alliance?) for its DRM method. 

Is there any way I can get the DRM free version of this title, or am I better off trying to track down a Kindle or other version with "easier" DRM?

### Which version of Calibre are you running?

7.22.0 (Win64)

### Which version of the DeDRM plugin are you running?

Latest Git commit

### Log output

```log
calibre, version 7.22.0 (win32, embedded-python: True)
Conversion error: Failed: Convert book 1 of 1 (0 EB100027174500100101502021)

Convert book 1 of 1 (0 EB100027174500100101502021)
DeDRM v10.0.9: Trying to decrypt s1g4ro9m.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Error 'File is not a zip file' when checking zip archive
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 321, in ePubDecrypt
  File "C:\Users\Intel Miner\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfix.py", line 66, in __init__
  File "C:\Users\Intel Miner\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 698, in __init__
  File "C:\Users\Intel Miner\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 724, in _GetContents
  File "C:\Users\Intel Miner\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 736, in _RealGetContents
zipfilerugged.BadZipfile: File is not a zip file
Conversion options changed from defaults:
  read_metadata_from_opf: 'C:\\Users\\INTELM~1\\AppData\\Local\\Temp\\calibre_jv_k9inb\\n7hd7air.opf'
  verbose: 2
  prefer_metadata_cover: True
  output_profile: 'generic_eink'
Resolved conversion options
calibre version: 7.22.0
{'add_alt_text_to_img': False,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_max_image_size': 'none',
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001EE13E8C690>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001EE13E8FF10>,
 'page_breaks_before': '/',
 'prefer_metadata_cover': True,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\INTELM~1\\AppData\\Local\\Temp\\calibre_jv_k9inb\\n7hd7air.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
DeDRM v10.0.9: Trying to decrypt s1g4ro9m.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Error 'File is not a zip file' when checking zip archive
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 321, in ePubDecrypt
  File "C:\Users\Intel Miner\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfix.py", line 66, in __init__
  File "C:\Users\Intel Miner\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 698, in __init__
  File "C:\Users\Intel Miner\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 724, in _GetContents
  File "C:\Users\Intel Miner\AppData\Roaming\calibre\plugins\DeDRM.zip\zipfilerugged.py", line 736, in _RealGetContents
zipfilerugged.BadZipfile: File is not a zip file
InputFormatPlugin: EPUB Input running
on C:\Users\INTELM~1\AppData\Local\Temp\calibre_jv_k9inb\s1g4ro9m.epub
EPUB appears to be invalid ZIP file, trying a more forgiving ZIP parser
Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 265, in convert
  File "calibre\utils\zipfile.py", line 774, in __init__
  File "calibre\utils\zipfile.py", line 809, in _GetContents
  File "calibre\utils\zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

Traceback (most recent call last):
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 265, in convert
  File "calibre\utils\zipfile.py", line 774, in __init__
  File "calibre\utils\zipfile.py", line 809, in _GetContents
  File "calibre\utils\zipfile.py", line 824, in _RealGetContents
calibre.utils.zipfile.BadZipfile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1129, in run
  File "calibre\customize\conversion.py", line 245, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 272, in convert
  File "calibre\utils\localunzip.py", line 255, in extractall
  File "calibre\utils\localunzip.py", line 242, in _extractall
ValueError: Not a ZIP file
```

**Comment by ElleKayEm** [comment]
Not a DRM these tools handle.
