### ISSUE TITLE
Exception when getting default Kindle Key

### ISSUE THREAD

**Issue by TT-ZX** [noDRM/DeDRM_tools#689]
### Question / bug report

Getting this error when importing a book.
`DeDRM v10.0.9: Failed to decrypt with error: unsupported operand type(s) for +: 'int' and 'str'`

### Which version of Calibre are you running?

3.48.0

### Which version of the DeDRM plugin are you running?

v10.0.9

### If applicable, which version of the Kindle software are you running?

2.4.70904

### Log output

```log
PS C:\Users\justin> calibre-debug -g
calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-7-6.1.7601-SP1 Windows ('64bit', 'WindowsPE')
('Windows', '7', '6.1.7601')
Python 2.7.15+
Windows: ('7', '6.1.7601', 'SP1', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 9)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 152.4 x 114.3
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.05] db initialized
[0.05] Constructing main UI...
[1.09] main UI initialized...
[1.09] Hiding splash screen
[1.52] splash screen hidden
[1.53] Started up in 1.53 seconds with 2 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['\xfa\x0b\xb8y+\xc9\x92\x9e\x9e\x80\xd6\xca\xe6\xec3jhP+\xc3\xf1\x9a\xf10\x07\xe0~\
xb9}++\x9a', 'C:\\Users\\justin\\Documents\\My Kindle Content\\B0149MCD0E_EBOK\\B0149MCD0E_EBOK.azw']
DeDRM v10.0.9: Trying to decrypt B0149MCD0E_EBOK.azw
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Automating Manufacturing Operations: The Penultimate Approach
Found 0 keys to try after 0.3 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: unsupported operand type(s) for +: 'int' and 'str'
DeDRM v10.0.9: Looking for new default Kindle Key after 0.3 seconds
searching for kinfoFiles in C:\Users\justin\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\justin\AppData\Local\Amazon\Kindle\storage\.kinf2018
DeDRM v10.0.9: Exception when getting default Kindle Key after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 943, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.kindlekey", line 894, in kindlekeys
  File "calibre_plugins.dedrm.kindlekey", line 382, in getDBfromFile
  File "calibre_plugins.dedrm.kindlekey", line 382, in <dictcomp>
  File "calibre_plugins.dedrm.kindlekey", line 127, in encodeHash
  File "calibre_plugins.dedrm.kindlekey", line 119, in encode
TypeError: unsupported operand type(s) for ^: 'str' and 'int'
DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/n
oDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 172, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://
github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Automating Manufacturing Operations: The Penultimate Approach to db in: 0.1
Added 1 books in 0.7 seconds
```

**Comment by ElleKayEm** [comment]
I suspect the issue may be the old version of calibre with this version of DeDRM.  You could try DeDRM 6.8.1: https://github.com/apprenticeharper/DeDRM_tools/releases/tag/v6.8.1

If that doesn't work, you might also need an older version of Kindle for PC in order to get a non-kfx copy of the book.  See method 1 or 2a under the spoiler at the bottom of this post: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by TT-ZX** [comment]
I can confirm, it's probably an issue with the old version of Calibre (the last version compatible with Windows 7).  I repeated my setup on a fresh Windows 10 install and everything works as expected.

Thanks!
