### ISSUE TITLE
DeDRM plugin for Calibre

### ISSUE THREAD

**Issue by 2Prestones** [noDRM/DeDRM_tools#692]
### Question / bug report

I successfully installed DeDRM in my Windows 11 machine, but was unable to save any books to Calibre. I'm new to this, so tried using both the EBOK.azw file type and the .azw.md file type, but neither would open. The debug file follows for the EBOK.azw file.

### Which version of Calibre are you running?

7.22

### Which version of the DeDRM plugin are you running?

v10.0.9

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 127.66492146596858 x 127.59069767441859
[0.00] Starting up...
[0.00] Showing splash screen...
[1.22] splash screen shown
[1.22] Initializing db...
[1.23] db initialized
[1.23] Constructing main UI...
[1.55] GUI main window shown
[1.62] main UI initialized...
[1.62] Hiding splash screen
[1.62] splash screen hidden
[1.62] Started up in 1.62 seconds with 9 books
DeDRM v10.0.9: Trying to decrypt B0834GK847_EBOK.azw
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'B\xbd\xfc>L\xb4\xf1)\x95zO\x9bV\xed\x16\xf4\xc6P\xaa0\x02\x94\x98\xc04\xad\xb4\xd2n\xd0\x1f[', b'C:\\Users\\mcnee\\Documents\\MYKIND~1\\B0834GK847_EBOK\\B0834GK847_EBOK.azw']
DeDRM v10.0.9: Failed to decrypt with error: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.9 seconds
searching for kinfoFiles in C:\Users\mcnee\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\mcnee\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '2846984891' and UserName 'mcnee'
DeDRM v10.0.9: Found 1 new key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\mcnee\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\mcnee\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.
DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\mcnee\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 170, in GetDecryptedBook
k4mobidedrm.DrmException: The .kfx DRMION file cannot be decrypted by itself. A .kfx-zip archive containing a DRM voucher is required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 1.1 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 483, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 267, in get_metadata
  File "calibre\ebooks\metadata\mobi.py", line 502, in get_metadata
  File "calibre\ebooks\mobi\reader\headers.py", line 295, in __init__
  File "calibre\ebooks\mobi\reader\headers.py", line 323, in identity
calibre.ebooks.mobi.MobiError: Unknown book type: b'\x02\xa2\x81\xc4\xde\x02\x9d\x8c'

```

**Comment by ElleKayEm** [comment]
Install the KFX Input plugin.  Also download the book with Kindle for PC 2.4.0 (70904) aka 2.4.70904 if you used a more recent version.

**Comment by 2Prestones** [comment]
Thanks @ElleKayEm! I'll get on it and report back - good or bad.
