### ISSUE TITLE
DeDRM does not work

### ISSUE THREAD

**Issue by sougeralan** [noDRM/DeDRM_tools#693]
### Question / bug report

Hi Friend, i met a trouble to DeDRM ebook, the report is described as below, could you please help me here? thanks advance.

### Which version of Calibre are you running?

7.22

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
Paste log output here.
```
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.12164948453608
[0.00] Starting up...
[0.00] Showing splash screen...
[1.86] splash screen shown
[1.86] Initializing db...
[1.88] db initialized
[1.88] Constructing main UI...
[2.42] GUI main window shown
[2.47] main UI initialized...
[2.47] Hiding splash screen
[2.47] splash screen hidden
[2.47] Started up in 2.47 seconds with 3 books
DeDRM v10.0.3: Trying to decrypt 楚辞.azw3
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 楚辞
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v10.0.3: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.3: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\Allan\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Allan\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1317685645' and UserName 'Allan'
DeDRM v10.0.3: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 楚辞
Got DSN key from database key_0
Found 4 keys to try after 0.5 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Allan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Allan\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 991, in KindleMobiDecrypt
  File "C:\Users\Allan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Allan\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 957, in KindleMobiDecrypt
  File "C:\Users\Allan\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 261, in GetDecryptedBook
  File "C:\Users\Allan\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 501, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1056, in run
  File "calibre_plugins.dedrm.__init__", line 1007, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.3: Ultimately failed to decrypt after 0.5 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
stdout+stderr from file dialog helper: [b'', b'']
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xca\xec\x89\xbb\xf8\t\x8c75\x85\x90\n>x\x82&(\x7f\x07\xe7n \xb7\x03Yn^\x13I\xe4\xbd\x91', b'D:\\Family\\\xe8\x8b\x8f\xe9\x94\x90\\Kindle \xe4\xb9\xa6\xe5\xba\x93\\\xe6\xa5\x9a\xe8\xbe\x9e.azw3']

**Comment by ElleKayEm** [comment]
If that book is for an E-ink Kindle (not a Fire), then you need to enter that Kindle's serial number into DeDRM's customization.

**Comment by sougeralan** [comment]
and i update the DeDRM to a high version 10.0.9, the problem is till there.

**Comment by ElleKayEm** [comment]
See my previous comment.

**Comment by sougeralan** [comment]
Thank you very much, the problem is solved, i can open the ebook again, thank you again.

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.
