### ISSUE TITLE
drm removal not working for kfx zip file 

### ISSUE THREAD

**Issue by Delli** [noDRM/DeDRM_tools#694]
### Question / bug report

About a mont ago i had not problems with other books but this 

ebook ( url below ) I get drm removal error 

I use kfx input  version 2.18.0 

https://www.amazon.nl/Essentials-Compassion-Focused-Therapy-Clinicians-ebook/dp/B0CKFK5YH3/ref=sr_1_1?crid=7S9GGKEEJ21N&dib=eyJ2IjoiMSJ9.EmjL1iFwq6QIMIp0iWCOwgdstZzYC6jInxIYFauDNkdi3bfjCKc1GRBJhdopgrhQbIiZPE0ndIjRDyKAoUISNxxIudZM8wmipFiNpagMASFipGT6KsXyY_HntxDeA3JI7zJ6Qs0V7n0MzFQRAFoWRDUXek1l2Z26n7tZiA3NQlmm0pfy6xxvBcVl9NgNojxa2vzBSLYoO2g3QdjnRrJah3O6TAohYyCz8CAW_Djoso4.PPTEPDorESo1yfP1ko5yDuzxmiBHjtVODruvkal9c8A&dib_tag=se&keywords=Compassion+Focused+Therapy&qid=1733780295&s=digital-text&sprefix=compassion+focused+therapy%2Cdigital-text%2C324&sr=1-1   

### Which version of Calibre are you running?

7.22.0

### Which version of the DeDRM plugin are you running?

DeDRM_alpha_7379b453199ed1ba91bf3a4ce4875d5ed3c309a9

### If applicable, which version of the Kindle software are you running?

2.4.1 (70946)

### Log output

ApplicationPaletteChange event ignored
Using calibre Qt style: True
ApplicationPaletteChange event received
calibre Debug log
calibre 7.13  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 18, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 18, 0) && KFX metadata reader (from KFX Input) (2, 18, 0) && From KFX (2, 18, 0) && KFX Input (2, 18, 0) && Obok DeDRM (10, 0, 9)
calibre 7.13  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 18, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 18, 0) && KFX metadata reader (from KFX Input) (2, 18, 0) && From KFX (2, 18, 0) && KFX Input (2, 18, 0) && Obok DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 108.91792294807368 x 108.85714285714285
[0.00] Starting up...
[0.02] Showing splash screen...
[0.44] splash screen shown
[0.44] Initializing db...
[0.53] db initialized
[0.53] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.09] GUI main window shown
[2.39] main UI initialized...
[2.39] Hiding splash screen
[28.67] splash screen hidden
[28.67] Started up in 28.67 seconds with 1118 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe35\x01\xe7\x1er\xe5I$\xa0\x13\\(\xba\xe6&I\xa9\n\xeb ?U2N\xee\xa5\xc9{a\xa0H', b'C:\\Users\\rjber\\Documents\\My Kindle Content\\B0CKFK5YH3_EBOK\\B0CKFK5YH3_EBOK.azw']
Gather KFX-ZIP (from KFX Input) 2.18.0: Importing C:\Users\rjber\Documents\My Kindle Content\B0CKFK5YH3_EBOK\B0CKFK5YH3_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 5 file(s) as C:\Users\rjber\AppData\Local\Temp\calibre_orwejdg1\uqfxazuo.kfx-zip
DeDRM v10.0.9: Trying to decrypt uqfxazuo.kfx-zip
Decrypting KFX-ZIP ebook: uqfxazuo
Got DSN key from database kindle_key_1663278286_1
Found 1 keys to try after 0.5 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.317f8f52-c1b5-402f-b501-05ae198f91a3.voucher
Traceback (most recent call last):
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
DeDRM v10.0.9: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Looking for new default Kindle Key after 0.5 seconds
searching for kinfoFiles in C:\Users\rjber\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\rjber\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '3974969929' and UserName 'rjber'
DeDRM v10.0.9: Found 1 new key
Decrypting KFX-ZIP ebook: uqfxazuo
Got DSN key from database key_0
Found 1 keys to try after 0.7 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.317f8f52-c1b5-402f-b501-05ae198f91a3.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 987, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1052, in run
  File "calibre_plugins.dedrm.__init__", line 1003, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 2.18.0: Packaging C:\Users\rjber\AppData\Local\Temp\calibre_orwejdg1\uqfxazuo.kfx-zip
Processing container: B0CKFK5YH3_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 23, in run
  File "calibre_plugins.kfx_input.package_filetype", line 34, in package_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 79, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 213, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 322, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0CKFK5YH3_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for C:\Users\rjber\AppData\Local\Temp\calibre_orwejdg1\xk9dn46f_add_books\0\B0CKFK5YH3_EBOK.kfx-zip
Failed to get text from book_id: 1157 format: KFX-ZIP
Traceback (most recent call last):
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 105, in decrypt_voucher
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 1416, in parse
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 124, in _assert
Exception: Unknown type encountered in envelope, expected VoucherEnvelope
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 987, in KindleMobiDecrypt
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook
  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key
Running file type plugin DeDRM failed with traceback:

Traceback (most recent call last):

  File "calibre_plugins.dedrm.__init__", line 950, in KindleMobiDecrypt

  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 204, in GetDecryptedBook

  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 68, in processBook

  File "C:\Users\rjber\AppData\Roaming\calibre\plugins\DeDRM.zip\kfxdedrm.py", line 112, in decrypt_voucher

Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins

  File "calibre_plugins.dedrm.__init__", line 1052, in run

  File "calibre_plugins.dedrm.__init__", line 1003, in KindleMobiDecrypt

calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.8 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

Traceback (most recent call last):

  File "calibre_plugins.kfx_input.__init__", line 102, in convert

  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 213, in decode_book

  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 322, in get_container

calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B0CKFK5YH3_EBOK.azw has DRM and cannot be converted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "runpy.py", line 198, in _run_module_as_main

  File "runpy.py", line 88, in _run_code

  File "site.py", line 83, in <module>

  File "site.py", line 78, in main

  File "site.py", line 50, in run_entry_point

  File "calibre\utils\ipc\worker.py", line 196, in main

  File "<string>", line 1, in <module>

  File "calibre\db\fts\text.py", line 103, in main

  File "calibre\db\fts\text.py", line 90, in extract_text

  File "calibre\ebooks\oeb\iterator\book.py", line 64, in extract_book

  File "calibre\customize\conversion.py", line 245, in __call__

  File "calibre_plugins.kfx_input.__init__", line 122, in convert

calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
Go back to Kindle for PC 2.4.0 (70904) aka 2.4.70904.  See info under method 2a in this post about blocking auto updates: https://www.mobileread.com/forums/showthread.php?t=361503
