### ISSUE TITLE
DRM not removed

### ISSUE THREAD

**Issue by jdecro** [noDRM/DeDRM_tools#695]
### Question / bug report

Hello! I am still facing issues with DRM in Calibre. Any help would be greatly appreciated! Thank you!!

### Which version of Calibre are you running?

7.22.0

### Which version of the DeDRM plugin are you running?

10.0.9

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.22  embedded-python: True
macOS-13.7.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Thu Sep  5 20:48:48 PDT 2024; root:xnu-8796.141.3.708.1~1/RELEASE_X86_64')
Python 3.11.5
OSX: ('13.7.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
calibre 7.22  embedded-python: True
macOS-13.7.1-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.6.0', 'Darwin Kernel Version 22.6.0: Thu Sep  5 20:48:48 PDT 2024; root:xnu-8796.141.3.708.1~1/RELEASE_X86_64')
Python 3.11.5
OSX: ('13.7.1', ('', '', ''), 'x86_64')
Interface language: None
EXE path: /Applications/calibre.app/Contents/MacOS/calibre-debug
Successfully initialized third party plugins: DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 9)
QPA platform: cocoa
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 125.50000188482092 x 125.50000188482092
[0.00] Starting up...
[0.11] Showing splash screen...
[1.32] splash screen shown
[1.32] Initializing db...
[1.34] db initialized
[1.34] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.99] GUI main window shown
[2.09] main UI initialized...
[2.09] Hiding splash screen
[2.18] splash screen hidden
[2.18] Started up in 2.18 seconds with 0 books
2024-12-10 18:16:23.363 calibre-debug[3808:1215173] +[CATransaction synchronize] called within transaction
DeDRM v10.0.9: Trying to decrypt McCance & Huether’s Pathophysiology - E-Book.azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: McCance & Huether’s Pathophysiology - E-Book
Found 2 keys to try after 2.0 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 2.0 seconds
No k4Mac kindle-info/rainier/kinf2011 files have been found.
DeDRM v10.0.9: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeff/Library/Preferences/calibre/plugins/DeDRM.zip/k4mobidedrm.py", line 203, in GetDecryptedBook
    mb.processBook(totalpids)
  File "/Users/jeff/Library/Preferences/calibre/plugins/DeDRM.zip/mobidedrm.py", line 401, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 201, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md

```

**Comment by ElleKayEm** [comment]
If that book is for an E-ink Kindle (not a Fire), then make sure you have that Kindle's serial number correctly entered into DeDRM's customization.
