### ISSUE TITLE
Error When Decrypting ASCM to PDF File

### ISSUE THREAD

**Issue by umbralbones** [noDRM/DeDRM_tools#697]
### Question / bug report

I downloaded a book I bought for academic research purposes and want to de-DRM it, but the pdf that is produced from the de-DRMing fails to open in any reader. The error log provides the log of attempting to de-DRM the ASCM file. The book itself is from 1996 so I don't think it should have any advanced DRM on it.

### Which version of Calibre are you running?

7.22

### Which version of the DeDRM plugin are you running?

10.0.3

### Log output

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 2.5
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.41395348837209
[0.00] Starting up...
[0.00] Showing splash screen...
[1.22] splash screen shown
[1.22] Initializing db...
[1.25] db initialized
[1.25] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[1.94] GUI main window shown
[2.19] main UI initialized...
[2.19] Hiding splash screen
[2.20] splash screen hidden
[2.20] Started up in 2.20 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xd3\xd0O~\xeaD\xa2/\xd0}0\xffgEN\xa3\x15*\x0f\x8b\xa9\xfa\xd4\xb8>\x92o\xb4>\x9d\x8d\xb6', b'C:\\Users\\bubbl\\Downloads\\Adapting_to_Capitalism-pdf(1).acsm']
DeDRM v10.0.3: Trying to decrypt _jm44m7g.pdf
DeDRM v10.0.3: _jm44m7g.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.3: _jm44m7g.pdf is a PDF ebook (EBX) for UUID a4e5a7f4-9c61-42a7-9592-30b98909c755
DeACSM v0.0.16: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 486, in run
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 923, in PDFDecrypt
  File "calibre_plugins.dedrm.__init__", line 695, in PDFIneptDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 483, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 325, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
DeACSM v0.0.16: Trying to parse file Adapting_to_Capitalism-pdf(1).acsm
DeACSM v0.0.16: Try to fulfill ...
Not notifying any server since that was disabled.
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://books.google.com/books/download/Adapting_to_Capitalism.pdf?acsid=urn:uuid:d6130947-6bab-516a-7951-c3492e258fe5&output=acs4_book_bytes
Download took 1582 ms (HTTP 200)
That's a PDF file
DeACSM v0.0.16: Downloaded PDF, adding encryption config ...
Searching for startxref ...
Got startxref: 12348757
Found ENC after 5 attempts - took 0 ms
Found EBX after 1687 attempts - took 2 ms


Encryption handler:
<</Root 1675 0 R/Info 1437 0 R/Encrypt 1676 0 R/ID[<EDD955ECA7EB8957749C7605095003CC><EDD955ECA7EB8957749C7605095003CC>]/Size 1677>>
EBX handler:
<</EBX_AUTHOR(Pamela Sharpe)/Filter/EBX_HANDLER/Length 128/ADEPT_ID(urn:uuid:d6130947-6bab-516a-7951-c3492e258fe5)/V 4/EBX_TITLE(Adapting to Capitalism)>>
Trimmed encryption handler:
<</Root 1675 0 R/Info 1437 0 R/Encrypt 1676 0 R/ID[<EDD955ECA7EB8957749C7605095003CC><EDD955ECA7EB8957749C7605095003CC>]/Size 1677>>
Updated EBX handler not logged due to sensitive data
Whole DRM patching took 17 milliseconds.
DeACSM v0.0.16: File successfully fulfilled ...
DeACSM v0.0.16: Executing plugin DeDRM ...
DeACSM v0.0.16: Plugin returned nothing - skipping
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
```

**Comment by ElleKayEm** [comment]
There's a bug in 10.0.3 which can cause an issue with the key.  Update to DeDRM 10.0.9: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.9

**Comment by umbralbones** [comment]
Thanks for the suggestion! Unfortunately I updated and it still did not work with a similar error. I will attach the log with no changes, aside from redacting my email. 

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Debug log
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 3)
calibre 7.22  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeACSM (0, 0, 16) && DeDRM (10, 0, 9) && Obok DeDRM (10, 0, 3)
QPA platform: windows
devicePixelRatio: 2.5
logicalDpi: 96.0 x 96.0
physicalDpi: 113.41395348837209 x 113.41395348837209
[0.00] Starting up...
[0.00] Showing splash screen...
[1.25] splash screen shown
[1.25] Initializing db...
[1.28] db initialized
[1.28] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.00] GUI main window shown
[2.27] main UI initialized...
[2.27] Hiding splash screen
[2.28] splash screen hidden
[2.28] Started up in 2.28 seconds with 1 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b"\xa9P|\xe7.]\xe3\x89\xfe\xc0\x0b\xb7\xf6\xb3%\xa4\xe4\xc4}W\xc7\xc8\xdaM\xd0.\xdd'\xbe,\x13\x1d", b'C:\\Users\\bubbl\\Downloads\\Adapting_to_Capitalism-pdf(1).acsm']
DeDRM v10.0.9: Trying to decrypt 04cl9ytv.pdf
DeDRM v10.0.9: 04cl9ytv.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.9: 04cl9ytv.pdf is a PDF ebook (EBX) for UUID a4e5a7f4-9c61-42a7-9592-30b98909c755
DeDRM v10.0.9: Trying UUID-matched encryption key a4e5a7f4-9c61-42a7-9592-30b98909c755_AdobeID_REDACTED@gmail.com
DeDRM v10.0.9: Exception when decrypting after 0.1 seconds - trying other keys
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 673, in PDFIneptDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
DeACSM v0.0.16: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "encodings\hex_codec.py", line 19, in hex_decode
ValueError: string argument should contain only ASCII characters

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 486, in run
  File "calibre_plugins.dedrm.__init__", line 1037, in run
  File "calibre_plugins.dedrm.__init__", line 897, in PDFDecrypt
  File "calibre_plugins.dedrm.__init__", line 692, in PDFIneptDecrypt
ValueError: decoding with 'hex' codec failed (ValueError: string argument should contain only ASCII characters)
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 483, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 325, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 126, in get_metadata
ValueError: Could not read info dict from PDF
DeACSM v0.0.16: Trying to parse file Adapting_to_Capitalism-pdf(1).acsm
DeACSM v0.0.16: Try to fulfill ...
Notifying server ...
Notifying server http://books.google.com/books/acs4/fulfillment/FulfillmentNotification
Fulfillment notification successful.
DeACSM v0.0.16: Downloading book ...
DeACSM v0.0.16: Loading book from https://books.google.com/books/download/_.pdf?acsid=urn:uuid:d6130947-6bab-516a-7951-c3492e258fe5&output=acs4_book_bytes
Download took 1365 ms (HTTP 200)
That's a PDF file
DeACSM v0.0.16: Downloaded PDF, adding encryption config ...
Searching for startxref ...
Got startxref: 12348757
Found ENC after 5 attempts - took 0 ms
Found EBX after 1687 attempts - took 3 ms


Encryption handler:
<</Root 1675 0 R/Info 1437 0 R/Encrypt 1676 0 R/ID[<ED1ED8BA0BB1D6EF04FBB98352730BBC><ED1ED8BA0BB1D6EF04FBB98352730BBC>]/Size 1677>>
EBX handler:
<</EBX_AUTHOR(Pamela Sharpe)/Filter/EBX_HANDLER/Length 128/ADEPT_ID(urn:uuid:d6130947-6bab-516a-7951-c3492e258fe5)/V 4/EBX_TITLE(Adapting to Capitalism)>>
Trimmed encryption handler:
<</Root 1675 0 R/Info 1437 0 R/Encrypt 1676 0 R/ID[<ED1ED8BA0BB1D6EF04FBB98352730BBC><ED1ED8BA0BB1D6EF04FBB98352730BBC>]/Size 1677>>
Updated EBX handler not logged due to sensitive data
Whole DRM patching took 15 milliseconds.
DeACSM v0.0.16: File successfully fulfilled ...
DeACSM v0.0.16: Executing plugin DeDRM ...
DeACSM v0.0.16: Plugin returned nothing - skipping
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
pdfinfo errored out with return code: 1
```

**Comment by ElleKayEm** [comment]
Try deleting the currently saved Adobe key from DeDRM's customization.  Let it automatically retrieve the key.

**Comment by umbralbones** [comment]
That worked beautifully! Thank you so much.

**Comment by Elmarts** [comment]
> Try deleting the currently saved Adobe key from DeDRM's customization. Let it automatically retrieve the key.

Um, how?  I have Calibre 5.37.0 (linux) with DeDRM 10.0.3, and I can't convert an ASCM file - or the output is less than 1 MB in size.  Log file follows:
calibre Debug log
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-161-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-161-generic', '#171-Ubuntu SMP Sat Oct 11 08:17:01 UTC 2025')
Python 3.10.12
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
calibre 5.37  embedded-python: False is64bit: True
Linux-5.15.0-161-generic-x86_64-with-glibc2.35 Linux ('64bit', 'ELF')
('Linux', '5.15.0-161-generic', '#171-Ubuntu SMP Sat Oct 11 08:17:01 UTC 2025')
Python 3.10.12
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 3)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 98.54965357967667 x 98.77777777777777
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.03] splash screen shown
[0.03] Initializing db...
[0.06] db initialized
[0.06] Constructing main UI...
[0.53] main UI initialized...
[0.53] Hiding splash screen
Starting QuickView
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1827, resource id: 14961803, major code: 40 (TranslateCoords), minor code: 0
[5.95] splash screen hidden
[5.95] Started up in 5.95 seconds with 697 books
Added By My Hands-epub to db in: 1.7
Added 1 books in 2.0 seconds

**Comment by ElleKayEm** [comment]
On Linux it's probably easiest to use DeACSM to download the book (pdf or epub) rather than messing with ADE.  Also might want to update calibre and DeDRM.

**Comment by Elmarts** [comment]
> On Linux it's probably easiest to use DeACSM to download the book (pdf or epub) rather than messing with ADE. Also might want to update calibre and DeDRM.

Sadly, that fails as well.  The tools install into Calibre fine (at least the plugin page says so), but the acsm file fails to convert - all I get is a file less than 1 MB in size.  Unless I misunderstand the instructions, which is not unlikely :)

**Comment by ElleKayEm** [comment]
The acsm file is not a book format.  You don't convert it.  It stands for Adobe Content Server Message.  It is just used to download the book file.  I'm on Windows so I  use Adobe Digital Editions.  Open the acsm file with ADE and the epub (or pdf) is downloaded.  Then I import it into calibre and DeDRM removes the DRM.  The DeACSM plugin is supposed to make the download happen directly into calibre, but I haven't actually used it myself.
