### ISSUE TITLE
Imported LCPL file not decrypted

### ISSUE THREAD

**Issue by Fabio-cyber751** [noDRM/DeDRM_tools#701]
### Question / bug report

Hi!
It is my first time trying to import a DRM-protected ebook in Calibre. I have installed the DeDRM plugin and customized it with the "Readium LCP" passphrase, but when I import an LCPL file I still cannot read it in Calibre.

### Which version of Calibre are you running?

7.6

### Which version of the DeDRM plugin are you running?

v10.0.3

### Log output

Log generated by Calibre in debug mode, when importing 2 LCPL files:

```log
ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre_plugins.obok_dedrm.obok.obok:419: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.obok_dedrm.obok.obok:419: SyntaxWarning: invalid escape sequence '\-'
calibre_plugins.obok_dedrm.obok.obok:419: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.obok_dedrm.obok.obok:433: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.obok_dedrm.obok.obok:433: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.obok_dedrm.obok.obok:443: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.obok_dedrm.obok.obok:443: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.obok_dedrm.obok.obok:450: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.obok_dedrm.obok.obok:450: SyntaxWarning: invalid escape sequence '\s'
calibre_plugins.obok_dedrm.obok.obok:649: SyntaxWarning: invalid escape sequence '\s'
calibre Debug log
calibre 7.6  embedded-python: False
Linux-6.8.0-51-generic-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
('Linux', '6.8.0-51-generic', '#52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024')
Python 3.12.3
Interface language: None
EXE path: /usr/bin/python3.12
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
calibre 7.6  embedded-python: False
Linux-6.8.0-51-generic-x86_64-with-glibc2.39 Linux ('64bit', 'ELF')
('Linux', '6.8.0-51-generic', '#52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024')
Python 3.12.3
Interface language: None
EXE path: /usr/bin/python3.12
Successfully initialized third party plugins: DeDRM (10, 0, 3) && Obok DeDRM (10, 0, 3)
QPA platform: wayland
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 102.04823529411765 x 102.66947368421053
[0.00] Starting up...
[0.01] Showing splash screen...
[0.09] splash screen shown
[0.09] Initializing db...
[0.23] db initialized
[0.23] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.1 obok::action_err.py - loading translations
[1.40] GUI main window shown
[1.43] main UI initialized...
[1.43] Hiding splash screen
[9.91] splash screen hidden
[9.91] Started up in 9.91 seconds with 1 books
Added a6750fdb-1728-4307-af68-cad12593d1ad to db in: 1.0
Added 1 books in 1.4 seconds
Added 94fffc87-2b24-4076-91cd-77a64b4f870a to db in: 0.7
Added 1 books in 1.2 seconds
```

Log when trying to open an imported file in Calibre reader:

```log
calibre, version 7.6.0
ERROR: Loading book failed: Failed to open the book at /home/fabio/Calibre Library/Unknown/94fffc87-2b24-4076-91cd-77a64b4f870a (7)/94fffc87-2b24-4076-91cd-77a64b4f870a - Unknown.lcpl. Click "Show details" for more info.

Failed to convert book: /home/fabio/Calibre Library/Unknown/94fffc87-2b24-4076-91cd-77a64b4f870a (7)/94fffc87-2b24-4076-91cd-77a64b4f870a - Unknown.lcpl with error:
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Traceback (most recent call last):
  File "/usr/bin/calibre-parallel", line 21, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 196, in main
    exec(sys.argv[-1])
  File "<string>", line 1, in <module>
  File "/usr/lib/calibre/calibre/srv/render_book.py", line 952, in viewer_main
    render_for_viewer(*args)
  File "/usr/lib/calibre/calibre/srv/render_book.py", line 943, in render_for_viewer
    return render(
           ^^^^^^^
  File "/usr/lib/calibre/calibre/srv/render_book.py", line 920, in render
    book_fmt, opfpath, input_fmt = extract_book(pathtoebook, output_dir, log=default_log)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/ebooks/oeb/iterator/book.py", line 53, in extract_book
    plumber = Plumber(pathtoebook, tdir, log, view_kepub=view_kepub)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 755, in __init__
    raise ValueError('No plugin to handle input format: '+input_fmt)
ValueError: No plugin to handle input format: lcpl
```

**Comment by ElleKayEm** [comment]
No longer supported.  See #18.

**Comment by Fabio-cyber751** [comment]
Sorry: I have just found out in the changelog that this feature has been removed (it would be clearer if it was not possible to enter an LCPL passphrase, by the way).
