### ISSUE TITLE
DRM is not removed from adobe digital edition

### ISSUE THREAD

**Issue by stephan1827** [noDRM/DeDRM_tools#702]
### Question / bug report

I just opend a book from thalia with adobe digital edition but when I import the epub file the drm is not removed.

### Which version of Calibre are you running?

7.23

### Which version of the DeDRM plugin are you running?

10.0.9

### Log output

```ApplicationPaletteChange event ignored
Using calibre Qt style: True
calibre Fehlerdiagnoseprotokoll
calibre 7.8  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 19, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 19, 0) && KFX metadata reader (from KFX Input) (2, 19, 0) && From KFX (2, 19, 0) && KFX Input (2, 19, 0)
calibre 7.8  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: de
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (2, 19, 0) && DeDRM (10, 0, 9) && Package KFX (from KFX Input) (2, 19, 0) && KFX metadata reader (from KFX Input) (2, 19, 0) && From KFX (2, 19, 0) && KFX Input (2, 19, 0)
QPA platform: windows
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 92.16571428571429 x 92.25642857142857
[0.00] Starting up...
[0.03] Showing splash screen...
[0.22] splash screen shown
[0.22] Initializing db...
[0.22] db initialized
[0.22] Constructing main UI...
[1.75] GUI main window shown
[1.95] main UI initialized...
[1.95] Hiding splash screen
DeDRM v10.0.9: Trying to decrypt Drama Free-1.epub
DeDRM v10.0.9: Verifying zip archive integrity
DeDRM v10.0.9: Drama Free-1.epub is a secure Adobe Adept ePub for UUID be203eba-e077-44f7-b373-54ae209ea902
DeDRM v10.0.9: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.9: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 584, in ePubDecrypt
  File "C:\Users\stephan\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 314, in adeptkeys
  File "C:\Users\stephan\AppData\Roaming\calibre\plugins\DeDRM.zip\adobekey.py", line 294, in CryptUnprotectData
adobekey.ADEPTError: Failed to decrypt user key key (sic)
DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 658, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
[16.81] splash screen hidden
[16.81] Started up in 16.81 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\\_s\xed9\xc8\xacE\xee\xd8\xc7\x0c\x87p\x06\xf43\xda\xab\xdf\x07\x8a\x0c\xb7R2YV#\xde\xa8R', b'\\\\Mac\\Home\\Downloads\\Drama Free-1.epub']
Added Drama Free to db in: 0.0
Added 1 books in 0.8 seconds

```

**Comment by ElleKayEm** [comment]
If ADE used to download the book (and preferably authorized with your Adobe ID) is on the same machine and user as calibre/DeDRM, it should work.

If not you could try deauthorizing and reauthorizing ADE by deleting the registry key.  Scroll down to "Troubleshooting reauthorization and deauthorization issues on Windows" on this page: https://helpx.adobe.com/digital-editions/kb/activation-errors-adobe-digital-editions.html

Or some have had luck using the DeACSM calibre plugin instead of ADE to download their books.  (I have no experience with this myself.)
