### ISSUE TITLE
kindlekey.py won't run, can't find Cryptodome even though installed

### ISSUE THREAD

**Issue by Ultrabenosaurus** [noDRM/DeDRM_tools#71]
I made the switch from Windows 10 to Manjaro several months ago and have been using Calibre with my existing library of books just fine. I recently decided to install DeDRM and backup my newer ebooks only to run into no end of problems. 

I can't get Kindle for PC 1.24.3 or 1.17.x to install under WINE (the former crashes after the installer runs and the latter launches but has no Internet connectivity. I have successfully installed KfPC 1.24.3 in a Windows 10 VM, downloaded the books, transfered to Manjaro, dragged into Calibre... only for the DRM to still be in place. 

Now I think I need to extract a key from KfPC under Windows to import into the DeDRM plugin customisation panel on Manjaro. Running the original `kindlekey.pyw` from apprencticeharper's repo apparently does nothing, no output at all. Running `kindlekey.py` from this repo gives me an error about no Crypto(dome) module. 

As you can see from the below cmd output, I have installed `pycryptodome` but the script still errors due to apparently finding neither the Crypto or Cryptodome modules. 

```
Microsoft Windows [Version 10.0.19044.1645]
(c) Microsoft Corporation. All rights reserved.

C:\Users\naebe>pip install pycryptodome
Requirement already satisfied: pycryptodome in c:\users\naebe\appdata\local\programs\python\python310\lib\site-packages (3.14.1)

C:\Users\naebe>cd Downloads

C:\Users\naebe\Downloads>kindlekey.py
Traceback (most recent call last):
  File "C:\Users\naebe\Downloads\kindlekey.py", line 49, in <module>
    from Cryptodome.Cipher import AES
ModuleNotFoundError: No module named 'Cryptodome'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\naebe\Downloads\kindlekey.py", line 53, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

C:\Users\naebe\Downloads>
```

I tried instaling pycrypto instead, which failed without wheels. I installed wheels then it failed due to lacking Microsoft C++ 14. I installed Microsoft C++ 14 via the recommended Build Tools link, and it still fails due to this: 

```
error: command'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

I have no experience using, working with, or debugging Python (or Microsoft C++ 14 build tools) so I have no idea where to go next.

**Comment by ElleKayEm** [comment]
Easiest workaround (in my opinion) is to temporarily install Windows calibre with DeDRM in your VM.  Then it just uses calibre's embedded Python.  Once you have your keys there, you can save them and import them into your Linux calibre/DeDRM.

**Comment by Ultrabenosaurus** [comment]
Ah, thanks for the advice, I didn't know you could export the key from within Calibre itself. I ended up installing Calibre in the VM, using it to strip the DRM, then copying the books out to my real Calibre library on Manjaro. 

I have now transferred the keys (there were 2, not sure if that's normal?) and will try stripping the DRM in Manjaro next time.

**Comment by Liamwil3** [comment]
In my experience, you can install the kindle pc 1.16 and 1.17 under wine. The problem with the connection is documented somewhere in winehp bugs, ubuntu and linux mint forums. The problem is that a certificate is disabled, it is just to copy the certificate in /etc/ssl. For decrypting I install calibre under wine and install the plugin, the key obtained by the calibre under wine does not work in the calibre under manjaro in my case. You can get the certificate here https://bugs.winehq.org/show_bug.cgi?id=50471
