### ISSUE TITLE
Problem decrypting pdf

### ISSUE THREAD

**Issue by github-nic** [noDRM/DeDRM_tools#73]
Hi, 
I'm not able to decrypt a certain pdf, here's the log:
`calibre Fehlerdiagnoseprotokoll
calibre 5.41 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (10, 0, 2)
calibre 5.41 Portable embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: de
Successfully initialized third party plugins: DeDRM (10, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 106.38743455497382 x 106.82242990654204
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[3.52] splash screen shown
[3.52] Initializing db...
[3.83] db initialized
[3.83] Constructing main UI...
[9.14] main UI initialized...
[9.14] Hiding splash screen
Starting QuickView
DeDRM v10.0.2: Trying to decrypt DM RT N DN.pdf
[53.64] splash screen hidden
[53.64] Started up in 53.64 seconds with 59 books
DeDRM v10.0.2: DM RT N DN.pdf is a PDF ebook with encryption EBX_HANDLER
DeDRM v10.0.2: DM RT N DN.pdf is a PDF ebook (EBX) for UUID bc139deb-dc41-484d-b8cd-b0c25c93c7bf
DeDRM v10.0.2: Trying encryption key default_key
error writing pdf: 'utf-8' codec can't decode byte 0xfc in position 2: invalid start byte
Traceback (most recent call last):
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 2276, in decryptBook
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 2104, in dump
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 1831, in getobj
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 693, in nextobject
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 578, in nexttoken
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 439, in parse_literal
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 265, in intern
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 224, in __init__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 2: invalid start byte
DeDRM v10.0.2: Failed to decrypt with key default_key after 9.2 seconds
DeDRM v10.0.2: Looking for new default Adobe Digital Editions Keys after 9.2 seconds
Found 1 keys
DeDRM v10.0.2: Trying a new default key
error writing pdf: 'utf-8' codec can't decode byte 0xfc in position 2: invalid start byte
Traceback (most recent call last):
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 2276, in decryptBook
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 2104, in dump
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 1831, in getobj
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 693, in nextobject
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 578, in nexttoken
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 439, in parse_literal
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 265, in intern
  File "C:\PortableApps\Calibre Portable\Calibre Settings\plugins\DeDRM.zip\ineptpdf.py", line 224, in __init__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 2: invalid start byte
DeDRM v10.0.2: Failed to decrypt with new default key after 20.4 seconds
DeDRM v10.0.2: Finished after 20.4 seconds
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre\customize\builtins.py", line 324, in get_metadata
  File "calibre\ebooks\metadata\pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler

pdfinfo eAdded DM RT N DN to db in: 2.7
Added 1 books in 27.3 seconds
`
With other pdfs it works like a charm. Thx in advance.

**Comment by ElleKayEm** [comment]
Maybe the "hardened" Adobe DRM?  Have you tried the current code here?  Including the stuff merged from Pull Request 48?  (From after the last release 10.0.2.)

**Comment by github-nic** [comment]
Yes, I tried [ DeDRM_tools_beta_2022-03-18.zip](https://github.com/noDRM/DeDRM_tools/files/8306286/DeDRM_tools_beta_2022-03-18.zip).

**Comment by ElleKayEm** [comment]
This is in the log several times:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 2: invalid start byte

I'm guessing that's the problem, but I don't know how to resolve it.

**Comment by noDRM** [comment]
This looks to me like a corrupted PDF; though I do not know that much about the actual PDF internals. Could be an error in the plugin's PDF parsing code, too ...

Can you try the latest 4.x Calibre version and see if that works? Maybe that code never worked properly in Python 3 since the plugin was ported from Python 2.

**Comment by MPeli** [comment]
I am having the same problem

- Python 3.12.0
- Windows 10
- calibre-64bit-6.28.1.msi

The file I was trying to open [CAS-PUBLIC-TEST.PDF](https://github.com/noDRM/DeDRM_tools/files/12873842/CAS-PUBLIC-TEST.PDF)

> DeDRM v10.0.3: Trying to decrypt edxq8ac9.pdf
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 914, in PDFDecrypt
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 2301, in getPDFencryptionType
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1871, in __init__
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1201, in set_parser
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1998, in read_xref
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1989, in read_xref_from
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1962, in read_xref_from
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 589, in nexttoken
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 507, in parse_keyword
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 276, in intern
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 254, in __init__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 1: invalid start byte
Conversion options changed from defaults:
  pdf_serif_family: 'Arial'
  pdf_mono_family: 'Courier New'
  verbose: 2
  pdf_sans_family: 'Arial'
  read_metadata_from_opf: 'C:\\Users\\MyUser\\AppData\\Local\\Temp\\calibre_788_tr9a\\982vp0k9.opf'
  output_profile: 'generic_eink'
Resolved conversion options
calibre version: 6.28.1
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'custom_size': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x000001F4201CF6A0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'new_pdf_engine': False,
 'no_chapters_in_toc': False,
 'no_images': False,
 'no_inline_navbars': False,
 'output_profile': <calibre.customize.profiles.GenericEink object at 0x000001F4201CDA50>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'paper_size': 'letter',
 'pdf_add_toc': False,
 'pdf_default_font_size': 20,
 'pdf_footer_template': None,
 'pdf_header_template': None,
 'pdf_hyphenate': False,
 'pdf_mark_links': False,
 'pdf_mono_family': 'Courier New',
 'pdf_mono_font_size': 16,
 'pdf_no_cover': False,
 'pdf_odd_even_offset': 0.0,
 'pdf_page_margin_bottom': 72.0,
 'pdf_page_margin_left': 72.0,
 'pdf_page_margin_right': 72.0,
 'pdf_page_margin_top': 72.0,
 'pdf_page_number_map': None,
 'pdf_page_numbers': False,
 'pdf_sans_family': 'Arial',
 'pdf_serif_family': 'Arial',
 'pdf_standard_font': 'serif',
 'pdf_use_document_margins': False,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\MyUser\\AppData\\Local\\Temp\\calibre_788_tr9a\\982vp0k9.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'uncompressed_pdf': False,
 'unit': 'inch',
 'unsmarten_punctuation': False,
 'unwrap_factor': 0.45,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'use_profile_size': False,
 'verbose': 2}
DeDRM v10.0.3: Trying to decrypt edxq8ac9.pdf
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 187, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1063, in run
  File "calibre_plugins.dedrm.__init__", line 914, in PDFDecrypt
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 2301, in getPDFencryptionType
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1871, in __init__
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1201, in set_parser
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1998, in read_xref
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1989, in read_xref_from
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 1962, in read_xref_from
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 589, in nexttoken
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 507, in parse_keyword
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 276, in intern
  File "C:\Users\MyUser\AppData\Roaming\calibre\plugins\DeDRM.zip\ineptpdf.py", line 254, in __init__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 1: invalid start byte
InputFormatPlugin: PDF Input running
on C:\Users\MyUser\AppData\Local\Temp\calibre_788_tr9a\edxq8ac9.pdf
Converting file to html...
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\pdf_input.py", line 51, in convert
  File "calibre\ebooks\pdf\pdftohtml.py", line 83, in pdftohtml
calibre.ebooks.ConversionError: pdftohtml failed with return code: 1
Syntax Error: Couldn't find the 'FOPN_foweb' security handler

**Comment by ElleKayEm** [comment]
@MPeli 
FileOpen encryption?  The plugin does not support this. But there is a [python script](https://github.com/noDRM/DeDRM_tools/tree/master/Other_Tools/Tetrachroma_FileOpen_ineptpdf) which works with it. Some discussion of it here: https://github.com/noDRM/DeDRM_tools/issues/157

(I don't have any experience using that myself.)

**Comment by MPeli** [comment]
@ElleKayEm, thank you. The script works fine.

**Comment by ElleKayEm** [comment]
@MPeli Thanks for reporting back.
