### ISSUE TITLE
No DeDRM_plugin.zip file in DeDRM_tools-master.zip archive - error "No module named '__version'"

### ISSUE THREAD

**Issue by flaxton** [noDRM/DeDRM_tools#78]
OK, it's been a while since I tried DeDRM for Kindle. I saw this forked project that is being maintained, great!

I followed the instructions, downloaded DeDRM_tools-master.zip, unzipped it, went into the DeDRM_tools-master folder, and there is no DeDRM_plugin.zip in there.

No problem, I manually zipped everything (including __version.py and other files starting with __) and tried installing that as a plugin in Calibre.

Here's the error it throws. And yes, I verified that __version.py is in the zip archive I created. So is it looking for __version instead of __version.py? No, I copied __version.py to __version, zipped it again and still get this error:

calibre, version 5.42.0
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named '__version'

calibre 5.42  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && Package KFX (from KFX Input) (1, 48, 0) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 326, in add_plugin
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 292, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 191, in exec_module
  File "calibre_plugins.dedrm.__init__", line 98, in <module>
    import __version
ModuleNotFoundError: No module named '__version'

Any ideas?

I'm a fairly inexperienced Python user, although I have written some Python programs (that worked lol).

Thanks!

Fred

**Comment by keithstellyes** [comment]
I ran into this exact issue, attempting to load DeDRM_plugin.zip and still had it. As a workaround, see my comment: https://github.com/noDRM/DeDRM_tools/issues/329#issuecomment-1912842807
