### ISSUE TITLE
KFX ebook DRM removal failed

### ISSUE THREAD

**Issue by pylongaretti** [noDRM/DeDRM_tools#80]
### Question / bug report

Hi everyone
I just bought "Limits and Beyond" from Amazon in Kindle format. The Amazon code for the book is B09YM414TF_EBOK. The book was issued very recently (05/09/2022).

I am using Calibre 5.42 with DeDRM 10.0.2

The DRM removal failed but I guess this is because the book is very recent. I wish to convert it to epub for my own use (in particular reformatting the book for better appearance as usually ebooks are poorly designed). Also, as a matter of policy, I object to the fact that I do not own a book I have paid for.

Thanks in advance.

### Which version of Calibre are you running?

5.42

### Which version of the DeDRM plugin are you running?

v10.0.2

### Log output

```log
EpubMerge: DEBUG: 2022-05-19 17:22:47,165: calibre_plugins.epubmerge.epubmerge_plugin(155): macmenuhack file_path:C:\Users\pylsk\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
calibre Journal de débogage
calibre 5.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 48, 0) && EpubMerge (2, 13, 0) && Hyphenate This! (0, 1, 3) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0) && KePub Input (3, 4, 3) && KindleUnpack - The Plugin (0, 83, 1) && Kobo Utilities (2, 16, 0) && Modify ePub (1, 7, 3) && Obok DeDRM (7, 2, 1)
calibre 5.42 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: fr
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 48, 0) && EpubMerge (2, 13, 0) && Hyphenate This! (0, 1, 3) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0) && KePub Input (3, 4, 3) && KindleUnpack - The Plugin (0, 83, 1) && Kobo Utilities (2, 16, 0) && Modify ePub (1, 7, 3) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 157.8252427184466 x 158.5664739884393
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.48] splash screen shown
[0.48] Initializing db...
[0.55] db initialized
[0.55] Constructing main UI...
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
DEBUG:    0.6 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    0.6 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
DEBUG:    0.6 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Pilote : KoboTouch'
DEBUG:    0.6 device_driver_name - could not load extended driver. Exception= No module named 'calibre_plugins.kobotouch_extended'
[1.36] main UI initialized...
[1.36] Hiding splash screen
Starting QuickView
Gather KFX-ZIP (from KFX Input) 1.48.0: Importing C:\Users\pylsk\Desktop\B09YM414TF_EBOK.azw
Gather KFX-ZIP (from KFX Input): Cannot locate some files needed for the book. KFX files must remain in their original folder structure for successful import. 
Gather KFX-ZIP (from KFX Input): Gathered 1 file(s) as C:\Users\pylsk\AppData\Local\Temp\calibre_n8ld1g1g\f9vkzqnl.kfx-zip
DeDRM v10.0.2: Trying to decrypt f9vkzqnl.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: f9vkzqnl
Found 2 keys to try after 0.1 seconds
DeDRM v10.0.2: Failed to decrypt with error: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher
DeDRM v10.0.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\pylsk\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\pylsk\AppData\Local\Amazon\Kindle\storage\.kinf2018
[12.42] splash screen hidden
[12.42] Started up in 12.42 seconds with 1672 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xca\xe1!}Q\x96>\x12\xf0\xd7\x12\xac\xd2}\xf4\x1f\xe0\xca\xb0\x15\xbb\xe8\x1b\xbfGW\x19\t\xc5\x8f-\xc8', b'C:\\Users\\pylsk\\Desktop\\B09YM414TF_EBOK.azw']
Decrypted key file using IDString '4001609881' and UserName 'pyl'
DeDRM v10.0.2: Found 1 new key
Decrypting KFX-ZIP ebook: f9vkzqnl
Got DSN key from database default_key_1
Found 1 keys to try after 2.4 seconds
DeDRM v10.0.2: Ultimately failed to decrypt after 2.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.48.0: Packaging C:\Users\pylsk\AppData\Local\Temp\calibre_n8ld1g1g\f9vkzqnl.kfx-zip
Processing container: B09YM414TF_EBOK.azw
KFX metadata reader (from KFX Input) activated for C:\Users\pylsk\AppData\Local\Temp\calibre_n8ld1g1g\lxqfvtei_add_books\0\B09YM414TF_EBOK.kfx-zip
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 66, in decrypt_voucher
Exception: The .kfx-zip archive contains an encrypted DRMION file without a DRM voucher

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 2.4 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 83, in convert_to_single_kfx
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B09YM414TF_EBOK.azw has DRM and cannot be converted
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 432, in get_file_type_metadata
  File "calibre_plugins.kfx_input.metadata_reader", line 28, in get_metadata
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 148, in get_metadata
Exception: Failed to locate a KFX container Added B09YM414TF EBOK to db in: 0.2
Added 1 books in 3.1 seconds
```

**Comment by noDRM** [comment]
KFX files are not really supported by this plugin. KFX is Amazon's newest DRM, and every time it gets cracked, they're updating it within days so the common DRM removal methods do not work. 

You'll need to acquire a non-KFX file for this book to remove the DRM. Either by using an old version of Kindle 4 PC (1.17, I believe), or by downloading the book file from the Amazon website for USB transfer. These usually give you another file type that can have the DRM removed.

**Comment by ElleKayEm** [comment]
See this post for details on methods for getting Amazon files you can decrypt:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by pylongaretti** [comment]
Thanks a lot. I am impressed with the speed of your answer. Preventing 
KFX in Kindle for PC 1.31 worked perfectly well.

Best
PYL

Le 19/05/2022 à 17:45, ElleKayEm a écrit :

**Comment by ElleKayEm** [comment]
If you're all set, you can close the issue.

**Comment by pylongaretti** [comment]
Thanks again for your fast and efficient help
