### ISSUE TITLE
DeDRM fails to run python3 to extract Kindle key under Wine

### ISSUE THREAD

**Issue by auspex** [noDRM/DeDRM_tools#81]
### Question / bug report

I expect my problem is that I haven't properly installed Python3 in my Wine but I'm at a loss to figure out what I need.

Despite error messages saying that python3 is _not_ found, eg:
```
DeDRM v10.0.2: Unable to find python3 executable in WINEPREFIX="/home/derek/.kindleUS"
```
it actually is found, but fails with the error:
```
Fatal Python error: init_sys_streams: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle
```

Note, it has the correct WINEPREFIX, and python is found in the PATH:
```
$ env WINEPREFIX="/home/derek/.kindleUS" wine python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
I've tried with both the 32-bit and 64-bit pythons from https://www.python.org/ftp/python/3.7.9/python-3.7.9.exe and https://www.python.org/ftp/python/3.7.9/python-3.7.9-amd64.exe, installed with:
```
env WINEPREFIX="/home/derek/.kindleUS" wine /tmp/python-3.7.9*.exe 
```

### Which version of Calibre are you running?

5.40

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1.17

### Log output

```log
calibre 5.40  embedded-python: True is64bit: True
Linux-5.13.0-40-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.13.0-40-generic', '#45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2) && Annotations (1, 17, 0) && Count Pages (1, 11, 2) && EpubMerge (2, 12, 0) && EpubSplit (3, 2, 0) && Extract ISBN (1, 5, 0) && Find Duplicates (1, 8, 5) && Goodreads (1, 5, 3) && Goodreads More Tags (1, 2, 1) && Goodreads Sync (1, 15, 1) && KindleUnpack - The Plugin (0, 83, 1) && Kobo Books (1, 8, 3) && Kobo Utilities (2, 15, 1) && KoboTouchExtended (3, 5, 4) && Overdrive Link (2, 50, 0) && Reading List (1, 8, 0) && SmartEject (2, 4, 0) && Sony Utilities (0, 7, 3)
Not controlling automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.18934911242603 x 96.25263157894737
physicalDpi: 81.58594730238394 x 82.13173652694611
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.12] splash screen shown
[0.12] Initializing db...
[0.47] db initialized
[0.47] Constructing main UI...
DEBUG:    0.0 Annotations plugin: Error loading libiMobileDevice. This hasn't worked for a while, and is blacklisted in calibre v3.
DEBUG:    0.0 Annotations plugin: Error is:  No module named 'calibre.devices.idevice'
DEBUG:    0.0 Annotations::reader_app_support.py - loading translations
DEBUG:    0.0 Annotations::common_utils.py - loading translations
DEBUG:    0.1 Annotations::appearance.py - loading translations
DEBUG:    0.1 Annotations::config.py - loading translations
DEBUG:    0.1 Annotations::annotated_books.py - loading translations
DEBUG:    0.1 Annotations::action.py - loading translations
DEBUG:    0.0 Goodreads Sync::dialogs.py - loading translations
DEBUG:    0.0 GoodreadsSync::action.py - loading translations
DEBUG:    0.0 Kobo Utilities Configuration - CreateNewCustomColumn is supported
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    0.0 KoboUtilites::dialogs.py - loading translations
DEBUG:    0.0 KoboUtilites::action.py - loading translations
DEBUG:    1.3  ~~~~~~~~~~~~~~~~~~~~~~ Annotations plugin 1.17.0 (linux) ~~~~~~~~~~~~~~~~~~~~~~~
DEBUG:    1.3 AnnotationsAction:genesis(ERROR) Error loading library libiMobileDevice: name 'libiMobileDevice' is not defined
DEBUG:    1.3 AnnotationsAction:init_options(disable_caching: False) 
DEBUG:    1.3 AnnotationsDB:connect(db_version: 1) 
DEBUG:    1.3 AnnotationsAction:load_dynamic_reader_classes() 
DEBUG:    1.3   loading built-in class 'BooxReaderApp'
DEBUG:    1.3   loading built-in class 'GoodReader'
DEBUG:    1.3   loading built-in class 'Kindle'
DEBUG:    1.3   loading built-in class 'KoboTouch'
DEBUG:    1.3   loading built-in class 'ParseKindleMyClippingsTxt'
DEBUG:    1.4   loading built-in class 'ParseTolinoNotesTxt'
DEBUG:    1.4   loading built-in class 'PocketBook'
DEBUG:    1.4   loading built-in class 'Sony'
DEBUG:    1.4   loading built-in class 'Tolino'
DEBUG:    1.4 AnnotationsAction:inflate_dialog_resources() 
DEBUG:    2.4 HttpHelper::__init__: proxy=None
DEBUG:    2.2 No Kobo Touch, Glo or Mini appears to be connected
DEBUG:    2.2 rebuild_menus - self.supports_ratings=None, self.supports_tiles=None
DEBUG:    2.2 KoboUtilities:set_toolbar_button_tooltip - start: text='None'
DEBUG:    2.2 KoboUtilities:set_toolbar_button_tooltip - setting to text='Utilities to use with Kobo ereaders

Driver: KoboTouchExtended'
[3.64] main UI initialized...
[3.64] Hiding splash screen
Starting QuickView
DeDRM v10.0.2: Trying to decrypt B07WZGNLBV_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Maker Messiah: A Near Future Novel
Found 0 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.1 seconds
[8.37] splash screen hidden
[8.37] Started up in 8.37 seconds with 3634 books
['kdialog', '--title', 'Select books', '--desktopfile', 'calibre-gui', '--attach', '56623127', '--multiple', '--separate-output', '--getopenfilename', '/home/derek/Downloads/Book Downloads/My Kindle Content', 'Books (*.lrf *.rtf *.lit *.txt *.txtz *.text *.htm *.xhtm *.html *.htmlz *.xhtml *.pdf *.pdb *.updb *.pdr *.prc *.mobi *.azw *.doc *.epub *.fb2 *.fbz *.djv *.djvu *.lrx *.cbr *.cb7 *.cbz *.cbc *.oebzip *.rb *.imp *.odt *.chm *.tpz *.azw1 *.pml *.pmlz *.mbp *.tan *.snb *.xps *.oxps *.azw4 *.book *.zbf *.pobi *.docx *.docm *.md *.textile *.markdown *.ibook *.ibooks *.iba *.azw3 *.ps *.kepub *.kfx *.kpf)\nEPUB books (*.epub *.kepub)\nKindle books (*.mobi *.prc *.azw *.azw3 *.kfx *.tpz *.azw1 *.azw4)\nPDF books (*.pdf *.azw4)\nHTML books (*.htm *.html *.xhtm *.xhtml)\nLIT books (*.lit)\nText books (*.txt *.text *.rtf *.md *.markdown *.textile *.txtz)\nComics (*.cbz *.cbr *.cbc)\nArchives (*.zip *.rar)\nWordprocessor files (*.odt *.doc *.docx)\nAll files (*)']
Fatal Python error: init_sys_streams: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle

Current thread 0x000000f8 (most recent call first):
0024:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0031F558
0100:err:module:process_init L"C:\\windows\\system32\\python3.exe" not found
DeDRM v10.0.2: wine python3.exe does not exist
Fatal Python error: init_sys_streams: can't initialize sys standard streams
OSError: [WinError 6] Invalid handle

Current thread 0x00000108 (most recent call first):
wine: cannot find L"C:\\Python27\\python.exe"
DeDRM v10.0.2: wine C:\Python27\python.exe does not exist
DeDRM v10.0.2: Unable to find python3 executable in WINEPREFIX="/home/derek/.kindleUS"
DeDRM v10.0.2: Ultimately failed to decrypt after 2.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 2.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Integration status: True
Added Maker Messiah: A Near Future Novel to db in: 1.6
Added 1 books in 5.0 seconds
Worker Launch took: 0.08 seconds
```

**Comment by ElleKayEm** [comment]
A workaround is to (at least remporarily) install Windows calibre with DeDRM under Wine.  Once you retrieved the key, save it, and import it into the Linux calibre DeDRM.

**Comment by auspex** [comment]
Thanks. I wasn't even aware that calibre would run in Wine.

So, what's the problem that needs to be worked around? Is it with DeDRM or python itself?

**Comment by ElleKayEm** [comment]
I don't know.  I've just often seen this issue here with retrieving the keys on Linux setups.  With Windows calibre, DeDRM uses calibre's embedded python to run those scripts.  Once you have the keys imported, the actual DRM removal should be fine though.

**Comment by auspex** [comment]
> A workaround is to (at least remporarily) install Windows calibre with DeDRM under Wine. Once you retrieved the key, save it, and import it into the Linux calibre DeDRM.

Easier said than done. I can't get both KindleForPc and Calibre to install in the same wineprefix... 

Any KindleForPc installation should work, though, right? I have a Windows machine I can use to get the keys.

**Comment by j-howell** [comment]
> Any KindleForPc installation should work, though, right? I have a Windows machine I can use to get the keys.

Each installation of Kindle for PC uses its own unique key even if registered to the same Amazon account.

**Comment by ElleKayEm** [comment]
Yes, as long as books and key are from the same Kindle for PC installation.  You might be able to run the kindlekey.py script and retrieve the key that way.

**Comment by auspex** [comment]
Then, no... Calibre will not install into the same WINEPREFIX as any KindleForPc. I just get "calibre Setup Wizard ended prematurely", and no opportunity to see _why_ (it puts a link on my desktop, but there's no calibre executable in the Wineprefix).

And attempting to run kindlekey.py is equally unhelpful:
```
  File "/tmp/kindlekey.pyw", line 295
    raise DecryptNotBlockAlignedError, 'Data not block aligned on decrypt'
```

**Comment by ElleKayEm** [comment]
Hmm, this used to be workaround.  Possibly the Python 2 versions?  The last ones were calibre 4.23 and DeDRM 6.8.1.

The previous maintainer of the DeDRM project (Apprentice Harper) had basicly dropped Linux support.  But perhaps @noDRM or someone else can look at getting things working correctly for Linux users.

**Comment by auspex** [comment]
I'm getting somewhere... Installed calibre 3.30 since it's the only version I could see in the WineHQ app database, and that is working fine.

At least now I know why the current calibre version won't install. I set the Windows version to 8.1 in `winecfg`, but the log is saying it's Windows 7. It's no longer complaining about keys at all. It doesn't look like it ever gets to them:
```
calibre Debug log
calibre 3.30  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Uniprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2)
calibre 3.30  embedded-python: True is64bit: False
Windows-7-6.1.7601-SP1 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '7', '6.1.7601')
Python 2.7.12+
Windows: ('7', '6.1.7601', 'SP1', u'Uniprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.047267356 x 95.9160839161
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.15] splash screen shown
[0.15] Initializing db...
[0.17] db initialized
[0.17] Constructing main UI...
[1.91] main UI initialized...
[1.91] Hiding splash screen
[4.53] splash screen hidden
[4.53] Started up in 4.53 seconds with 0 books
stdout+stderr from file dialog helper: ['', '']
piped data from file dialog helper: ['`\x96\x8f}\x9a\x087M\xcb\xe5\x85\xd2\xfc1\x9a\xc6\x84\x94S,\x9aW\xb2\t\xb4K\xd0?\xba\xc1\xe0/', 'C:\\users\\derek\\My Documents\\My Kindle Content\\B00TQEM1BW_EBOK.azw']
DeDRM v10.0.2: Trying to decrypt B00TQEM1BW_EBOK.azw
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "site-packages\calibre\customize\ui.py", line 171, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 782, in KindleMobiDecrypt
  File "site-packages\calibre\customize\zipplugin.py", line 183, in load_module
  File "calibre_plugins.dedrm.k4mobidedrm", line 72, in <module>
ImportError: No module named entities
Added Thousand Shrine Warrior (The Tomoe Gozen Saga) to db in: 2.6
Added 1 books in 4.9 seconds
Worker Launch took: 0.455000162125
```

**Comment by ElleKayEm** [comment]
With older calibre, you might want to try the last python 2 version of DeDRM -- 6.8.1.  While 10.0.2 is intended to work with both python 2 and 3 versions of calibre, I don't think the python 2 side has been tested.

**Comment by auspex** [comment]
Success!

1. Use `winetricks` to create a clean, new, 32-bit prefix (I don't know if it's necessary to be 32-bit, but that worked for me)
2. Then install the "kindle" application using winetricks (that will be 1.16.0)
3. Download the calibre 3.30 Windows msi from https://download.calibre-ebook.com/3.30.0/calibre-3.30.0.msi
4. Install it: it's easiest to use `winetricks` again, and open `explorer`
5. Download DeDRM.zip from https://github.com/apprenticeharper/DeDRM_tools/releases/download/v6.8.1/DeDRM_tools_6.8.1.zip and install as one usually would.
6. Export the key...

**Comment by ElleKayEm** [comment]
Excellent!  Thanks for reporting back on the details.

**Comment by auspex** [comment]
Well… Partial success. While the books downloaded in Wine can be loaded and DeDRM'd with Calibre in Wine, exporting the key and importing to the native calibre was not successful.

**Comment by auspex** [comment]
I've imported a key, and it didn't work, but DeDRM is now reporting it's found keys, which it didn't before, so I can't see how that can possibly happen if I actually exported the key I thought I did! At this point it looks like probable user error, but I likely won't get back to it until the weekend.

**Comment by derek-mba** [comment]
I left this much too long...

I just tried importing a book to the native Linux calibre and it _has_ been decrypted. Which suggests that maybe I just needed to restart Calibre after importing the DRM key. Sorry!

**Comment by auspex** [comment]
oops. That was me, not realizing I was logged in from my work account (while still wondering why there was no "Close" button!)

**Comment by ElleKayEm** [comment]
Thanks for coming back and wrapping this up.
