### ISSUE TITLE
Problems with decrypting .azw (On PC)

### ISSUE THREAD

**Issue by 81milwir** [noDRM/DeDRM_tools#82]
### Question / bug report

I'm trying to run DeDRM on Kindle .azw files, but it isn't working - it worked about a month ago, but all the recent books I've downloaded refuse to convert. 

### Which version of Calibre are you running?

5.42

### Which version of the DeDRM plugin are you running?

10.0.2

### Log output

```log
calibre Debug log
calibre 5.43 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 48, 0) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0)
calibre 5.43 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.8.5
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 48, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 48, 0) && KFX metadata reader (from KFX Input) (1, 48, 0) && KFX Input (1, 48, 0)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 89.6470588235294 x 90.53465346534654
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.24] splash screen shown
[0.24] Initializing db...
[0.24] db initialized
[0.24] Constructing main UI...
[0.62] main UI initialized...
[0.62] Hiding splash screen
Starting QuickView
DeDRM v10.0.2: Trying to decrypt A Beautifully Foolish Endeavor (The Carls).azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Beautifully Foolish Endeavor (The Carls)
Found 2 keys to try after 0.0 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Gaming Computer POG\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Gaming Computer POG\AppData\Local\Amazon\Kindle\storage\.kinf2018
[84.58] splash screen hidden
[84.58] Started up in 84.58 seconds with 49 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b';`F\x8a\x8d\xfd\x89s\xcb\xd3\xc8O\xa9\x88U\xd7\xe0V\xafC\xf3\xb5\x83|\x04u\x0fW\xd0zq>', b'C:\\Users\\Gaming Computer POG\\Downloads\\A Beautifully Foolish Endeavor (The Carls).azw3']
Decrypted key file using IDString '674347999' and UserName 'Gaming Computer POG'
DeDRM v10.0.2: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: A Beautifully Foolish Endeavor (The Carls)
Got DSN key from database default_key_1
Found 4 keys to try after 2.0 seconds
Crypto Type is: 2
DeDRM v10.0.2: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 2.0 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/Added A Beautifully Foolish Endeavor (The Carls) to db in: 0.1
Added 1 books in 2.4 seconds
```

**Comment by ElleKayEm** [comment]
If you're downloading from the website, make sure you've chosen an E-ink Kindle (not a Fire) for the device.  And make sure you have that Kindle's serial number entered correctly into DeDRM's customization.

**Comment by chrisrm9208** [comment]
I'm having the exact same issue with the same setup:
calibre Debug log
calibre 5.43  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 49, 0) && Find Duplicates (1, 9, 5) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 62, 0) && KFX Output (1, 62, 0) && Obok DeDRM (7, 2, 1)
calibre 5.43  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 49, 0) && Find Duplicates (1, 9, 5) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Set KFX metadata (from KFX Output) (1, 62, 0) && KFX Output (1, 62, 0) && Obok DeDRM (7, 2, 1)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 106.5967213114754 x 119.52941176470588
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.83] splash screen shown
[0.83] Initializing db...
[1.00] db initialized
[1.00] Constructing main UI...
DEBUG:    0.0 obok::utilities.py - loading translations
DEBUG:    0.0 obok::dialogs.py - loading translations
DEBUG:    0.0 obok::config.py - loading translations
DEBUG:    0.0 obok::action_err.py - loading translations
[2.53] main UI initialized...
[2.53] Hiding splash screen
Starting QuickView
DeDRM v10.0.2: Trying to decrypt 99%.azw3
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 99%
Found 8 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 8 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.2 seconds
searching for kinfoFiles in C:\Users\chrismitchell\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\chrismitchell\AppData\Local\Amazon\Kindle\storage\.kinf2018
[7.11] splash screen hidden
[7.11] Started up in 7.11 seconds with 1552 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\n\x81\xb1.\xeb\xf3M\x83\xd0\xd73\xc9\xfd>Mj;\xee\xd5\x94W\x98\xce\xc7CK\xf8\xab\xa8\xb6\xfcD', b'C:\\Users\\chrismitchell\\Downloads\\99%.azw3']
Decrypted key file using IDString '3534028031' and UserName 'chrismitchell'
DeDRM v10.0.2: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: 99%
Got DSN key from database default_key_1
Found 4 keys to try after 5.2 seconds
Crypto Type is: 2
DeDRM v10.0.2: Ultimately failed to decrypt after 5.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 8 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 5.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/Added 0 books in 6.0 seconds

**Comment by ElleKayEm** [comment]
Same answer then.  Make sure you have chosen an E-ink Kindle when downloading.  Make sure that Kindle's serial number is entered correctly into DeDRM's customization before importing the book.

**Comment by chrisrm9208** [comment]
Regrettably, this is a change from a working system to this error, and my purchasing habits for Kindle ebooks hasn't changed. The serial number hasn't changed on either Kindle, and they're still in the DeDRM plugin correctly. Of course, this is KFX, so something has probably been changed by Amazon; is there any other info I could provide that might help?

**Comment by ElleKayEm** [comment]
I don't see KFX in this log.  You won't get that from "download & transfer via usb".

**Comment by chrisrm9208** [comment]
Ah, I thought that 'Kindle Format 8' was KFX... My mistake. Nonetheless, the question still stands; how can I provide extra info to help debug this format?

**Comment by ElleKayEm** [comment]
Kindle Format 8 is the older format with the extension azw3.  Should work fine if you chose the correct device when downloading and its serial number is in DeDRM.  The only error I'm seeing here is that none of the keys work for this book.

**Comment by KarellenX** [comment]
I had a similar issue with a particular book. Just a single book refused to convert, but the other books I tried converting immediately before and after had no issue. And I have had no issue since that book. I think (with no proof to provide) that some kindle books are problematic.

https://github.com/noDRM/DeDRM_tools/issues/66

**Comment by ElleKayEm** [comment]
@KarellenX The issue in that case was KFX format.  Not the issue here.

**Comment by j-howell** [comment]
Something is odd here. The file name isn’t what it would expect from Download & Transfer. Could you share a link to the Amazon listing for the book in question?

**Comment by KarellenX** [comment]
@j-howell Who, me or the OP?

**Comment by 81milwir** [comment]
https://www.amazon.com/Beautifully-Foolish-Endeavor-Novel-Carls/dp/152474347X

**Comment by chrisrm9208** [comment]
The title I have an  isse with is this: https://www.amazon.co.uk/gp/product/B07SZ95LX1/ref=ppx_yo_dt_b_d_asin_title_o00?ie=UTF8&psc=1 , '99%' by Mark E. Thomas.

**Comment by j-howell** [comment]
> The title I have an issue with is this: https://www.amazon.co.uk/gp/product/B07SZ95LX1/ref=ppx_yo_dt_b_d_asin_title_o00?ie=UTF8&psc=1 , '99%' by Mark E. Thomas.

Thanks. The file name does make sense for that title. I was mistaken that it was related to the problem.

**Comment by 81milwir** [comment]
oh. The device matters???? We have 3 kindles, I just did the route of least resistance - the one default selected. Oops.

**Comment by ElleKayEm** [comment]
Yes, each device (and app) has a different key even if they are registered (logged in) to the same account.

**Comment by ElleKayEm** [comment]
As I said, all I see from logs is that none of the keys are the correct ones for the books.  The reasons for that are either a different device was chosen when downloading.  Or the serial number for that E-ink Kindle wasn't correctly entered into DeDRM.

The alternative is using books from Kindle for PC/Mac.  See this post:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by chrisrm9208** [comment]
Looks like a problem with running Win10 as a VM under Parallels. This is the only oddity I've noticed from Parallels... After the emphatic comments, I ran up Calibre on macOS, loaded DeDRM, copied and pasted the Kindle serial no from the Amazon devices page, and lo! the thing comes through with DRM removed and legible. Thanks for all the help on this.

**Comment by ohare93** [comment]
Same issue here. Though strangely it says I have 2 keys, when I only entered in 1.

On my Linux machine I am downloading via the Amazon Digital Content page, selecting my only Kindle, and I have that Kindle's serial number entered into the E-Ink Kindle Ebooks section of Calibre. What did I do wrong?

```
Decrypting Mobipocket 6 ebook: C. S. Lewis Bible: New Revised Standard Version (NRSV)
Found 2 keys to try after 0.1 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 2 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.1 seconds
DeDRM v10.0.2: Exception when getting default Kindle Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 812, in KindleMobiDecrypt
    defaultkeys = WineGetKeys(scriptpath, ".k4i",dedrmprefs['kindlewineprefix'])
  File "calibre_plugins.dedrm.wineutils", line 74, in WineGetKeys
    pyexec = WinePythonCLI(wineprefix)
  File "calibre_plugins.dedrm.wineutils", line 37, in __init__
    self.check_call(["-c", self.py3_test])
  File "calibre_plugins.dedrm.wineutils", line 62, in check_call
    subprocess.check_call(self.python_exec + cli_args, env=env_dict,
  File "subprocess.py", line 359, in check_call
  File "subprocess.py", line 340, in call
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'wine'
DeDRM v10.0.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 2 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```

**Comment by ElleKayEm** [comment]
You can only download books from the website if you have a Kindle device.  If it's an E-ink Kindle (not a Fire), you can decrypt those books by having its serial number in DeDRM.  DeDRM automatically gets the key from the currently installed Kindle for PC/Mac for the books downloaded via the app.

**Comment by guyuxiang** [comment]
> You can only download books from the website if you have a Kindle device. If it's an E-ink Kindle (not a Fire), you can decrypt those books by having its serial number in DeDRM. DeDRM automatically gets the key from the currently installed Kindle for PC/Mac for the books downloaded via the app.

Actually, there is a way you do not need a kindle device to download the books, using only the cookies and csrfToken of the kindle content webpage.
Check out this repository. 
https://github.com/yihong0618/Kindle_download_helper

**Comment by ElleKayEm** [comment]
So you can bulk download, but you have to disconnect any devices or other apps from your account?
