### ISSUE TITLE
Cannot install plugin on Mac OS 12.3

### ISSUE THREAD

**Issue by berriganator** [noDRM/DeDRM_tools#83]
Hello! I am trying to install the plugin .zip file into Calibre 5.43.0 on Mac 12.3 but I get the following error:

calibre, version 5.43.0
ERROR: Unhandled exception: <b>SyntaxError</b>:invalid syntax (calibre_plugins.dedrm.__init__, line 169)

calibre 5.43  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.4.0', 'Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: 
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 326, in add_plugin
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 292, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 184, in exec_module
  File "calibre/customize/zipplugin.py", line 180, in get_code
  File "calibre_plugins.dedrm.__init__", line 169
    print u"{0} v{1}: Copying needed library files from plugin's zip".format(PLUGIN_NAME, PLUGIN_VERSION)
          ^
SyntaxError: invalid syntax

**Comment by ElleKayEm** [comment]
Looks like the error you'd get when trying to install a very old version of the plugin.  Make sure you're loading DeDRM_plugin.zip from the current 10.0.2 version.

**Comment by berriganator** [comment]
Yes, I downloaded the 10.0.2 version and the DeDRM_plugin.zip indicates that it was created on January 11, 2022

**Comment by ElleKayEm** [comment]
That doesn't appear to be the one you tried to load in this log though.  Line 169 where it gave the invalid syntax error is line 219 in version 10.0.2.

**Comment by berriganator** [comment]
You are right. I didn't realize there were older versions on my computer and loaded that one of them by mistake. Now it works. Thank you!
