### ISSUE TITLE
DeDRM plugin cannot run correctly on mac due to "incompatible architecture" of libcrypto

### ISSUE THREAD

**Issue by lamons** [noDRM/DeDRM_tools#85]
### Question / bug report

The plugin could be successfully installed, but it only returns an error dialogue when I tried to configure it (double click on the plugin or click on "Customise Plug-in"):
`OSError: dlopen(/Users/jsheng/lib/libcrypto.dylib, 0x0006): tried: '~/lib/libcrypto.dylib' (mach-o file, but is an incompatible architecture (have 'i386', need 'x86_64h'))`
I am using a 2020 Intel MacBook 13 with macOS 12.4
Details in log.

### Which version of Calibre are you running?

5.43

### Which version of the DeDRM plugin are you running?

10.0.2

### Log output

```log
calibre, version 5.43.0
ERROR: Unhandled exception: <b>OSError</b>:dlopen(~/lib/libcrypto.dylib, 0x0006): tried: '~/lib/libcrypto.dylib' (mach-o file, but is an incompatible architecture (have 'i386', need 'x86_64h'))

calibre 5.43  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.5.0', 'Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: en_GB
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 49, 0) && EpubMerge (2, 13, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && KindleUnpack - The Plugin (0, 83, 1) && Obok DeDRM (10, 0, 0)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 299, in double_clicked
  File "calibre/gui2/preferences/plugins.py", line 380, in modify_plugin
  File "calibre/customize/__init__.py", line 166, in do_user_config
  File "calibre_plugins.dedrm.__init__", line 911, in config_widget
    import calibre_plugins.dedrm.config as config
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 191, in exec_module
  File "calibre_plugins.dedrm.config", line 28, in <module>
    from calibre_plugins.dedrm.utilities import uStrCmp
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 191, in exec_module
  File "calibre_plugins.dedrm.utilities", line 4, in <module>
    from calibre_plugins.dedrm.ignoblekeygen import generate_key
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 191, in exec_module
  File "calibre_plugins.dedrm.ignoblekeygen", line 196, in <module>
    AES = _load_crypto()
  File "calibre_plugins.dedrm.ignoblekeygen", line 190, in _load_crypto
    AES = loader()
  File "calibre_plugins.dedrm.ignoblekeygen", line 129, in _load_crypto_libcrypto
    libcrypto = CDLL(libcrypto)
  File "ctypes/__init__.py", line 373, in __init__
OSError: dlopen(~/lib/libcrypto.dylib, 0x0006): tried: '~/lib/libcrypto.dylib' (mach-o file, but is an incompatible architecture (have 'i386', need 'x86_64h'))

```

**Comment by ElleKayEm** [comment]
The only other time I've seen a similar error recently was also on Monterey.  I believe the need for libcrypto has been removed in the current master code here, but that change was after the 10.0.2 release.

**Comment by noDRM** [comment]
Correct, the need for libcrypto has been removed, so with 10.0.3 (which has just been released) that bug should be gone. 
I'm closing this issue, if this still happens in 10.0.3 please re-open this issue and post a new log from 10.0.3.
