### ISSUE TITLE
DeDRM 10.0.2  won't install in Calibre 5.43.0

### ISSUE THREAD

**Issue by jimkdrm** [noDRM/DeDRM_tools#90]
### Question / bug report

I have attempted to install DeDRM 10
.0.2 into Calibre 5.43.0 and it abends with the message:  
calibre, version 5.43.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in 'J:\\$DriveH-Downloads Interim Folder!!!\\DeDRM_tools-10.0.2.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.43  embedded-python: True is64bit: False
Windows-10-10.0.19041 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 326, in add_plugin
  File "calibre\customize\ui.py", line 476, in add_plugin
  File "calibre\customize\ui.py", line 64, in load_plugin
  File "calibre\customize\zipplugin.py", line 283, in load
  File "calibre\customize\zipplugin.py", line 378, in _locate_code
calibre.customize.InvalidPlugin: The plugin in 'J:\\$DriveH-Downloads Interim Folder!!!\\DeDRM_tools-10.0.2.zip' is invalid. It does not contain a top-level __init__.py file

### Which version of Calibre are you running?

5.43.0

### Which version of the DeDRM plugin are you running?

v10

### Log output

```log
Paste log output here.
```

**Comment by ElleKayEm** [comment]
That's the wrong file.  Download DeDRM_tools_10.0.2.zip from the release page: https://github.com/noDRM/DeDRM_tools/releases/tag/v10.0.2

Unzip it and load DeDRM_plugin.zip into calibre.

**Comment by ElleKayEm** [comment]
It has been updated a couple times to decrypt the newer KFX DRM.  Both times Amazon broke it by the next day.  So if someone has figured it out again, it would be unwise to add it here.

If you can download a book with 1.26 or earlier Kindle for PC (without KFX downloads disabled), then you can decrypt KFX format.  But you can get most books in azw3/kf8 or other older formats which are better for archiving or converting anyway.

In fact, looks like the book in this log should be DRM-free if it was purchased and not borrowed through Kindle Unlimited and you use one of the methods to get the older format.

**Comment by jimkdrm** [comment]
Oh, I was wondering about Big Brother.  That doses make sense.  You are most correct, there are multiple ways to get from here to there.  I was just being lazy and wanted to do it all in Calibre.  Thank you for you time and help.
