### ISSUE TITLE
no calibre/dedrm plugin combo was able to remove the adobe drm

### ISSUE THREAD

**Issue by juliuspam** [noDRM/DeDRM_tools#91]
the only time i was able to catch an error log was with calibre 5.44 and dedrm 7.2.1
I have tried dedrm 10.0.2 and also tried downgrading to calibre 4.23 and dedrm 6.8.1
any ideas what i can do?

calibre, version 5.44.0
ERROR: Loading book failed: Failed to open the book at C:\Users\49179\Calibre Library\George R. R. Martin\A Game of Thrones 5-Book Bundle_ A S (6)\A Game of Thrones 5-Book Bundle - George R. R. Martin.epub. Click "Show details" for more info.

Failed to convert book: C:\Users\49179\Calibre Library\George R. R. Martin\A Game of Thrones 5-Book Bundle_ A S (6)\A Game of Thrones 5-Book Bundle - George R. R. Martin.epub with error:
DeDRM v7.2.1: Trying to decrypt A Game of Thrones 5-Book Bundle - George R. R. Martin.epub
DeDRM v7.2.1: Verifying zip archive integrity
DeDRM v7.2.1: A Game of Thrones 5-Book Bundle - George R. R. Martin.epub is a secure Adobe Adept ePub
DeDRM v7.2.1: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v7.2.1: Exception when getting default Adobe Key after 0.1 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 358, in adeptkeys
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 358, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 361, in adeptkeys
calibre_plugins.dedrm.adobekey.ADEPTError: Adobe Digital Editions not activated
DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: EPUB Input running
on C:\Users\49179\Calibre Library\George R. R. Martin\A Game of Thrones 5-Book Bundle_ A S (6)\A Game of Thrones 5-Book Bundle - George R. R. Martin.epub
Failed to run pipe worker with command: from calibre.srv.render_book import viewer_main; viewer_main()
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 644, in run
  File "calibre_plugins.dedrm.__init__", line 415, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v7.2.1: Ultimately failed to decrypt after 0.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 196, in main
  File "<string>", line 1, in <module>
  File "calibre\srv\render_book.py", line 823, in viewer_main
  File "calibre\srv\render_book.py", line 814, in render_for_viewer
  File "calibre\srv\render_book.py", line 791, in render
  File "calibre\ebooks\oeb\iterator\book.py", line 62, in extract_book
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre\ebooks\conversion\plugins\epub_input.py", line 287, in convert
calibre.ebooks.DRMError: A Game of Thrones 5-Book Bundle - George R. R. Martin.epub
Exception ignored in: <function NativeFunction.__del__ at 0x000001E57CC4F430>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function NativeFunction.__del__ at 0x000001E57CC4F430>
Traceback (most recent call last):
  File "calibre_plugins.dedrm.adobekey", line 268, in __del__
TypeError: 'NoneType' object is not callable

**Comment by ElleKayEm** [comment]
Here is the problem:

> ADEPTError: Adobe Digital Editions not activated

Adobe Digital Editions (preferably 2.0.1) on the same machine and user as calibre with DeDRM needs to be authorized with your Adobe ID BEFORE opening the ACSM file to download the EPUB.

There is also the [ACSM input plugin](https://www.mobileread.com/forums/showthread.php?t=341975) which can be used instead of ADE.  DeDRM 10.0.2 automatically works with this plugin.  I haven't used it myself, but have seen others report that it worked well for them.

**Comment by juliuspam** [comment]
Thank you for clarification will try
