### ISSUE TITLE
Trouble to convert KFX-ZIP to epub

### ISSUE THREAD

**Issue by podiphan** [noDRM/DeDRM_tools#92]
Question / bug report
I tried to convert my amazon books to epub. From all the books, the ones with the KFX-ZIP format refuse to be converted.
I get a pop up from Calibre that says "This book is locked by DRM. To learn more ... "
Is that a known problem you guys are working on? Or am I doing something wrong?

Which version of Calibre are you running?
5.44.0

Which version of the DeDRM plugin are you running?
10.0.2
I'm also having KFX Conversion Input Plugin installed that is linked in the readme

If applicable, which version of the Kindle software are you running?
PC Version 1.37.0

Log output

Buch 1 von 1 (The Mermaid from Jeju) konvertieren
DeDRM v10.0.2: Trying to decrypt ys50f_6d.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: ys50f_6d
Got DSN key from database default_key
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.d585cbe8-db11-4bef-b008-3e3f7d629604.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.2: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.2: Looking for new default Kindle Key after 0.1 seconds
searching for kinfoFiles in C:\Users\Padiphan\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Padiphan\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1181562083' and UserName 'Padiphan'
DeDRM v10.0.2: Found 1 new key
Decrypting KFX-ZIP ebook: ys50f_6d
Got DSN key from database default_key_1
Found 1 keys to try after 3.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.d585cbe8-db11-4bef-b008-3e3f7d629604.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.2: Ultimately failed to decrypt after 3.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Conversion options changed from defaults:
  allow_conversion_with_errors: True
  read_metadata_from_opf: 'C:\\Users\\Padiphan\\AppData\\Local\\Temp\\calibre_232lfj4w\\n0gujzhd.opf'
  output_profile: 'ipad3'
  verbose: 2
  cover: 'C:\\Users\\Padiphan\\AppData\\Local\\Temp\\calibre_232lfj4w\\8jxa0dnw.jpeg'
  input_profile: 'kindle'
Resolved conversion options
calibre version: 5.44.0
{'allow_conversion_with_errors': True,
 'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': 'C:\\Users\\Padiphan\\AppData\\Local\\Temp\\calibre_232lfj4w\\8jxa0dnw.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_split_on_page_breaks': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.KindleInput object at 0x000001F7913DB850>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.iPad3Output object at 0x000001F7913DBB80>,
 'page_breaks_before': '/',
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': 'C:\\Users\\Padiphan\\AppData\\Local\\Temp\\calibre_232lfj4w\\n0gujzhd.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'transform_html_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 3.1 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeDRM v10.0.2: Trying to decrypt ys50f_6d.kfx-zip
Decrypting KFX-ZIP ebook: ys50f_6d
Got DSN key from database default_key
Found 1 keys to try after 0.0 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.d585cbe8-db11-4bef-b008-3e3f7d629604.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.2: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.2: Looking for new default Kindle Key after 0.0 seconds
searching for kinfoFiles in C:\Users\Padiphan\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\Users\Padiphan\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1181562083' and UserName 'Padiphan'
DeDRM v10.0.2: Found 1 new key
Decrypting KFX-ZIP ebook: ys50f_6d
Got DSN key from database default_key_1
Found 1 keys to try after 2.9 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.d585cbe8-db11-4bef-b008-3e3f7d629604.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 759, in pkcs7unpad
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 879, in decryptvoucher
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 758, in pkcs7unpad
  File "C:\Users\Padiphan\AppData\Roaming\calibre\plugins\DeDRM.zip\ion.py", line 98, in _assert
Exception: Incorrect padding - Wrong key
DeDRM v10.0.2: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 888, in run
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 2.9 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
InputFormatPlugin: KFX Input running
on C:\Users\Padiphan\AppData\Local\Temp\calibre_232lfj4w\ys50f_6d.kfx-zip
Software versions: KFX Input 1.49.0, calibre 5.44 [64bit], Windows-10-10.0.19041
KFX Input plugin help is available at https://www.mobileread.com/forums/showthread.php?t=291290
Converting C:\Users\Padiphan\AppData\Local\Temp\calibre_232lfj4w\ys50f_6d.kfx-zip
Processing container: B08272M3C6_EBOK.azw
Traceback (most recent call last):
  File "calibre_plugins.kfx_input.__init__", line 105, in convert
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 210, in decode_book
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 317, in get_container
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B08272M3C6_EBOK.azw has DRM and cannot be converted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 82, in <module>
  File "site.py", line 77, in main
  File "site.py", line 49, in run_entry_point
  File "calibre\utils\ipc\worker.py", line 215, in main
  File "calibre\gui2\convert\gui_conversion.py", line 38, in gui_convert_override
  File "calibre\gui2\convert\gui_conversion.py", line 25, in gui_convert
  File "calibre\ebooks\conversion\plumber.py", line 1108, in run
  File "calibre\customize\conversion.py", line 242, in __call__
  File "calibre_plugins.kfx_input.__init__", line 125, in convert
calibre.ebooks.DRMError: This book has DRM!

**Comment by ElleKayEm** [comment]
To decrypt KFX format, they need to be downloaded with no later then Kindle for PC 1.26.  Better off using one of the methods to get them in non-KFX format.  See this post: https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by podiphan** [comment]
That worked perfectly fine, thanks alot for the fast answer!
