### ISSUE TITLE
Cnable to dedrm epub file Calibre 4.44 DeDRMv10.0.2

### ISSUE THREAD

**Issue by pmblc** [noDRM/DeDRM_tools#94]
### Question / bug report

ebook downloaded from public library borrowing site .acsm and imported and converted to epub by Adobe Digital Edition 4.5
ref of the book in log file
Thanks for help
Regards

### Which version of Calibre are you running?

5.44

### Which version of the DeDRM plugin are you running?

v10.0.2

### Log output

calibre Debug log
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2)
calibre 5.44 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.19041 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19041')
Python 3.8.5
Windows: ('10', '10.0.19041', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (10, 0, 2)
Turning on automatic hidpi scaling
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 93.6046065259117 x 93.62457337883959
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Showing splash screen...
[0.66] splash screen shown
[0.66] Initializing db...
[0.73] db initialized
[0.73] Constructing main UI...
[1.48] main UI initialized...
[1.48] Hiding splash screen
Starting QuickView
DeDRM v10.0.2: Trying to decrypt Shakespeare 2037.epub
DeDRM v10.0.2: Verifying zip archive integrity
DeDRM v10.0.2: Shakespeare 2037.epub is a secure Adobe Adept ePub for UUID 4768a06d-6cd1-4ef1-ae88-70ebfc6f26cc
DeDRM v10.0.2: Looking for new default Adobe Digital Editions Keys after 0.2 seconds
DeDRM v10.0.2: Exception when getting default Adobe Key after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 483, in ePubDecrypt
  File "calibre_plugins.dedrm.adobekey", line 393, in adeptkeys
  File "calibre_plugins.dedrm.adobekey", line 371, in CryptUnprotectData
calibre_plugins.dedrm.adobekey.ADEPTError: Failed to decrypt user key key (sic)
Traceback (most recent call last):
  File "calibre_plugins.dedrm.config", line 35, in checkForDeACSMkeys
ModuleNotFoundError: No module named 'calibre_plugins.deacsm'
DeDRM v10.0.2: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
[16.19] splash screen hidden
[16.19] Started up in 16.19 seconds with 1532 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xe0\x92E\xe9\x04\xdcz\xf4\x99`(\x1b\xc4.\xe2,3\x9e9\xe2\xc8\xa5K\xf8h\x8c\x07\xcbeo\xe9\x0c', b'D:\\PAM\\Documents PM\\My Digital Editions\\Shakespeare 2037.epub']
Added Shakespeare 2037 to db in: 1.4
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre\customize\ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 899, in run
  File "calibre_plugins.dedrm.__init__", line 562, in ePubDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/maAdded 1 books in 2.1 seconds
Worker Launch took: 0.00 seconds

**Comment by shalym329** [comment]
I just tried downloading and adding some recently purchased Amazon 
books, and it worked just fine.

I am confused, though...in your subject, you say that you are unable to 
dedrm an epub file.  Where did that epub file come from?  Amazon doesn't 
do epub.

**Comment by KennethEvans** [comment]
The two books I tried to convert were AWZ from "Download via USB" at Amazon. Yes, the topic says EPUB, but it didn't seem wise to start a different issue.

What actually happened is that I had 7.2 1 installed and updated to 5.44 frpm 5.40 on opening Calibre. Things had been working for some time.

It then asked to update KFX Input. I then imported the books, and then Count Pages failed.

I then uninstalled 5.44 and installed 5.40. I was unable to find a way to install the older KFX Input. I then did a number of things eventually ending up with 10.0.2 and 5.44. Nothing I tried would allow Count Pages or Viewing the 2 books. Owing to DRM.

It isn't de-DRM'ing now. It could be KFX input. I'm not sure what it does.

**Comment by KennethEvans** [comment]
I did some more testing.

- I tried adding a book I had previously added with DRM working. It was ok.
- I downloaded the same book from Amazon and added it from the new file. It was ok.
- I re-downloaded the 2 books that were not ok and added them. They were ok.

So it is working for me now. And there is no evidence things have changed at Amazon. Apparently something happened with the two downloads that didn't work, possibly associated with the version change and plug-in update.

For the record, I also did a binary compare on the two versions of the bad files. They are not binary equal, and there are a lot of differences. There is one possible explanation. I just got an Oasis, and I probably set the download device to that. Previous I was using a Paperwhite, and for the new downloads I did today, I set the download device to the Paperwhite as all past downloads have been.

I see 6.00 is available. I will update to it and continue to use 10.0.2.

I'm good. Thanks.

**Comment by ElleKayEm** [comment]
Don't update to calibre 6.  DeDRM 10.0.2 is not compatible.  It is being worked on and should be compatible with the next release.

Enter the serial number for your Oasis too.  Then you won't have to worry about which one you pick when downloading books.

**Comment by KennethEvans** [comment]
I already did, but haven't added books. I'll revert to 5.4.4. Thanks for the warning.

(I did find and reported a bug with 6.0.0, though. 😉)

I don't understand about the Oasis serial. When I do "Download via USB", it pops up a dialog, now with 2 devices, neither checked. I have set the Oasis as the default. The item in the dialog was never checked when the Paperwhite was default. 

Maybe setting the Oasis as default was what you meant. I don't recall ever using a serial. 

As a note, I usually use the Amazon versions for first reads rather than the Calibre ones. It is my understanding the authors don't get paid unless Amazon thinks they have been read. 

Thanks again.

**Comment by shalym329** [comment]
You need to add the serial number of the Oasis to the Calibre plugin.  
In Calibre's preferences, click to view the plugins, then go to "File 
type" plugins, then click on the DeDRM plugin and click the "customize 
plugin" button.  From there, click on "eInk Kindle ebooks" and add the 
serial number for your Oasis.

Shari

**Comment by KennethEvans** [comment]
I apologize. Having to enter the serial number got lost from my memory and wasn't in my notes. It is in the readme. I didn't read all of it. I was already multi-tasking and in too much of a hurry, I guess. Definitely my bad.

So that was the problem all along. If I'd known what I know now, I would have made it a separate issue, except under those circumstances, there wouldn't be an issue. ;-)

Thanks for all the help, including clarifying the issue with Prime, Unlimited, and First Reads.
