### ISSUE TITLE
Adobe's new DRM - "This DRM cannot be removed yet"

### ISSUE THREAD

**Issue by kn1ght3rrand** [noDRM/DeDRM_tools#95]
### Question / bug report

Hi there, thank you for all the contributors who made this project possible for the public.

I am trying to decrypt both the Adobe ACSM (using DeACSM) as well as DeDRM latest release tools but couldn't. The error I got was "This seems to be an Adobe ADEPT PDF with Adobe's new DRM. This DRM cannot be removed yet." Does that mean these tools does not work with it or have I done something wrong? 

Here's Calibre's debug log: 

Thank you in advance for your kind assistance and guidance! 

### Which version of Calibre are you running?

5.44

### Which version of the DeDRM plugin are you running?

10.0.2

### Log output

```calibre Debug log
calibre 5.44  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.0.0', 'Darwin Kernel Version 22.0.0: Tue Jun 28 20:48:02 PDT 2022; root:xnu-8792.0.134.131.2~1/RELEASE_ARM64_T8103')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 15) && DeDRM (10, 0, 2)
calibre 5.44  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '22.0.0', 'Darwin Kernel Version 22.0.0: Tue Jun 28 20:48:02 PDT 2022; root:xnu-8792.0.134.131.2~1/RELEASE_ARM64_T8103')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: DeACSM (0, 0, 15) && DeDRM (10, 0, 2)
devicePixelRatio: 2.0
logicalDpi: 72.0 x 72.0
physicalDpi: 93.50000140422914 x 93.50000140422914
Using calibre Qt style: True
[0.00] Starting up...
[0.03] Showing splash screen...
[0.25] splash screen shown
[0.25] Initializing db...
[0.27] db initialized
[0.27] Constructing main UI...
[0.77] main UI initialized...
[0.77] Hiding splash screen
Starting QuickView
DeDRM v10.0.2: Trying to decrypt Effective Counseling and Psychotherapy.pdf
DeDRM v10.0.2: Effective Counseling and Psychotherapy.pdf is a PDF ebook for UUID b16bf76b-c68b-4aeb-bd9a-a79306810f59
DeDRM v10.0.2: Looking for new default Adobe Digital Editions Keys after 0.1 seconds
DeDRM v10.0.2: Found new key 'DeACSM_uuid_b16bf76b-c68b-4aeb-bd9a-a79306810f59' in DeACSM plugin
DeDRM v10.0.2: Trying a new default key
This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet. 
Try getting your distributor to give you a new ACSM file, then open that in an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give you a copy with the old DRM.
DeDRM v10.0.2: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 712, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2322, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "calibre_plugins.dedrm.ineptpdf", line 2128, in __init__
    doc.initialize(userkey, inept)
  File "calibre_plugins.dedrm.ineptpdf", line 1504, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1708, in initialize_ebx_inept
    raise ADEPTNewVersionError("Book uses new ADEPT encryption")
calibre_plugins.dedrm.ineptpdf.ADEPTNewVersionError: Book uses new ADEPT encryption
DeDRM v10.0.2: Failed to decrypt with new default key after 0.2 seconds
DeDRM v10.0.2: Trying a new default key
This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet. 
Try getting your distributor to give you a new ACSM file, then open that in an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give you a copy with the old DRM.
DeDRM v10.0.2: Exception when decrypting after 0.3 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 712, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2322, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "calibre_plugins.dedrm.ineptpdf", line 2128, in __init__
    doc.initialize(userkey, inept)
  File "calibre_plugins.dedrm.ineptpdf", line 1504, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1708, in initialize_ebx_inept
    raise ADEPTNewVersionError("Book uses new ADEPT encryption")
calibre_plugins.dedrm.ineptpdf.ADEPTNewVersionError: Book uses new ADEPT encryption
DeDRM v10.0.2: Failed to decrypt with new default key after 0.3 seconds
DeDRM v10.0.2: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 175, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 895, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 770, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.3 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 432, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
[2.25] splash screen hidden
[2.25] Started up in 2.25 seconds with 0 books
Added Effective Counseling and Psychotherapy to db in: 0.0
Added 1 books in 0.8 seconds
DeDRM v10.0.2: Trying to decrypt czh8klyw.pdf
DeDRM v10.0.2: czh8klyw.pdf is a PDF ebook for UUID b16bf76b-c68b-4aeb-bd9a-a79306810f59
DeDRM v10.0.2: Looking for new default Adobe Digital Editions Keys after 0.0 seconds
DeDRM v10.0.2: Found new key 'DeACSM_uuid_b16bf76b-c68b-4aeb-bd9a-a79306810f59' in DeACSM plugin
DeDRM v10.0.2: Trying a new default key
This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet. 
Try getting your distributor to give you a new ACSM file, then open that in an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give you a copy with the old DRM.
DeDRM v10.0.2: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 712, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2322, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "calibre_plugins.dedrm.ineptpdf", line 2128, in __init__
    doc.initialize(userkey, inept)
  File "calibre_plugins.dedrm.ineptpdf", line 1504, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1708, in initialize_ebx_inept
    raise ADEPTNewVersionError("Book uses new ADEPT encryption")
calibre_plugins.dedrm.ineptpdf.ADEPTNewVersionError: Book uses new ADEPT encryption
DeDRM v10.0.2: Failed to decrypt with new default key after 0.2 seconds
DeDRM v10.0.2: Trying a new default key
This seems to be an Adobe ADEPT PDF with Adobe's new DRM
This DRM cannot be removed yet. 
Try getting your distributor to give you a new ACSM file, then open that in an old version of ADE (2.0).
If your book distributor is not enforcing the new DRM yet, this will give you a copy with the old DRM.
DeDRM v10.0.2: Exception when decrypting after 0.2 seconds
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 712, in PDFDecrypt
    result = ineptpdf.decryptBook(userkey, path_to_ebook, of.name)
  File "calibre_plugins.dedrm.ineptpdf", line 2322, in decryptBook
    serializer = PDFSerializer(inf, userkey, inept)
  File "calibre_plugins.dedrm.ineptpdf", line 2128, in __init__
    doc.initialize(userkey, inept)
  File "calibre_plugins.dedrm.ineptpdf", line 1504, in initialize
    return self.initialize_ebx_inept(password, docid, param)
  File "calibre_plugins.dedrm.ineptpdf", line 1708, in initialize_ebx_inept
    raise ADEPTNewVersionError("Book uses new ADEPT encryption")
calibre_plugins.dedrm.ineptpdf.ADEPTNewVersionError: Book uses new ADEPT encryption
DeDRM v10.0.2: Failed to decrypt with new default key after 0.2 seconds
DeDRM v10.0.2: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
DeACSM v0.0.15: Running file type plugin failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.deacsm.__init__", line 448, in run
    plugin_ret = plugin.run(rpl)
  File "calibre_plugins.dedrm.__init__", line 895, in run
    decrypted_ebook = self.PDFDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 770, in PDFDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION, time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 0.2 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Traceback (most recent call last):
  File "calibre/customize/ui.py", line 432, in get_file_type_metadata
  File "calibre/customize/builtins.py", line 324, in get_metadata
  File "calibre/ebooks/metadata/pdf.py", line 124, in get_metadata
ValueError: Could not read info dict from PDF
DeACSM v0.0.15: Trying to parse file 1272941.acsm
DeACSM v0.0.15: Try to fulfill ...
Notifying server ...
Notifying server https://acs.ebookcentral.proquest.com/fulfillment/FulfillmentNotification
Fulfillment notification successful.
DeACSM v0.0.15: Downloading book ...
DeACSM v0.0.15: Loading book from https://acs.ebookcentral.proquest.com/document/001/001272/dbaba0cc-e866-3224-a581-9a64894b2de6.pdf
Download took 506 ms (HTTP 200)
That's a PDF file
DeACSM v0.0.15: Downloaded PDF, adding encryption config ...
Searching for startxref ...
Got startxref: 16295328
Found ENC after 29 attempts - took 0 ms
Found EBX after 32 attempts - took 0 ms


Encryption handler:
<</Length     6806/Type/XRef/Root 1 0 R/Info 20 0 R/Encrypt 4540 0 R/ID[<D863D69404A09753B7E446731AB8EE05><AC17A7D024AC4FC4CE02F64FF26EE00C>]/Size 4542/Index[0 4542]/W[1 3 1]/DecodeParms<</Columns 5/Predictor 12>>/Filter/FlateDecode>>stream
EBX handler:
<</EBX_PUBLISHER(Taylor & Francis Group)/Filter/EBX_HANDLER/Length 128/ADEPT_ID(urn:uuid:00000000-0000-0000-0000-000001272941)/V 4/EBX_TITLE(Psychotherapy)/EBX_AUTHOR(Schilder, Paul, Paul;)>>
Trimmed encryption handler:
<</Length     6806/Type/XRef/Root 1 0 R/Info 20 0 R/Encrypt 4540 0 R/ID[<D863D69404A09753B7E446731AB8EE05><AC17A7D024AC4FC4CE02F64FF26EE00C>]/Size 4542/Index[0 4542]/W[1 3 1]/DecodeParms<</Columns 5/Predictor 12>>/Filter/FlateDecode>>
Updated EBX handler not logged due to sensitive data
Whole DRM patching took 9 milliseconds.
DeACSM v0.0.15: File successfully fulfilled ...
DeACSM v0.0.15: Executing plugin DeDRM ...
DeACSM v0.0.15: Plugin returned nothing - skipping
Syntax Error: Couldn't find the 'EBX_HANDLER' security handler
```

**Comment by ElleKayEm** [comment]
Support for the newer Adobe DRM is still being worked on.  You can give the beta version linked in this comment a try:  https://github.com/noDRM/DeDRM_tools/pull/48#issuecomment-1072589825

**Comment by kn1ght3rrand** [comment]
Thank you ElleKayEm! It worked! Really appreciate your kind assistance
