### ISSUE TITLE
Obok DeDRM button causes unhandled exception

### ISSUE THREAD

**Issue by bszonye** [noDRM/DeDRM_tools#98]
### Question / bug report

I'm using Calibre for the first time on Windows 11, and I've installed build 59 (based on 10.0.2) to use the new features for Nook keys. When I press the ObokDeDRM button, it throws an unhandled exception:

> AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'

As this is my first install, I'm not sure whether this is a compatibility problem with Calibre 6.0 (just released today!) or a configuration problem with the plugin. However, when I try to use the "Kobo directory" button in the plugin configurator, I get another unhandled exception:

> AttributeError: type object 'QFileDialog' has no attribute 'ShowDirsOnly'

The log output below is from the first exception.

### Which version of Calibre are you running?

6.0

### Which version of the DeDRM plugin are you running?

v10.0.2 (build 59)

### Log output

```log
calibre, version 6.0.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.0  embedded-python: True
Windows-10-10.0.22000 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22000')
Python 3.10.1
Windows: ('10', '10.0.22000', '', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 49, 0) && DeDRM (10, 0, 2) && Package KFX (from KFX Input) (1, 49, 0) && KFX metadata reader (from KFX Input) (1, 49, 0) && KFX Input (1, 49, 0) && Obok DeDRM (10, 0, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'
```

**Comment by cgoubert** [comment]
Encountering a similar on PopOS! 22.04.
v10.0.2
```
calibre, version 6.0.0
ERROR: Unhandled exception: <b>AttributeError</b>:type object 'QTableWidgetItem' has no attribute 'UserType'

calibre 6.0  embedded-python: True
Linux-5.17.15-76051715-generic-x86_64-with-glibc2.33 Linux ('64bit', 'ELF')
('Linux', '5.17.15-76051715-generic', '#202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: Obok DeDRM (10, 0, 0)
Traceback (most recent call last):
  File "calibre_plugins.obok_dedrm.action", line 135, in launchObok
    dlg = SelectionDialog(self.gui, self, books)
  File "calibre_plugins.obok_dedrm.dialogs", line 102, in __init__
    self.books_table.populate_table(self.books)
  File "calibre_plugins.obok_dedrm.dialogs", line 154, in populate_table
    self.populate_table_row(row, book)
  File "calibre_plugins.obok_dedrm.dialogs", line 179, in populate_table_row
    status_cell = IconWidgetItem(None, icon, val)
  File "calibre_plugins.obok_dedrm.dialogs", line 439, in __init__
    ReadOnlyTableWidgetItem.__init__(self, text)
  File "calibre_plugins.obok_dedrm.dialogs", line 412, in __init__
    QTableWidgetItem.__init__(self, text, QTableWidgetItem.UserType)
AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'
```

**Comment by bszonye** [comment]
I downgraded Calibre to version 5.44, and the Obok extension worked flawlessly, so it appears that this is a Calibre 6.0 incompatibility.

**Comment by sidney** [comment]
[Here is a post ](https://www.mobileread.com/forums/showpost.php?p=4237911&postcount=75)by the author of Caibre that explains the problem and the small code change in DeDRM that is needed to fix it.

**Comment by agentxan** [comment]
If you make the following changes it works for me on windows 10

in Obok_plugin/config.py on line 65 change
QFileDialog.ShowDirsOnly to QFileDialog.Option.ShowDirsOnly

in Obok_plugin/dialogs.py on line 412 and 451
QTableWidgetItem.UserType to QTableWidgetItem.ItemType.UserType

**Comment by noDRM** [comment]
Thanks for the report. I have never personally used the Obok plugin so I can't really test that, but I've added the changes suggested by agentxan. 

Can someone who used the Obok plugin in the past check if that fixes it? The new version can be downloaded under the [Actions](https://github.com/noDRM/DeDRM_tools/actions) tab.
